.github/workflows/release.yml, package.json, packages/components/src/icon/iconfont/iconfont.html, packages/types/package.json, tools/template/package.json
- 修复 Github CI 选择 Node.js 版本的流程
=> fix: Github CI selecting the version of Node.js

packages/terminal-next/src/browser/contribution/terminal.lifecycle.ts, packages/terminal-next/src/browser/terminal.theme.ts
fixes #147 
- 完善 Terminal 主题 colorToken 注册逻辑
=> feat: terminal register color token

packages/extension/src/browser/shadowRoot.tsx
> 请将这段及下面未选中的项一起删除，保持 PR 描述的简洁性
- components 使用 unpkg 资源
=> chore: use unpkg

packages/file-tree-next/src/browser/file-tree.tsx
=> fix: optimize filetree view perf

.eslintignore, .github/workflows/check.yml, .github/workflows/ci.yml, packages/core-browser/src/react-providers/config-provider.tsx, packages/extension/src/browser/extension-view.service.ts, packages/extension/src/browser/shadowRoot.tsx
支持通过配置 `componentCDNType` 设置三种 CDN 资源路径模式，`'unpkg' | 'jsdelivr' | 'alipay'` 
support component cdn type configuration
=> feat: support component cdn type configuration

packages/extension/src/browser/shadowRoot.tsx
=> fix: set correct component CDN url

configs/vscode-extensions.json, packages/startup/entry/web/app.tsx
=> chore: update extensions

.github/workflows/check.yml, .github/workflows/ci.yml
- Update workflow, add workflow_dispatch
=> chore: add workflow_dispatch

CONTRIBUTING-zh_CN.md, CONTRIBUTING.md, scripts/pkg.ts
=> chore(docs): replace tnpm as npm

packages/extension/__tests__/browser/main.thread.workspace.test.ts, packages/file-tree-next/__tests__/browser/file-tree.test.ts
=> fix: test cases

scripts/download.js, scripts/rebuild-native.js, scripts/watch.ts, tools/electron/build/pack.js
=> chore: format scripts directory

.github/workflows/pre-release.yml
=> chore: add pre-release workflow

.github/workflows/pre-release.yml, lerna.json, tools/dev-tool/package.json
新增 Prerelease workflow，用于自动发布测试包，使用流程
1. 新建 issue，标题暂定，类似 [Prerelease] 2.15.0 测试版本
2. issue 正文开头包含 ` ## OpenSumi next version prerelease` ，会触发 prerelease workflow
3. 打包并发布版本完成后在 issue 回复类似 
🎉 Pre Release. You can install prerelease version via `npm install package@next` 
- 更新 prerelease workflow
=> chore: optimize prerelease workflow

.github/workflows/pre-release.yml, packages/types/package.json
=> chore: update workflow

package.json, scripts/changelog/github.ts, scripts/changelog/index.ts, scripts/changelog/run.ts, scripts/changelog/types.ts, scripts/changelog/util.ts
=> chore: support changelog script

scripts/changelog/index.ts
=> chore: show correct tips while running changelog script

.github/workflows/pre-release.yml
=> chore: add changelog step

.github/workflows/pre-release.yml
生成 changelog 依赖 ts-node，将安装依赖和构建流程放在 changelog 之前
=> fix: install dependencies first

.github/workflows/pre-release.yml, scripts/changelog/github.ts, scripts/changelog/index.ts, scripts/changelog/run.ts
=> chore: support generate changelog all using github api

.github/workflows/pre-release.yml, scripts/changelog/github.ts, scripts/changelog/run.ts, scripts/changelog/util.ts
=> chore: update changelog scripts

.github/workflows/pre-release.yml
发布  prerelease 版本时使用唯一的版本号
- 发布 prerelease 版本时使用唯一的版本号
=> chore: use unique version for prerelease

.github/PULL_REQUEST_TEMPLATE.md, scripts/changelog/run.ts
use GITHUB_SHA as changelog title if exist
=> chore: use GITHUB_SHA as changelog title if exist

.github/workflows/pre-release.yml, .github/workflows/release.yml
=> chore: add release workflow

.github/workflows/pre-release.yml, .github/workflows/release.yml
=> fix: release output

packages/core-common/src/types/extension.ts, packages/extension/src/browser/extension.service.ts, packages/theme/src/browser/theme.contribution.ts, packages/theme/src/browser/workbench.theme.service.ts
=> fix: theme fallback logic

packages/main-layout/src/browser/tabbar/bar.view.tsx
close: #175 
only bottom slot will apply `hideSlotTabBarWhenHidePanel` settings
=> feat: 只允许 bottom slot 隐藏 tab

.github/workflows/pre-release.yml, .github/workflows/release.yml
=> fix: finish release workflow

packages/core-browser/src/common/common.contribution.ts, packages/electron-basic/src/browser/header.tsx
before:
after:
- update app name on windows version
=> chore: update app name on windows version

packages/extension/src/browser/vscode/api/tree-view/tree-view-node.module.less
=> chore: update tree node styles

packages/main-layout/src/browser/tabbar/bar.view.tsx, packages/main-layout/src/browser/tabbar/tabbar.service.ts
隐藏 bottom slot tabbar 时双击 tab 不会再隐藏整个 slot
=> feat: 完善隐藏底部 tabbar 的表现

lerna.json
=> chore: update version in `lerna.json`

LICENSE, README-zh_CN.md, README.md
Upgrade Ant Group name
chore: upgrade license
=> chore: upgrade license

packages/components/src/checkbox/style.less, packages/components/src/scrollbars/styles.less, packages/core-browser/src/style/normalize.less, packages/core-browser/src/style/utilities.less, packages/core-browser/src/style/variable.less, packages/debug/src/browser/view/watch/debug-watch.module.less, packages/extension-manager/src/browser/extension/extension.module.less, packages/file-tree-next/src/browser/file-tree-node.module.less, packages/file-tree-next/src/browser/file-tree.module.less, packages/main-layout/src/browser/layout.service.ts, packages/main-layout/src/browser/tabbar/tabbar.service.ts, packages/markers/src/browser/markers.module.less, packages/output/src/browser/output.module.less, packages/preferences/src/browser/preferences.module.less, packages/search/src/browser/search.module.less, packages/status-bar/src/browser/status-bar.module.less
=> style: clean all less variables

.github/ISSUE_TEMPLATE/-------pre-release--.md, .github/ISSUE_TEMPLATE/-------release--.md, .github/workflows/issue-checker.yml
auto close unauth release workflow
=> chore: auto close unauth release workflow

packages/core-browser/src/react-providers/slot.tsx, packages/main-layout/src/browser/default-config.ts, packages/main-layout/src/browser/layout.service.ts, packages/theme/src/browser/theme-store.ts, tools/electron/src/browser/layout.ts
=> chore: remove useless view defined

packages/debug/src/browser/editor/debug-editor-contribution.ts
在没有开启调试的情况下按 alt/option 键之后会导致 hover 语法失效
=> fix: alt/option causes hover to fail

.github/workflows/pr-next-release.yml
在 pull request 评论触发的 issue_comment 事件中执行，需满足评论人为项目 OWNER 或 MEMBER，或评论人为 PR 发起人
- 添加 pr release workflow, 支持任意 pr 回复指定内容后发布 next 版本
=> chore: add pr release workflow

.github/workflows/pr-next-release.yml
=> chore: use node 12

.github/workflows/pr-next-release.yml
pr 中发布next 版本开始后自动评论类似
> 🎉Next version is publishing. Please wait for the next release...
发布成功后@发起人
=> chore: add comment for pr

packages/extension-manager/src/browser/extension/extension.module.less, packages/file-tree-next/src/browser/file-tree-node.module.less, packages/file-tree-next/src/browser/file-tree.module.less, packages/preferences/src/browser/preferences.module.less, packages/search/src/browser/search.module.less
=> chore: add less variables import

packages/debug/src/browser/view/watch/debug-watch.module.less
add debug module less variables import
=> fix: add less variables import

packages/core-browser/src/components/index.ts
fixed #258 
re-export recycle-list from ide-components
=> chore: re-export recycle-list from ide-components

.github/workflows/pr-next-release.yml
=> chore: use github script

.github/workflows/pr-next-release.yml, .github/workflows/pre-release.yml, .github/workflows/release.yml
=> chore: use exact version

packages/file-search/package.json, packages/file-search/src/node/file-search.service.ts, packages/search/package.json, packages/search/src/node/content-search.service.ts, tools/electron/build/pack.js, tools/electron/build/webpack.node.config.js, tools/electron/package.json
=> chore: use @opensumi/vscode-ripgrep

.github/workflows/release.yml
=> chore: add git identity

tools/dev-tool/src/webpack.js
for cloud ide
read host from environment variable
=> chore: read host from environment variable

packages/debug/__tests__/browser/breakpoint/breakpoint-decoration.test.ts, packages/debug/__tests__/browser/debugModel.test.ts, packages/debug/__tests__/browser/editor/debug-model.test.ts, packages/debug/__tests__/browser/model/debug-breakpoint.test.ts, packages/debug/__tests__/browser/model/debug-source.test.ts, packages/debug/src/browser/breakpoint/breakpoint-decoration.ts, packages/debug/src/browser/breakpoint/breakpoint-manager.ts, packages/debug/src/browser/breakpoint/breakpoint-marker.ts, packages/debug/src/browser/debug-contribution.ts, packages/debug/src/browser/debug-session.ts, packages/debug/src/browser/editor/debug-breakpoint-widget.ts, packages/debug/src/browser/editor/debug-breakpoint-zone-widget.tsx, packages/debug/src/browser/editor/debug-editor-contribution.ts, packages/debug/src/browser/editor/debug-hover-widget.tsx, packages/debug/src/browser/editor/debug-model-manager.ts, packages/debug/src/browser/editor/debug-model.ts, packages/debug/src/browser/editor/debug-run-to-cursor.service.ts, packages/debug/src/browser/model/debug-source.ts, packages/debug/src/browser/view/breakpoints/debug-breakpoints.service.ts, packages/debug/src/browser/view/breakpoints/debug-breakpoints.view.tsx, packages/debug/src/common/debug-breakpoint.ts, packages/debug/src/common/debug-hover.ts, packages/debug/src/common/debug-model.ts, packages/debug/src/common/debug-session.ts, packages/debug/src/common/index.ts, packages/debug/src/common/inline-values.ts, packages/extension/src/browser/vscode/api/main.thread.debug.ts
提取 interface 到 common 模块
优化 debug 模块代码
=> chore: optimization debug module code

packages/debug/__tests__/browser/view/console/debug-console.view.test.tsx, packages/debug/src/browser/debug-session.ts, packages/debug/src/browser/view/console/debug-console-model.ts, packages/editor/src/browser/view/suggest-widget.ts, packages/extension/src/common/sumi/extension.ts, packages/file-scheme/src/browser/file-doc.ts, packages/theme/__tests__/browser/theme.service.test.ts, packages/types/sumi-worker/sumi-worker.d.ts, packages/types/sumi-worker/worker.doc.d.ts, packages/types/sumi-worker/worker.editor.d.ts, packages/types/sumi-worker/worker.language.d.ts, packages/types/vscode/typings/vscode.d.ts, packages/types/vscode/typings/vscode.editor.d.ts, packages/types/vscode/typings/vscode.env.d.ts, packages/types/vscode/typings/vscode.extension.d.ts, packages/types/vscode/typings/vscode.language.d.ts, packages/types/vscode/typings/vscode.message.d.ts, packages/types/vscode/typings/vscode.quickpick.d.ts, packages/types/vscode/typings/vscode.scm.d.ts, packages/types/vscode/typings/vscode.workspace.d.ts
=> chore: remove useless people name

.github/workflows/pr-next-release.yml, .github/workflows/pre-release.yml, .github/workflows/release.yml, packages/core-browser/src/core-preferences.ts, packages/extension/__tests__/browser/main.thread.task.test.ts, packages/extension/__tests__/hosted/api/vscode/ext.host.task.test.ts, packages/extension/src/browser/vscode/api/main.thread.terminal.ts, packages/terminal-next/__tests__/browser/inject.ts, packages/terminal-next/__tests__/browser/terminal.service.test.ts, packages/terminal-next/__tests__/node/pty.test.ts, packages/terminal-next/__tests__/node/terminal.service.client.test.ts, packages/terminal-next/src/browser/index.ts, packages/terminal-next/src/browser/terminal.client.ts, packages/terminal-next/src/browser/terminal.internal.service.ts, packages/terminal-next/src/browser/terminal.service.ts, packages/terminal-next/src/common/client.ts, packages/terminal-next/src/common/pty.ts, packages/terminal-next/src/common/service.ts, packages/terminal-next/src/common/shell.ts, packages/terminal-next/src/node/pty.ts, packages/terminal-next/src/node/shell.ts, packages/terminal-next/src/node/terminal.service.client.ts, packages/terminal-next/src/node/terminal.service.ts
=> refactor: adjust shell launch config logic

.github/workflows/pr-next-release.yml
Pull request 中发布 next 版本时新增一个 checkSuite，用于在 PR check 区域显示发布状态，成功/失败后分别显示不同内容，类似
=> chore: update pr release workflow

.github/workflows/pr-next-release.yml
=> fix: workflow syntax error

packages/components/src/recycle-tree/RecycleTree.tsx, packages/file-tree-next/src/browser/file-tree.tsx
=> fix: some hooks warning

packages/core-browser/src/layout/layout-state.ts, packages/core-common/package.json, packages/extension-manager/package.json, packages/theme/src/browser/theme-store.ts
fixed #279 
try to load latest theme data while refreshing page
=> fix: try to load latest theme data while refreshing page

packages/core-common/__tests__/arrary.test.ts, packages/core-common/__tests__/map.test.ts, packages/core-common/__tests__/utils/strings.test.ts, packages/debug/src/browser/editor/debug-hover-widget.tsx, packages/extension/src/browser/vscode/api/main.thread.language.ts, packages/extension/src/common/vscode/ext-types.ts, packages/extension/src/hosted/api/vscode/ext.host.workspace.ts, packages/extension/src/hosted/api/vscode/language/code-action.ts, packages/extension/src/hosted/api/vscode/language/rename.ts, packages/startup/entry/web-lite/modules/language-service/simple.ts
=> style: update code style

.github/workflows/issue-checker.yml
workflow file has unexpected symbol: '&&'
=> chore: workflow file has unexpected symbol: '&&'

.github/workflows/release-check.yml
fix release check workflow script
=> chore: fix release check workflow script

.github/ISSUE_TEMPLATE/-------pre-release--.md, .github/workflows/release-check.yml
=> chore: update pre-release template

.github/workflows/pre-release.yml
update pre release verify logic
=> chore: update pre release verify logic

README.md
=> chore: update README with new logo

README-zh_CN.md, README.md
=> chore: update README badge

.github/workflows/pre-release.yml
=> chore: update pre-release workflow

packages/components/src/recycle-tree/basic/tree-node.define.ts, packages/components/src/recycle-tree/basic/tree-node.tsx, packages/components/src/recycle-tree/basic/types.ts, packages/main-layout/src/browser/main-layout.contribution.ts, packages/testing/src/browser/components/testing.explorer.tree.tsx, packages/testing/src/browser/components/testing.module.less, packages/testing/src/browser/icons.ts, packages/testing/src/browser/test-tree-view.model.ts, packages/testing/src/browser/testing.contribution.ts, packages/testing/src/common/tree-view.model.ts
PS: loading 效果没处理
支持测试资源管理器的树形结构的数据更新
=> feat: support refresh testing explorer tree data

packages/task/src/browser/task.service.ts, packages/task/src/common/index.ts
- emit task provider registered event
=> feat: emit task provider registered event

packages/extension/src/hosted/api/vscode/ext.host.preference.ts
fixed #88 
fix configuration contributionPoint parse error
=> fix: configuration contributionPoint parse error

packages/components/src/recycle-tree/RecycleTree.tsx
ref: https://github.com/opensumi/core/pull/307
这里实际上不需要去处理文件树内的 `dispatchChange` 方法，`doDispatchChange` 方法主要是用于文件树更新前作合并更新所做的特殊操作
optimize RecycleTree update performence
=> fix: optimize RecycleTree update performence

.github/workflows/pre-release.yml, .github/workflows/release-check.yml
update issue status while pulishing Pre-Release
=> fix: update issue status while pulishing Pre-Release

packages/components/src/scrollbars/styles.less, packages/core-browser/src/components/actions/styles.module.less
fixed #364 
align filetree and menu scrollbar width
=> style: align filetree and menu scrollbar width

packages/main-layout/src/browser/tabbar/styles.module.less, packages/startup/entry/web-lite/modules/view/styles.less
fixed #358
remove border from right tabbar button
=> style: remove border from right tabbar button

packages/search/src/browser/search.module.less, packages/search/src/browser/search.replace.widget.tsx, packages/search/src/browser/search.view.tsx
fixed #367 
update replace all button correctly while updating replace the value on search view
=> fix: update replace all button correctly while updating replace the value  on search view

packages/core-browser/src/contextkey/resource.ts, packages/editor/src/browser/editor-collection.service.ts, packages/editor/src/browser/workbench-editor.service.ts
=> fix: fixes #360

packages/core-browser/src/components/layout/default-layout.tsx, packages/main-layout/src/browser/accordion/styles.module.less, packages/main-layout/src/browser/tabbar/bar.view.tsx, packages/main-layout/src/browser/tabbar/styles.module.less, packages/startup/entry/web-lite/modules/view/custom-layout-component.tsx, packages/startup/entry/web-lite/modules/view/custom-tabbar-renderer.tsx
fixed #358
after:
optimize sidebar border and size style
=> style: optimize sidebar border and size style

packages/preferences/src/browser/preference-contribution.ts
fixed #363 
auto position setting id when invisible
=> fix: auto position setting id when invisible

packages/task/src/browser/task.service.ts, packages/task/src/browser/terminal-task-system.ts, packages/task/src/common/index.ts, packages/task/src/common/task.ts
- fire task background begin and ended event
=> feat: fire task background begin and ended event

packages/core-browser/src/common/common.module.ts
- add remote opener contribution to contributionProvider
=> fix: add remote opener contribution

configs/ts/tsconfig.resolve.json, scripts/generate-tsconfig-resolve.ts
=> chore: add generate-tsconfig-resolve script

packages/extension/src/browser/vscode/api/main.thread.api.webview.ts
if view container changed then display or hiding the webviewview
if view container changed then display or hiding the webviewview
=> fix: if view container changed then display or hiding the webviewview

packages/core-browser/src/menu/next/menu-id.ts, packages/testing/src/browser/test-decorations.ts, packages/testing/src/browser/testing.contribution.ts, packages/testing/src/common/commands.ts
Testing decorations 支持右键菜单触发 run&debug testing
=> feat: support testing decorations glyph contextmenu

packages/comments/package.json, packages/comments/src/browser/comments-body.tsx, packages/comments/src/browser/comments-item.view.tsx, packages/extension/src/common/vscode/converter.ts, packages/markdown/package.json, packages/markdown/src/browser/markdown.service.ts, packages/overlay/package.json, packages/overlay/src/browser/message.service.tsx, packages/startup/package.json, tools/dev-tool/package.json, tools/electron/package.json
fixed security alerts.
upgrade marked and node-notifier for security
=> chore: upgrade marked and node-notifier for security

packages/file-tree-next/src/browser/services/file-tree-api.service.ts, packages/file-tree-next/src/browser/services/file-tree-model.service.ts
fixed #404, #403 
improve file move and contextMenu operation UX
=> fix: improve file move and contextMenu operation UX

packages/components/src/recycle-tree/basic/tree-node.tsx, packages/monaco-enhance/src/browser/peek-view.ts, packages/testing/src/browser/outputPeek/test-message-container.tsx, packages/testing/src/browser/outputPeek/test-peek-widget.less, packages/testing/src/browser/outputPeek/test-peek-widget.tsx, packages/testing/src/browser/outputPeek/test-tree-container.tsx, packages/testing/src/browser/test-decorations.ts, packages/testing/src/browser/test-tree-view.model.ts, packages/testing/src/browser/testing.contribution.ts, packages/testing/src/common/testingStates.ts
同时修复 hide peekwidget 之后控制台报错的问题
支持按 esc 隐藏 testing outputpeek view 视图
=> feat: support testing outputpeek view hide

packages/extension/src/hosted/api/vscode/ext.host.workspace.ts, packages/types/vscode/typings-pending/vscode.proposed.d.ts
typescript-language-feature@1.61.2 depends on the trust api
requestWorkspaceTrust api happ impl
=> chore: requestWorkspaceTrust api happ impl

package.json, packages/core-browser/src/components/select/index.tsx, tools/electron/README.md, tools/electron/package.json
fix #416 
fix npm run start:electron
=> fix: npm run start:electron

packages/core-browser/src/components/actions/styles.module.less, packages/extension-manager/src/browser/vsx-extension.module.less, packages/menu-bar/src/browser/menu-bar.module.less, packages/preferences/src/browser/preferences.module.less, packages/quick-open/src/browser/styles.module.less, tools/dev-tool/src/index.html
for #385 ，一些不希望用户可以选中文本的场景没有禁止这个功能
修复了 5 处我发现的
=> fix: fix some text unexpected select

packages/addons/src/browser/file-search.contribution.ts
quicksearch possible infinite recursion
=> fix: quicksearch possible infinite recursion

packages/testing/src/browser/testing.contribution.ts, packages/testing/src/common/commands.ts
测试资源管理器面板支持运行所有测试、调试所有测试、清除所有测试结果三个菜单
=> feat: support testing explorer actions menu

packages/monaco/package.json
=> chore: upgrade monaco-editor version

packages/scm/src/browser/components/scm-resource-tree/scm-tree-model.service.ts
open with editor open if scm node no command
=> fix: open with editor open if scm node no command

CONTRIBUTING-zh_CN.md, CONTRIBUTING.md, README-zh_CN.md
Update canvas_binary_host_mirror url
=> docs: update zh document

packages/extension/src/hosted/api/vscode/ext.host.output.ts
和终端原理一样，在插件频繁调用 outputChannel.append 时批量发送到前端
https://github.com/opensumi/core/pull/304
- add message batcher for output channel
=> feat: add message batcher for output channel

packages/components/src/select/index.tsx, packages/components/src/select/style.less, packages/preferences/src/browser/preferenceItem.view.tsx, packages/preferences/src/browser/preferences.view.tsx, packages/theme/src/common/color-tokens/custom/select.ts
close: #419
Select component: show warning when select value is invalid
=> feat: show warning when select value is invalid

packages/editor/src/browser/editor.decoration.service.ts
before:
after:
editor decoration alignment
=> fix: editor decoration alignment

packages/core-common/src/utils/arrays.ts, packages/extension/src/hosted/api/telemetry/ext.host.api.impl.ts, packages/extension/src/hosted/ext.host.ts
具体的 api 实现还没写，先暂时挖个坑
拦截 telemetry 模块的实现
=> feat: intercept telemetry module 

packages/startup/package.json
支持Dev过程中Node进程的watch和自动重启
之前修改Node代码后需要手动重新运行Node程序才可以应用最新代码
- 引入Nodemon
- Nodemon自定义配置
=> feat: support node watch reload

packages/extension/src/hosted/api/vscode/ext.host.terminal.ts, packages/terminal-next/__tests__/node/pty.test.ts, packages/terminal-next/src/common/pty.ts, packages/terminal-next/src/node/pty.ts, packages/terminal-next/src/node/terminal.service.ts
I think this compatibility should remove on 2.17.0
compatible with 2.14.x
=> chore: compatible with 2.14.x

packages/extension/src/common/vscode/ext-types.ts, packages/extension/src/hosted/api/vscode/ext.host.api.impl.ts, packages/types/vscode/typings/vscode.d.ts
- Add missing TerminalLink definition
=> fix: add missing TerminalLink definition

.github/workflows/release.yml
=> chore: move create release log

packages/testing/src/browser/testing.contribution.ts
修复 OpenerContribution 控制台报错的问题
=> fix: remove OpenerContribution in testing contribution

.github/workflows/pr-next-release.yml, .github/workflows/pre-release.yml, .github/workflows/release-check.yml, .github/workflows/release.yml
add permission check logic on workflow
=> chore: add permission check logic on workflow

packages/startup/package.json
增加core-browser到nodemon ignore
避免不必要的node重启
=> feat: add core-browser nodemon ignore

packages/extension/src/hosted/ext.host.ts
=> fix: missing sumi api

packages/theme/src/common/color-tokens/index.ts
- remove useless self re-export
=> chore: remove self re-export

packages/scm/src/browser/components/scm-resource-tree/scm-tree-model.service.ts
This reverts commit d87bf44b6adffb676ed7baa76ac2e6f6294d9a4a.
=> Revert "fix: open with editor open if scm node no command (#426)"

packages/terminal-next/src/browser/terminal.service.ts
模板字符串中变量运行时调用 toString 方法导致输出 [object Object]
修复关闭终端时打印日志不完整的问题
=> chore: update close terminal log

packages/components/src/style/base.less, packages/file-tree-next/src/browser/file-tree-contribution.ts, packages/file-tree-next/src/browser/file-tree.module.less, packages/file-tree-next/src/browser/file-tree.tsx, packages/file-tree-next/src/browser/services/file-tree-model.service.ts
fixed #483
always show paste menu while has paste content
=> fix: always show paste menu while has paste content

packages/editor/src/browser/tab.view.tsx
before
after
- 优化编辑器 tab 栏加载中图标
=> feat: 💄 update loading icon for editor tab

packages/components/src/input/ValidateInput.tsx, packages/components/src/select/index.tsx, packages/core-browser/src/preferences/preference-contribution.ts, packages/editor/src/browser/preference/schema.ts, packages/i18n/src/common/en-US.lang.ts, packages/i18n/src/common/zh-CN.lang.ts, packages/preferences/src/browser/preferenceItem.view.tsx
fixed #440, #473
also fix `fontWeight` configuration define.
show correct values on preference setting view
=> fix: show correct values on preference setting view

packages/terminal-next/src/browser/terminal.client.ts
拆分终端时因为是在同一个组件，terminal widget 渲染较早，导致 terminalClient 没有监听到 onShow 事件，进而导致后续一系列事件都没有监听(因为依赖 onShow 里将 deferred resolve 掉)
在 widget show 已经为 true 时将 deferred resolve，否则等待 onShow 事件
- 修复拆分终端场景下无法监听终端设置的问题
=> fix: terminal widget show event

packages/monaco/package.json
回退 monaco editor 到 0.29.1-patch.1 版本
=> fix: downgrade monaco version

packages/types/package.json
=> chore: types build scripts

.github/workflows/release.yml
=> chore: fix release workflow changelog generate

packages/core-browser/package.json, packages/core-browser/src/style/icon/ide-iconfont.ts
=> fix: use codicon resource from CDN

packages/editor/src/browser/editor.module.less, packages/editor/src/browser/tab.view.tsx
=> fix: editor tab loading style

packages/connection/__test__/node/index.test.ts, packages/core-browser/src/bootstrap/app.ts, packages/core-browser/src/react-providers/config-provider.tsx, packages/core-common/src/node/port.ts, packages/debug/src/browser/debugUtils.ts, packages/express-file-server/__tests__/browser/index.test.ts, packages/express-file-server/__tests__/node/index.test.ts, packages/express-file-server/src/browser/file-server.contribution.ts, packages/express-file-server/src/common/index.ts, packages/extension/__tests__/hosted/api/vscode/ext.host.debug.test.ts, packages/extension/src/browser/extension-worker.service.ts, packages/remote-cli/src/index.ts, packages/remote-opener/__tests__/browser/remote-opener-converter.test.ts, packages/remote-opener/__tests__/browser/remote.opener.service.test.ts, packages/remote-opener/src/browser/remote.opener.service.ts, packages/startup/entry/web-lite/lite-module/file-provider/index.contribution.ts, packages/startup/entry/web/render-app.tsx, packages/static-resource/src/browser/static.definition.ts, packages/terminal-next/__tests__/browser/render.test.ts, tools/dev-tool/src/webpack.js
=> chore: replace 127.0.0.1 to 0.0.0.0

packages/electron-basic/src/browser/header/header.tsx
支持 Electron Header 是否自动隐藏。默认行为是在 macOS 的全屏自动隐藏 Header
支持 Electron Header 自动隐藏能力
=> feat: display the remote title in the remote mode

README-zh_CN.md, README.md, packages/i18n/src/common/en-US.lang.ts, packages/startup/entry/sample-modules/editor-empty-component.contribution.tsx
=> chore: update readme

.github/workflows/check.yml, .github/workflows/ci.yml
=> chore: update workflows scripts

.github/workflows/pre-release.yml, .github/workflows/release.yml, scripts/changelog/github.ts, scripts/changelog/index.ts, scripts/changelog/run.ts, scripts/changelog/util.ts
针对 Release 打包链路，优先使用 TAG 信息进行 Changelog 解析
过滤掉空 changelog 的 PR
=> chore: use tag to generate changelog

packages/preferences/src/browser/preferenceItem.view.tsx
fix re-render errors on preference view
=> fix: re-render errors on preference view

README-zh_CN.md
=> docs: fix a typo

packages/terminal-next/src/browser/terminal.client.ts, packages/terminal-next/src/node/pty.ts, packages/terminal-next/src/node/terminal.service.client.ts
close: #542
use home dir as initial cwd when workspace is invalid
=> feat(terminal): use home dir as initial cwd

packages/preferences/src/browser/preferenceItem.view.tsx
change handlerValueChange deps and function name
=> fix: change handlerValueChange deps and function name

NOTICE.md, packages/core-browser/src/encoding-registry.ts, packages/core-common/src/contribution-provider.ts, packages/core-common/src/utils/file-uri.ts, packages/editor/src/browser/monaco-contrib/tokenizer/textmate-registry.ts, packages/extension-manager/src/common/vsx-registry-types.ts, packages/extension/src/hosted/api/vscode/language/code-action.ts, packages/extension/src/hosted/api/vscode/language/declaration.ts, packages/extension/src/hosted/api/vscode/language/implementation.ts, packages/extension/src/hosted/api/vscode/language/lens.ts, packages/extension/src/hosted/api/vscode/language/on-type-formatting.ts, packages/extension/src/hosted/api/vscode/language/outline.ts, packages/extension/src/hosted/api/vscode/language/range-formatting.ts, packages/extension/src/hosted/api/vscode/language/type-definition.ts, packages/extension/src/hosted/api/vscode/language/workspace-symbol.ts, packages/file-service/src/common/files.ts, packages/file-service/src/node/file-change-collection.ts, packages/file-service/src/typings/drivelist.d.ts, packages/quick-open/src/browser/prefix-quick-open.service.ts, packages/quick-open/src/browser/quick-open-action-provider.ts, packages/task/src/browser/problem-collector.ts, packages/task/src/browser/problem-line-matcher.ts, typings/file-icons-js/index.d.ts
thanks [如何评价阿里 & 蚂蚁自研 IDE 研发框架 OpenSumi？ - WorldHello的回答 - 知乎](https://www.zhihu.com/question/519740662/answer/2372678679)
add NOTICE.md file
=> chore: add NOTICE.md file

CONTRIBUTING-zh_CN.md, CONTRIBUTING.md
修改了一些英语翻译上的问题
修改了`CONTRIBUTION`文件第一段。
=> chore: use correct statement in CONTRIBUTION

packages/core-browser/src/react-providers/slot.tsx, packages/startup/package.json
fix
- remove resize wrapper background color
=> fix: remove resize wrapper background color

packages/types/vscode/typings/vscode.d.ts, packages/types/vscode/typings/vscode.proposed.d.ts
=> fix: FilePermission type

packages/core-browser/src/style/monaco-override.less, packages/terminal-next/src/browser/component/terminal.module.less
before
aftar
- improve editor and terminal search widget styles
=> chore: improve editor and terminal search widget styles

packages/core-browser/src/components/recycle-tree/recycle-tree.view.tsx
link #592
add a deprecated warning on DeprecatedRecycleTree
=> chore: add deprecated warning on DeprecatedRecycleTree

packages/core-browser/src/quick-open/index.ts, packages/extension/src/browser/vscode/api/main.thread.quickopen.ts, packages/extension/src/common/vscode/window.ts, packages/extension/src/hosted/api/vscode/ext.host.quickopen.ts, packages/i18n/src/common/en-US.lang.ts, packages/i18n/src/common/zh-CN.lang.ts, packages/quick-open/src/browser/quick-input-service.ts, packages/quick-open/src/browser/quick-open.service.tsx, packages/quick-open/src/browser/quick-open.view.tsx, packages/quick-open/src/browser/quick-open.widget.tsx, packages/quick-open/src/browser/quick-title-bar.ts, packages/quick-open/src/browser/quickInput.inputBox.ts
close: #563 
close: #314
通过 `vscode.window.createInputBox` 创建的 InputBox 可以动态更新显示效果了
=> refactor(ext): improve createInputBox behavior

CONTRIBUTING-zh_CN.md
=> chore: update contributing

packages/editor/src/browser/navigation.module.less, packages/editor/src/browser/navigation.view.tsx
before
after
- improve  breadcrumb menus style
=> feat: improve breadcrumb style

packages/extension/src/browser/extension-node.service.ts, packages/main-layout/src/browser/tabbar/tabbar.service.ts
Fix extension register container hidden state not restore
=> fix(ext): restore container hidden state

packages/components/src/style/base.less, packages/main-layout/src/browser/tabbar/bar.view.tsx, packages/main-layout/src/browser/tabbar/panel.view.tsx, packages/main-layout/src/browser/tabbar/styles.module.less
- improve some bottom lines style
=> chore: improve some lines styles

packages/components/src/recycle-tree/tree/TreeNode.ts
close #629
- add tree operation lock
=> feat: add tree operation lock

packages/search/src/browser/search.input.widget.tsx, packages/search/src/browser/search.module.less, packages/search/src/browser/search.rules.widget.tsx
before
after
- improve search panel style
=> fix: search panel styles

packages/components/src/recycle-tree/prompt/PromptHandle.ts
修复创建文件时样式问题   close #628  
before
after
- fix validate style when create file
=> fix: validate style while create file

packages/editor/src/browser/grid/grid.service.ts, packages/editor/src/browser/workbench-editor.service.ts, packages/opened-editor/__tests__/browser/opened-editor.service.test.ts, packages/opened-editor/src/browser/services/opened-editor-event.service.ts, packages/opened-editor/src/browser/services/opened-editor-tree.service.ts
close #630
use sorted editor groups
=> fix: use sorted editor groups

packages/extension/src/browser/vscode/contributes/menu.ts, packages/i18n/src/common/en-US.lang.ts, packages/i18n/src/common/zh-CN.lang.ts
=> fix: add missing i18n

packages/components/package.json, packages/components/src/menu/MenuItem.tsx, packages/components/src/menu/SubMenu.tsx, packages/components/src/menu/index.tsx, packages/core-browser/package.json, packages/core-browser/src/components/actions/index.tsx
closes [#531 ](https://github.com/opensumi/core/issues/531)
related: [#409](https://github.com/opensumi/core/issues/409) [#530](https://github.com/opensumi/core/pull/530)
update rc-menu to 9
=> feat: update rc-menu to 9

packages/editor/src/browser/doc-model/saveParticipants.ts, packages/workspace-edit/src/browser/bulk-edit.service.ts
fixes: #654
- support `source.fixAll` actions from extension
=> feat: support source fixall from extension

packages/storage/src/browser/storage.service.ts
减少重复 IO
- optimize storage init logic
=> feat: optimize storage init logic

packages/core-browser/src/monaco/index.ts, packages/editor/src/browser/monaco-contrib/tokenizer/textmate.service.ts, packages/extension/__tests__/browser/main.language.test.ts, packages/extension/__tests__/browser/main.thread.editor.test.ts, packages/extension/__tests__/browser/main.thread.task.test.ts, packages/extension/__tests__/browser/main.thread.workspace.test.ts, packages/extension/__tests__/browser/vscode.contributes.test.ts, packages/extension/src/browser/extension.contribution.ts, packages/extension/src/browser/vscode/api/main.thread.language.ts, packages/monaco/__mocks__/monaco-loader.ts, packages/monaco/__mocks__/monaco.service.mock.ts, packages/monaco/__tests__/browser/monaco-command.test.ts, packages/monaco/__tests__/browser/monaco-service.test.ts, packages/monaco/__tests__/browser/textmate.test.ts, packages/monaco/src/browser/monaco.contribution.ts, packages/monaco/src/browser/monaco.service.ts, packages/output/__tests__/browser/output.service.test.ts, packages/task/__test__/browser/task.service.test.ts
- remove deprecated `monacoLoaded` logic
=> chore: remove some dead code

packages/extension/src/hosted/ext.process-base.ts, packages/i18n/src/common/en-US.lang.ts, packages/i18n/src/common/zh-CN.lang.ts, packages/preferences/src/browser/preference-settings.service.ts, packages/terminal-next/src/browser/terminal.client.ts, packages/terminal-next/src/browser/terminal.preference.ts, packages/terminal-next/src/browser/xterm.ts, packages/terminal-next/src/common/preference.ts
close: #644 
Support terminal `copyOnSelection` preference
=> feat(terminal): support copyOnSelection

packages/extension/src/browser/vscode/api/main.thread.output.ts, packages/extension/src/common/vscode/ext-types.ts, packages/extension/src/common/vscode/window.ts, packages/extension/src/hosted/api/vscode/ext.host.output.ts, packages/output/__tests__/browser/output.channel.test.ts, packages/output/src/browser/output.channel.ts, packages/types/vscode/typings/vscode.window.d.ts
close #577 
- add outputChannel replace API
=> feat: add outputChannel replace API

packages/core-electron-main/src/bootstrap/window.ts
Electron main process error truncate log
=> fix: electron main process log error truncate

packages/core-browser/src/hash-calculate/hash-calculate.contribution.ts, packages/extension-storage/__tests__/browser/storage.test.ts, packages/extension-storage/src/browser/index.ts, packages/extension-storage/src/browser/storage-path.ts, packages/extension/__tests__/browser/main.thread.workspace.test.ts, tools/dev-tool/src/injector-helper.ts
close: #627
Use WebAssembly Hash in extension storage
=> feat: extension storage use wasm hash

packages/core-browser/src/common/common.command.ts, packages/file-tree-next/__tests__/browser/file-tree-contribution.test.ts, packages/file-tree-next/src/browser/file-tree-contribution.ts, packages/file-tree-next/src/browser/file-tree.service.ts, packages/file-tree-next/src/browser/file-tree.tsx, packages/file-tree-next/src/browser/services/file-tree-model.service.ts
Close: #670 
Close: #663
Improve file tree use experience
=> feat: improve filetree use experience

packages/extension/src/browser/extension.service.ts, packages/extension/src/browser/types.ts
- add extension initialzied event
=> feat: add extension inited event

packages/core-browser/src/bootstrap/app.ts, packages/core-browser/src/bootstrap/connection.ts, packages/core-browser/src/utils/electron.ts, packages/core-electron-main/browser-preload/index.js, packages/extension/src/browser/extension-node.service.ts, tools/electron/src/browser/app.tsx
Fix extension host cannot connect to backend
=> fix: ext host cannot create connection

packages/terminal-next/src/browser/terminal.client.ts, packages/terminal-next/src/browser/terminal.preference.ts, packages/terminal-next/src/browser/xterm.ts, packages/terminal-next/src/common/preference.ts
terminal's font fallback to use editor font
=> feat: terminal's font fallback to use editor font

packages/core-browser/src/react-providers/config-provider.tsx
=> chore: prune type imports for react-providers

packages/components/src/menu/MenuItem.tsx, packages/components/src/menu/SubMenu.tsx, packages/components/src/menu/index.tsx, packages/components/src/menu/style.less, packages/core-browser/src/components/actions/index.tsx
fixes: #690 
- fix: submenu hide issue
=> fix: submenu hide issue

.github/workflows/release.yml, scripts/changelog/run.ts
当 main 分支进行正式版本发布时，不使用 lerna 的 push 能力，创建回源 PR
=> chore: update release workflows

packages/addons/__test__/node/inde.test.ts, packages/addons/src/browser/connection-rtt-contribution.ts, packages/addons/src/browser/index.ts, packages/addons/src/common/index.ts, packages/addons/src/node/connection-rtt-service.ts, packages/addons/src/node/index.ts, packages/i18n/src/common/en-US.lang.ts, packages/i18n/src/common/zh-CN.lang.ts, packages/menu-bar/src/browser/menu-bar.module.less
command
- add `Developer Tool: Measure Connection RTT` command
=> feat: add connection rtt measure command for developer

packages/core-browser/src/monaco/index.ts, packages/editor/__tests__/browser/editor.feature.test.ts, packages/editor/src/browser/editor.contribution.ts, packages/editor/src/browser/index.ts, packages/editor/src/browser/menu/editor.context.ts, packages/monaco/src/browser/monaco.contribution.ts
https://user-images.githubusercontent.com/17701805/159426603-da5f2d0c-5630-4717-9fb7-92f4f0ab78e5.mp4
fixes: #694 
- refactor: editor context menu injection logic
=> refactor: editor context menu injection logic

packages/extension/src/browser/sumi/contributes/submenu.ts, packages/extension/src/browser/vscode/contributes/commands.ts, packages/extension/src/browser/vscode/contributes/icon.ts, packages/extension/src/browser/vscode/contributes/menu.ts, packages/extension/src/browser/vscode/contributes/view-containers.ts, packages/extension/src/common/index.ts
fixes: #647 
- viewsContainers support icon resolver
=> fix: viewsContainers icon resolver

packages/terminal-next/src/browser/terminal.client.ts, packages/terminal-next/src/browser/terminal.preference.ts, packages/terminal-next/src/browser/xterm.ts
=> feat: add more term preferences

packages/terminal-next/__tests__/browser/client.test.ts, packages/terminal-next/src/browser/component/tab.item.tsx, packages/terminal-next/src/browser/component/tab.module.less, packages/terminal-next/src/browser/component/tab.view.tsx, packages/terminal-next/src/browser/terminal.client.ts
https://user-images.githubusercontent.com/17701805/159620580-8efb4401-5509-4ff0-99cb-68c36ceaeeaa.mp4
- update terminal tab loading style
=> feat: update terminal tab loading style

packages/core-browser/src/common/common.command.ts, packages/i18n/src/common/en-US.lang.ts, packages/i18n/src/common/zh-CN.lang.ts, packages/terminal-next/src/browser/contribution/terminal.command.ts, packages/terminal-next/src/browser/contribution/terminal.keybinding.ts
https://user-images.githubusercontent.com/17701805/159872008-002cff1a-4fa5-44cc-93d3-8f9f244aac16.mp4
- support focus next or prev terminal by shortcuts
=> feat: support focus next or prev terminal by shortcuts

packages/core-browser/src/preferences/settings.ts, packages/editor/src/browser/workbench-editor.service.ts, packages/i18n/src/common/en-US.lang.ts, packages/i18n/src/common/zh-CN.lang.ts, packages/preferences/src/browser/folders-preferences-provider.ts, packages/preferences/src/browser/preference-contribution.ts, packages/preferences/src/browser/preference-settings.service.ts, packages/preferences/src/browser/preferenceItem.view.tsx, packages/preferences/src/browser/preferences.view.tsx
=> feat: adjust preference behavior

packages/components/src/recycle-tree/prompt/PromptHandle.ts, packages/components/src/recycle-tree/tree/TreeNode.ts, packages/file-tree-next/__tests__/browser/file-tree.test.ts, packages/file-tree-next/src/browser/file-tree-node.module.less, packages/file-tree-next/src/browser/file-tree.service.ts, packages/file-tree-next/src/browser/file-tree.tsx, packages/file-tree-next/src/browser/services/file-tree-api.service.ts, packages/file-tree-next/src/browser/services/file-tree-model.service.ts, packages/file-tree-next/src/common/file-tree-node.define.ts
=> fix: file tree focus issue

packages/extension/src/common/index.ts, packages/startup/package.json
=> fix: icon contributes

.github/workflows/next-release.yml, .github/workflows/pr-next-release.yml
this close: #612
Add action which can manual release from a specific ref
=> ci: add manual release

packages/components/src/recycle-tree/tree/model/TreeModel.ts, packages/file-service/src/common/files.ts, packages/file-tree-next/src/browser/file-tree-contribution.ts, packages/file-tree-next/src/browser/file-tree.service.ts, packages/file-tree-next/src/browser/services/file-tree-model.service.ts
之前的 refresh 是一种类似 debounce 的效果，现在改成了 throttle 并且优化了一些逻辑，更快了。
https://user-images.githubusercontent.com/13938334/160142973-22411ac8-3531-405a-b7c6-bd360b1ebfcb.mp4
Optimize file tree refresh speed
=> feat: optimize refresh speed

.github/workflows/release.yml
=> chore: use github-script to create pr

packages/components/src/recycle-tree/tree/Tree.ts, packages/file-tree-next/__tests__/browser/file-tree.test.ts, packages/file-tree-next/src/browser/file-tree.service.ts, packages/file-tree-next/src/browser/services/file-tree-model.service.ts
=> chore: fix file tree service test

packages/main-layout/src/browser/tabbar/styles.module.less
=> fix: bottom border sizing

packages/core-common/src/settings/search.ts, packages/i18n/src/common/en-US.lang.ts, packages/i18n/src/common/zh-CN.lang.ts, packages/preferences/src/browser/preference-settings.service.ts, packages/search/src/browser/search-preferences.ts, packages/search/src/browser/search.service.ts, packages/search/src/browser/search.view.tsx
close: #480 
Support search on type
=> feat: support search on type

packages/components/src/notification/index.tsx, packages/core-browser/src/markdown/index.tsx, packages/core-browser/src/progress/progress.service.tsx
https://user-images.githubusercontent.com/20262815/160527110-d69256d6-3207-4d99-93db-3b2734ed142b.mp4
progress report 支持 command 链接语法
=> feat: support progress report markdown renderer

packages/extension/src/browser/extension.contribution.ts, packages/extension/src/browser/vscode/builtin-commands.ts
实现 workbench.action.openSettingsJson 命令
=> feat: implement openSettingsJson command

packages/terminal-next/src/browser/terminal.controller.ts, packages/terminal-next/src/browser/terminal.service.ts, packages/terminal-next/src/browser/terminal.view.ts, packages/terminal-next/src/common/pty.ts, packages/terminal-next/src/node/pty.manager.ts, packages/terminal-next/src/node/pty.proxy.ts, packages/terminal-next/src/node/pty.ts
=> fix: terminal title restore

packages/components/src/recycle-tree/tree/Tree.ts, packages/file-tree-next/__tests__/browser/file-tree.test.ts, packages/file-tree-next/src/browser/file-tree.service.ts, packages/file-tree-next/src/browser/services/file-tree-model.service.ts
=> chore: fix file tree service test (#744)

packages/components/src/recycle-list/RecycleList.tsx, packages/quick-open/src/browser/quick-input-service.ts, packages/quick-open/src/browser/quick-open.view.tsx, packages/quick-open/src/browser/quickInput.inputBox.ts
this close: #742 
this close: #752 
Fix quickinput may cause max stack exceed
=> fix: quickInput may cause max stack exceed

packages/task/src/browser/task.service.ts, packages/task/src/browser/terminal-task-system.ts, packages/task/src/common/index.ts, packages/terminal-next/src/browser/terminal.client.ts, packages/terminal-next/src/browser/terminal.controller.ts, packages/terminal-next/src/common/client.ts, packages/terminal-next/src/common/controller.ts
=> feat: support attach task by restored terminal

packages/terminal-next/src/browser/terminal.view.ts
https://user-images.githubusercontent.com/17701805/160971974-66324651-9575-4966-98d9-a0dcb98a2cb7.mp4
- auto focus last terminal when exit terminal
=> feat: auto focus last terminal when exit terminal

packages/core-browser/src/components/actions/styles.module.less, packages/core-browser/src/style/monaco-override.less, packages/core-browser/src/style/override.less, packages/editor/src/browser/navigation.module.less
=> fix: editor context menu style

packages/task/src/browser/task.service.ts, packages/task/src/browser/terminal-task-system.ts, packages/terminal-next/package.json, packages/terminal-next/src/browser/terminal.controller.ts
=> fix: wait for task registered event

packages/editor/__tests__/browser/resource.test.ts, packages/editor/src/browser/doc-model/editor-document-model-service.ts, packages/editor/src/browser/doc-model/editor-document-model.ts, packages/editor/src/browser/doc-model/types.ts, packages/editor/src/browser/fs-resource/fs-resource.ts, packages/editor/src/browser/untitled-resource.ts, packages/editor/src/browser/workbench-editor.service.ts, packages/editor/src/common/editor.ts, packages/editor/src/common/resource.ts
1. fixed #672 
原因是 untitled 文件之前设置永远是 dirty 导致 model 没有 dispose 掉
2. 新增 untitled 文件关闭时的提醒
new untitled dont dispose model
=> fix: new untitled dont dispose model

packages/connection/package.json, packages/extension/package.json
- update vscode-jronrpc@8.0.0-next.2
=> chore: update vscode-jronrpc@8.0.0-next.2

packages/core-browser/src/index.ts, packages/core-browser/src/terminal/index.ts, packages/task/src/browser/task.contribution.ts, packages/task/src/browser/task.service.ts, packages/terminal-next/package.json, packages/terminal-next/src/browser/terminal.client.ts, packages/terminal-next/src/browser/terminal.controller.ts
=> fix: use terminal client attached event

packages/status-bar/src/browser/status-bar.module.less
=> style: adjust statusbar icon style

packages/keymaps/src/browser/keymaps.service.ts, packages/keymaps/src/browser/keymaps.view.tsx
closed #789
修复后：
improve keymaps search speed
=> fix: improve keymaps search speed

scripts/add-node.ts
=> chore: remove useless code

packages/debug/__tests__/browser/launch-preferences.test.ts, packages/file-service/src/browser/file-service-client.ts, packages/file-service/src/node/file-service-watcher.ts, packages/preferences/src/browser/abstract-resource-preference-provider.ts, packages/preferences/src/browser/folders-preferences-provider.ts
=> feat: optimize file watcher logic

packages/components/src/menu/MenuItem.tsx, packages/debug/__tests__/browser/editor/editor-hover-contribution.test.ts, packages/debug/src/browser/debug-session-manager.ts, packages/debug/src/browser/editor/debug-editor-contribution.ts
修复在 debug 模式下 hover 变量提示与语言服务提示重复显示的问题
=> fix: debug alt hover options

packages/search/__tests__/browser/search-tree.service.test.ts, packages/search/__tests__/browser/search.service.test.ts, packages/search/src/browser/search.service.ts
1. 优化搜索按钮样式
before:
after:
change padding for search button
=> chore: change padding for search button 

packages/components/src/recycle-tree/tree/TreeNode.ts
该问题会导致压缩目录在刷新加载时被忽略
fix refresh while has compressed nodes
=> fix: refresh while has compressed nodes

packages/components/src/input/ValidateInput.tsx, packages/components/src/select/index.tsx, packages/core-browser/src/preferences/preference-contribution.ts, packages/editor/src/browser/preference/schema.ts, packages/i18n/src/common/en-US.lang.ts, packages/i18n/src/common/zh-CN.lang.ts, packages/preferences/src/browser/preferenceItem.view.tsx
(cherry-pick)fix: show correct values on preference setting view (#491)
=> (cherry-pick)fix: show correct values on preference setting view (#491)

packages/components/src/dialog/index.tsx, packages/components/src/overlay/index.tsx, packages/core-browser/src/common/common.command.ts, packages/core-browser/src/contextkey/dialog.ts, packages/core-browser/src/contextkey/index.ts, packages/i18n/src/common/en-US.lang.ts, packages/i18n/src/common/zh-CN.lang.ts, packages/overlay/src/browser/dialog.contextkey.ts, packages/overlay/src/browser/dialog.contribution.ts, packages/overlay/src/browser/dialog.service.ts, packages/overlay/src/browser/dialog.view.tsx, packages/overlay/src/browser/index.ts
close #814 
support ESC and Enter keyboard on the dialog
=> feat: support ESC and Enter keyboard on the dialog

packages/core-electron-main/src/bootstrap/window.ts
=> fix: set minimum font size to 12px

packages/terminal-next/__tests__/browser/client.test.ts, packages/terminal-next/__tests__/browser/inject.ts, packages/terminal-next/__tests__/browser/mock.service.ts, packages/terminal-next/package.json, packages/terminal-next/src/browser/component/terminal.module.less, packages/terminal-next/src/browser/terminal.client.ts, packages/terminal-next/src/browser/terminal.color.ts, packages/terminal-next/src/browser/terminal.search.ts, packages/terminal-next/src/browser/xterm.ts, packages/terminal-next/src/common/client.ts
closed #810 
https://user-images.githubusercontent.com/17701805/162893525-f74da22f-746f-4159-885f-e8e73b2dc327.mp4
- improve terminal search style
=> feat: improve terminal search matched styles

package.json, packages/extension/package.json
=> chore: update package.json

packages/debug/src/browser/view/console/debug-console.module.less, packages/debug/src/browser/view/console/debug-console.view.tsx
before
after
优化调试控制台表达式 icon 样式
=> chore: optimize debug console icon

packages/extension/src/hosted/api/vscode/debug/ext.host.debug.ts, packages/extension/src/hosted/api/vscode/debug/extension-debug-adapter-starter.ts, packages/extension/src/hosted/ext.process-base.ts
=> chore: update comments

jest.setup.js, package.json, packages/connection/src/browser/connect.ts, packages/connection/src/browser/index.ts, packages/connection/src/common/message.ts, packages/connection/src/common/proxy.ts, packages/core-browser/src/bootstrap/connection.ts
patch #839 
make runtime abstraction layer tobe correctly
=> fix: patch make runtime abstraction layer tobe correctly

packages/extension/src/browser/vscode/api/main.thread.api.impl.ts, packages/extension/src/common/vscode/index.ts
worker host add file decoration api
=> feat: worker host add file decoration api

packages/search/src/browser/search-tree.view.tsx, packages/search/src/browser/search.contribution.ts, packages/search/src/browser/search.service.ts, packages/search/src/browser/search.view.tsx
this close: #880
新增了当搜索条件变化时自动搜索，并且优化了当前激活的编辑器的选中状态。
=> feat: search on include/exclude change

packages/extension/src/browser/extension.service.ts, packages/extension/src/browser/types.ts
-  add ExtensionsInitializedEvent
=> feat: add ExtensionsInitializedEvent

packages/keymaps/__tests__/browser/keymaps.service.test.ts, packages/keymaps/src/browser/keymaps.module.less, packages/keymaps/src/browser/keymaps.service.ts, packages/keymaps/src/browser/keymaps.view.tsx, packages/keymaps/src/common/keymaps.ts
close #878 
顺便优化了快捷键面板表头样式及验证信息展示错误问题
improve keymaps modify and redo progress
=> fix: keymaps modify and redo progress

configs/vscode-extensions.json, tools/electron/config/vscode-extensions.json
close #879 
add available node debug extension version and remove missing extension
=> chore: add available node debug extension version and remove missing extension

packages/scm/src/browser/components/scm-resource-input.module.less, packages/scm/src/browser/components/scm-resource-tree/index.tsx
close #875 
修改前:
修改后：
improve SCM panel style
=> style: improve scm panel style

packages/editor/src/browser/fs-resource/fs-resource.ts
=> fix: fix race issue in fs-resource

packages/preferences/src/browser/preferences.view.tsx
close: #870 
Fix does not show preferences search results
=> fix(preference): do not show search results

packages/preferences/src/browser/preferences.view.tsx
=> fix(preferences): restore the previous behaviour

packages/extension/src/browser/types.ts
=> chore: remove duplicate identifier

packages/extension/src/common/vscode/languages.ts, packages/extension/src/hosted/api/vscode/ext.host.language.ts
=> fix: add fallback value for language features

packages/extension/__tests__/browser/main.language.test.ts, packages/extension/src/browser/vscode/api/main.thread.language.ts
fixed #852
- fix language features match issue
=> fix: language selector match logic

packages/terminal-next/src/browser/component/terminal.view.tsx, packages/terminal-next/src/browser/terminal.search.ts
- terminal support search on type
=> feat(terminal): support search on type

packages/core-browser/src/common/common.command.ts, packages/editor/__tests__/browser/editor.feature.test.ts, packages/editor/__tests__/browser/format.service.test.ts, packages/editor/src/browser/editor.contribution.ts, packages/editor/src/browser/format/format.service.ts, packages/editor/src/browser/format/formatterSelect.ts, packages/i18n/src/common/en-US.lang.ts, packages/i18n/src/common/zh-CN.lang.ts, packages/monaco/src/browser/monaco.contribution.ts
closed #820 
- support format document with menu
=> feat: support format document with menu

packages/terminal-next/__tests__/browser/inject.ts, packages/terminal-next/__tests__/browser/terminal.service.test.ts, packages/terminal-next/src/browser/terminal.client.ts, packages/terminal-next/src/browser/terminal.internal.service.ts, packages/terminal-next/src/browser/terminal.service.ts, packages/terminal-next/src/browser/xterm.ts, packages/terminal-next/src/common/pty.ts, packages/terminal-next/src/common/service.ts, packages/terminal-next/src/common/xterm.ts, packages/terminal-next/src/node/terminal.service.client.ts
=> refactor: adjust attachByLaunchConfig params

.github/workflows/release.yml
=> chore: fix pr create workflow

packages/terminal-next/src/browser/component/tab.view.tsx
default:
out of range:
fix: plus icon follows the terminal tab
=> fix: plus icon follows the terminal tab

packages/components/src/input/ValidateInput.tsx
Fix password input box UI error.
=> fix: input box password ui error

packages/core-browser/src/style/normalize.less, packages/core-browser/src/style/variable.less
before
after
- add base font size variable
=> feat: add base font size variable

configs/vscode-extensions.json, tools/electron/config/vscode-extensions.json
update builtin debug extension version
=> chore: update builtin debug extension version

packages/editor/__tests__/browser/editor.feature.test.ts, packages/editor/src/browser/format/format.service.ts, packages/editor/src/browser/format/formatterSelect.ts
=> fix: handle format selector mode argument

packages/debug/__tests__/browser/debug-session-connection.test.ts, packages/explorer/src/browser/explorer-contribution.ts, packages/file-tree-next/__tests__/browser/file-tree-contribution.test.ts, packages/file-tree-next/src/browser/file-tree-contribution.ts, packages/file-tree-next/src/common/index.ts, packages/opened-editor/src/browser/opened-editor.contribution.ts, packages/opened-editor/src/browser/services/opened-editor-model.service.ts, packages/outline/__tests__/browser/services/outline-model.service.test.ts, packages/outline/src/browser/outline-node.define.ts, packages/outline/src/browser/outline-node.tsx, packages/outline/src/browser/outline.contribution.ts, packages/outline/src/browser/outline.tsx, packages/outline/src/browser/services/outline-model.service.ts, packages/outline/src/common/index.ts
大纲折叠的情况下不再响应文件内容修改的更新，减少页面多余的重绘操作
优化 Outilne 面板更新逻辑
=> feat: improve outline tree update progress

packages/core-common/src/types/markdown.ts, packages/extension/src/common/vscode/converter.ts, packages/extension/src/common/vscode/ext-types.ts
* add `supportHtml` property to `MarkdownString`
=> feat: MarkdownString 添加 supportHtml 属性

packages/preferences/src/browser/abstract-resource-preference-provider.ts, packages/preferences/src/browser/folders-preferences-provider.ts
=> fix: preference change event

packages/extension/src/hosted/api/vscode/debug/extension-debug-adapter-tracker.ts
修复 DebugAdapterTracker 的 message 类型错误问题
=> fix: debugAdapterTracker message type error

packages/connection/src/common/rpcProtocol.ts
rpcProtocol 支持 ArrayBuffer 消息类型
=> feat: support rpcProtocol handle arraybuffer message type

packages/terminal-next/src/node/pty.proxy.ts
去除终端里面Terminal RESTORE的提示
功能本身不是很完善 + 避免用户误解
#938
=> feat: remove terminal restore hint

packages/components/package.json, packages/core-browser/src/components/recycle-tree/recycle-tree.view.tsx, packages/core-common/package.json, packages/utils/package.json
=> chore: update @opensumi/ide-utils version

packages/terminal-next/src/browser/terminal.client.ts, packages/terminal-next/src/browser/terminal.controller.ts, packages/terminal-next/src/browser/terminal.internal.service.ts, packages/terminal-next/src/browser/terminal.view.ts, packages/terminal-next/src/common/pty.ts
=> fix: extension terminal recovery

jest.setup.jsdom.js, jest.setup.node.js, package.json, packages/terminal-next/__tests__/node/pty.test.ts, tools/electron/package.json
=> test: use jest-canvas-mock

packages/file-tree-next/src/browser/file-tree.tsx
=> chore: remove filetree renderer effect

packages/workspace/src/browser/workspace-variable-contribution.ts
close #927 
fix windows variables paths
=> fix: windows variables paths

configs/vscode-extensions.json
upgrade builtin vscode git extension version, close #574
=> chore: upgrade builtin vscode git extension version

.github/ISSUE_TEMPLATE/-------question--.md
=> chore: add question issue template

.github/workflows/ci.yml, codecov.yml
=> chore: update codecov

README-zh_CN.md, README.md
=> chore: add contributors image and add emoji icons

packages/addons/src/browser/file-drop.service.ts, packages/addons/src/common/index.ts, packages/addons/src/node/file-drop.service.ts
=> fix: nonstandard rpc method

packages/components/src/recycle-tree/tree/TreeNode.ts, packages/file-tree-next/src/browser/services/file-tree-model.service.ts
fix recycle tree snapshot recovery logic
=> fix: recycle tree snapshot recovery logic

packages/editor/src/browser/editor.view.tsx, packages/editor/src/browser/index.ts, packages/editor/src/browser/menu/open-type-menu.contribution.ts, packages/editor/src/browser/workbench-editor.service.ts, packages/i18n/src/common/en-US.lang.ts, packages/i18n/src/common/zh-CN.lang.ts
PS: 如果资源文件仅有一种打开方式，则不显示该菜单项
https://user-images.githubusercontent.com/20262815/167248947-9c0e62f2-c221-44ee-9367-a4679e728828.mp4
编辑器右上角区域支持切换文件打开方式
=> feat: support openType menu in editor/title

packages/terminal-next/__tests__/browser/client.test.ts, packages/terminal-next/src/browser/component/tab.module.less, packages/terminal-next/src/browser/terminal.client.ts, packages/terminal-next/src/browser/terminal.view.ts
=> fix: terminal title fallback to default name

packages/editor/src/browser/workbench-editor.service.ts, packages/editor/src/common/editor.ts, packages/file-tree-next/src/browser/file-tree-contribution.ts, packages/markers/__tests__/browser/markes-service.test.ts
fix changeOpenType function type error
=> chore: fix changeOpenType function type error

packages/terminal-next/src/browser/component/tab.item.tsx, packages/terminal-next/src/browser/terminal.view.ts, packages/terminal-next/src/common/render.ts
=> fix: use observer for terminal view component

tools/dev-tool/package.json
=> chore: update terser deps

packages/extension/__tests__/node/extension.host.manager.common-tester.ts, packages/terminal-next/__tests__/node/pty.manager.test.ts
=> chore: fix pty manager test case

packages/core-browser/src/style/override.less, packages/monaco/src/browser/monaco.contribution.ts, packages/startup/entry/sample-modules/status-bar.contribution.ts
closed #920 
before
after
- support icontheme on editor
=> feat: patch monaco theme service

tools/dev-tool/src/webpack.js
修复在 Windows 下拼接的 worker-host 路径异常
=> fix: worker-host static uri resource

packages/file-scheme/src/browser/file-scheme.contribution.ts
untitled 文件仅支持 type 为 code 的打开方式
=> fix: untitled file render other editor component

packages/debug/src/browser/view/variables/debug-variables-tree.model.service.ts
=> fix: debug variables ThrottledDelayer cancel

packages/core-browser/src/components/layout/split-panel.tsx
=> chore: fix a typo

packages/editor/src/browser/menu/open-type-menu.contribution.ts
=> fix: toggle editor group opentype error

packages/debug/src/browser/view/watch/debug-watch-tree.model.service.ts
=> fix: debug watch ThrottledDelayer cancel

package.json, packages/extension/__tests__/node/baseInjector.ts, packages/extension/__tests__/node/extension.service.client.test.ts, packages/extension/src/node/extension.service.client.ts, packages/startup/entry/web-lite/lite-module/overrides/doc-client.ts, packages/startup/package.json, tools/electron/package.json
=> chore: uniformly use same md5 service

.github/workflows/manual-release-rc.yml
=> ci: update workflow

configs/vscode-extensions.json, packages/core-common/src/const/application.ts, packages/core-node/src/bootstrap/app.ts, packages/extension-manager/src/browser/extension-overview/index.tsx, packages/extension-manager/src/browser/extension/index.tsx, packages/extension-manager/src/browser/vsx-extension.service.ts, packages/extension-manager/src/node/vsx-extension.service.ts, scripts/download.js, tools/dev-tool/src/server.ts, tools/electron/config/vscode-extensions.json, tools/electron/src/node/server.ts
测试下来我这边本地网络，国内镜像安装插件的速度有 10 倍左右的速度优化
https://marketplace.smartide.cn：
https://open-vsx.org：
support OpenVSX China mirror
=> feat: support OpenVSX China mirror

packages/file-service/src/node/file-service-watcher.ts
fixed  #867
- remove some temporary fileservice event
=> fix: remove some temporary fs event

packages/extension/webpack.config.ext-host.js, tools/dev-tool/src/webpack.js
=> chore: full sourcemap ability support

README.md
fix link bug in README.md file
=> docs: fix link bug in README.md file

packages/core-browser/__tests__/services/clipboard.service.test.ts, packages/core-browser/__tests__/services/external-uri.service.test.ts, packages/extension/__tests__/browser/extension.test.ts, packages/extension/__tests__/browser/index.test.ts, packages/extension/__tests__/common/activator.test.ts, packages/extension/__tests__/common/require-interceptor.test.ts, packages/extension/__tests__/hosted/api/vscode/editor/editor.host.test.ts, packages/extension/__tests__/hosted/api/vscode/ext.host.quickopen.test.ts, packages/extension/__tests__/hosted/api/vscode/ext.host.terminal.test.ts, packages/extension/__tests__/hosted/ext.host.proxy.test.ts, packages/extension/__tests__/node/extension.host.manager.common-tester.ts, packages/quick-open/__tests__/browser/prefix-quick-open.service.test.ts, packages/quick-open/__tests__/browser/quick-open.service.test.ts, packages/quick-open/__tests__/browser/quick-pick.service.test.ts, tools/dev-tool/__tests__/mock-injector.test.ts
=> test: change __dirname in test file to a string

packages/terminal-next/src/browser/terminal.addon.ts, packages/terminal-next/src/browser/terminal.client.ts, packages/terminal-next/src/node/pty.manager.ts
增加对Terminal性能的监控
增加了一些IPC监控，以及补充了一些旧代码的注释。
=> feat: support trace terminal

packages/scm/src/browser/components/scm-resource-tree/scm-tree-node.ts
before
after
- scm resource tree node uri
=> fix: scm resource tree node uri

.github/ISSUE_TEMPLATE/-------bug-report--.md
=> chore: update issue bug report format

packages/components/src/recycle-tree/RecycleTree.tsx, packages/debug/__tests__/browser/tree/debug-tree-node.define.test.ts, packages/debug/src/browser/debug-link-detector.ts, packages/debug/src/browser/debug-session.ts, packages/debug/src/browser/tree/debug-console-tree-node.define.tsx, packages/debug/src/browser/tree/debug-tree-node.define.ts, packages/debug/src/browser/view/console/debug-console.view.tsx
close #1066
support use top-level await on debug console
=> fix: use top-level await on debug console

packages/file-search/__tests__/node/file-search.service.test.ts, packages/file-search/src/node/file-search.service.ts
before:
after:
support search hidden file
=> fix: support search hidden file

packages/components/__tests__/recycle-tree/tree/TreeNode.test.ts, packages/components/src/recycle-tree/tree/TreeNode.ts, packages/file-tree-next/src/browser/file-tree-contribution.ts, packages/file-tree-next/src/browser/file-tree.service.ts, packages/file-tree-next/src/browser/services/file-tree-api.service.ts, packages/file-tree-next/src/browser/services/file-tree-dnd.service.ts, packages/file-tree-next/src/browser/services/file-tree-model.service.ts, packages/file-tree-next/src/common/file-tree-node.define.ts
cherry-pick #1095 
弱化文件树对于文件事件依赖，优化文件树操作响应速度
=> fix: cherry-pick #1095

package.json, packages/addons/src/browser/toolbar-customize/toolbar-customize.contribution.ts, packages/main-layout/src/browser/layout.service.ts, packages/main-layout/src/browser/tabbar-handler.ts, packages/main-layout/src/browser/tabbar/tabbar.service.ts, packages/main-layout/src/common/main-layout.defination.ts, packages/terminal-next/__tests__/browser/mock.service.ts, packages/terminal-next/src/browser/component/terminal.view.tsx, packages/terminal-next/src/browser/terminal.controller.ts, packages/terminal-next/src/common/controller.ts, tools/dev-tool/package.json, tools/electron/package.json
pls see:
- https://github.com/opensumi/core/discussions/1031
Wait for tabbar service ready
=> fix: wait for tabbar service ready

packages/i18n/src/common/en-US.lang.ts
=> chore: fix typos in i18n

packages/main-layout/src/browser/layout.service.ts
pls see:
- https://github.com/opensumi/core/discussions/1031
Ensure restore tabbar before layout ready
=> fix: ensure restore tabbar before layout ready 

packages/main-layout/src/browser/layout.service.ts
=> Revert "fix: ensure restore tabbar before layout ready "

packages/terminal-next/__tests__/browser/mock.service.ts, packages/terminal-next/src/browser/terminal.controller.ts
=> chore: fix merge conflict

packages/extension/src/browser/vscode/api/main.thread.api.impl.ts, packages/extension/src/hosted/api/vscode/ext.host.statusbar.ts, packages/extension/src/hosted/api/worker/worker.host.api.impl.ts
=> fix: some worker host api issue

packages/extension/package.json
yargs miss in extension package
=> chore: yargs miss in extension package

packages/extension/src/hosted/api/vscode/ext.host.terminal.ts, packages/terminal-next/src/browser/terminal.controller.ts, packages/terminal-next/src/browser/terminal.service.ts, packages/terminal-next/src/common/client.ts, packages/terminal-next/src/node/pty.proxy.ts, packages/terminal-next/src/node/terminal.service.ts
close #1107 
https://user-images.githubusercontent.com/9823838/170456030-2668a962-2529-4712-93a9-6307f2d4fdc5.mp4
close terminal after type exit
=> fix: close terminal after type exit

packages/quick-open/src/browser/quick-open.service.tsx
=> fix: remove quick open invalid style

README-zh_CN.md
移除了 canvas 包以后不需要再指定 canvas 的下载地址了
update zh doc
=> chore: update zh doc

packages/webview/src/webview-host/common.ts
hide extension webview scrollbar corner
=> style: hide extension iframe scrollbar corner

packages/extension/__tests__/hosted/api/vscode/ext.host.task.test.ts, packages/extension/__tests__/hosted/api/vscode/ext.host.terminal.test.ts, packages/extension/src/browser/vscode/api/main.thread.terminal.ts, packages/extension/src/common/vscode/terminal.ts, packages/extension/src/hosted/api/vscode/ext.host.terminal.ts, packages/terminal-next/src/browser/terminal.api.ts, packages/terminal-next/src/browser/terminal.client.ts, packages/terminal-next/src/browser/terminal.controller.ts, packages/terminal-next/src/common/api.ts, packages/terminal-next/src/common/client.ts, packages/terminal-next/src/common/controller.ts
close #1140.
make sure terminal instance can be got
=> fix: make sure terminal instance can be got

packages/extension/src/browser/vscode/api/main.thread.terminal.ts, packages/extension/src/hosted/api/vscode/ext.host.terminal.ts, packages/terminal-next/src/browser/terminal.api.ts, packages/terminal-next/src/common/client.ts, packages/terminal-next/src/common/extension.ts
=> fix: get proxy terminal from web end

packages/extension/src/browser/vscode/api/main.thread.terminal.ts, packages/extension/src/hosted/api/vscode/ext.host.terminal.ts, packages/terminal-next/src/browser/terminal.api.ts, packages/terminal-next/src/browser/terminal.client.ts, packages/terminal-next/src/browser/terminal.controller.ts, packages/terminal-next/src/browser/terminal.internal.service.ts, packages/terminal-next/src/common/client.ts, packages/terminal-next/src/common/extension.ts, packages/terminal-next/src/common/pty.ts
close #1158 
https://user-images.githubusercontent.com/9823838/171438764-8f08bc54-b244-4797-a095-90ae68b927d4.mp4
get the correct terminal instance by terminal short id
=> fix: get the correct terminal instance by terminal short id 

packages/terminal-next/src/browser/terminal.client.ts
=> fix: types

packages/debug/src/browser/view/frames/debug-call-stack.contribution.ts, packages/debug/src/browser/view/variables/debug-variables.contribution.ts, packages/i18n/src/common/en-US.lang.ts, packages/i18n/src/common/zh-CN.lang.ts, packages/preferences/README.md
worksace => workspace
replace every `deugger` to `debugger`
=> chore: fix typos

.github/workflows/pre-release.yml, .github/workflows/release-check.yml, .github/workflows/release.yml, scripts/github/createPrNextCheckSuite.js, scripts/github/notifyPrNextResult.js, scripts/github/notifyPreReleaseResult.js
=> ci: fix workflow

packages/quick-open/src/browser/components/quick-open-tabs/style.module.less
=> style: add tab padding and remove fixed width

packages/preferences/src/browser/preferenceItem.view.tsx
Fix settings panel failed to rendering
=> fix: settings panel failed to rendering

packages/core-browser/src/preferences/early-preferences.ts, packages/core-common/src/index.ts, packages/core-common/src/settings/general.ts, packages/core-common/src/settings/index.ts, packages/preferences/src/browser/preference-settings.service.ts, packages/preferences/src/browser/preferenceItem.view.tsx, packages/preferences/src/browser/preferences.view.tsx, packages/theme/src/browser/icon.service.ts
Fix setting panel render default value error
=> fix: setting panel render default value error

packages/core-common/__tests__/coreCommandRegistry.test.ts, packages/core-common/src/command.ts
重构了 beforeExecuteCommand 的能力，优化了性能
=> refactor: update pre command hooks

packages/extension/src/hosted/api/vscode/ext.host.extensions.ts, packages/types/vscode/typings/vscode.proposed.d.ts
目前 anycode@0.67 依赖此 API
新增 allAcrossExtensionHosts api
=> feat: 新增 allAcrossExtensionHosts api

packages/extension/src/hosted/api/vscode/language/completion.ts
代码补全的 provideCompletionItems 阶段传输所有字段
=> chore: provideCompletionItems dto convert all fields

configs/vscode-extensions.json, tools/electron/config/vscode-extensions.json
原来内置的大部分插件主要是为了验证框架功能，当前已无实际用途
这个 PR 移除了无实际作用的插件，减少初始化等待时间
=> chore: update default extension config

packages/core-browser/src/services/storage-service.ts, packages/core-common/src/storage.ts, packages/storage/__tests__/browser/index.test.ts, packages/storage/__tests__/browser/storage.service.test.ts, packages/storage/src/browser/storage.contribution.ts, packages/storage/src/browser/storage.service.ts, packages/storage/src/browser/storage.ts
close #1200.
after:
https://user-images.githubusercontent.com/9823838/173522903-140c6796-38d7-431d-99ad-3c1ac6f85f7b.mp4
use browser LocalStorage to cache real storage
=> refactor: use browser LocalStorage to cache real storage

packages/task/src/browser/terminal-task-system.ts
- remove useless select widget logic
=> fix: remove useless select widget logic

jest.config.js, packages/terminal-next/__tests__/browser/client.test.ts, packages/terminal-next/__tests__/browser/controller.test.ts, packages/terminal-next/__tests__/browser/inject.ts, packages/terminal-next/__tests__/browser/terminal.service.test.ts, packages/terminal-next/src/browser/terminal.client.ts, packages/terminal-next/src/browser/terminal.controller.ts, packages/terminal-next/src/common/controller.ts, packages/terminal-next/src/common/pty.ts
=> fix: `PseudoTerminal` not work

packages/comments/src/browser/comments-body.tsx
目前这个文件会有副作用，挪到组件里。
move renderer in component
=> chore: move renderer in component

packages/core-browser/src/common/common.command.ts, packages/core-common/src/command.ts, packages/core-common/src/localize.ts, packages/editor/src/browser/monaco-contrib/command/command.service.ts, packages/extension/__tests__/browser/extension-service/extension-service-mock-helper.ts, packages/extension/__tests__/browser/extension-service/extension.service.test.ts, packages/extension/src/browser/vscode/contributes/commands.ts, packages/extension/src/common/index.ts, packages/i18n/src/common/en-US.lang.ts, packages/i18n/src/common/zh-CN.lang.ts, packages/quick-open/__tests__/browser/prefix-quick-open-command.service.test.ts, packages/quick-open/src/browser/quick-open.command.service.ts
QuickCommand support display alias
=> feat: QuickCommand support display alias

packages/core-browser/src/bootstrap/app.ts, packages/core-browser/src/core-preferences.ts, packages/core-common/src/settings/index.ts, packages/core-common/src/settings/terminal.ts, packages/preferences/src/browser/preference-settings.service.ts, packages/terminal-next/src/browser/contribution/terminal.command.ts, packages/terminal-next/src/browser/contribution/terminal.preference.ts, packages/terminal-next/src/browser/terminal.profile.internal.ts, packages/terminal-next/src/common/preference.ts, packages/theme/src/browser/icon.service.ts, packages/theme/src/browser/theme.contribution.ts
=> refactor: unified settings id

packages/core-browser/__tests__/toolbar/toolbar.registry.test.ts
=> test: add toolbar test

packages/i18n/src/common/en-US.lang.ts, packages/i18n/src/common/zh-CN.lang.ts, packages/preferences/src/browser/preference-settings.service.ts, packages/terminal-next/src/browser/terminal.addon.ts, packages/terminal-next/src/browser/terminal.client.ts, packages/terminal-next/src/browser/terminal.typeAhead.addon.ts, packages/terminal-next/src/browser/terminal.typeAhead.ext.ts, packages/terminal-next/src/browser/xterm-private.d.ts, packages/terminal-next/src/common/preference.ts
适配VSCode Remote上Local Echo功能到OpenSumi上。
在终端输入到达pty并且被处理之前，先在本地半透明预测和显示输入的内容。
待办：
目前的远程终端使用体验依然非常受限于网络稳定性已经RPC通道流畅度，在网络不稳定的时候，终端使用卡顿感会更加明显。因此需要一个本地化方案来让用户的输入得到尽可能快的反馈。
- 初步适配TypeAheadAddon
- 修复了一些奇怪的BUG
=> [BETA] 实验性: 添加/适配 终端LocalEcho功能

packages/i18n/src/common/en-US.lang.ts, packages/i18n/src/common/zh-CN.lang.ts, packages/main-layout/src/browser/main-layout.contribution.ts
codeswing 依赖这两个命令
支持 workbench.action.closePanel 和 workbench.action.closeSidebar 命令
=> feat: 支持 workbench.action.closePanel 和 workbench.action.closeSidebar 命令

packages/core-browser/src/preferences/preference-service.ts, packages/core-browser/src/preferences/types.ts, packages/terminal-next/__tests__/browser/mock.service.ts, packages/terminal-next/src/browser/contribution/terminal.command.ts, packages/terminal-next/src/browser/contribution/terminal.menu.ts
close #1165 
fix set default terminal type features
=> fix: set default terminal type

tools/electron/src/main/index.ts
=> fix: incorrect extensions path

packages/components/src/recycle-tree/RecycleTree.tsx, packages/components/src/recycle-tree/tree/model/treeState/TreeStateManager.ts
closed #1229 
preview：
https://user-images.githubusercontent.com/9823838/175006679-de5ce041-f5c2-4305-a2de-5498c97949c0.mp4
- destory prompt input when it is dispeared
=> fix: destory prompt input when it is dispeared

packages/extension/src/browser/extension.contribution.ts, packages/extension/src/hosted/api/vscode/ext.host.api.command.ts
=> fix: vscode.open command arguments

packages/terminal-next/src/browser/component/terminal.view.tsx
CherryPick #1244 
fix(terminal): close search input box (#1244)
- fix(terminal): close search input box #1244
=> fix: cherrypick #1244

codecov.yml, jest.setup.base.js, jest.setup.jsdom.js, jest.setup.node.js, scripts/changelog/index.ts, scripts/dist-tag.ts, scripts/generate-manifest-json.ts, scripts/iteration-plan.ts, scripts/jest/runTest.ts, scripts/module-jest.ts, scripts/pkg.ts, scripts/publish.ts
=> ci: fix ci

packages/terminal-next/__tests__/browser/mock.service.ts, packages/terminal-next/package.json, packages/terminal-next/src/browser/xterm.ts
=> chore: update xterm deps version

packages/core-common/src/types/markdown.ts, packages/extension/src/common/vscode/converter.ts, packages/extension/src/common/vscode/ext-types.ts, packages/extension/src/common/vscode/models/html-content.ts, packages/types/sumi-worker/worker.language.d.ts, packages/types/vscode/typings/vscode.language.d.ts
ts-language-feature 最新版需要
implement vscode.MarkdownString.baseUri
=> feat: implement vscode.MarkdownString.baseUri

packages/storage/src/browser/storage.ts
close #1216.
load cache from browserStorage correctly
=> fix: load cache from browserStorage correctly

codecov.yml, scripts/github/helpers.js
=> ci: fix version publish scripts

packages/electron-basic/src/browser/welcome/welcome.tsx, packages/i18n/src/common/en-US.lang.ts, packages/i18n/src/common/zh-CN.lang.ts, packages/markers/src/browser/messages.ts, packages/preferences/src/browser/preference-contribution.ts
Fix edit in settings.json will jump to wrong position
=> fix: wrong position when edit in settings.json

packages/components/src/recycle-tree/tree/TreeNode.ts, packages/components/src/recycle-tree/tree/model/treeState/TreeStateManager.ts, packages/extension/src/browser/vscode/api/main.thread.treeview.ts, packages/extension/src/browser/vscode/api/tree-view/tree-view.model.service.ts, packages/extension/src/browser/vscode/api/tree-view/tree-view.node.defined.ts, packages/extension/src/common/vscode/treeview.ts, packages/extension/src/hosted/api/vscode/ext.host.treeview.ts
cherry-pick:
- #1262 
- https://github.com/opensumi/core/commit/6934cbe27642432ace4f0bc25a51b10adfe622c9
improve FileTree and extension Treeview display logic
=> fix: improve FileTree and extension TreeView display logic

packages/components/src/recycle-tree/tree/TreeNode.ts, packages/extension/src/browser/components/extension-tree-view-node.tsx, packages/extension/src/browser/vscode/api/main.thread.treeview.ts, packages/extension/src/browser/vscode/api/tree-view/tree-view.model.service.ts, packages/extension/src/browser/vscode/api/tree-view/tree-view.node.defined.ts, packages/extension/src/common/vscode/treeview.ts, packages/extension/src/hosted/api/vscode/ext.host.treeview.ts
close #723
同时优化了 TreeView 内的节点缓存逻辑，提高节点二次加载速度以及刷新响应速度，由原本的 500ms 响应加快至 200ms
support the old Browser Preview extension
=> fix: support browser preview extension

packages/comments/src/browser/comment-reactions.view.tsx, packages/core-browser/src/menu/next/menu-id.ts, packages/editor/src/browser/menu/open-type-menu.contribution.ts, packages/electron-basic/src/browser/index.ts, packages/main-layout/src/browser/accordion/accordion.service.ts, packages/main-layout/src/browser/tabbar/tabbar.service.ts, packages/terminal-next/src/browser/contribution/terminal.menu.ts
收敛模块代码里 registerMenuItem 注册的 menu id 到枚举列表里
=> chore: convergence registerMenuItems key by menuId enum

tools/template/package.json
=> chore: upgrade version of opensumi in template

packages/core-browser/src/monaco/index.ts, packages/core-browser/src/services/label-service.ts, packages/monaco/src/common/types.ts
=> feat: change modes to languageServices

packages/monaco/src/browser/monaco-snippet-suggest-provider.ts, packages/monaco/src/browser/monaco.context-key.service.ts, packages/monaco/src/browser/monaco.contribution.ts, packages/scm/__tests__/browser/dirty-diff/dirty-diff-model.test.ts
=> refactor: (wip)

packages/extension/src/browser/vscode/api/main.thread.language.ts, packages/monaco/src/browser/monaco.context-key.service.ts
=> refactor: inlayHints on monaco 0.33

packages/monaco/src/browser/contrib/callHierarchy.ts, packages/monaco/src/browser/monaco-api/services.ts
=> chore: code styles

packages/extension/src/hosted/api/vscode/debug/extension-debug-adapter-starter.ts, packages/storage/src/browser/storage.ts
- 修复 spawn 进程参数错误
- 处理拼写错误
incorrect debug adapter spawn options
=> fix: incorrect debug adapter spawn options

packages/extension/src/browser/vscode/api/main.thread.language.ts, packages/extension/src/common/vscode/doc.ts, packages/extension/src/common/vscode/languages.ts, packages/extension/src/hosted/api/vscode/doc/doc-manager.host.ts, packages/extension/src/hosted/api/vscode/ext.host.language.ts, packages/extension/src/hosted/api/vscode/language/inlay-hints.ts, packages/types/vscode/typings/vscode.proposed.d.ts
最新的InlayHints api支持
- 之前旧的不支持resolve
=> refactor: change to new inlay hint api

packages/opened-editor/src/browser/opened-editor-node.define.ts, packages/scm/src/browser/components/scm-resource-tree/scm-tree-node.ts, packages/scm/src/browser/components/scm-resource-tree/scm-tree-node.view.tsx, packages/scm/src/browser/components/scm-resource-tree/scm-tree.service.ts
show staged files on the SCM panel
=> fix: show staged files on the SCM panel

packages/extension/src/browser/vscode/api/main.thread.comments.ts, packages/extension/src/common/vscode/comments.ts, packages/extension/src/common/vscode/ext-types.ts, packages/extension/src/common/vscode/models/comments.ts, packages/extension/src/hosted/api/vscode/ext.host.comments.ts, packages/types/vscode/typings/vscode.proposed.d.ts
=> implement comment api

packages/extension/src/hosted/api/vscode/ext.host.window.api.impl.ts, packages/types/vscode/typings/vscode.d.ts, packages/types/vscode/typings/vscode.window.d.ts
finalize onDidChangeTerminalState api type
=> chore: finalize onDidChangeTerminalState api type

packages/editor/src/common/language-status.ts, packages/extension/src/hosted/api/vscode/ext.host.language.ts, packages/types/vscode/typings-pending/vscode.proposed.d.ts, packages/types/vscode/typings/vscode.d.ts, packages/types/vscode/typings/vscode.language.d.ts
Standardized in v1.65
finalize language statusbar API
=> chore: finalize language statusbar API

packages/core-common/src/types/file.ts, packages/file-service/src/browser/file-service-client.ts, packages/file-service/src/node/disk-file-system.provider.ts, packages/preferences/src/browser/userstorage/user-storage.service.ts
close #1308 
fix: log recursive output
=> fix: log recursive output

packages/editor/src/browser/workbench-editor.service.ts
this close: #1317 
revive editor preview state
=> fix: revive preview state

packages/debug/src/browser/view/configuration/debug-configuration.module.less
close #1326 
remove outline from debug configuration selection
=> style: remove outline from debug configuration selection

jest.config.js, packages/addons/src/browser/connection-rtt-contribution.ts, packages/addons/src/browser/index.ts, packages/addons/src/browser/language-change.contribution.ts, packages/core-browser/__tests__/external-preference.test.ts, packages/core-browser/src/common/common.command.ts, packages/core-browser/src/common/common.contribution.ts, packages/core-browser/src/core-preferences.ts, packages/core-browser/src/preferences/early-preferences.ts, packages/core-common/src/localize.ts, packages/debug/src/browser/debug-session.ts, packages/electron-basic/src/browser/index.ts, packages/extension/src/browser/extension-instance-management.ts, packages/extension/src/browser/extension-management.service.ts, packages/extension/src/browser/extension.contribution.ts, packages/extension/src/browser/extension.service.ts, packages/extension/src/browser/vscode/contributes/localization.ts, packages/i18n/__tests__/dataValidity.test.ts, packages/i18n/src/common/en-US.lang.ts, packages/i18n/src/common/zh-CN.lang.ts, packages/output/src/browser/output-contribution.ts, packages/startup/entry/web/app.tsx, packages/task/src/browser/task.contribution.ts
this may close: #1332 
优化了部分国际化字符串
=> refactor: update i18n

packages/core-browser/src/common/common.contribution.ts, packages/core-browser/src/components/layout/split-panel.tsx, packages/core-browser/src/components/layout/styles.module.less, packages/core-browser/src/core-preferences.ts, packages/core-browser/src/layout/constants.ts, packages/core-browser/src/style/normalize.less, packages/debug/src/browser/view/configuration/debug-toolbar.view.tsx, packages/editor/src/browser/editor.module.less, packages/editor/src/browser/tab.view.tsx, packages/electron-basic/src/browser/header/header.module.less, packages/electron-basic/src/browser/header/header.tsx, packages/main-layout/src/browser/accordion/accordion.view.tsx, packages/main-layout/src/browser/accordion/styles.module.less, packages/main-layout/src/browser/accordion/titlebar.view.tsx, packages/main-layout/src/browser/tabbar/panel.view.tsx, packages/main-layout/src/browser/tabbar/styles.module.less, packages/menu-bar/src/browser/menu-bar.module.less, packages/menu-bar/src/browser/menu-bar.view.tsx, packages/scm/src/browser/scm-view-container.tsx, packages/scm/src/browser/scm.module.less, packages/startup/entry/sample-modules/menu-bar/menu-bar.module.less, packages/startup/entry/sample-modules/menu-bar/menu-bar.view.tsx, packages/terminal-next/src/browser/component/tab.item.tsx, packages/terminal-next/src/browser/component/tab.module.less
close #1324 
adjust debug toolbar position
=> fix: adjust debug toolbar position

packages/components/src/recycle-list/RecycleList.tsx, packages/components/src/scrollbars/index.tsx, packages/editor/src/browser/editor.view.tsx, packages/editor/src/browser/tab.view.tsx, packages/keymaps/src/browser/keymaps.contribution.ts, packages/keymaps/src/browser/keymaps.module.less, packages/keymaps/src/browser/keymaps.service.ts, packages/keymaps/src/browser/keymaps.view.tsx
close #1325 
同时优化了部分代码写法以及固定了快捷键面板的 Header 到顶部，不会随滚动消失
remove mobx and improve keymaps view
=> fix: remove mobx and improve keymaps view

packages/i18n/src/common/en-US.lang.ts, packages/i18n/src/common/zh-CN.lang.ts, packages/search/src/browser/search-tree.view.tsx, packages/search/src/browser/search.contribution.ts
=> fix: shortcut trigger search

packages/debug/src/browser/view/frames/debug-call-stack-session.view.tsx, packages/debug/src/browser/view/frames/debug-call-stack-thread.view.tsx, packages/debug/src/browser/view/frames/debug-call-stack.module.less, packages/debug/src/browser/view/variables/debug-variables.view.tsx
improve debug call stack style
=> style: improve debug call stack style

packages/editor/src/browser/workbench-editor.service.ts
- add missing type declaration
=> fix: add missing type declaration

packages/opened-editor/__tests__/browser/opened-editor.service.test.ts, packages/opened-editor/src/browser/opened-editor.contribution.ts, packages/opened-editor/src/browser/opened-editor.tsx, packages/opened-editor/src/browser/services/opened-editor-event.service.ts, packages/opened-editor/src/browser/services/opened-editor-model.service.ts
close #1362 
after:
https://user-images.githubusercontent.com/9823838/179443015-b41b8350-09b2-43e6-aac6-1ebb3089d0a1.mp4
clean opened editor while calling closeAll
=> fix: clean opened editor while calling closeAll

packages/extension/src/hosted/worker.host.ts
- worker host logger init error
=> fix: worker host logger error

packages/preferences/src/browser/preferenceItem.view.tsx
=> fix: preference name syntax

packages/extension/src/browser/extension.contribution.ts
修复部分 contribute 由于没有 schema 字段所导致的 registerSchema 报错问题
=> fix: contribute json schema of undefined

packages/extension/src/common/index.ts
- fix: menu icon default use background mode
=> fix: menu icon default use background mode

packages/extension/src/hosted/api/vscode/ext.host.extensions.ts, packages/types/vscode/typings/vscode.proposed.d.ts
=> feat: all across extension hosts

packages/extension/src/hosted/api/worker/worker.host.api.impl.ts
feat: add open external api in worker host
=> feat: add open external api in worker host

packages/components/src/checkbox/index.tsx
=> chore: fix-typo

packages/components/src/recycle-tree/tree/TreeNode.ts, packages/scm/src/browser/components/scm-resource-tree/scm-tree-api.ts, packages/scm/src/browser/components/scm-resource-tree/scm-tree-model.service.ts, packages/scm/src/browser/components/scm-resource-tree/scm-tree-model.ts, packages/scm/src/browser/components/scm-resource-tree/scm-tree-node.ts
after:
fix SCM tree view duplication problem
=> fix: SCM tree view duplication problem

packages/debug/src/browser/debug-session.ts, packages/i18n/src/common/en-US.lang.ts, packages/i18n/src/common/zh-CN.lang.ts
close #1391.
using debug to launch program on terminal
=> fix: using debug to launch program on terminal

packages/components/src/tooltip/index.tsx
closes #1400 
在组件卸载后不进行组件的相关操作
=> fix: tooltip memory leak

packages/core-browser/src/bootstrap/app.ts, packages/theme/src/browser/theme.contribution.ts, tools/dev-tool/src/index.html
=> fix: set default dark theme if theme options is like dark

packages/components/src/button/style.less
closes #1395 
添加 `white-space: nowrap` 属性
=> fix: button-text-display

packages/file-tree-next/src/browser/dialog/file-dialog.service.ts, packages/file-tree-next/src/browser/dialog/file-dialog.view.tsx, packages/file-tree-next/src/browser/file-tree-model.ts
ref #1358 
open save dialog correctly while save new file
=> fix: open save dialog correctly while save new file

packages/scm/__tests__/browser/dirty-diff/dirty-diff-model.test.ts, packages/scm/src/browser/dirty-diff/dirty-diff-model.ts, packages/scm/src/browser/dirty-diff/index.ts
close #1387 
remove warnings while dispose dirty diff model
=> chore: remove warnings while dispose dirty diff model

packages/extension/src/hosted/api/vscode/language/completion.ts
之前 CompletionItem 中没有消费 command 这个字段
=> fix(completion): consume command field

packages/theme/src/common/color-tokens/button.ts, packages/theme/src/common/color-tokens/custom/button.ts
before:
after:
fix custom button fallback colors
=> style: fix custom button fallback colors

packages/extension/src/hosted/worker.host.ts
=> fix: logger init error

packages/core-browser/src/style/override.less
before
after
- 优化 codicon 默认样式
=> fix: codicon default style

packages/extension/src/hosted/api/vscode/ext.host.file-system-event.ts, packages/types/vscode/typings/vscode.workspace.d.ts
closed #1412 
- add cancellation token for files operation events
=> feat: add cancellation token for files operation

packages/editor/src/browser/types.ts, packages/editor/src/browser/workbench-editor.service.ts, packages/extension/__tests__/browser/main.thread.editor.test.ts, packages/extension/src/browser/vscode/api/main.thread.editor.ts
https://user-images.githubusercontent.com/17701805/182111449-ad15c1e4-7dca-4eb6-9601-d7b9b37ac202.mp4
- 修复 gitlens 左侧 originaleditor 无法展示 blame 的问题
=> fix: sync both diff editor to extension host

.github/stale.yml
=> chore: configure stale.yml

packages/extension/src/hosted/api/vscode/ext.host.treeview.ts
- fix extension tree view order
=> fix: extension tree view order

packages/theme/src/browser/icon.service.ts
=> fix: update icon style

packages/theme/src/common/color-tokens/custom/button.ts
fix #1463.
improve ghost and secondary button fallback style
=> style: improve ghost and secondary button fallback style

packages/components/src/recycle-tree/basic/tree-node.tsx, packages/core-browser/src/style/override.less, packages/extension/src/browser/components/extension-tree-view-node.tsx, packages/main-layout/src/browser/accordion/accordion.service.ts, packages/main-layout/src/browser/tabbar-handler.ts
=> fix: remove tree icon height

packages/keymaps/src/browser/keymaps.service.ts
fixed #1479.
sync keymaps resource all the time
=> fix: sync keymaps resource all the time

packages/monaco/src/browser/monaco-snippet-suggest-provider.ts, packages/utils/src/path.ts
=> chore: fix eslint types check

packages/theme/src/browser/icon.service.ts
原有改动会让 Toolbar 上的按钮位置不对
mask icon fallback to use 50% size
=> style: mask icon fallback to use 50% size

packages/editor/src/browser/editor-collection.service.ts, packages/editor/src/browser/workbench-editor.service.ts, packages/monaco/src/browser/monaco-snippet-suggest-provider.ts, packages/preferences/src/browser/preference-contribution.ts, packages/utils/src/path.ts
fixed #1472 
https://user-images.githubusercontent.com/17701805/183550385-e36da728-c793-4014-b9be-60f244500640.mp4
https://user-images.githubusercontent.com/17701805/183550400-a6b40774-fd1c-4b83-8f6f-f671566a1c47.mp4
- 优化编辑器打开后滚动到屏幕中间的行为
=> fix: improve editor reveal in center behavior

packages/debug/src/browser/tree/debug-tree-node.define.ts
VS Code:
After fixed:
improve debug variables order
=> fix: improve debug variables order

packages/editor/src/browser/editor.module.less
before:
after:
improve editor tab text style
=> style: improve editor tab text style

packages/core-browser/src/menu/next/menu-id.ts, packages/debug/src/browser/debug-contribution.ts, packages/i18n/src/common/en-US.lang.ts, packages/i18n/src/common/zh-CN.lang.ts
=> feat: support editor/title/run menu contributes

packages/search/src/browser/search-tree.service.ts
搜索面板打开的内容，每次点击都会产生一个 doc model 的副作用，导致 ReferenceManager 中大量当前 doc 的引用。这种情况会进一步导致搜索的结果中包含已经删除的内容。
修复搜索中包含已经删除的文件内容的问题
=> fix: clean up search result side effect of opening files

packages/extension/src/common/vscode/extension.ts, packages/extension/src/hosted/api/vscode/ext.host.window.api.impl.ts, packages/types/vscode/typings/vscode.d.ts
=> fix: with progress api error

packages/core-browser/src/layout/index.ts, packages/main-layout/src/browser/tabbar/panel.view.tsx
feat: custom view container mini-size
=> feat: custom view container mini-size

packages/core-browser/src/progress/progress.service.tsx, packages/utils/src/progress.ts
Usage:
```ts
this.progressService.withProgress({
location: ProgressLocation.Notification,
title: 'test',
closeable: false,
}, () => {}, () => {
// cancel
});
```
support closeable option on progress api
=> feat: support closeable option on progress api

packages/extension/src/browser/vscode/api/main.thread.api.webview.ts, packages/webview/src/browser/types.ts
=> fix: connect lost when webview is visible

scripts/rebuild-native.js
=> chore: fix rebuild native deps script on Linux

packages/core-browser/src/components/layout/box-panel.tsx, packages/core-browser/src/components/layout/split-panel.tsx, packages/core-browser/src/react-providers/slot.tsx, packages/startup/entry/web/layout.tsx, packages/startup/entry/web/render-app.tsx
1. 修复骨架屏失效
2. 优化 startup 的骨架屏，适配 web 版本的加载
https://user-images.githubusercontent.com/2226423/184803590-f5502235-8f54-420e-bb78-4caa88c521b5.mov
修复骨架屏加载失效问题
=> fix: skeleton screen loading not working

packages/debug/src/browser/debug-contribution.ts, packages/i18n/src/common/en-US.lang.ts, packages/i18n/src/common/zh-CN.lang.ts, packages/keymaps/src/browser/keymaps.module.less, packages/keymaps/src/browser/keymaps.service.ts, packages/keymaps/src/browser/keymaps.view.tsx, packages/main-layout/src/browser/main-layout.contribution.ts, packages/output/src/browser/output-contribution.ts
https://user-images.githubusercontent.com/9823838/184803060-3f02f88a-75ba-441c-9200-a68544d3bfbb.mp4
improve keymaps style and support command id search
=> feat: improve keymaps style and support command id search

packages/startup/entry/web/render-app.tsx, packages/utils/src/event.ts
=> fix: startup read wrong workspace dir

packages/scm/src/browser/scm.contribution.ts
修复 diff editor 下 上一个变化/下一个变化 时光标会消失的问题
=> fix: diff editor previous/next mouse position

packages/editor/src/browser/workbench-editor.service.ts, packages/opened-editor/src/browser/services/opened-editor-model.service.ts
修复文件的 dirty 状态与左侧状态栏的提示数字不一致的问题
=> fix: dirty count calculate mistake

packages/components/src/select/index.tsx
=> fix: debug toolbar select options position
