opensumi/core

tools/electron/build/webpack.extension-host.config.js
tools/electron/build/webpack.node.config.js

- 修复 webpack loader 相关的异常和 yargs 等 esm

fix: handle webpack loader and esm module

---

packages/core-browser/src/toolbar/components/button.tsx

使用 toolbar 的 button 会报下面的错误：
- 修复 Toolbar 按钮的 min-width 属性名

fix: the min-width property name of the toolbar button

---

packages/editor/src/browser/view/suggest-widget.ts

内部接口的 widget 可以直接获取了，且去除了 getValue 方法
fix: suggestController._widget to suggestController.widget

fix: suggestController._widget to suggestController.widget

---

packages/editor/src/browser/editor.module.less
packages/editor/src/browser/navigation.module.less

fixes #156 
before
after
seti 主题下(使用 icon font)
before
after
- 优化编辑器 Tab 栏图标样式

fix: editor tab icon style

---

packages/extension/src/browser/vscode/api/main.thread.treeview.ts
packages/theme/src/browser/icon.service.ts
packages/theme/src/common/theme.service.ts

初始化过程中存在插件注册大量 icon 的情况，icon 注册会分别为其生成 classname 并 append 到文档中，导致界面频繁重绘，甚至卡住
导致例如图中这种 gitlens 的 commit 面板卡住 2 秒以上
> 注意看 COMMIT 面板下的 ProgressBar，此时会插入 900+条 css 样式
优化后
> 仅插入十几次样式
- 优化图标注册性能，增加延时逻辑

chore: optimize icon service append style perf

---

CONTRIBUTING-zh_CN.md
README-zh_CN.md
README.md

ZH_CN
EN
use OpenSumi theme preview image

chore: use opensumi theme preview image

---

packages/outline/src/browser/outline.tsx

没有图，原理和之前几个一样
- 优化大纲面板 treeview 渲染性能

chore: optimize outline treeview perf

---

packages/editor/src/browser/doc-model/editor-document-model.ts

fix: editor save issue

---

packages/theme/src/browser/theme.contribution.ts
packages/theme/src/browser/workbench.theme.service.ts

fix: remove theme fallback logic

---

packages/core-browser/src/react-providers/config-provider.tsx
packages/editor/src/browser/monaco-contrib/tokenizer/textmate.service.ts

Windows 上面使用 Path 字符串传递会出现一些明显的路径问题，而且对于集成方会出现一些难以预知的问题
- 弃用 ongiWasmPath 使用 ongiWasmUri

refactor: deprecated ongiWasmPath uses ongiWasmUri

---

packages/core-browser/src/raw-context-key.ts
packages/debug/__tests__/browser/view/console/debug-console-tree.model.service.test.ts
packages/debug/src/browser/contextkeys/debug-contextkey.service.ts
packages/debug/src/browser/debug-contribution.ts
packages/debug/src/browser/debug-session.ts
packages/debug/src/browser/view/console/debug-console-tree.model.service.ts
packages/debug/src/browser/view/console/debug-console.contribution.ts
packages/debug/src/browser/view/console/debug-console.view.tsx
packages/debug/src/common/constants.ts

1. **运行到光标处** 和 **强制运行到光标处** 只有在开启调试的时候才 enabled
2. 调试控制台只有触发右键菜单的时候才开启 **清空日志** 和 **折叠全部**
fix: Clean up the wrong usage of debug command

fix: clean up the wrong usage of debug command

---

packages/extension/src/browser/vscode/api/main.thread.terminal.ts
packages/extension/src/hosted/api/vscode/ext.host.terminal.ts
packages/terminal-next/__tests__/browser/links/helpers.test.ts
packages/terminal-next/__tests__/browser/links/protocol-link-provider.test.ts
packages/terminal-next/__tests__/browser/links/validated-local-link-provider.test.ts
packages/terminal-next/__tests__/browser/terminal.hover.manager.test.ts
packages/terminal-next/__tests__/browser/utils.ts
packages/terminal-next/src/browser/index.ts
packages/terminal-next/src/browser/links/external-link-provider-adapter.ts
packages/terminal-next/src/browser/links/link-manager.ts
packages/terminal-next/src/browser/links/link.ts
packages/terminal-next/src/browser/links/protocol-link-provider.ts
packages/terminal-next/src/browser/links/validated-local-link-provider.ts
packages/terminal-next/src/browser/terminal.hover.manager.ts
packages/terminal-next/src/common/controller.ts
packages/terminal-next/src/common/extension.ts
packages/terminal-next/src/common/xterm-private.d.ts
packages/types/vscode/typings/vscode.d.ts

close #77 
支持 VSCode 1.60 API。
- 支持链接跳转提示
- 支持非链接声明的 tooltips，并且执行 command [TerminalLink API](https://code.visualstudio.com/api/references/vscode-api#TerminalLink)
- 支持 TerminalLink 的 tooltips API

feat: support TerminalLink tooltips api

---

packages/core-common/src/types/extension.ts
packages/extension/src/browser/extension.service.ts
packages/theme/src/browser/workbench.theme.service.ts

1. 添加 ExtensionDidContributes 事件
2. 注册主题时若是已设置的自动应用
3. 主题全部注册完成后，如果已设置的主题没有安装，fallback 到默认主题
[默认主题相关修改](https://github.com/opensumi/Default-Themes/commit/6050a0a1b70b42140269aee837827570cdabda6f)
1. 合并所有定义到 plus.json, 原因是之前定义了三层的继承关系(include), 但实际是不必要的，需要分别读取三个文件，导致加载主题时较慢
- 修正主题 fallback 逻辑

fix: add ExtensionDidContributes event for themes

---

packages/extension-storage/src/browser/storage-path.ts

while `workspaceDir` is undefined, the storage path will use fallback `.sumi` path
use temp uri to build storage path while workspace is undefined

fix: use temp uri to build storage path while workspace is undefined

---

scripts/changelog/run.ts

use type as a fallback in changelog script

chore: use type as a fallback in changelog script

---

packages/debug/src/browser/debug-session.ts

在接收 BreakpointEvent 这个自定义事件的时候，应该只改变状态，而不应该再触发断点的任何 DAP 请求
修复 breakpointLocations DAP 重复请求的问题

fix: repeat breakpointLocations DAP request

---

packages/extension-storage/src/browser/storage.ts

其中一个 asAccess 当作 path 参数传入了。 close #233 
- storage use asAccess with uri

fix: storage use asAccess with uri

---

packages/theme/src/browser/theme.contribution.ts

register default color theme before render

fix: register default color theme before render

---

packages/extension/src/browser/vscode/api/main.thread.editor.ts

Wrong `removed` changes were push to extension host after closing diffEditors, causing `TextEditor` without `TextDocument` kept in `workspace.textEditors`.  
- fixes editor features failing after closing diffEditors.

fix: fix ext-host editors error on closing diff editors

---

.github/workflows/pre-release.yml
.github/workflows/release.yml

修改了一下 pre-release 和 release 版本的发布条件
1. 基于 issue 模板创建标题为 `OpenSumi Pre-release`  的 issue，会自动添加 `pre-release` 标签
2. 创建后会触发一次 next 版本发布
3. 在 issue 评论 `/pre-release` 也会触发发布
同时运行判断了以下条件
1.  issue、评论人权限必须为 `OWNER` 或 `MEMBER`
2. issue 正文包含 'Pre-Release'
3. issue 标题包含 'OpenSumi Pre-Release'
4. 若有评论，issue 评论包含 '/pre-release'
5. issue label 包含 'pre-release'
与 pre-release 区别在于
1. 发布前需要手动修改 `lerna.json` 为期望发布的版本号
2. 创建 issue 后不会自动发布，只有 `OWNER` 权限评论后才会发布
3. 发布后自动添加 tag ，发布 github release 以及 push 代码
4. 发布后自动添加 changelog 到 issue 正文
5. 发布后自动关闭 issue
6. 发布后自动锁定 issue
- 更新 workflow 运行条件

chore: update release condition

---

packages/debug/src/browser/editor/debug-model.ts
packages/extension/__tests__/browser/main.thread.debug.test.ts
packages/extension/src/browser/vscode/api/main.thread.debug.ts

test code
```
const bp = vscode.debug.breakpoints;
vscode.debug.removeBreakpoints(bp);
```
预期效果: 所有断点均被删除
修复 debug.removeBreakpoints API 失效的问题

fix: debug.removeBreakpoints api

---

packages/extension/src/browser/vscode/api/main.thread.editor.ts

fix ext-host editors error on closing diff editors

fix: ext-host editors error on closing diff editors

---

packages/extension/src/hosted/api/vscode/language/completion.ts

修复在没有 resolveCompletionItem 的情况下补全列表的 documentation 丢失的问题

fix: completion item documentation

---

packages/file-tree-next/__tests__/browser/file-tree-model.service.test.ts
packages/file-tree-next/src/browser/file-tree.tsx
packages/file-tree-next/src/browser/services/file-tree-model.service.ts
packages/file-tree-next/src/common/file-tree-node.define.ts

follow vscode explorerResourceIsFolder behavior
right click explorer empty area still set this value to true.
配置了右键菜单 explorerResourceIsFolder：
然后在 vscode 下在根目录是有这个选项的：
在 sumi 里根目录下右键没:
set explorerResourceIsFolder to `true` when right click in explorer root

feat: adjust explorerResourceIsFolder behavior

---

packages/terminal-next/src/node/terminal.service.ts

参考自 [hyper 3](https://hyper.is/blog) 的一篇博客，原理是批处理终端 pty 的输出，将 16ms 内的输出内容合并到一起批量发送到前端，避免在终端执行输出很多的命令时阻塞 RPC 通信
before
在终端执行 `find ~` 命令后，文件树打开等操作明显变慢，同时按快捷键 `ctrl+c` 也无法终止命令，原因是 terminal 消息挤占了 RPC 通信
after
优化后同样在执行 `find ~` 命令时，文件打开等操作不受影响，且终端 `ctrl+c` 交互正常 
- 提升终端性能

feat: 🚀🚀🚀 add message batcher for pty

---

scripts/download.js

下载插件的脚本中，关于 asar 和 electron 的判断现在看起来没有必要。因为这个是执行在 Node.js 环境中的。
- 清理下载插件脚本中无用的代码

chore: remove useless asar code from download extension scripts

---

packages/extension/src/browser/components/extension-tree-view.tsx
packages/extension/src/browser/vscode/api/main.thread.treeview.ts
packages/main-layout/src/browser/layout.service.ts
packages/main-layout/src/common/main-layout.defination.ts

之前对于折叠或者隐藏状态下的 view 也会加载数据，例如这个场景下第一次激活插件所有的 treeview 加起来会创建 760 个 treeNode 实例
优化后，当视图展开且显示状态下，才会在第一次激活时获取数据，对于这个场景，第一次只创建 49 个 treeNode，后续视图折叠/展开时都会刷新并重新获取数据(与 VS Code 表现一致)
- 优化插件 treeview 初始化逻辑，减少冗余的加载逻辑

fix: optimize extension treeview init logic

---

packages/extension/src/hosted/api/vscode/ext.host.quickopen.ts

demo:
```js
const vscode = require('vscode')
exports.activate = () => {
const statusBar = vscode.window.createStatusBarItem(vscode.StatusBarAlignment.Left);
const quickPick = vscode.window.createQuickPick();
quickPick.items = [
{
label: 'Create Project',
command: 'test.createProject'
},
{
label: 'Run dev node',
command: 'test.runDevNode'
},
{
label: 'hide',
command: 'test.hide'
},
]
vscode.commands.registerCommand('test.createProject', () => {
vscode.window.showInformationMessage('createProject');
});
vscode.commands.registerCommand('test.runDevNode', () => {
vscode.window.showInformationMessage('runDevNode');
});
vscode.commands.registerCommand('test.hide', () => {
quickPick.hide();
});
vscode.commands.registerCommand('test.openQuickPick', () => {
quickPick.show();
}); …
```

fix: QuickOpen hide do not dispose

---

packages/testing/src/browser/components/testing.explorer.tree.tsx
packages/testing/src/browser/test-tree-view.model.ts
packages/testing/src/browser/testing.contribution.ts
packages/testing/src/common/commands.ts
packages/testing/src/common/testing-view.ts
packages/testing/src/common/tree-view.model.ts

feat: support go to test

---

packages/core-browser/src/contextkey/testing.ts
packages/debug/src/browser/debug-preferences.ts
packages/extension/src/browser/vscode/api/main.thread.tests.ts
packages/testing/src/browser/components/testing.explorer.tree.tsx
packages/testing/src/browser/components/testing.module.less
packages/testing/src/browser/test-tree-view.model.ts
packages/testing/src/browser/test.result.service.ts
packages/testing/src/browser/test.service.ts
packages/testing/src/common/getComputedState.ts
packages/testing/src/common/test-result.ts
packages/testing/src/common/testingStates.ts

feat: support testing result refresh

---

packages/extension/src/hosted/api/vscode/ext.host.quickopen.ts

demo:
```js
const vscode = require('vscode')
exports.activate = () => {
const statusBar = vscode.window.createStatusBarItem(vscode.StatusBarAlignment.Left);
const quickPick = vscode.window.createQuickPick();
quickPick.items = [
{
label: 'Create Project',
command: 'test.createProject'
},
{
label: 'Run dev node',
command: 'test.runDevNode'
},
{
label: 'hide',
command: 'test.hide'
},
]
vscode.commands.registerCommand('test.createProject', () => {
vscode.window.showInformationMessage('createProject');
});
vscode.commands.registerCommand('test.runDevNode', () => {
vscode.window.showInformationMessage('runDevNode');
});
vscode.commands.registerCommand('test.hide', () => {
quickPick.hide();
});
vscode.commands.registerCommand('test.openQuickPick', () => {
quickPick.show();
}); …
```

fix: quickopen hide don't exec dispose

---

configs/ts/references/tsconfig.remote-opener.json
configs/ts/tsconfig.build.json
configs/ts/tsconfig.resolve.json
jest.config.js
packages/core-browser/__tests__/remote-opener/remote-opener-converter.test.ts
packages/core-browser/src/common/common.module.ts
packages/core-browser/src/remote-opener/converter.contribution.ts
packages/core-browser/src/remote-opener/index.ts
packages/remote-cli/bin/open
packages/remote-cli/package.json
packages/remote-cli/src/index.ts
packages/remote-cli/tsconfig.json
packages/remote-cli/webpack.config.js
packages/remote-opener/__tests__/browser/remote.opener.service.test.ts
packages/remote-opener/__tests__/node/opener.client.test.ts
packages/remote-opener/__tests__/node/opener.service.test.ts
packages/remote-opener/package.json
packages/remote-opener/src/browser/index.ts
packages/remote-opener/src/browser/remote.opener.service.ts
packages/remote-opener/src/common/index.ts
packages/remote-opener/src/node/index.ts
packages/remote-opener/src/node/opener.client.ts
packages/remote-opener/src/node/opener.service.ts
packages/startup/entry/web/app.tsx
packages/startup/entry/web/render-app.tsx
packages/startup/entry/web/server.ts
packages/startup/package.json
tools/dev-tool/package.json
tools/dev-tool/src/server.ts

close #266 
1. 自行构建 `packages/remote-cli`, 将其内置在 CloudIDE 运行环境，若需要支持类似自动打开的能力，需要注入 `BROWSER` 环境变量，指向 cli 路径
2. 参考 `packages/startup/entry/web/render-app.tsx` 中的实现，自定义 `CLIENT_ID` 并注入到终端环境变量
3. 注册 RemoteOpenerConverterContribution，提供默认的 `converter`
4. server 端实现一个 /open 接口，逻辑参考 tools/dev-tool/src/server.ts
- Add remote opener

feat: add remote opener

---

packages/file-tree-next/src/browser/file-tree-contribution.ts
packages/file-tree-next/src/browser/services/file-tree-model.service.ts

set correct context menu on empty view block

fix: set correct context menu on empty view block

---

packages/debug/src/browser/editor/debug-model-manager.ts
packages/debug/src/browser/editor/debug-model.ts
packages/extension/src/browser/vscode/api/main.thread.tests.ts
packages/testing/src/browser/icons/icons.less
packages/testing/src/browser/test-decorations.ts
packages/theme/src/common/color-tokens/index.ts

1. 在测试资源管理器里运行测试状态也会同步到编辑器，反之亦然
2. 如果当前 line 存在 testing decoration 则不会走到 debug 的断点逻辑
实现在 Testing Decoration 里运行测试用例

feat: support testing decorations run test

---

packages/debug/src/browser/editor/debug-breakpoint-zone-widget.tsx
packages/extension/src/browser/vscode/api/main.thread.tests.ts
packages/monaco-enhance/src/browser/folded-code-widget.ts
packages/monaco-enhance/src/browser/peek-view.ts
packages/monaco-enhance/src/browser/zone-widget.ts
packages/scm/src/browser/dirty-diff/dirty-diff-widget.ts
packages/testing/package.json
packages/testing/src/browser/index.ts
packages/testing/src/browser/outputPeek/test-output-peek.ts
packages/testing/src/browser/outputPeek/test-peek-opener.service.ts
packages/testing/src/browser/outputPeek/test-peek-widget.less
packages/testing/src/browser/outputPeek/test-peek-widget.tsx
packages/testing/src/browser/testing.contribution.ts
packages/testing/src/common/commands.ts
packages/testing/src/common/test-result.ts
packages/testing/src/common/testingPeekOpener.ts
packages/testing/src/common/testingUri.ts

基于 ZoneWidget 拓展了 PeekView 组件，Testing Output Peek 组件继承于它，但还未实现 body 里左侧 markdown 右侧树组件的效果，相当于目前只有个壳
实现简单的 Testing Output Peek Widget 组件

feat: support simple testing outputpeek view widget

---

packages/testing/src/browser/index.ts
packages/testing/src/browser/test-decorations.ts
packages/testing/src/browser/theme.less
packages/testing/src/common/constants.ts

当测试结果为 error 时在对应测试函数右侧显示测试结果
实现 Test Message 的内敛显示

feat: support testing message inline content

---

packages/preferences/src/browser/preference-contribution.ts

fixed #363
当不存在配置时，会根据设置ID自动填充内容并提示补全：
当存在非 `String` 类型配置时，如 `Array`,  `Object` 会定为到配置位置，但不会提示补全信息：
locating setting id while clicking edit in settings.json

fix: locating setting id while clicking edit in settings.json

---

packages/components/src/recycle-tree/RecycleTree.tsx

- #359
- #354 
fix new files on fileTree

fix: use the last call when repeating update RecycleTree

---

packages/editor/src/browser/preference/schema.ts

fix: tabsize minimum should be >= 1

---

packages/comments/src/browser/comments-zone.view.tsx
packages/core-browser/src/contextkey/testing.ts
packages/markdown/src/browser/markdown-widget.tsx
packages/markdown/src/browser/markdown.service.ts
packages/markdown/src/common/index.ts
packages/monaco-enhance/src/browser/zone-widget.ts
packages/testing/src/browser/index.ts
packages/testing/src/browser/outputPeek/test-message-container.tsx
packages/testing/src/browser/outputPeek/test-output-peek.ts
packages/testing/src/browser/outputPeek/test-peek-message.service.ts
packages/testing/src/browser/outputPeek/test-peek-opener.service.ts
packages/testing/src/browser/outputPeek/test-peek-widget.less
packages/testing/src/browser/outputPeek/test-peek-widget.tsx
packages/testing/src/browser/test-decorations.ts
packages/testing/src/browser/testing.contribution.ts
packages/testing/src/common/commands.ts
packages/testing/src/common/index.ts
packages/theme/src/common/color-tokens/testing.ts

1. 对于 assertEquals 的测试用例是打开 diffEditor 面板来对比查看 expected 和 actual 的值
2. 对于堆栈信息的错误则是打开 markdown 视图并支持 command 命令
PS: OutputPeek 的右侧文件树还未实现
支持 Testing OutputPeek 查看测试结果

feat: support testing message output peek view

---

packages/search/src/browser/search.replace.widget.tsx

fixed #367 
wrap replace button with observer on search panel

fix: wrap replace button with observer on search panel

---

packages/components/src/select/index.tsx
packages/components/src/select/style.less
packages/core-common/src/preferences/preference-schema.ts
packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts
packages/preferences/src/browser/preferenceItem.view.tsx
packages/preferences/src/browser/preferences.module.less
scripts/watch.ts

fixed #357 ，支持枚举配置，以及 default 提示
support enumDescriptions on preference view

feat: support enumDescriptions on preference view

---

packages/core-common/__tests__/path.test.ts
packages/core-common/src/path.ts

close #393
- fix: 修复 Path.join 不能正确处理相对路径的问题。

fix: fix Path.join cannot handle relative path correctly

---

packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts
packages/testing/src/browser/components/testing.explorer.tree.tsx
packages/testing/src/browser/components/testing.module.less
packages/testing/src/browser/icons/icons.ts
packages/testing/src/browser/outputPeek/test-message-container.tsx
packages/testing/src/browser/outputPeek/test-peek-widget.less
packages/testing/src/browser/outputPeek/test-peek-widget.tsx
packages/testing/src/browser/outputPeek/test-tree-container.tsx
packages/testing/src/common/test-result.ts
packages/testing/src/common/testingStates.ts
packages/testing/src/common/tree-view.model.ts

PS: 还未实现 testing result storage，正常来说右边的树是测试结果的历史记录
Testing OutputPeek 右侧支持测试用例的树展示

feat: support message output peek tree

---

packages/extension/src/hosted/api/vscode/ext.host.quickopen.ts

Gitlens uses the private property of vscode quickopen, we also need to adapt
change quickopen eventEmitter to private property

fix: change quickopen eventEmitter to private property

---

packages/core-common/src/utils/strings.ts
packages/monaco-enhance/src/browser/peek-view.ts
packages/monaco-enhance/src/browser/zone-widget.ts
packages/testing/src/browser/outputPeek/test-output-peek.ts
packages/testing/src/browser/outputPeek/test-peek-widget.tsx
packages/testing/src/common/testingStates.ts

之后对于继承于 zone widget 的组件只需要传递 isResizeable options 即可
zone widget 支持高度自定义拖拽能力

feat: support output peek horizontal resizeable

---

packages/core-browser/src/menu/next/menu-id.ts
packages/monaco-enhance/src/browser/peek-view.ts
packages/testing/src/browser/outputPeek/test-output-peek.ts
packages/testing/src/browser/outputPeek/test-peek-widget.less
packages/testing/src/browser/outputPeek/test-peek-widget.tsx
packages/testing/src/browser/test-tree-view.model.ts
packages/testing/src/browser/test.result.service.ts
packages/testing/src/browser/testing.contribution.ts
packages/testing/src/common/commands.ts

新增以下5个菜单项
testing output peek 面板支持新标签页打开日志等菜单项

feat: support output peek actions bar

---

packages/remote-cli/package.json
packages/task/src/browser/problem-line-matcher.ts
packages/task/src/browser/terminal-task-system.ts

- process multi-line output in task
- ignore equals problem data

fix: process multi-line output in task

---

packages/main-layout/src/browser/tabbar/tabbar.service.ts

containerId 同时也是入参的名字，导致之前这里漏了取当前遍历项的 containerId
- 修复 tabbar 插入 item 后 hidden 状态丢失问题

fix: 修复 tabbar 插入 item 后 hidden 状态丢失问题

---

packages/startup/package.json

去掉tools目录的nodemon watch 
减少因为extension相关js文件导致频繁的自动更新

fix: nodemon remove tools watch

---

packages/status-bar/src/browser/status-bar-item.view.tsx
packages/status-bar/src/browser/status-bar.module.less

status-bar 增加了 Popover 后父元素的 flex 作用不到 Popover 里面的 item 导致布局出问题了。
- 修复 status-bar 中 Popover 下元素的布局问题

fix: 修复 status-bar 元素排版问题

---

packages/file-tree-next/src/browser/services/file-tree-model.service.ts

fixed #458
new folder with contextMenu after rename file cause error

fix: new folder with contextMenu after rename file cause error

---

packages/core-browser/src/services/external-uri.service.ts
packages/remote-opener/__tests__/browser/remote-opener-converter.test.ts
packages/remote-opener/__tests__/browser/remote.opener.service.test.ts
packages/remote-opener/src/browser/remote.opener.service.ts

去除掉默认的SupportHost 把自定义能力完全暴露给调用用户。
方便url打开的默认情况直接走OpenerService。
export一个接口，方便集成方继承。

feat: remove default supportHosts

---

packages/terminal-next/src/browser/terminal.client.ts
packages/terminal-next/src/browser/terminal.service.ts

handle `shellPath` not passed when create terminal

fix(terminal): handle shellPath not passed case

---

packages/terminal-next/src/node/pty.ts

[测试版](https://github.com/opensumi/core/issues/453) 这里有两个问题
```ts
kill() {
if(this.disposed) {
return;
}
}
```
因为 `this.disposed` 的实现是判断 disposables. length === 0, 而 ptyService 中没有注册任何 disposable，导致在这一步认为已经 `disposed`，直接返回，导致 pty 进程没有退出
为 `pty.onExit` 和 `pty.onData` 注册 disposable 后出现第二个问题
在 kill 中调用 `ptyProcess.kill` 后直接 dispose ，导致之前的事件监听一并被清理，没有触发退出事件
1. 为 `pty.onExit` 和 `pty.onData` 注册 disposable 
2. 在 onExit 事件回调里执行 dispose 清理事件监听

fix: pty process exit issue

---

packages/components/src/popover/index.tsx
packages/status-bar/src/browser/status-bar-item.view.tsx

fix: hide pophover if no tooltip

---

packages/testing/src/browser/outputPeek/test-output-peek.ts
packages/testing/src/browser/outputPeek/test-peek-widget.tsx
packages/testing/src/browser/test-contextkey.service.ts
packages/testing/src/browser/testing.contribution.ts

fix: command palette esc Keybinding event

---

packages/status-bar/src/browser/status-bar-item.view.tsx
packages/status-bar/src/browser/status-bar.module.less

Fixed #481 
fix: hide statusbar popover if no command

fix: hide statusbar popover if no command

---

packages/core-browser/src/window/window.service.ts

close #35 
不能打开 `http://127.0.0.1:8000` 是因为 Electron 环境不需要处理 localhost 的路径。Web 会通过 external 属性替换 localhost。
- only web env deal with openNewWindow external prop

fix: only web env deal with openNewWindow external prop

---

packages/file-tree-next/src/browser/file-tree.service.ts
packages/file-tree-next/src/browser/services/file-tree-model.service.ts

优化了文件树的更新队列，移除了原来多余的 500ms 时延，让文件树在频繁的文件变化情况下也能保持 500ms 更新一次的频率，有效保证了更新的稳定性
案例模拟了每 200ms 创建一个文件的情况
improve filetree update process

fix: improve filetree update process

---

packages/editor/src/browser/editor.module.less
packages/keymaps/src/browser/keymaps.service.ts
packages/keymaps/src/common/keymaps.ts
packages/startup/entry/sample-modules/editor-empty-component.contribution.tsx
packages/startup/entry/web/render-app.tsx

- 替换新 LOGO
- 让空白编辑器的快捷键能够正常展示
- 支持通过 `editorBackgroundImage` 指定背景图片
dark：
light： 
fix empty editor background show logic

fix: empty editor background show logic

---

packages/testing/src/browser/outputPeek/test-output-peek.ts
packages/testing/src/browser/test-contextkey.service.ts

由于错误的使用 monaco editor dom 来创建 context key scoped ，会导致很多 monaco 自身事件（如撤销、回退等）失效。
所以直接采用 monaco 自身的 contextKeyService 来创建 scoped
修复撤销、回退失效的问题

fix: peek view context key scoped

---

packages/editor/src/browser/editor.module.less
packages/editor/src/browser/editor.view.tsx
packages/editor/src/browser/workbench-editor.service.ts

fix
and
样式优化
- 字号减小
- 添加 max-width ，超出后显示省略号
- 修复某些情况下编辑器打开方式没有被清除的问题
- 修复已打开文件注册 openType 可能不生效的问题
- 优化打开方式开关样式

fix: editor opentype switcher

---

packages/main-layout/src/browser/tabbar/bar.view.tsx

拖拽时图片显示成顶栏上的头像部分了。
- 修复侧边栏 tab 拖拽时拖拽图显示问题

fix: 修复侧边栏 tab 拖拽时拖拽图显示问题

---

packages/components/src/checkbox/index.tsx
packages/quick-open/src/browser/quick-open.view.tsx

add tabindex=0 to checkbox wrap,see https://stackoverflow.com/questions/42764494/blur-event-relatedtarget-returns-null
quickopen hide when blur

fix: quickopen hide when checkbox trigger blur event

---

package.json

目前 CI 中较多的 warning 影响错误信息的定位
only show error while running lint script

chore: only show error while running lint script

---

packages/core-browser/src/toolbar/components/button.tsx

编辑器的文件树点击事件好像阻止了冒泡，导致点文件树时工具栏上的 popover 没法自动收起
- 修复阻止冒泡导致的 popover 自动隐藏不生效问题

fix: toolbar popover autohide not working

---

packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts
packages/terminal-next/src/browser/links/link.ts
packages/terminal-next/src/browser/links/validated-local-link-provider.ts

close #486 
> 同步 VSCode 1.63.2 版本的正则 `vs/workbench/contrib/terminal/browser/links/terminalValidatedLocalLinkProvider.t`
1. 鼠标移到对应的路径，有明确提示行为"Open file in editor"，在新窗口打开文件夹
2. 如果是项目内的文件，有明确的提示"Focus folder in explorer"，并支持在当前工作区打开或者聚焦到对应的目录
3. 如果是项目外的文件，在 Electron 环境通过新窗口打开
support terminal to open folder and file

feat: support terminal to open folder and file

---

packages/extension/__tests__/browser/main.thread.decoration.test.ts
packages/extension/src/browser/vscode/api/main.thread.api.impl.ts
packages/extension/src/browser/vscode/api/main.thread.editor-tabs.ts
packages/extension/src/common/vscode/editor-tabs.ts
packages/extension/src/common/vscode/index.ts
packages/extension/src/hosted/api/vscode/ext.host.api.impl.ts
packages/extension/src/hosted/api/vscode/ext.host.editor-tabs.ts
packages/extension/src/hosted/api/vscode/ext.host.window.api.impl.ts
packages/extension/src/hosted/api/worker/worker.host.api.impl.ts
packages/types/vscode/typings/vscode.proposed.d.ts

在插件里通过 vsocde.window.openEditors 可获取多个 editor group 下的所有 tabs 信息
实现 vscode.OpenEditorInfo API

feat: implememt window editor tabs API

---

packages/core-browser/src/react-providers/slot.module.less
packages/core-browser/src/react-providers/slot.tsx
packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts

before:
after:
这里的“详情”展示是根据系统语言展示，展示不需要做国际化处理
improve error boundary block style

style: improve error boundary block style

---

packages/components/src/style/mixins.less
packages/core-browser/src/style/override.less
packages/quick-open/src/browser/styles.module.less

原有的 quickOpen 和 menu 边角样式太锐，优化了阴影并添加了圆角
before
after
- improve menus box-shadow
- add border-radius

feat: 💄  improve shadow styles

---

packages/main-layout/src/browser/tabbar/tabbar.service.ts

Display `containerId` when not set `title` in browserView contributes

feat: use id as hide menu fallback name

---

packages/quick-open/src/browser/quick-open.view.tsx

onClick too late, cause the onBlur first, replaced by MouseDown
fix: use onMouseDown to run quickopen item

fix: use onMouseDown to run quickopen item

---

packages/core-browser/src/components/actions/styles.module.less
packages/core-browser/src/style/override.less
packages/core-browser/src/style/variable.less
packages/editor/src/browser/editor.module.less
packages/theme/src/common/color-tokens/custom/menu.ts

before
after
before
after
-   improve some editor styles

feat: improve some editor styles

---

packages/extension/src/browser/vscode/api/main.thread.api.webview.ts
packages/extension/src/common/vscode/webview.ts
packages/types/sumi-worker/sumi-worker.d.ts
packages/types/vscode/typings/vscode.d.ts
packages/webview/src/browser/iframe-webview.ts
packages/webview/src/browser/types.ts
packages/webview/src/webview-host/webview-manager.ts

Defaults to true if WebviewOptions.enableScripts scripts are enabled Otherwise defaults to false.
support enableForms api like this
enableForms: false
add WebviewOptions enableForms api

feat: add WebviewOptions enableForms api

---

packages/components/src/style/mixins.less

在以下版本中测试通过
```
less: 4.1.2
less-loader: 10.2.0
less: 3.13.1
less-loader: 5.0.0
```
close #586 
修复 less unit 函数在高版本下编译失败

fix: 修复 less unit 函数在高版本下编译失败

---

packages/core-common/src/types/file.ts
packages/extension/src/browser/vscode/api/main.thread.file-system.ts
packages/extension/src/common/vscode/file-system.ts
packages/extension/src/hosted/api/vscode/ext.host.file-system.ts
packages/file-service/src/browser/file-service-client.ts
packages/types/vscode/typings/vscode.proposed.d.ts

在之前，如果实现了 FileSystemProvider ，只有在 registerFileSystemProvider 的时候传递 isReadonly 为 true 才会令打开的文件为只读，且只能令所有打开的文件作为只读
而该 api 就是可以自己实现 stat 方法来决定打开的某一个文件是否为只读模式
实现了 FileStat permissions API

feat: implement FileStat permissions api

---

packages/main-layout/src/browser/tabbar/styles.module.less

before:
after:
- improve panel border style

style: improve panel border style

---

packages/extension/src/browser/extension-instance-management.ts
packages/extension/src/browser/extension-view.service.ts
packages/extension/src/browser/extension.service.ts
packages/extension/src/browser/types.ts
packages/extension/src/common/extension.service.ts

sumi 插件如果申明了 browserView 的 contributes，那么每次插件激活的时候都会重复执行该贡献点。由于插件进程重启的时候会重新激活插件，会导致贡献点被重复执行
修复插件进程重启时带视图组件的 sumi 插件副作用清理逻辑

fix: plugin registers browserComponent repeatedly when restart plugin process

---

packages/extension/src/browser/sumi-browser/contribution/editor.ts
packages/extension/src/browser/sumi-browser/contribution/editorSide.ts
packages/extension/src/browser/sumi-browser/contribution/tabbar.ts
packages/extension/src/browser/sumi-browser/contribution/toolbar.ts
packages/types/sumi-browser.d.ts

Add intialProps support for sumi extension type

chore: Add intialProps support for sumi type extension 

---

packages/file-tree-next/src/browser/file-tree.service.ts
packages/file-tree-next/src/browser/services/file-tree-model.service.ts

ensure refresh task before location file on filetree

fix: ensure refresh task before location file on filetree

---

packages/core-electron-main/browser-preload/index.js
packages/core-electron-main/src/types.ts
packages/extension/src/browser/extension-node.service.ts

Fix NodeExtProcessService cannot create RPC connection in electron

fix(ext): update invalid import

---

packages/core-common/src/localize.ts
packages/extension/__tests__/browser/main.thread.env.test.ts
packages/extension/src/browser/vscode/api/main.thread.env.ts

close: #613 
Change `vscode.env.language` default value to `en`

feat: change vscode.env.language

---

packages/core-browser/__tests__/bootstrap/connection.test.ts
packages/core-browser/src/bootstrap/connection.ts

fixed #635 
fire ws connected after core module initialized

fix: fire ws connected after core module initialized

---

packages/remote-opener/__tests__/node/opener.client.test.ts
packages/remote-opener/src/node/opener.client.ts

避免Remote Opener异常导致Websocket连接创建失败。在某些网络环境不稳定或者其他未知情况下，setRemoteOpenerServiceInstance会被多次调用，然后抛出异常导致上层connection创建过程被异常中断。
WS创建被异常终端导致IDE Crash
- 调整 RemoteOpener 异常抛出行为

fix: ws connection error caused by remote opener

---

packages/editor/src/browser/format/formatterSelect.ts

fixes: #661 
对于同一个插件重复调用多次 `registerDocumentFormattingEditProvider` 注册多个 DocumentFormattingEditProvider 的情况下，这里原有的逻辑可能会错误的获取的 Provider
原本的 formatters 是 monaco 内部计算得出的顺序结果，也就是说索引越靠前准确性越高，之前的逻辑在赋值给 elements 是就已经丢失了正确的 formatter (因为它们的 extensionId 一致，forEach 赋值时会后面会直接直接覆盖掉)
- fix document formatting provider bug

fix: editor formatting provider preferred logic

---

packages/core-browser/src/quick-open/index.ts
packages/editor/src/browser/editor.contribution.ts
packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts
packages/quick-open/src/browser/components/quick-open-tabs/index.tsx
packages/quick-open/src/browser/components/quick-open-tabs/style.module.less
packages/quick-open/src/browser/prefix-quick-open.service.ts
packages/quick-open/src/browser/styles.module.less

close: #632 
第一种解法，隐藏该 Tab：
第二种，来自 #636：
Adjust QuickOpen Tab Style

style: adjust quickOpen style

---

packages/webview/src/browser/plain-webview.ts

Calling `loadUrl` on Electron's `plainWebview` instance may result in webview loading twice.
* fix plainWebview may load twice in electron

fix: fix plain webview may load twice in electron

---

packages/editor/src/browser/fs-resource/fs-resource.ts
packages/file-tree-next/src/browser/dialog/window-dialog.service.tsx

- 在 Remote 模式下，文件在远端，使用远端的文件保存窗口。
use web save dialog in Remote Mode

fix: use web save dialog in Remote Mode

---

packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts
packages/main-layout/src/browser/main-layout.contribution.ts
packages/main-layout/src/browser/tabbar/tabbar.service.ts

close #619 
起因，由于切换底部面板最大化是两个 command，需要提供默认的 when 去区分。 具体看：#619 
- 修复之前翻译
- 支持最大化切换，提供默认的 when 设置
效果：
添加底部面板最大化快捷键

feat: added shortcuts expand panel at the bottom

---

packages/core-browser/src/authentication/authentication.service.ts
packages/core-common/src/types/authentication.ts
packages/extension/__tests__/hosted/api/vscode/ext.host.authentication.test.ts
packages/extension/src/browser/vscode/api/main.thread.authentication.ts
packages/extension/src/common/vscode/authentication.ts
packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts
packages/startup/package.json
packages/types/vscode/typings/vscode.authentication.d.ts

package.json
```json
{
"publisher": "opensumi",
"name": "auth-demo",
"version": "1.0.0",
"engines": {
"vscode": "^1.22.0"
},
"activationEvents": [
"*"
],
"main": "./index",
"contributes": {
"commands": [
{
"command": "auth.login",
"title": "Login"
},
{
"command": "auth.relogin",
"title": "Relogin"
},
{
"command": "auth.logout",
"title": "Logout"
}
]
},
"dependencies": {
"express": "^4.17.1",
"passport": "^0.4.1",
"passport-github2": "^0.1.12"
}
}
```
index.js
```js
const vscode = require('vscode');
const express = require('express');
const passport = require('passport');
const { Strategy: GitHubStrategy } = require('passport-github2');
const AUTH_PORT = 10899;
const clientID = '7629552d4c5f0116620d';
const clientSecret = 'fd24f43e4b0248fed5abba5a1ba49037c67b4bc9';
let init = false;
class …
```

feat: implement forceNewSession and silent to authentication api

---

package.json

> The package simple-git before 3.3.0 is vulnerable to Command Injection via argument injection. When calling the .fetch(remote, branch, handlerFn) function, both the remote and branch parameters are passed to the git fetch subcommand. By injecting some git options, it was possible to get arbitrary command execution.
- upgrade simple-git to v3.3.0

chore: upgrade simple-git to v3.3.0

---

README-zh_CN.md
README.md

试了一下，npm 8 已经可以直接安装了，移除 README 中的提示语句

docs: update README

---

packages/addons/__test__/node/inde.test.ts
packages/addons/src/index.ts
packages/express-file-server/src/index.ts
packages/extension-manager/src/index.ts
packages/extension/src/index.ts
packages/file-search/__tests__/node/file-search.service.test.ts
packages/file-search/src/index.ts
packages/process/__tests__/node/index.test.ts
packages/process/src/index.ts
packages/search/__tests__/node/content-search.service.test.ts
packages/search/src/index.ts
packages/startup/entry/web/server.ts
packages/startup/src/node/common-modules.ts
packages/task/src/index.ts
packages/task/src/node/index.ts
tools/electron/src/browser/index.ts
tools/electron/src/modules/topbar/index.ts
tools/electron/src/node/index.ts
tools/template/src/index.ts

fixes #633 
集成可能需要修改的
将
```ts
import { ExtensionModule } from '@opensumi/ide-extension';
import { ProcessModule } from '@opensumi/ide-process';
import { ExpressFileServerModule } from '@opensumi/ide-express-file-server';
import { SearchModule } from '@opensumi/ide-search';
```
修改为
```ts
import { ExtensionModule } from '@opensumi/ide-extension/lib/node';`
import { ProcessModule } from '@opensumi/ide-process/lib/node';
import { ExpressFileServerModule } from '@opensumi/ide-express-file-server/lib/node';
import { SearchModule } from '@opensumi/ide-search/lib/node';
```
- remove unused export

chore: remove unused export

---

packages/editor/src/browser/editor.contribution.ts
packages/editor/src/browser/monaco-contrib/callHierarchy/callHierarchy.service.ts
packages/editor/src/browser/monaco-contrib/tokenizer/textmate.service.ts
packages/editor/src/browser/workbench-editor.service.ts
packages/search/src/browser/search.service.ts

fixed #688
dispose model reference

fix: dispose model reference

---

packages/core-electron-main/browser-preload/index.js

给 electronEnv 增加 os 版本，指定 bigSur 及以上的 macOS 窗口， header 要适应新系统的高度
fix: electron window header hight incorrect

fix: electron window header hight incorrect

---

packages/editor/src/browser/editor.module.less
packages/main-layout/src/browser/tabbar/styles.module.less
packages/terminal-next/src/browser/component/tab.item.tsx
packages/terminal-next/src/browser/component/tab.module.less
packages/terminal-next/src/browser/terminal.client.ts
packages/terminal-next/src/browser/terminal.view.ts

1. 终端 Tab 栏与编辑器样式保持一致
2. 默认添加 `terminal` icon
3. 拆分终端场景下，tab 标题根据当前激活的终端动态展示
4. 去除了使用逗号分割终端标题的行为
5. 拆分终端后自动聚焦
https://user-images.githubusercontent.com/17701805/159862885-4ad31818-cc10-4a89-abf6-c4fc2b653c59.mp4
- improve terminal tab styles

feat: improve terminal tab styles

---

packages/core-common/src/hash-calculate/hash-calculate.ts
packages/editor/src/browser/doc-model/editor-document-model-service.ts

provider.onDidChangeContent may be triggered at very early stage. 
wait until hash service initialize before accept external change, fixing possible issues.

fix: wait until hash service initialize before accept external change

---

packages/quick-open/src/browser/quick-open.view.tsx
packages/quick-open/src/browser/quickInput.inputBox.ts

`QuickOpen` do not hide when blur on electron

fix: quick open do not hide on electron

---

packages/main-layout/src/browser/tabbar/renderer.view.tsx
packages/main-layout/src/browser/tabbar/tabbar.service.ts

用户反馈编辑器组件消失：
目前排查到结果如下：
我们通过 ToolBarActionContribution 调用 registerToolbarAction，使用 createToolbarActionBtn 往 tabbar 上挂这个编辑器按钮（调试器左边的位置）： 
整体大概是这么用的：
```ts
registry.registerToolbarAction({
id: 'editor111',
component: createToolbarActionBtn({
delegate: () => {
this.layoutService.bottomExpanded;
}
})
});
```
这个按钮会在渲染时（useEffect(, [])）调用这个 delegate 函数，函数中调用了 bottomExpanded。
bottomExpanded 调用后就会产生报错：
MainLayoutModuleContribution 中是在 initialize 生命周期中初始化的所有 slot，其中会初始化 NextBottomTabRenderer，然后该 render 内部才会把 resizeHandle 注册给 TabBar。
如果在这个 resizeHandle 被注册之前调用 bottomExpanded，就会报错。
所以在我们这个 case 下，渲染 registerToolbarAction 注册的 component 的时机比渲染底部 NextBottomTabRenderer 还早。
目前还不知道这个时序问题是怎么触发的，但 OpenSumi 这里需要容错。
Update tabbar resizeHandle logic

feat: update tabbar resizeHandle logic

---

packages/core-browser/src/components/actions/index.tsx

fix
rc-menu 升级后，这里的 children 可能不是数组
- find menu children logic

fix: find menu children logic

---

packages/file-tree-next/src/browser/file-tree.service.ts
packages/file-tree-next/src/browser/services/file-tree-model.service.ts

- 移除了 TreeModel 初始化阶段对 labelService 多余的响应，解决首屏闪烁问题
- 确保文件树快照恢复完成后再进行文件树的定位
improve filetree snapshot recovery progress

fix: improve filetree snapshot recovery progress

---

packages/theme/src/browser/icon.service.ts
packages/theme/src/browser/workbench.theme.service.ts

close #774 
make icon theme apply correctly

fix: make icon theme apply correctly

---

packages/editor/src/browser/workbench-editor.service.ts

快速切换tab时，需在open前做判断  close #735
修复快速切换打开文件时展示问题

fix: quick change tabs when opening

---

packages/core-browser/src/style/monaco-override.less
packages/debug/src/browser/editor/debug-hover-widget.tsx
packages/debug/src/browser/editor/debug-hover.module.less

before
after
修复 debug hover 变量面板会被溢出隐藏的问题

fix: debug hover overflow hidden

---

packages/editor/src/browser/workbench-editor.service.ts

fix: cache component resource open types

---

packages/file-tree-next/src/browser/file-tree.service.ts
packages/file-tree-next/src/browser/services/file-tree-model.service.ts

原有的删除文件依赖文件 URI 去获取节点，在压缩节点情况下，获取到的节点如下所示为 `.../test/fixture`, 但实际期望删除的是 `.../test`, 该 PR 修复改问题
make sure delete files correctly on compressed nodes

fix: make sure delete files correctly on compressed nodes

---

packages/components/src/recycle-tree/RecycleTree.tsx
packages/components/src/recycle-tree/tree/TreeNode.ts
packages/file-tree-next/__tests__/browser/file-tree.test.ts

定位到造成文件树文件重复的原因在于，折叠/展开目录操作本身与“刷新”操作存在可能的冲突问题，这里的“刷新”指的是广义上的刷新，如文件在文件树上定位，也会触发 “刷新” 操作，去展开对应目录下的文件目录，相似的操作还有 快照恢复、刷新等。
修复中首先对 RecycleTree 中的渲染函数增加了一个 bufferPromise，保障在触发视图渲染时，在渲染未完成前讲后续可能的渲染函数调用合并为 1 次调用。
其次在调用 “刷新” 操作时触发的 `hardReloadChildren` 方法中增加了对两种冲突情况的处理，保障了在 “刷新” 和 展开/折叠 快速操作，并且存在并发掉用情况时正确处理 `flattenedBranch` 的更新。
问题复现及修改前效果：
修改后效果：
set branch correctly while doing expand & refresh at the same time

fix: set branch correctly while doing expand & refresh at the same time

---

packages/file-tree-next/src/browser/services/file-tree-model.service.ts

close #792 
ignore file open logic while clicking on file tree empty block

fix: ignore file open logic while clicking on file tree empty block

---

packages/core-electron-main/src/bootstrap/window.ts
packages/electron-basic/src/browser/welcome/welcome.module.less
packages/electron-basic/src/browser/welcome/welcome.tsx

- 指定 electron 默认的的 font-size 大小为 13px
close: #805
set default font size for electron

fix: set default font size for electron

---

packages/components/src/recycle-tree/tree/TreeNode.ts
packages/file-tree-next/src/browser/file-tree-contribution.ts
packages/file-tree-next/src/browser/file-tree.service.ts
packages/file-tree-next/src/browser/services/file-tree-model.service.ts

improve keybinding behavior
improve file tree navigator

fix: improve file tree navigator

---

packages/editor/src/browser/component.ts

部分视图设置可能因为激活、写法问题导致对同一个 schema 注册了相同内容，这里在获取 SchemaResolver 的时候做了一下 array 的去重处理，防止出现下面的视觉问题：
merge equal code type on editor component

fix: merge equal code type on editor component

---

packages/quick-open/src/browser/quick-title-bar.ts

Before:
After:
fix the quick-open title button theme

fix: the quick-open title button theme

---

packages/core-browser/src/react-providers/config-provider.tsx
packages/storage/src/browser/storage.service.ts

修复部分无法访问的代码注释路径，添加额外的 log 用于后续定位 storage 问题
upate some code comment

chore: upate some code comment

---

packages/core-common/src/utils/ipc.ts
packages/core-electron-main/src/bootstrap/window.ts
packages/extension/__tests__/node/extension.service.test.ts
packages/extension/src/common/index.ts
packages/extension/src/node/extension.service.client.ts
packages/extension/src/node/extension.service.ts
packages/extension/src/node/index.ts

this close: #806 
fix extHost process start timing problem

fix: consumed floating promises

---

packages/components/src/recycle-tree/RecycleTree.tsx
packages/components/src/recycle-tree/tree/TreeNode.ts
packages/components/src/recycle-tree/tree/model/TreeModel.ts
packages/components/src/recycle-tree/types/watcher.ts
packages/file-tree-next/src/browser/file-tree-model.ts
packages/file-tree-next/src/browser/services/file-tree-decoration.service.ts
packages/scm/src/browser/components/scm-resource-tree/scm-tree-model.ts

优化文件树的界面绘制过程，以文件编辑场景并同时启动编译服务的程序为例：
之前（一次编辑操作，触发 3 次文件树重绘操作）：
https://user-images.githubusercontent.com/9823838/163801620-110c4324-4e31-4ace-a80c-eda67860bd88.mp4
之后（对于文件树无变化的更新场景，过滤掉该重绘操作）：
https://user-images.githubusercontent.com/9823838/163801442-16a22037-9629-4ca1-8a0b-a8909319f730.mp4
improve file tree re-render progress

fix: improve file tree re-render progress

---

packages/search/src/browser/search.view.tsx

1. 修复搜索面板 processbar 进度条卡顿
2. searchBrowserService.search 调用需要加上 context
close #854 
fix search panel process bar performance

fix: search panel process bar performance

---

packages/webview/src/browser/plain-webview.ts

- assign url value to `webview`'s `src` attribute will trigger webview's `attach` lifecycle immediately (which was triggered in next event loop in previous electron versions), resulting in missing of `preload` scripts.

fix: adaptor webview lifecycle for electron 18

---

packages/extension/src/common/vscode/ext-types.ts

在 vscode-hexeditor 插件中，使用了最新的 RelativePattern 类，且第一个参数是 Uri 类型
但在我们的旧实现当中并不支持，导致该插件运行报错
kaitian.RelativePattern 参数支持 Uri

feat: improve RelativePattern

---

packages/preferences/src/browser/preference-contribution.ts

close #877 
trigger suggest correctly while opening settings.json

fix: trigger suggest correctly while opening settings.json

---

packages/extension/src/node/extension.service.ts

Fix mistakenly deleting a socket being listened on

fix: mistakenly deleting a socket being listened on

---

packages/theme/src/browser/icon.service.ts
packages/theme/src/browser/theme.contribution.ts
packages/theme/src/browser/workbench.theme.service.ts
packages/theme/src/common/mocks/theme.service.ts
packages/theme/src/common/theme.service.ts

第一次加载时（无缓存），在设置了 `defaultPreferences.general.theme` 的情况下，会先应用一次内置的 baseTheme(vs-dark), 然后等主题插件加载完后再次应用设置的主题，并且之前的改造是在插件全部 contributes 结束之前就 render 了界面，因为这样看起来会快一些。于是这中间主题切换的过程会导致闪烁。有缓存的情况下，会直接从缓存中获取上一次的主题，相对等待插件 contributes 来说会快很多。
这里有几个问题
1. opensumi 并没有默认渲染时就将 baseTheme 应用上去，而是等 initialize 阶段才应用（可以优化）
2. 等待所有插件 contributes 完成太慢，不等会在配置的主题加载时闪烁
3. 较小概率会出现的是，themeService 中会监听 preferencesChange 事件，而可能在插件 contributes 未执行完（也就是设置的主题还没注册时）就调用 `applyTheme` ，而这里又因为此时主题并不存在，会走到默认 fallback 到 baseTheme 的逻辑，导致出现设置了 defaultPreferences.general.theme 且安装了主题，但并未加载成功的情况。
1、2 解决方式是在 `ThemeContribution` 中等待配置的主题加载完成
```ts
initialize() {
async initialize() {
await this.themeService.themeLoaded.promise;
}
```
由于不同集成、配置、插件安装情况不同，这里 `themeLoaded` resolve 的时机也有所不同
1. 设置了 defaultPreferences.general.theme …

feat: wait for color theme applied

---

packages/core-common/src/disposable.ts
packages/editor/src/browser/index.ts
packages/editor/src/browser/monaco-contrib/callHierarchy/callHierarchy.service.ts
packages/editor/src/browser/monaco-contrib/index.ts
packages/editor/src/browser/monaco-contrib/typeHierarchy/typeHierarchy.contribution.ts
packages/editor/src/browser/monaco-contrib/typeHierarchy/typeHierarchy.service.ts
packages/extension/__tests__/browser/main.language.test.ts
packages/extension/src/browser/vscode/api/main.thread.language.ts
packages/extension/src/common/vscode/converter.ts
packages/extension/src/common/vscode/ext-types.ts
packages/extension/src/common/vscode/languages.ts
packages/extension/src/common/vscode/model.api.ts
packages/extension/src/hosted/api/vscode/ext.host.api.command.ts
packages/extension/src/hosted/api/vscode/ext.host.language.ts
packages/extension/src/hosted/api/vscode/language/type-hierarchy.ts
packages/monaco/src/browser/contrib/index.ts
packages/monaco/src/browser/contrib/typeHierarchy.ts
packages/types/vscode/typings/vscode.language.d.ts

support vscode 1.63.2 type hierarchy api
sample: https://github.com/Eskibear/type-hierarchy-sample/blob/main/src/extension.ts
sample: ESLint extension (version 2.2.2)
* support vscode 1.63.2 type hierarchy api

feat: support type hierarchy api

---

packages/extension/src/hosted/api/vscode/ext.host.language.ts

fix the problem caused by missing parameters in withAdapter method

chore: fix missing parameters in withAdapter method

---

packages/components/src/recycle-tree/RecycleTree.tsx
packages/components/src/recycle-tree/tree/TreeNode.ts
packages/file-tree-next/src/browser/services/file-tree-model.service.ts

补充一种新的可能造成副作用的操作方式，即在展开节点的时候快速折叠，处理优先级如下：
同时优化 `←`,`→`,`↑`,`↓` 文件树操作的流畅性
https://user-images.githubusercontent.com/9823838/165311110-b1c4e6ff-4ec2-4e36-86db-f45938b1f324.mp4
optimized tree operations and conflict handling

fix: optimized tree operations and conflict handling

---

packages/terminal-next/src/browser/component/tab.module.less
packages/terminal-next/src/browser/terminal.view.ts

- terminal title fallback to default name

fix: terminal title fallback to default name

---

packages/connection/package.json
packages/connection/src/browser/ws-channel-handler.ts
packages/startup/entry/web/render-app.tsx
packages/utils/package.json
packages/utils/src/uuid.ts

Use [nanoid](https://github.com/ai/nanoid) to replace [shortid](https://github.com/dylang/shortid)
close #882  
replace shortid with nanoid dependency

feat: remove shortid dependency

---

scripts/module-jest.ts

```
npm run test:module -- --module=debug   
> @opensumi/core@ test:module C:\Users\Desktop\opensumi-core
> cross-env NODE_OPTIONS=--max_old_space_size=5120 node -r ts-node/register ./scripts/module-jest "--module=debug"
Error: ● Validation Error:
Module ./jest.setup.js in the setupFiles option was not found.
```

chore: fix module jest scripts

---

packages/debug/__tests__/browser/debug-session-connection.test.ts
packages/debug/src/browser/debug-session-connection.ts

#930
sendCustomRequest应该是只返回body
response customRequest with the body in debug session

fix: response customRequest with the body in debug session

---

packages/extension/__tests__/browser/extension-service/extension.service.test.ts
packages/extension/src/browser/extension.service.ts

#859 
当页面不可见的时候，不进行插件进程重启，同时监听 visibilitychange 事件，当页面变为可见后再重启

feat: pause restart ext process when the page is not visible 

---

.vscode/launch.json

在 debug 后端或插件 host 代码时可以跳过 node 程序的内部文件，避免不必要的单步跳转
attach 后端或 host 时跳过  node_internals

feat: attach backend or extension host skip node_internals

---

packages/utils/package.json

- remove @opensumi/ide-core-common dependence from utils

chore: remove @opensumi/ide-core-common dependency from utils

---

packages/editor/src/browser/preference/schema.ts
packages/editor/src/browser/workbench-editor.service.ts
packages/editor/src/common/editor.ts
packages/extension/src/browser/vscode/contributes/customEditors.tsx
packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts
packages/preferences/src/browser/preference-settings.service.ts

同时作以下调整
1. 当 customEditors 的 priority 为 option 时，weight 的优先级降为最低，不作为默认打开方式
2. 如果 priority 为 default ，则根据 selector filenamePattern 匹配规则来作为默认打开方式
右下角的悬浮按钮需要作调整，收敛到右上角作为下拉菜单项，不在此 pr 处理
支持 workbench.editorAssociations 配置项

feat: support workbench.editorAssociations

---

packages/terminal-next/src/browser/terminal.client.ts
packages/terminal-next/src/browser/terminal.controller.ts
packages/terminal-next/src/common/pty.ts
packages/terminal-next/src/node/pty.ts
packages/terminal-next/src/node/terminal.service.ts

在TerminalProfile中有 isTransient 或者 检测到Terminal是 Extension创建 的时候，不纳入保活逻辑，窗口关闭自动杀
JSDebugger 插件适配因为终端恢复逻辑导致生命周期异常。

fix: shellLaunchConfig isTransient not keepalive

---

.npmrc
package.json

增加对 engine 的限制，按照文档限制在了 v12 - 14
背景是在其他项目中 nvm 切到 17 后返回 opensumi 安装依赖出错

chore: check node version

---

packages/core-browser/package.json

ref: https://github.com/microsoft/vscode-languageserver-node/releases/tag/release%2Ftypes%2F3.17.0
lock vscode-languageserver-protocol dependence version

chore: lock vscode-languageserver-protocol dependence version

---

packages/core-browser/src/components/actions/styles.module.less
packages/core-browser/src/style/monaco-override.less
packages/core-browser/src/style/normalize.less
packages/editor/src/browser/view/topPadding.ts

Close #960
- 在 reset 中增加 scrollbar 样式
- 移除了额外的 scrollbar 配置
- 对于 monaco 覆盖了滚动条样式
- 对于 tab 等滚动保持原有逻辑
Request reviewers: @erha19 @bytemain

style: default and editor scroll width

---

packages/core-electron-main/src/bootstrap/types.ts
packages/express-file-server/package.json
packages/express-file-server/src/browser/file-server.contribution.ts
packages/express-file-server/src/node/express-file-server.contribution.ts
tools/dev-tool/src/server.ts

修复 Windows 启动 core 后，IDE 不能正常加载资源比如图标主题或者 worker 资源
close #1015 
1. 静态资源拼接用 path 而不是 fsPath
```js
// windows
assetsUri.toString()
'http://127.0.0.1:8000/'
uri.toString()
'file:///c%3A/Users/Administrator/repo/core/tools/extensions/vscode-icons-team.vscode-icons/icons/folder_type_kubernetes.svg'
// 组合
assetsUri.withPath(`assets${decodeURIComponent(uri.codeUri.fsPath)}`).toString();
'http://127.0.0.1:8000/assetsc%3A/Users/Administrator/repo/core/tools/extensions/vscode-icons-team.vscode-icons/icons/folder_type_kubernetes.svg'
```
标准的 uri windows 路径是：`file:///d:/some/path/to/repos/on/d/drive`
所以如果用 assets 拼接，应该是 http://127.0.0.1:8000/assets/d:/some/path/to/repos/on/d/drive 而不是现在的
http://127.0.0.1:8000/assetsd:/some/path/to/repos/on/d/drive
2. 解析使用 uri 解析，而不是截断
从 http://127.0.0.1:8000/assets …

fix: windows-compatible static resource URIs

---

packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts
packages/preferences/src/browser/preferenceItem.view.tsx
packages/preferences/src/browser/preferences.module.less
packages/preferences/src/browser/preferences.view.tsx

通过默认配置传入配置项时可能会与配置项 Scheme 定义冲突，此时应该优先使用默认配置作为默认值
优化部分文案，移除了有工作区设置情况下自动跳转工作区设置的交互
resolve correct default value on preference view

fix: resolve correct default value on preference view

---

packages/core-electron-main/src/bootstrap/window.ts
packages/electron-basic/src/browser/header/header.module.less
tools/electron/src/node/server.ts

1. 修复 windows menu 和 title bar 高度不一致
2. 修改 macOS 版本红绿灯位置
close #989 
fix the height of electron windows header bar

fix: the height of electron windows header bar

---

packages/extension-manager/src/browser/extension-overview/index.tsx
packages/extension-manager/src/browser/extension-overview/overview.module.less
packages/extension-manager/src/browser/extension/extension.module.less
packages/extension-manager/src/browser/extension/index.tsx
packages/extension-manager/src/browser/vsx-extension.contribution.ts
packages/extension-manager/src/browser/vsx-extension.service.ts
packages/extension-manager/src/browser/vsx-extension.view.tsx
packages/extension-manager/src/common/index.ts
packages/extension-manager/src/node/vsx-extension.service.ts

Related issues: https://github.com/opensumi/core/issues/747 https://github.com/opensumi/core/issues/750
> 目前解决的问题
>
> - 插件详情页按钮样式
> - 为 `<Extension />` 添加 type，在 init 时扩展市场可以正确判断安装、已安装与更新状态
> - 修复部分 lint warning
>
>这个改动复杂度比想象中大，所有有些疑问的点想先讨论下
>
> - 发现额外的问题
> - 搜索栏切换到 “已安装插件” 后依然搜索市场中的插件
> - 插件有部分能力没有实现，包括激活、禁用、卸载
> - browser 侧的 installedExtensions property 是通过 `getExtensionInstances` computed ，实际调用的 extensionMap 并没有在增删插件时更新，是通过 initExtensionMetaData 从 node 侧的 nodeExtensionService 初始化时读取的，要实现同步的话这块改动可能比较大
> - 对于更新来说，可能还需要增加额外的逻辑，在安装前首先卸载相同 extensionId 的插件，保持插件唯一。另外项目本身也会在 `tools/extensions` 安装插件，和 `~/.sumi/extensions` 中 extensionId 相同时，更新应该操作哪一侧
**Fix**
- 已安装与更新逻辑可正常在插件市场 tab 显示
> 提到的同步和搜索等其他问题后续拆成其他 PR，关联 issue 先不 close 了
improve extension-management state & detail page styles

fix: extension-management state & detail page styles

---

packages/core-browser/src/common/common.command.ts
packages/core-browser/src/common/common.contribution.ts

~~由于 command 没有 label，new_folder 在 menu 中引用没有生效，同时命令面板中也没有注册~~
在 file menu 中移除相关逻辑

fix: file menus remove new_folder

---

packages/remote-cli/package.json
packages/remote-cli/src/index.ts
packages/remote-cli/webpack.config.js

chore: unified command processing capability

---

packages/core-browser/src/preferences/preference-service.ts
packages/core-common/__tests__/di-helper.test.ts
packages/extension/__tests__/node/extension.host.manager.common-tester.ts
packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts
packages/preferences/src/browser/preferenceItem.view.tsx
packages/preferences/src/browser/preferences.module.less
packages/preferences/src/browser/preferences.view.tsx
packages/scm/__tests__/browser/scm-model.test.ts
packages/search/__tests__/browser/search-tree.service.test.ts
packages/search/src/browser/search.service.ts

主题初始化较早，而配置完成初始化太晚，导致主题色这种配置项无法被读到，最终导致主题闪烁或展示异常问题

fix: wait for all preference provider ready

---

packages/debug/src/browser/view/frames/debug-call-stack-session.view.tsx
packages/debug/src/browser/view/frames/debug-call-stack.module.less

before：
after:
improve debug stack item style

style: improve debug stack item style

---

package.json
scripts/changelog/github.ts
scripts/changelog/types.ts
scripts/changelog/util.ts
scripts/iteration-plan.ts

用于按日期，按版本生成一份迭代计划模板，调用格式如下：
```bash
$ GITHUB_TOKEN=... npm run iteration -- --time=2022-2-2 --version=2.18
```

chore: add iteration plan generate script

---

packages/components/src/recycle-list/RecycleList.tsx
packages/core-browser/src/quick-open/index.ts
packages/extension/__tests__/hosted/api/vscode/ext.host.quickopen.test.ts
packages/extension/src/browser/vscode/api/main.thread.quickopen.ts
packages/extension/src/common/vscode/window.ts
packages/extension/src/hosted/api/vscode/ext.host.quickopen.ts
packages/quick-open/__tests__/browser/quick-open.service.test.ts
packages/quick-open/src/browser/quick-open-item.service.ts
packages/quick-open/src/browser/quick-open.service.tsx
packages/quick-open/src/browser/quick-open.type.ts
packages/quick-open/src/browser/quick-open.view.tsx
packages/quick-open/src/browser/quick-open.widget.tsx
packages/quick-open/src/browser/quick-pick.service.ts
packages/quick-open/src/browser/quick-title-bar.ts
packages/quick-open/src/browser/styles.module.less
packages/quick-open/src/common/icon.ts
packages/types/vscode/typings/vscode.quickpick.d.ts

1. 支持 VSCode 插件 API 1.63.2 中的 QuickOpen 相关 API：
QuickPick
[x] onDidTriggerItemButton
[x] keepScrollPosition
QuickPickItem
[x] buttons
[x] QuickPickItemButtonEvent
2. 支持 RecycleList 新接口 onScroll，完善类型补全
3. 修复 QuickOpen 如果没有 title 内容就不显示 TitleBar 的问题
效果：
1. 支持在 QuickOpen Item 中添加 buttons 按钮
动图（gif）：
2. 支持添加 keepScrollPosition 选项，在 quickOpen items 更新后，继续显示当前内容，而不是置顶
support quick-open buttons and keepScrollPosition plugin api

feat: support quick-open buttons and keepScrollPosition plugin api

---

packages/connection/src/common/proxy.ts
packages/core-common/src/application-error.ts
packages/debug/src/browser/debug-configuration-manager.ts
packages/workspace-edit/src/browser/workspace-edit.service.ts

closes #779 
原来后端报错的时候，返回给前端的只有message和stack，所以前端不具有使用`FileSystemError`进行错误信息判断的能力。
在使用了`FileSystemError`的时候，补充了相关属性。

fix: add missing data when use ApplicationError

---

packages/file-tree-next/src/browser/file-tree.tsx

before:
after:
remove loading while non-workspace

fix: remove loading while non-workspace

---

packages/editor/src/browser/quick-open/go-to-line.ts
packages/quick-open/src/browser/quick-open.type.ts
packages/quick-open/src/browser/quick-open.view.tsx
packages/quick-open/src/browser/quick-open.widget.tsx

当前的 "转到行" 功能无法使用，我们在输入完行号之后，按下回车，此时由于 editor 是 focus 状态，导致会触发 quickInput 的 onBlur 事件，导致其实行为是取消的。
fix "Go To Line" not work

fix: go to line not work

---

packages/terminal-next/src/node/pty.proxy.ts

终端 PTY 缓存数据的时候只存放前1024个字符，因为正常情况下也不会超过1024个，如果超过的话，基本上是用户误操作导致的cat 二进制文件或者其他未知问题，比如说之前npm会有一直往终端输出不可见内容的问题，导致打爆cache。
通过缓存限制在每行1024字符来避免潜在的单行字符量太大导致内存泄漏问题。

feat: add pty line cache max length

---

packages/core-browser/src/layout/accordion/tab-bar-toolbar.tsx

related: #1042 
注册工具菜单项用的是`registerMenuItem`函数，取消注册使用`unRegisterMenuItem`函数，所以我在 [tab-bar-toolbar.tsx](https://github.com/opensumi/core/pull/1058/files) 中补充了一下，不确定能不能解决问题。

feat: add unregister item

---

packages/terminal-next/src/browser/terminal.controller.ts
packages/terminal-next/src/node/terminal.service.ts

在Electron环境下，终端不恢复，并且生命周期跟随window，和旧的生命周期一样。
避免功能故障以及内存泄漏。
因为终端恢复能力是依赖于云研发场景下Server不会被kill的前提的，Electron模式是运行在用户本机，所以终端也应该按照传统的生命周期走。

Electron环境下忽略终端恢复逻辑

---

packages/components/__tests__/recycle-tree/tree/TreeNode.test.ts
packages/components/src/recycle-tree/tree/TreeNode.ts
packages/file-tree-next/src/browser/file-tree-contribution.ts
packages/file-tree-next/src/browser/file-tree.service.ts
packages/file-tree-next/src/browser/services/file-tree-api.service.ts
packages/file-tree-next/src/browser/services/file-tree-dnd.service.ts
packages/file-tree-next/src/browser/services/file-tree-model.service.ts
packages/file-tree-next/src/common/file-tree-node.define.ts

close #1084.
close #1077.
通过移除掉多余的文件事件处理逻辑以及加入临时节点的创建过程，让文件树内的文件操作可以在脱离文件服务的情况下也可以正常响应用户操作。
同时在切换 Tabbar 时移除文件树焦点，修复 collapsedAll 后文件树快照没有及时更新问题
以下为屏蔽了文件事件响应情况下的操作效果，在文件事件正常运作时，文件树的状态更新将会更加准确：
https://user-images.githubusercontent.com/9823838/169974759-406cba6d-9357-4746-8215-24a9424a05b6.mp4
弱化文件树对于文件事件依赖，优化文件树操作响应速度

fix: improve file tree new or rename files speed

---

packages/editor/src/browser/editor.module.less

closes #1085 
before:
after:
improve editor tab close button style

style: close button hover

---

packages/core-node/src/bootstrap/app.ts
packages/extension-manager/src/browser/extension-overview/index.tsx
packages/extension-manager/src/browser/extension/index.tsx
packages/extension-manager/src/browser/vsx-extension.contribution.ts
packages/extension-manager/src/browser/vsx-extension.service.ts
packages/extension-manager/src/browser/vsx-extension.view.tsx
packages/extension-manager/src/common/index.ts
packages/extension-manager/src/node/vsx-extension.service.ts
tools/dev-tool/src/server.ts
tools/electron/src/node/server.ts

closes #1049 
1. 去掉 [app.ts](https://github.com/opensumi/core/pull/1064/files#diff-3b0a46e1b06590eb974b8dd6c73d012bce362456f0e1b156c448502d5dd2a892L187) 和[server.ts](https://github.com/opensumi/core/pull/1064/files#diff-cdd58a0e7b8a27dd0543bacc14c79ecdaf52845389936d3156a1e33d2c9b5e11L58) 的 `endpoint`的`/api`这一段path，让后端自主拼接，例如，[这里](https://github.com/opensumi/core/pull/1064/files#diff-bebbc315d5b07466553702f80427a0e83b6fd631b4fd50b4b9ad55d9ad79f8b1L63)。
2. 在激活的时候，通过`this.vsxExtensionService.getOpenVSXRegistry`  获取后端返回的`registry`，抹除前端硬编码的 Registry 逻辑。
full support for extension marketplace config

chore: remove registry constant in fe

---

package.json
tools/dev-tool/package.json
tools/electron/package.json

chore: lock typescript version to 4.6.4

---

packages/editor/src/browser/editor.contribution.ts

Background: 浏览器中，diff 模式下，切换编码不生效。
editor.contribution 注册编码切换的命令，执行 changeModelOptions。changeModelOptions中，根据 uri 获取 docRef 进行编码切换，当 uri 为 diff uri，获取不到 docRef。
solution:  diff 模式下，分别获取  original/modify uri (git uri)，拿到 docRef 进行编码切换
修复编辑器 Diff 模式下切换编码失效问题

fix: diff editor encoding switch

---

packages/terminal-next/src/browser/terminal.controller.ts

在终端恢复时检测到sessionID不包含"|"时不启用hack clientID逻辑
某集成端完成重写了Terminal前端连接逻辑以及sessionID逻辑，此时terminal.controller不应该强行做clientID的hack，这样会导致终端基础逻辑反而出bug。
因此在执行Hack逻辑判断下sessionID是否包含"|"这个字符，如果没有的话，可以认为这是被干预过的SessionID，不执行Hack逻辑。
不过本质上是集成端的覆写逻辑太过于老旧导致的，正好借此回归验证的机会对这里的hack逻辑做一个Corner Case 的处理。

在终端恢复时检测到sessionID不包含"|"时不启用hack clientID逻辑

---

packages/file-tree-next/src/browser/file-tree-node.module.less

fix: #673
filetree input selection color should inherit parent node

fix: filetree input selection color should inherit parent node

---

packages/extension-manager/src/browser/vsx-extension.contribution.ts

close  #1120.
show extension list while extension manager is activated

fix: show extension list while extension manager is activated

---

packages/file-tree-next/src/browser/file-tree.tsx
packages/file-tree-next/src/browser/services/file-tree-dnd.service.ts
packages/file-tree-next/src/browser/services/file-tree-model.service.ts
packages/i18n/src/common/zh-CN.lang.ts

close #1131 
优化了文案展示，强调该部分功能为筛选功能，是基于当前的文件树进行筛选操作，而不是查找，这里仅会基于当前状态做筛选
remove unexpected expandAll action before filtering the file tree

fix: remove unexpected expandAll action before filtering the file tree

---

packages/terminal-next/__tests__/node/pty.proxy.test.ts
packages/terminal-next/src/node/pty.manager.remote.ts

支持了终端双容器模式的RPC Socket重连。之前的终端双容器模式只会执行一次连接，如果因为各种原因（比如说PtyService启动慢了一步）导致连接失败，整个终端功能都会失效。因此需要一个自动重连PtyService的功能，在Socket连接失败后自动轮询，自动连接的逻辑。
目前还有一个未知的疑惑，为什么在我调用了RPCServiceCenter.removeConnection之后，之前的方法调用依然会被执行，导致注册的方法被重复多次调用，目前使用了标志位做规避，背后的原因暂时没有调查出来。
终端双容器偶现的连接失败。

feat: add pty remote reconnection

---

packages/core-browser/src/components/actions/styles.module.less
packages/core-browser/src/style/override.less

style: revert menu item style

---

packages/extension-manager/src/browser/extension-overview/index.tsx
packages/extension-manager/src/browser/extension-overview/overview.module.less

before:
after:
improve extension manager scroller style

style: improve extension manager scroller style

---

packages/file-tree-next/src/browser/file-tree-contribution.ts
packages/search/src/browser/search.service.ts

1. 修复了 include 条件不能和 only opened docs 一起使用
2. 修复了点击默认排除项后，从 node_modules 中的文件夹右键点击 在文件夹中搜索 不生效的 case。（解决方案就是在路径后加一个 /），但这只是暂时的修复，之后从根本上修一下。
3. 修复了当前打开的文档 & include 条件会出现多个结果
Fix inaccurate search results when use `include` and `isOnlyOpenEditors`

fix: inaccurate search results

---

packages/terminal-next/src/node/pty.manager.remote.ts

socket.connect 连接错误的时候会抛出异常，此时自动重连，同时需要 catch 错误。
避免在抛出错误的时候导致的外部逻辑异常。
- 增加socket connect的try catch

fix: Pty Service远程服务错误重连的异常处理

---

tools/electron/src/node/server.ts

fix an error `TS2305: Module '"@opensumi/ide-core-common"' has no exported member 'DEFAULT_OPENVSX_REGISTRY'.`
Original terminal output
```powershell
ERROR in C:\Users\situ\github\opensumi\core\tools\electron\src\node\server.ts     
[tsl] ERROR in C:\Users\situ\github\opensumi\core\tools\electron\src\node\server.ts(6,20)
TS2305: Module '"@opensumi/ide-core-common"' has no exported member 'DEFAULT_OPENVSX_REGISTRY'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @opensumi/ide-electron@1.1.0 build:main: `webpack --config ./build/webpack.main.config.js `
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @opensumi/ide-electron@1.1.0 build:main script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run …
```

fix: wrong import in tools/electron

---

packages/terminal-next/src/browser/terminal.controller.ts

对recovery数据做一个简单校验，因为之前groups数据可能是字符串或object，而现在抛弃了字符串的方式，所以为了避免旧逻辑写入localStorage的数据混乱，这里做一个简单的校验
增加终端恢复的数据校验逻辑

fix: 增加对Terminal Recovery逻辑下错误数据的防御

---

packages/core-browser/src/components/layout/split-panel.tsx
packages/main-layout/src/browser/tabbar/tabbar.service.ts

SplitPanel 组件中 getMaxSizeProperty 的时候拿的是 minSize property
修改为 maxSize

fix: get layout maxSize property error

---

packages/terminal-next/src/node/terminal.service.client.ts

修复getCodePlatformKey方法的错误，该错误会导致Linux环境在该方法会被返回为windows。
致使前端判断错误，导致ISSUE #1110 
修复 BUG ISSUE #1110 
点击终端新增旁边下拉按钮无反应，修复了该case
- 修复getCodePlatformKey方法的错误

fix: get wrong code platform key

---

packages/file-tree-next/src/browser/file-tree.module.less

This PR fixes #1141.
So, there is a file called [`tree.module.less`](https://github.com/opensumi/core/blob/cec41477f77274d807b4378c2cb9a132dfba4b2c/packages/core-browser/src/components/tree/tree.module.less) which is similar to [`file-tree.module.less`](https://github.com/opensumi/core/blob/cec41477f77274d807b4378c2cb9a132dfba4b2c/packages/file-tree-next/src/browser/file-tree.module.less). In the file, a pseudo `:before` is adopted to add outline for tree container when mouse hovering on it. And `z-index` is also set to 5 to make sure that the inner treenode won't cover the outline. In this way, the outline works well, like this:
So I use the same way to prevent the outline of file-tree from being covered by its inner elements. Now it works well:
improve the file tree outer activate style

style: improve the file tree outer activate style

---

packages/core-browser/src/components/actions/index.tsx

OS: **Windows**11 22000.708
incorrect title (Before)
After fixing it

fix: incorrect keybinding format in title of InlineActionWidget

---

packages/extension/src/browser/components/extension-tree-view-node.tsx
packages/theme/src/browser/icon.service.ts

插件中会注册大量的 icon，目前框架添加 icon 的逻辑是往已有的 style 标签中添加新的 class，这会导致频繁的触发 reflow，优化方式是插件动态注册的 icon 插入 style 标签
同时优化了 extension treeview node 的渲染性能
before
after
- improve extension icon style performance

fix: improve extension icon style append performance

---

packages/core-common/src/electron.ts
packages/core-electron-main/src/bootstrap/services/ui.ts
packages/electron-basic/src/browser/index.ts

this close: #1104
add missing  `getZoomFactor` method declaration

fix: add missing part for zoom

---

packages/connection/README.md

fix typos and remove empty lines in packages/connection/README.md
fileSevice => fileService
thie => this
By the way, the doc was automatically formatted by  `prettier --write`, how to prevent it?
```shell
(base) PS C:\Users\situ\github\opensumi\core> git commit -m "fix: fix typos and remove empty lines"
[STARTED] Preparing lint-staged...
[SUCCESS] Preparing lint-staged...
[STARTED] Running tasks for staged files...
[STARTED] package.json — 1 file
[STARTED] *.{js,jsx,ts,tsx,md,html,css,less,json} — 1 file
[STARTED] *.{js,jsx,ts,tsx} — 0 file
[SKIPPED] *.{js,jsx,ts,tsx} — no files
[STARTED] prettier --write
[SUCCESS] prettier --write
[SUCCESS] *.{js,jsx,ts,tsx,md,html,css,less,json} — 1 file
[SUCCESS] package.json — 1 file
[SUCCESS] Running tasks for staged files...
[STARTED] Applying …
```

chore: fix typos and remove empty lines

---

packages/core-browser/src/preferences/preference-service.ts
packages/preferences/src/browser/preferenceItem.view.tsx

`preferenceService.get` 不支持指定作用域获取，需要通过 `resolve` 方法获取，同时需要兼容 Scope === 0 的情况
get the default value correctly on preference view

fix: get the default value correctly on preference view

---

packages/components/src/recycle-tree/tree/TreeNode.ts

问题定位：
这里的路径判断出现问题导致同名目录被忽略处理了
improve treenode path check logic

fix: improve treenode path check logic

---

.github/workflows/release.yml
package.json
scripts/generate-manifest-json.ts

manifest.json 存放了 OpenSumi 包的元信息，供插件安装引擎、自动更新版本插件这些地方消费，这些数据在 2.14 后没有生成了
release 时生成 manifest 文件

feat: release 时生成 manifest 文件

---

packages/file-service/package.json

锁定NSFW版本，在2022年6月初 NSFW发布的2.2.1版本中，存在着Linux系统上watch巨大项目时无限循环/递归的问题。
导致await watcher.start() 的操作无限等待，进而造成IDE启动一直失败。
因此把版本锁定到测试无问题的2.2.0上。
- nsfw 2.2.1版本出现致命bug
- lock nsfw version

fix: lock nsfw version

---

packages/file-service/package.json
packages/terminal-next/src/node/pty.manager.remote.ts
packages/terminal-next/src/node/terminal.service.client.ts

Cherry Pick 3 Bug Fixes by retrox
- 后续的一些对OpenSumi的修复需要pick到2.18上
- fix: get wrong code platform key #1159
- fix: handle socket uncaught error #1193 
- fix: lock nsfw version #1204

fix: cherry-pick #1159 #1193 #1204

---

package.json
packages/remote-cli/package.json

在 Electron 17 环境下使用目前存在该问题 https://github.com/sindresorhus/got/issues/1803 ，通过升级依赖的方式解决该问题

chore: upgrade got dependence to v12.1.0

---

scripts/start-electron.ts

`npm run start:electron` does not work because `touch` does not exist on Windows.
Here is a solution(using fs API that is equivalent to `touch`) to this issues: https://stackoverflow.com/a/34259166/8096007

fix: start electron not work on Windows

---

packages/core-browser/src/toolbar/toolbar.registry.ts
packages/core-browser/src/toolbar/toolbar.tsx
packages/core-browser/src/toolbar/types.ts
packages/extension/src/browser/sumi/main.thread.toolbar.ts
packages/extension/src/browser/sumi/types.ts

fix: #1192
```json
"kaitianContributes": {
"workerMain": "./index.js",
"toolbar": {
"actions": [
{
"type": "button",
"title": "运行",
"id": "common-start",
"when": "showMe == 1",
"states": {
"default": {
"titleForeground": "#FF004F"
},
"clicked": {
"titleForeground": "#CCC"
}
}
}
]
}
},
```
toolbar support when clause contexts

feat: toolbar support when clause contexts

---

packages/extension/src/browser/vscode/api/main.thread.language.ts

兼容没有指定 language 但包含 pattern 和 scheme 的 languagefeature
- 兼容没有指定 language 但包含 pattern 和 scheme 的 languagefeature

fix: matchLanguage logic

---

scripts/download.js

之前升级 got 是为了 stream 的问题 
#1208
但 got 最新版本使用了 esm，导致下载插件异常，当前替换 got 为 node-fetch。
replace got with node-fetch

fix: replace got with node-fetch

---

packages/terminal-next/src/browser/component/terminal.view.tsx

Fix can not click to close the search box in the terminal

fix(terminal): close search input box

---

packages/components/src/dialog/index.tsx
packages/overlay/__tests__/browser/dialog.service.test.tsx
packages/overlay/src/browser/dialog.service.ts
packages/overlay/src/browser/dialog.view.tsx
packages/overlay/src/common/index.ts

Close #1057
对于 `dialogService.open` 增加 `props` 透传给 Overlay 组件
**使用方式**
例如对 https://github.com/opensumi/core/blob/main/packages/editor/src/browser/untitled-resource.ts#L205 增加 props
触发 dialog 增加对应 className
`dialogService.open` 增加 props 自定义 dialog 样式

feat: dialog support custom props for overlay

---

packages/express-file-server/src/browser/file-server.contribution.ts

close https://github.com/opensumi/ide-startup/issues/25.
the AppConfig.staticServicePath config supports domain with path

fix: the AppConfig.staticServicePath supports domain with path

---

packages/connection/__test__/node/index.test.ts
packages/connection/src/browser/ws-channel-handler.ts
packages/connection/src/node/common-channel-handler.ts
packages/connection/src/node/ws.ts
packages/core-browser/src/bootstrap/app.ts
packages/core-browser/src/bootstrap/connection.ts
packages/core-browser/src/react-providers/config-provider.tsx
packages/core-common/src/types/common.ts
packages/core-node/src/bootstrap/app.ts
packages/core-node/src/common-module/credential.server.ts
packages/core-node/src/connection.ts
packages/core-node/src/hash-calculate/hash-calculate.contribution.ts
packages/core-node/src/index.ts
packages/core-node/src/types.ts
packages/extension/src/hosted/ext.host.ts
packages/extension/src/hosted/ext.process-base.ts
packages/extension/src/hosted/extension-log2.ts
packages/logs-core/src/node/log-manager.ts

fix: #1222
之后鉴权方式：
前端：
```ts
new ClientApp({
connectionPath: async () => {
return `${wsPath}/service?token=${await getAuthToken()}`;
}
})
```
后端
```ts
new ServerApp({
wsServerOptions: {
verifyClient: (info, done) => {
const url = URL.parse(info.req.url, true);
const { query } = url;
if (!query.token) {
done(false);
}
// 在这里实现鉴权逻辑
const authed = await ctx.service.cloudideWsGateway.verifyAuthToken(query.token);
done(authed);
}
}
})
```
新增 websocket 鉴权机制

feat: 新增 websocket 鉴权机制

---

packages/terminal-next/src/browser/terminal.typeAhead.addon.ts

- 默认屏蔽掉TypeAhead的日志
- 添加了一些便于理解的日志
- 这块日志本身没有打印或者落盘的必要，因为这部分日志本身的目的是为了在开发的时候窥探Xterm 和 Pty 的工作原理。而不是相关能力的工作状态记录，所以不需要打印，只是在做相关功能开发或者调试的时候打开。
- 在堆TypeAhead本地补偿能力的学习和了解过程中，写了一些额外的注释到代码里
- add some logs
- hide terminal typeahead logs by default

chore: hide terminal typeahead logs by default

---

packages/terminal-next/src/common/preference.ts

限制默认的Xterm终端显示行数到1000行，之前的5000行内容太多，会导致一些关联处理逻辑的CPU占用太高甚至在极端情况下造成某些ANR。
对于正常情况的用户而言1000行是完全足够的，不够的话也可以在设置中自定义配置。
> 后续需要看看具体是哪条流程导致IDE整体的卡死
- 某些极端场景下（程序巨量输出链接）终端buffer内链接太多的时候会导致IDE卡死
- 目前默认的xterm buffer的行数由5000太多了
- 因此决定默认设置到1000
- chore: limit default xterm scrollback lines

chore: limit default xterm scrollback lines

---

packages/editor/src/browser/untitled-resource.ts
packages/editor/src/browser/workbench-editor.service.ts
packages/extension/src/browser/vscode/api/main.thread.doc.ts
packages/extension/src/common/vscode/doc.ts
packages/extension/src/hosted/api/vscode/doc/doc-manager.host.ts

close #909
support openTextDocument(options?: { language?: string; content?: string; })

feat: update openTextDocument Api

---

packages/debug/src/browser/view/configuration/debug-configuration.module.less
packages/debug/src/browser/view/configuration/debug-toolbar.view.tsx

close https://github.com/opensumi/core/issues/1009
- fix(electron): debug toolbar can't be clicked

fix(electron): debug toolbar can't be clicked

---

packages/core-node/src/types.ts
packages/debug/__tests__/browser/launch-preferences.test.ts
packages/extension-manager/src/node/vsx-extension.service.ts
packages/extension-storage/__tests__/browser/storage.test.ts
packages/extension/__tests__/browser/main.thread.workspace.test.ts
packages/extension/src/hosted/ext.host.ts
packages/extension/src/hosted/ext.process-base.ts
packages/extension/src/hosted/extension-log2.ts
packages/logs-core/__tests__/node/log-manager.test.ts
packages/logs-core/__tests__/node/log.service.test.ts
packages/logs-core/src/node/log-manager.ts

fix keytar in exthost
import appConfig types form ide-core-node/lib/types

fix: import appConfig types form ide-core-node/lib/types

---

packages/task/src/browser/terminal-task-system.ts
packages/terminal-next/src/browser/terminal.controller.ts

Terminal Task 会在任务进程结束后直接退出，不符合预期。本PR修复了这个问题。
修复CherryPick到2.18版本上 #1345
- Terminal Task 会在任务进程结束后直接退出，不符合预期
- cherrypick: #1345 terminal task auto close issue

cherrypick: terminal task auto close issue

---

packages/task/src/browser/terminal-task-system.ts
packages/terminal-next/src/browser/terminal.controller.ts

Terminal Task 会在任务进程结束后直接退出，不符合预期。本PR修复了这个问题。
- Terminal Task 会在任务进程结束后直接退出，不符合预期。
- fix: terminal task auto close issue

fix: terminal task auto close issue

---

packages/scm/src/browser/components/scm-resource-tree/scm-tree-node.module.less

before:
after:
improve SCM treenode tail style

style: improve SCM treenode tail style

---

packages/extension/src/browser/extension-worker.service.ts

部分插件申明 worker 入口文件时不会写明文件.js后缀，在补全后缀时候因补全逻辑比较靠后，导致部分集成场景下出现地址错误的问题
提前进行后缀补全

fix: worker entry file load error

---

packages/terminal-next/src/browser/terminal.preference.ts
packages/terminal-next/src/common/preference.ts

支持了line作为终端指针样式的选项，并且支持了终端指针样式的动态修改，而无需重建Xterm
this close: #1318
- 之前使用bar作为line（Xterm规则），可能会导致用户误解
- 修改此配置后需要重开终端才可生效
- feat: line terminal style and support perf change

feat: line terminal style and support perf change

---

packages/components/src/checkbox/index.tsx

原来自定义工具栏依赖了 CheckBox 默认的开关能力，在设置 checked 默认为 false 后，该开关能力失效导致功能不可用
修复自定义工具栏按钮无法点击问题

fix: custom toolbar buttons

---

packages/components/src/tooltip/index.tsx
packages/components/src/tooltip/style.less

closes #1356 
closes #1359 
issue1 解决截图:
issue2 解决截图:
解决箭头问题
解决当左边空间不足，tip意外显示到页面中部的问题
解决鼠标未enter目标，在同一行时，也会显示tip的问题。
1. 增加children 声明
2. 样式文件补充target容器的display解决鼠标未enter目标，在同一行时，也会显示tip的问题。
3. 新增一个else if 判断 解决当左边空间不足，tip意外显示到页面中部的问题

chore: add missing type declaration

---

packages/terminal-next/src/browser/terminal.controller.ts

修复某些集成端直接调用Terminal Task时遇到的关闭问题。
- 集成端Task结束后关闭生命周期有问题
- cherrypick fix: terminal task system exit failed

fix: terminal task system exit failed

---

package.json
packages/core-browser/src/bootstrap/app.ts
packages/core-browser/src/react-providers/config-provider.tsx
packages/core-common/src/node/port.ts
packages/debug/src/browser/debugUtils.ts
packages/express-file-server/__tests__/browser/index.test.ts
packages/express-file-server/src/browser/file-server.contribution.ts
packages/express-file-server/src/common/index.ts
packages/extension/src/browser/extension-worker.service.ts
packages/remote-cli/src/index.ts
packages/remote-opener/__tests__/browser/remote.opener.service.test.ts
packages/remote-opener/src/browser/remote.opener.service.ts
packages/startup/entry/web-lite/lite-module/file-provider/index.contribution.ts
packages/startup/entry/web/render-app.tsx
tools/dev-tool/src/webpack.js

统一框架内启动时获取到的 HOSTNAME，减少跨域报错及问题

chore: use equal hostname to start server

---

packages/core-browser/src/style/icon/fileicons.less
packages/extension/src/browser/vscode/contributes/menu.ts
packages/extension/src/common/index.ts
packages/theme/src/browser/icon.service.ts

fix #1378
before:
after:
use background image type on extension menu

fix: use background image type on extension menu

---

packages/file-tree-next/__tests__/browser/file-tree.test.ts
packages/file-tree-next/src/browser/services/file-tree-model.service.ts

原有的 `smart` 交互在文件树下很奇怪，不可见节点会默认在顶部会底部出现
show node on the center while revealing filetree node

chore: show node on the center while revealing filetree node

---

packages/debug/src/browser/view/configuration/debug-toolbar.service.ts
packages/debug/src/browser/view/configuration/debug-toolbar.view.tsx

ref https://github.com/opensumi/core/pull/1342/files#diff-78b009ab7192cc151d4422b5c96eb8a0af9ab1f893e1e937eb1aba4278c0dab0R254
lazy load mainUIService on Electron renderer

fix: lazy load mainUIService on Electron renderer

---

packages/core-browser/src/menu/next/renderer/ctxmenu/electron.ts

使用多个 customEditor 的 api 时，会有一个编辑器右上角会出现一个菜单，显示打开的方式。如果出现同一个 command 但不同参数的场景，会导致创建的菜单异常。
https://user-images.githubusercontent.com/2226423/180906017-c389bcb4-6a99-4068-9cc2-7e043a268a96.mov
ctx-menu conflict when same command id

fix: ctxmenu conflig when same command id

---

packages/file-service/package.json
packages/file-service/src/node/file-service-watcher.ts

原来的 Windows 下事件处理逻辑存在问题，依赖了事件执行顺序
实际执行顺序可能与预期不一致
fix windows file event filter

fix: windows file event filter

---

packages/components/src/recycle-tree/tree/TreeNode.ts

当节点处于加载子节点过程时，尽管为展开状态，但此时不应该支持折叠节点，否则后续节点计算可能存在问题
disable node collapse while node is expanding

fix: disable node collapse while node is expanding

---

packages/components/src/recycle-tree/tree/TreeNode.ts

问题定位在针对子节点的刷新过程中，频繁刷新会导致根节点受影响造成异常，最终修改还是将节点暂存于刷新节点的 Children 内，最后再进行统一合并
fix file missing while refresh on sub files

fix: file missing while refresh on sub files

---

packages/keymaps/src/browser/keymaps.view.tsx

原来的错误写法会在每次渲染 Reset 按钮时再次调用 Open 方法导致异常
keymaps view cannot be closed

fix: keymaps view cannot be closed

---

packages/express-file-server/src/browser/file-server.contribution.ts
packages/express-file-server/src/common/index.ts
packages/static-resource/src/browser/static.definition.ts
packages/webview/src/webview-host/webview-manager.ts

close #1450 
原因是部分资源，如字体，webp 没有被正常加载导致界面异常
improve Gitlens 12+ welcome page style

fix: improve Gitlens 12+ welcome page style

---

packages/editor/src/browser/tab.view.tsx
packages/file-tree-next/__tests__/browser/file-tree.test.ts
packages/file-tree-next/src/browser/file-tree.service.ts

feat: improve editor focus behavior

---

packages/file-tree-next/__tests__/browser/file-tree.test.ts
packages/file-tree-next/src/browser/file-tree.service.ts

单击打开文件的情况下不应该把焦点放置到编辑器上
#1448 修改导致的问题
open file on the filetree should not focus on the editor

fix: open file on the filetree should not focus on the editor

---

packages/core-browser/src/common/common.contribution.ts
packages/editor/src/browser/tab.view.tsx

before:
after:
fix editor tabs wrap and debug toolbar position

fix: editor tabs wrap and debug toolbar position

---

packages/core-browser/src/dom/index.ts
packages/core-browser/src/quick-open/index.ts
packages/quick-open/src/browser/quick-open.service.tsx
packages/quick-open/src/browser/quick-open.type.ts
packages/quick-open/src/browser/quick-open.widget.tsx
packages/terminal-next/src/browser/links/link.ts

提供 quickOpen 通用的 modifier 按键监听方法，常用于 quickOpen 上监听用户是否按了 Cmd 或者 Ctrl 或者 Alt。
使用方法：
```
quickPickService.show(items, {
onKeyMods: (mods: KeyMods) => console.log('mods:', mods),
});
```
提供 quickOpen 通用的 modifier 按键监听方法

feat: quickopen add onKeyMods listener

---

packages/search/src/browser/search.contribution.ts

- 编辑器选中文本，在点击搜索面板后停止自动赋值。这会导致用户之前的搜索结果变了，然后重新搜索，这里优化一下交互，点击搜索面板，不会重新赋值。
- 其它情况，比如通过快捷键，通过 quickpick 等行为去触发全局搜索，就会自动赋值。
上面这两种行为和其它编辑器一致。
取消搜索面板自动设置来自编辑器的选中文本

chore: search panel automatically sets selected text

---

packages/components/src/style/base.less
packages/core-browser/src/style/normalize.less
packages/core-browser/src/style/utilities.less

在 component 中使用 less function ，所以 less 的变量是固定值，也一定会出现这种问题。现在直接使用默认值即可。
改变选中文本后的颜色为默认值

style: change text input selection color to default

---

packages/theme/src/browser/icon.service.ts

getIcon basePath maybe has custom scheme
fix: custom icon scheme

fix: custom icon scheme

---

packages/file-tree-next/src/browser/services/file-tree-api.service.ts

fix: auto focus when created new file

---

packages/components/src/recycle-tree/tree/TreeNode.ts
packages/extension/src/browser/vscode/api/main.thread.treeview.ts
packages/extension/src/hosted/api/vscode/ext.host.treeview.ts

fix: remove treeview cached data

---

packages/editor/src/browser/untitled-resource.ts
packages/file-tree-next/__tests__/browser/dialog/file-dialog.service.test.ts
packages/file-tree-next/src/browser/dialog/file-dialog.service.ts

close #1511.
close #1358.
fix saving untitled file on Windows will occur crash

fix: saving untitled file on Windows will occur crash

---

packages/extension/src/browser/extension.contribution.ts
packages/extension/src/browser/vscode/builtin-commands.ts

#1105 的相关问题
<html>
<body>
<!DOCTYPE html>
Linux, Windows | macOS | Feature | 插件自身是否支持 | 对应的command | OpenSumi 是否有实现对应插件命令
-- | -- | -- | -- | -- | --
ctrl+alt+s | cmd+, | Open Settings dialog | ✅ | workbench.action.openGlobalSettings | N/A
ctrl+alt+s | cmd+numpad_separator | Open Settings dialog | ✅ | workbench.action.openGlobalSettings | N/A
</body>
</html>
通过命令代理，借助现有的 `OPEN_PREFERENCES` 适配插件的 `ctrl+alt+s` 快捷键打开设置页面功能。
before:
after:
感觉命令注册部分可能存在重复注册的问题。

feat: shortcut adaptation of ctrl+alt+s

---

packages/core-common/src/preferences/preference-schema.ts
packages/extension/src/browser/vscode/contributes/configuration.ts
packages/preferences/src/browser/preference-settings.service.ts
packages/preferences/src/browser/preferenceItem.view.tsx
packages/preferences/src/browser/preferences.module.less

Previous：
Now:
support display configuration markdown description

feat: support markdown description of preference item

---

packages/core-browser/src/components/actions/styles.module.less
packages/editor/src/browser/editor.module.less
packages/terminal-next/src/browser/component/tab.module.less
packages/theme/src/common/color-tokens/custom/button.ts

统一框架内所有按钮 Hover 默认样式
before:
after:
use css variable as icon hover background

style: use css variable as icon hover background

---

packages/monaco/src/browser/monaco.contribution.ts

- 去除多余的 textmateService 主题初始化逻辑

fix: remove useless textmate theme init logic

---

packages/main-layout/src/browser/main-layout.contribution.ts
packages/main-layout/src/browser/tabbar/tabbar.service.ts

close #1517.
修复终端面板未激活情况下底部工具栏功能缺失问题

fix: 修复终端面板未激活情况下底部工具栏功能缺失问题

---

packages/theme/src/browser/icon.service.ts

fix:
the background mode icon should on position 0 0

style: background mode icon should on position 0 0

---

packages/core-browser/src/common/common.command.ts
packages/extension/src/browser/extension.contribution.ts
packages/extension/src/browser/vscode/builtin-commands.ts
packages/markers/src/browser/markers-contribution.ts

#1105 的相关问题
<html>
<body>
<!DOCTYPE html>
Linux, Windows | macOS | Feature | 插件自身是否支持 | 对应的command | OpenSumi 是否有实现对应插件命令
-- | -- | -- | -- | -- | --
alt+0 | cmd+0 | Activate Messages window (Problems) | ✅ | workbench.actions.view.problems | N/A
alt+numpad0 | cmd+numpad0 | Activate Messages window (Problems) | ✅ | workbench.actions.view.problems | N/A
</body>
</html>
新增一个 `TOGGLE_SHOW_ERRORS_WARNINGS` 命令，然后通过命令代理，适配插件的快捷键 `alt+0` 和`alt+numpand0`。
before:
after:

feat: shortcut-adaptation-of-alt+0

---

packages/core-browser/src/common/common.command.ts
packages/extension/src/browser/extension.contribution.ts
packages/extension/src/browser/vscode/builtin-commands.ts
packages/scm/src/browser/scm.contribution.ts

#1105 相关问题
<html>
<body>
<!DOCTYPE html>
Linux, Windows | macOS | Feature | 插件自身是否支持 | 对应的command | OpenSumi 是否有实现对应插件命令
-- | -- | -- | -- | -- | --
alt+9 | cmd+9 | Close corresponding tool window (Git) | ✅ | workbench.action.toggleSidebarVisibility | N/A
alt+numpad9 | cmd+numpad9 | Close corresponding tool window (Git) | ✅ | workbench.action.toggleSidebarVisibility | N/A
</body>
</html>
在 `SCM_COMMANDS`命名空间新增 `TOGGLE_VISIBILITY `命令，通过命令代理适配插件的`alt+9`和`alt+numpad9`快捷键。
before:
after:

feat: shortcut adaptation of alt+9

---

packages/core-browser/src/style/toolbar.less

fix: toolbar action button not middle

---

packages/terminal-next/src/browser/terminal.context-menu.ts

fix: terminal contextmenu prevent default

---

packages/editor/src/browser/tab.view.tsx

close #1542 
定位到原因是因为 Editor Tabs 的菜单渲染仅与 Group Change 事件关联，导致大部分情况下，Editor Title Menu 的执行参数都是错的
修复编辑器菜单执行参数错误问题

fix: editor title menu should always be worked

---

packages/core-common/src/types/editor.ts
packages/editor/src/browser/doc-model/editor-document-model.ts
packages/editor/src/browser/doc-model/save-task.ts
packages/file-scheme/src/browser/file-doc.ts
packages/file-scheme/src/browser/file-scheme-doc.client.ts
packages/file-scheme/src/common/index.ts
packages/file-scheme/src/node/file-scheme-doc.service.ts

修改原有一旦存在进行中的保存任务就退出的保存逻辑，防止因为用户网络/波动，文件大等原因出现的保存失败后无法进一步保存的问题，有效避免保存假死情况
cancel long time save operator

fix: cancel long time save operator

---

packages/extension/src/browser/extension.contribution.ts
packages/extension/src/browser/vscode/builtin-commands.ts

#1105 相关问题
<html>
<body>
<!DOCTYPE html>
Linux, Windows | macOS | Feature | 插件自身是否支持 | 对应的command | OpenSumi 是否有实现对应插件命令
-- | -- | -- | -- | -- | --
ctrl+` | ctrl+` | Quick switch current scheme | ✅ | workbench.action.selectTheme | N/A
</body>
</html>
通过命令代理适配插件的 ```ctrl+` ```  快捷键。
before:
after:

feat: shortcut adaptation of ctrl+`

---

packages/editor/src/browser/editor.decoration.service.ts
packages/editor/src/common/editor.ts
packages/extension/src/common/vscode/converter.ts
packages/types/vscode/typings/vscode.theme.d.ts

这是一个新需求，想在 editor 上展示这个 css style 的效果，也同步给 VSCode 提了 PR:
- https://github.com/microsoft/vscode/pull/158717
`createTextEditorDecorationType` support `textUnderlinePosition` field

feat: decoration support `textUnderlinePosition`

---

packages/components/src/select/index.tsx
packages/debug/src/browser/view/configuration/debug-toolbar.view.tsx

修复开启多调试 session 时 select 组件的显示问题

fix: multiple debug session toolbar select show options label

---

configs/vscode-extensions.json
packages/core-common/src/const/application.ts
scripts/download.js
tools/electron/config/vscode-extensions.json

升级主题插件，解决两个问题：
- https://github.com/opensumi/Default-Themes/issues/4
- https://github.com/opensumi/Default-Themes/issues/3
同时修改框架默认插件市场镜像，目前国内镜像存在同步问题，有些滞后，后续仅在启动案例中使用

chore: upgrade opensumi-theme to v2.5.6

---

packages/extension/src/browser/loader.ts
packages/extension/src/hosted/worker.host-preload.ts

`data:text/javascript;` 的方式在某些浏览器下会因为操作不安全而被阻止抛出 `The operation is insecure` 异常
- 使用 Blob url 加载 Worker Host

fix: worker url use blob url

---

packages/core-common/src/types/file-watch.ts
packages/core-common/src/types/file.ts
packages/file-service/__tests__/node/file-service-watcher.test.ts
packages/file-service/src/browser/file-service-client.ts
packages/file-service/src/node/disk-file-system.provider.ts
packages/file-service/src/node/file-service-watcher.ts
packages/file-service/src/node/file-service.ts

通过这层改造，更好的支持了不存在文件的监听逻辑：
https://user-images.githubusercontent.com/9823838/186811197-3b93c3bf-a196-43f6-8d65-3b11c09995e4.mp4
同时，经过简单在 ide-startup 中项目中测试，以 `opensumi/core` 项目为基本仓库，安装预装插件后，运行效果如下：
测试脚本：[inotify-consumers](https://github.com/fatso83/dotfiles/blob/master/utils/scripts/inotify-consumers)
结论：运行 Watcher 数量接近 1 倍，从接近 8w+ 减少至 4.8w+，目前测试无进一步问题，需要持续验证
merge common file events to improve file watch service performance

feat: merge common file events to improve file watch service performance

---

.github/stale.yml

add extension api to exemptLabels

chore: add extension api to exemptLabels

---

package.json

否则在 Cloud IDE 运行 WS 的地址是 0.0.0.0，这个需要在容器内指定
删除 start:remote 指定 0.0.0.0

chore: 删除 start:remote 指定 0.0.0.0

---

packages/file-tree-next/src/browser/file-tree.service.ts

close https://github.com/opensumi/core/issues/1556
不过现在这种 display name 的处理，不同 root 下是相同的 displayName，那 FileMap 应该还是会获取到错误的结果
> 两个 workspace 的根文件夹同名或者多窗口情况下工作区同名的情况
- fix file-tree multiple workspaces getNodes action

fix(file-tree): multi roots `getNodeByPathOrUri`

---

packages/extension/src/hosted/api/vscode/ext.host.treeview.ts

- treeview reveal API 优先使用 treeItemId 查找 item

fix: treeview reveal use treeitem id

---

packages/components/src/badge/styles.less
packages/components/src/button/style.less
packages/components/src/checkbox/style.less
packages/components/src/dialog/styles.less
packages/components/src/dropdown/style.less
packages/components/src/icon/styles.less
packages/components/src/input/input.less
packages/components/src/input/validate-input.less
packages/components/src/menu/style.less
packages/components/src/message/style.less
packages/components/src/modal/style.less
packages/components/src/notification/notification.less
packages/components/src/overlay/styles.less
packages/components/src/popover/styles.less
packages/components/src/scrollbars/styles.less
packages/components/src/style/variable.less
packages/components/src/tabs/style.less
packages/components/src/tooltip/style.less

close #1538.
重构 Component 模块内样式前缀，统一使用 `@prefix` 变量。
优化 Dialog 样式
before:
after:
优化消息弹窗按钮样式
before:
after:
improve dialog and notification style

style: improve dialog and notification style

---

packages/opened-editor/src/browser/opened-editor-node.define.ts
packages/opened-editor/src/browser/services/opened-editor-tree.service.ts

fix: use unequal name on opened editor

---

packages/file-tree-next/src/browser/services/file-tree-model.service.ts

close #1580.
remove loading after move file

fix: remove loading after move file

---

packages/electron-basic/src/browser/header/header.tsx

由于 Electron Header Bar 在不同的场景提供的内容不一样，需要把 Electron 的左右两个组件拆出来，方便集成方直接使用对应的组件，进行自由组合。

chore: extract electron header bar components

---

packages/components/src/scrollbars/index.tsx
packages/components/src/scrollbars/styles.less
packages/editor/src/browser/editor.module.less
packages/editor/src/browser/tab.view.tsx
packages/main-layout/src/browser/accordion/titlebar.view.tsx
packages/startup/entry/web/layout.tsx

统一使用了 `@opensumi/ide-components` 内的 `Scroller` 组件，后续对于引用 [packages/core-browser/src/components/scroll/index.tsx](https://github.com/opensumi/core/blob/5bbeaa642290304f5d43693713ac26a09f645fb4/packages/core-browser/src/components/scroll/index.tsx) 的组件均可平滑替换，具备更良好的拓展性
同时移除了原有依赖 DOM 计算去定位 Tab 的逻辑（存在时序问题），由于 `Scroller` 组件依旧是基于原生 Scroller 做的拓展，故可以直接使用兼容性良好的 `Element.scrollIntoView() API`，相关兼容性见：[浏览器兼容性](https://developer.mozilla.org/zh-CN/docs/Web/API/Element/scrollIntoView#%E6%B5%8F%E8%A7%88%E5%99%A8%E5%85%BC%E5%AE%B9%E6%80%A7)
修改后效果预览（跳转丝滑许多）
https://user-images.githubusercontent.com/9823838/188296450-77c2ac72-da51-41ca-836d-879f1211d7fc.mp4
auto focus editor tab when opening a file on filetree

fix: auto focus editor tab when opening a file on filetree

---

packages/editor/src/browser/workbench-editor.service.ts

close #1626.
reveal file on the filetree when editor tobe focused

fix: reveal file on the filetree when editor focused

---

packages/core-browser/src/services/label-service.ts

由于 monaco 0.3x 版本的 guessLanguageIdByFilepathOrFirstLine 函数返回值发生了变化，由原来匹配不到就返回 null 的行为调整成了返回 unknown 字符串，进而影响了后续的文件类型操作
修复文件类型检测错误的问题

fix: detect language mode id

---

packages/debug/src/browser/debug-session.ts
packages/debug/src/common/index.ts
packages/debug/src/common/terminal.ts
packages/extension/src/browser/vscode/api/debug/extension-debug-session-factory.ts
packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts
packages/main-layout/src/browser/tabbar/styles.module.less
packages/terminal-next/src/browser/terminal.api.ts
packages/terminal-next/src/common/api.ts
packages/terminal-next/src/common/pty.ts
packages/theme/src/common/color-tokens/custom/badge.ts

兼容 JavaScript Debugger 插件至最新 1.71.0 版本，解决调试终端不退出问题
close #1637.
close #1423.
auto-close debug terminal after finished or closed

fix: auto-close debug terminal after finished or closed

---

packages/file-service/src/browser/file-service-provider-client.ts
packages/file-service/src/common/file-ext.ts
packages/file-service/src/common/index.ts
packages/file-service/src/node/disk-file-system.provider.ts
packages/file-service/src/node/file-service.ts
packages/startup/entry/web-lite/lite-module/file-provider/browser-fs-provider.ts

- refactor: add missing type for method of `DiskFsProviderClient`
- refactor: add missing type for method of `DiskFileSystemProvider`

refactor: add missing type for `file-service`

---

packages/editor/src/browser/editor.contribution.ts
packages/editor/src/browser/monaco-contrib/tokenizer/textmate.service.ts
packages/editor/src/browser/preference/schema.ts
packages/editor/src/browser/workbench-editor.service.ts
packages/extension/src/browser/vscode/api/main.thread.language.ts
packages/extension/src/browser/vscode/contributes/language.ts
packages/monaco/src/browser/contrib/tokenizer.ts
packages/monaco/src/common/index.ts
packages/monaco/src/common/types.ts

1.65 版本之前，JavaScript/TypeScript 语言注册一部分在 language basic 插件的 json 文件中声明，而另一部分(如 onEnterRules、indentationRules 等)在 typescript language features 插件中调用 API 注册。这部分恰巧在之前的版本中也没有实现。
在这个 [commit](https://github.com/microsoft/vscode/commit/2b92835853693127ba5a92e1750169b28b11a849) 之后语言注册全部都迁移到了 language basic 插件中，这会导致在使用 1.65+版本 typescript language features 插件时缺失一部分例如块注释中按下回车自动插入 `*` 以及自动缩进规则等特性
- 重构语言注册逻辑

refactor: refactor register language configuration

---

packages/terminal-next/package.json
packages/terminal-next/src/browser/terminal.preference.ts
packages/terminal-next/src/browser/xterm.ts
packages/utils/src/platform.ts

终端使用 webGL 渲染器以支持更多功能，在不支持 webgl 的浏览器下 fallback 到 canvas
- terminal use webgl renderer

feat: terminal use webgl renderer

---

packages/components/src/input/ValidateInput.tsx
packages/core-browser/src/quick-open/index.ts
packages/extension/__tests__/hosted/api/vscode/ext.host.quickopen.test.ts
packages/extension/src/browser/vscode/api/main.thread.quickopen.ts
packages/extension/src/common/vscode/enums.ts
packages/extension/src/common/vscode/ext-types.ts
packages/extension/src/common/vscode/window.ts
packages/extension/src/hosted/api/vscode/ext.host.quickopen.ts
packages/extension/src/hosted/api/vscode/ext.host.window.api.impl.ts
packages/quick-open/src/browser/quick-input-service.ts
packages/quick-open/src/browser/quick-open.view.tsx
packages/quick-open/src/browser/quickInput.inputBox.ts
packages/quick-open/src/browser/styles.module.less
packages/types/vscode/typings/vscode.quickpick.d.ts

resolve #1409
warning
error
implement InputBoxValidationMessage and InputBoxValidationSeverity

feat: implement InputBoxValidationMessage and InputBoxValidationSeverity

---

packages/components/src/scrollbars/index.tsx
packages/editor/src/browser/editor.module.less
packages/main-layout/src/browser/accordion/titlebar.view.tsx
packages/main-layout/src/browser/tabbar/styles.module.less
packages/terminal-next/src/browser/component/tab.module.less
packages/types/package.json
packages/utils/package.json

修复 Terminal Tab 选中态样式以及编辑器 Tab 无法滚动到底部的问题
improve terminal and editor tabs style

style: improve terminal and editor tabs style

---

packages/core-browser/src/common/common.command.ts
packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts
packages/quick-open/src/browser/quick-open.command.service.ts

this close: #1457 
- Support `Toggle Word Wrap` command
- Support `Close All Editor` command
- Update command display descriptions
- update some editor commands description

fix: update some editor commands description

---

packages/extension/__tests__/browser/main.thread.treeview.test.ts
packages/extension/src/browser/vscode/api/main.thread.api.impl.ts
packages/extension/src/browser/vscode/api/main.thread.treeview.ts
packages/extension/src/hosted/api/sumi/ext.host.api.impl.ts
packages/extension/src/hosted/worker.host.ts

修复类似[ json 插件](https://github.com/ZainChen/vscode-json) 不能使用收拢所有节点的问题。
在 main.thread.xxx.tx 中会被 WorkerExtProcessService 和 NodeExtProcessService 各实例化一次，导致在点收拢的时候，很可能会调用到 worker 的 command。
fix: showCollapseAll prop invalid

fix: showCollapseAll prop invalid

---

packages/extension/src/browser/vscode/api/main.thread.api.webview.ts
packages/extension/src/common/sumi/webview.ts
packages/extension/src/common/vscode/webview.ts
packages/extension/src/hosted/api/sumi/ext.host.webview.ts
packages/types/sumi.d.ts
packages/webview/__tests__/browser/webview.service.test.ts
packages/webview/src/browser/plain-webview.ts
packages/webview/src/browser/types.ts

我们使用 `opensumi.webview.getPlainWebviewHandle(xx)` 获取一个 webview 的时候， OpenSumi 在 Electron 上不会给这个 webview 设置 partition，导致该 webview 会同步默认的 session，导致 localStorage 和其他页面互通了。
Allow set partition value to webview element by PlainWebviewHandle

feat(ext-host): can set partition in plain webview

---

packages/startup/entry/web-lite/lite-module/extension/utils.ts

fix: startup utils typo

---

packages/components/src/input/input.less
packages/components/src/select/style.less
packages/core-browser/src/components/actions/styles.module.less
packages/core-browser/src/style/normalize.less
packages/debug/src/browser/view/configuration/debug-configuration.module.less
packages/extension-manager/src/browser/vsx-extension.module.less
packages/file-tree-next/src/browser/file-tree-node.module.less
packages/main-layout/src/browser/tabbar/styles.module.less
packages/menu-bar/src/browser/menu-bar.module.less
packages/preferences/src/browser/preferences.module.less
packages/search/src/browser/search.module.less
packages/theme/src/common/color-tokens/custom/button.ts
packages/theme/src/common/color-tokens/custom/icon.ts
packages/theme/src/common/color-tokens/custom/input.ts
packages/theme/src/common/color-tokens/custom/select.ts

close #1678.
调整自定义 ColorToken 注册 fallback 色值，使框架更贴合主题效果
修改后:
- improve select component and global color tokens style

style: improve select component and global color tokens style

---

packages/file-tree-next/src/browser/file-tree-contribution.ts

fix: revealInSideBar invalid

---

packages/collaboration/src/browser/collaboration.service.ts
packages/collaboration/src/node/y-websocket-server.ts

handle了scheme不为`file`的TextModel，引起报错
- [fix: only handle scheme file on collaborative mode](https://github.com/opensumi/core/commit/c51eaf9dba6eeb69c1f19a357e7a0432f09448ae)
- [fix: should break all awaiting init content request before removal](https://github.com/opensumi/core/commit/a4b1202954877f0d42ea6702d9c69d9a2af365a4)
- only handle scheme file on collaborative mode

fix: only handle scheme `file` on collaborative mode

---

packages/electron-basic/src/browser/header/header.module.less

titlebar 的高度没有撑满整个 headerbar，导致拖拽区域狭窄。
修复 Electron HeaderBar 的拖动区域狭窄问题

fix: title bar height narrow

---

packages/status-bar/src/browser/status-bar-item.view.tsx

extension demo:
```
const statusBar = vscode.window.createStatusBarItem();
statusBar.text = 'eslint';
statusBar.tooltip = 'stopping';
statusBar.show();
setTimeout(() => {
statusBar.tooltip = 'running';
}, 3000);
```
change statusbar view when tooltip updated

fix: change statusbar view when tooltip updated

---

packages/editor/src/browser/editor.module.less
packages/editor/src/browser/navigation.module.less

- improve tabs and breadcrumb icon style

style: improve tabs and breadcrumb icon style

---

packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts
packages/terminal-next/src/browser/component/tab.item.tsx
packages/terminal-next/src/browser/component/tab.view.tsx
packages/terminal-next/src/common/render.ts

chore: improve terminal tab title

---

packages/components/src/input/input.less

lost selection style
recover deleted input selection style

fix: recover deleted input selection style

---

packages/file-tree-next/src/browser/services/file-tree-model.service.ts

fix: file tree input validateMessage not hide

---

packages/quick-open/package.json
packages/quick-open/src/browser/components/highlight-label/index.tsx
packages/quick-open/src/browser/quick-open.service.tsx
packages/quick-open/src/browser/quick-open.view.tsx
packages/quick-open/src/browser/styles.module.less
packages/utils/src/iconLabels.ts

命令面板的 label、description 和 detail 都支持渲染 codicons 图标，同时修改之前的搜索匹配逻辑，在命令搜索时不会去搜索图标内的文本。如: $(git-commit)
https://user-images.githubusercontent.com/20262815/191670705-52207e16-418d-4844-a53d-ebae26e310ac.mp4
quickOpen 支持 codicons 图标渲染

feat: support quickopen render codicons

---

packages/preferences/src/browser/preferences.module.less

before:
after:
select option style in light mode

fix: select option style in light mode

---

packages/addons/src/browser/toolbar-customize/toolbar-customize.tsx

show toolbar button id in Toolbar Customize

chore: show toolbar button id

---

packages/electron-basic/src/browser/header/header.tsx
packages/main-layout/src/browser/main-layout.contribution.ts

- 默认在标题栏不加应用名
- 支持自定义标题栏组件，比如自己添加 commander 组件到 headerbar
> 红绿灯位置已经在 #1584  修复
支持自定义 electron 的 header 组件

feat: custom electron headerbar title compoment

---

packages/core-browser/src/components/layout/box-panel.tsx

原来我们将 Top Slot 的 zIndex 设置的比较高以便于我们顶部的 popOver 可以展示出来。
所以 #1676 这个修复在支付宝小程序 IDE 上还是没生效，我们现在可以动态调整 zIndex，但是 BoxPanel 并没有生成这些 SlotRenderer 的 className，导致我们取不到这个 DOM
BoxPanel generate child with className

feat: box panel generate child with className

---

packages/utils/package.json

fix: ide-utils miss package mri

---

packages/extension/__tests__/hosted/api/vscode/ext.host.quickopen.test.ts
packages/extension/src/common/vscode/ext-types.ts
packages/extension/src/hosted/api/vscode/ext.host.quickopen.ts
packages/types/vscode/typings/vscode.quickpick.d.ts

```
const items = [
{
label: 'APIs',
kind: vscode.QuickPickItemKind.Separator
},
{
label: 'showQuickPick',
},
{
label: 'showInputBox',
},
{
label: 'createQuickPick',
},
{
label: 'createInputBox',
},
{
label: 'Types',
kind: vscode.QuickPickItemKind.Separator
},
{
label: 'QuickPickItemKind',
},
{
label: 'QuickInputButton',
},
{
label: 'QuickQuick',
},
{
label: 'InputBox',
},
];
const result = await vscode.window.showQuickPick(items);
vscode.window.showInformationMessage(`You selected: ${result?.label ?? 'nothing'}`);
```
implement quickpick kind api

feat: implement quickpick kind api

---

packages/startup/entry/web/app.tsx
packages/startup/entry/web/server.ts
tools/playwright/configs/playwright.ci.config.ts
tools/playwright/configs/playwright.config.ts
tools/playwright/src/editor.ts
tools/playwright/src/explorer-view.ts
tools/playwright/src/menu-item.ts
tools/playwright/src/panel.ts
tools/playwright/src/quick-command-palette.ts
tools/playwright/src/quick-open-palette.ts
tools/playwright/src/search-view.ts
tools/playwright/src/terminal.ts
tools/playwright/src/tests/editor.test.ts
tools/playwright/src/tests/explorer-view.test.ts
tools/playwright/src/tests/search-view.test.ts
tools/playwright/src/workspace.ts

提升原有测试的稳定性，增加在终端创建文件后，文件树实时同步的测试案例
improve e2e test stability and  add terminal test case

test: improve e2e test stability and  add terminal test case

---

packages/editor/package.json
packages/editor/src/browser/monaco-contrib/tokenizer/textmate-tokenizer.ts
packages/editor/src/browser/monaco-contrib/tokenizer/textmate.service.ts
packages/monaco/src/browser/contrib/tokenizer.ts
packages/monaco/src/common/index.ts
packages/utils/src/arrays.ts

Fixed #1746
- 更新语法注册逻辑，解决新版本编辑器无法正确匹配括号的问题

refactor: 更新语法注册逻辑，解决新版本编辑器无法正确匹配括号的问题

---

packages/editor/__tests__/browser/editor.contribution.test.ts
packages/editor/src/browser/editor.contribution.ts
tools/dev-tool/src/mock-injector.ts

fix: editor copy path command

---

packages/editor/src/browser/fs-resource/fs-resource.ts
packages/editor/src/browser/resource.service.ts
packages/file-scheme/__tests__/browser/resource.test.ts

closed #1708.
limit editor tab subname length

fix: limit editor tab subname length

---

packages/components/src/button/style.less
packages/theme/src/common/color-tokens/custom/button.ts

在 Button 的设计规范中， Secondary Button 应该与 Primary Button 保持一致的无 Border 样式
before:
after:
remove useless sencondaryButtonBorder style

style: improve secondaryButton style

---

packages/remote-cli/package.json

`packages/remote-cli` 这个包是 private 的，然后无法被 lerna 更新到 2.20.3，所以在 core 里 run init 会报错
fix build

build: fix build

---

packages/debug/src/browser/editor/debug-editor-contribution.ts

fix: debug terminated editor hover invalid

---

packages/file-tree-next/src/browser/dialog/file-dialog.view.tsx

before:
after:
improve file dialog tree style

style: improve file dialog tree style

---

packages/core-browser/src/browser-module.ts
packages/editor/src/browser/index.ts
packages/menu-bar/src/browser/index.ts
packages/status-bar/src/browser/index.ts
tools/dev-tool/src/injector-helper.ts
tools/template/src/browser/index.ts

chore: remove useless component declaration

---

packages/editor/src/browser/editor.module.less
packages/editor/src/browser/tab.view.tsx

通过将拖拽作用范围扩大来支持 Editor Tab 在 Tabbar 上的拖拽能力
https://user-images.githubusercontent.com/9823838/190940715-8f2b1781-8d85-498e-b6f3-14c2e3ad61d9.mp4
- support move editor tabs over the tabbar

feat: support move editor tabs over the tabbar

---

packages/core-common/src/electron.ts
packages/core-common/src/types/extension.ts
packages/core-electron-main/src/bootstrap/services/ui.ts
packages/core-electron-main/src/bootstrap/window.ts
packages/editor/src/browser/editor.contribution.ts
packages/editor/src/browser/resource.service.ts
packages/editor/src/browser/workbench-editor.service.ts
packages/editor/src/common/resource.ts

MacOS 可以设置 document edit 的状态，见左上角的红绿灯。
support macos native dirty indicator

feat: support macos native dirty indicator

---

packages/components/src/recycle-tree/RecycleTree.tsx
packages/components/src/recycle-tree/decorators/Filter/index.tsx
packages/file-tree-next/src/browser/file-tree-contribution.ts
packages/file-tree-next/src/browser/file-tree.tsx

close #842.
close #1320.
support more menus on filetree filter mode

feat: support more menus on filetree filter mode

---

.github/workflows/e2e.yml
tools/playwright/.gitignore
tools/playwright/configs/playwright.ci.config.ts
tools/playwright/src/tests/app.test.ts

chore: broken actions while catching failure

---

packages/editor/src/browser/editor.contribution.ts
packages/editor/src/browser/workbench-editor.service.ts
packages/editor/src/common/editor.ts

https://user-images.githubusercontent.com/17701805/196366685-82272948-912d-4b96-ba12-2b50520038bb.mp4
-  编辑器向右拆分后不滚动到屏幕中间

fix: 编辑器向右拆分后不滚动到屏幕中间

---

packages/core-common/src/types/editor.ts
packages/editor/src/browser/doc-model/editor-document-model.ts
packages/editor/src/browser/doc-model/save-task.ts
packages/editor/src/browser/fs-resource/fs-editor-doc.ts
packages/editor/src/browser/untitled-resource.ts
packages/file-scheme/src/node/file-scheme-doc.service.ts

快速触发多次保存后会有概率提示`文件保存失败，原因：cancel ` 
- 文件保存取消后不抛出错误

fix: 文件保存取消后不抛出错误

---

packages/terminal-next/src/browser/terminal.client.ts

Fix: 某些奇怪的情况下 用户会无意中把这个字段设置成字符串  导致终端crash
用户反馈终端不可用，排查发现是 localEchoExcludePrograms.map 不可用导致的。然后发现设置中此项变成了字符串，因此需要做个防御。
- add localEcho exclude program config type defense

fix: localEcho exclude program config type defense

---

packages/electron-basic/src/browser/header/header.module.less

现在我们对 menubar 设置颜色的 css 变量是错的：
而且造成了错误的样式生效，
应该使用 --kt-menubar-background
unified menubar background color

fix: unified menubar background color

---

packages/core-browser/src/react-providers/config-provider.tsx
packages/core-common/src/types/extension.ts
packages/extension/src/browser/extension-view.service.ts
packages/extension/src/browser/shadowRoot.tsx
packages/startup/entry/sample-modules/status-bar.contribution.ts

新增 extensionBrowserStyleSheet Config，支持配置插件 browser 层的样式表文件

feat: intranet resource config

---

tools/playwright/src/editor.ts
tools/playwright/src/menubar.ts
tools/playwright/src/tests/editor.test.ts
tools/playwright/src/tests/explorer-view.test.ts

E2E 测试过程中不能对 Dom 快照进行缓存，否则一旦页面更新，该快照即刻便会失效

chore: fix unstalable e2e test case

---

packages/workspace/src/browser/workspace-service.ts

把工作空间连接过程中对workspace uri的watch优化成异步操作。
进而优化工作空间连接速度。
通过对工作空间连接过程的耗时分析与打点，发现在Storage初始化过程中会依赖workspace-service.ready，而workspace.ready需要等待watch完成。
watch的耗时大部分情况下需要300ms左右，但是在容器不稳定的情况下可能需要4s甚至更多，而且watch本身不应该阻塞工作空间的启动，因此做了异步处理。会优化极端情况下的工作空间连接速度。
附件：某些极端情况下的watch耗时
- improve workspaceService initialize speed

feat: improve workspaceService initialize speed

---

packages/terminal-next/package.json

Xterm Version Bump
升级Xterm版本。
在Xterm 5.0.0 beta18种发现了一个bug，导致cursorStyle不管设置什么都会触发一个异常，即使这个配置是正确的。
恰好Xterm 5.0.0 release，对终端的依赖做一次整体的升级。
- chore: xterm version bump

chore: xterm version bump

---

packages/core-browser/src/core-preferences.ts
packages/editor/src/browser/preference/schema.ts
packages/i18n/src/common/en-US.lang.ts
packages/preferences/src/browser/preference-contribution.ts
packages/preferences/src/browser/preferenceItem.view.tsx
packages/search/src/browser/search-preferences.ts
packages/task/src/common/index.ts

- 修复部分设置项需要转为 markdown 展示，如果是用 localize 会提前让英文见面也展示为中文
- 修正文字错误
fix: 修复设置项不能展示 markdown

fix: the preference markdown display with placeholder

---

packages/core-browser/src/layout/layout.ts
packages/explorer/src/browser/explorer-contribution.ts
tools/playwright/src/app.ts
tools/playwright/src/component-editor.ts
tools/playwright/src/editor.ts
tools/playwright/src/menu-item.ts
tools/playwright/src/tests/keymaps.test.ts
tools/playwright/src/text-editor.ts
tools/playwright/src/utils/index.ts
tools/playwright/src/utils/key.ts

test: add keymaps e2e test

---

tools/playwright/src/tests/scm.test.ts
tools/playwright/src/tree-node.ts

打开一个 Git 项目，文件树根据文件 Git 状态显示对应的装饰逻辑，如：初始化 Git 项目后，文件末尾有个 "U" 字符

test: get correct git decoration on filetree

---

packages/components/src/button/style.less
packages/components/src/input/input.less
packages/core-common/src/const/application.ts
packages/extension-manager/src/browser/extension-overview/index.tsx
packages/extension-manager/src/browser/extension-overview/overview.module.less
packages/extension-manager/src/browser/vsx-extension.service.ts
packages/extension-manager/src/browser/vsx-extension.view.tsx
packages/extension-manager/src/common/index.ts
packages/extension/src/browser/extension-instance-management.ts
packages/extension/src/browser/types.ts
packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts

close #1845.
https://user-images.githubusercontent.com/9823838/197994532-d794b417-5981-4658-9a80-70c578930e32.mp4
improve extension installing UX and support unstall

fix: improve extension installing UX and support unstall

---

packages/debug/src/browser/debug-session-manager.ts
packages/debug/src/browser/debug-session.ts
packages/debug/src/browser/index.ts
packages/debug/src/browser/view/frames/debug-call-stack-thread.view.tsx

close #1849.
fix debug statck frame not update on the first stoped

fix: debug statck frame not update on the first stoped

---

packages/debug/src/browser/debug-session-manager.ts
packages/debug/src/browser/debug-session.ts

revert some code change by #1859.

fix: some event should not be dispose while switch session

---

packages/core-browser/src/layout/constants.ts
packages/electron-basic/src/browser/header/header.tsx

修复 Electron 版本在 Big Sur 之前的版本高度不正确
修复 Electron 版本的 Header Bar 异常

fix: electron header height incorrect

---

packages/editor/src/browser/workbench-editor.service.ts

- refactor: parallel open resource

refactor: parallel open resource

---

packages/file-service/src/node/file-service-watcher.ts

设置未传入 exclude 参数时，ParcelWatcher 的默认监听行为，减少首次监听带来的性能问题
add default watcher exclude

fix: add default watcher exclude

---

packages/main-layout/src/browser/quick-open-view.ts

原来的写法会导致无法搜索 `view` 开头的文件内容，如 `view.ts`

chore: update view quick open prefix

---

packages/file-tree-next/src/browser/file-tree-contribution.ts

chore: change filetree context menu order

---

packages/core-browser/src/components/actions/index.tsx

对于没有 command 命令的 submenu，以及没有往 submenu 上贡献菜单项的菜单都应该隐藏起来
修复总是显示 editor/title/run 的菜单项问题

fix: submenus show/hide rule

---

packages/components/src/recycle-tree/basic/index.tsx
packages/components/src/recycle-tree/tree/Tree.ts
packages/components/src/recycle-tree/tree/model/TreeModel.ts
packages/debug/__tests__/browser/editor/debug-hover-model.test.ts
packages/debug/__tests__/browser/editor/debug-hover-tree.model.service.test.ts
packages/debug/__tests__/browser/view/console/debug-console-tree.model.service.test.ts
packages/debug/__tests__/browser/view/variables/debug-variables-tree.model.service.test.ts
packages/debug/__tests__/browser/view/watch/debug-watch-tree.model.service.test.ts
packages/debug/src/browser/editor/debug-hover.view.tsx
packages/debug/src/browser/view/console/debug-console.view.tsx
packages/debug/src/browser/view/variables/debug-variables-tree.model.service.ts
packages/debug/src/browser/view/watch/debug-watch.view.tsx
packages/file-tree-next/__tests__/browser/dialog/file-dialog-model.service.test.ts
packages/file-tree-next/__tests__/browser/file-tree-model.service.test.ts
packages/file-tree-next/__tests__/browser/file-tree.test.ts
packages/file-tree-next/src/browser/dialog/file-dialog.view.tsx
packages/file-tree-next/src/browser/file-tree.tsx
packages/opened-editor/__tests__/browser/opened-editor-model.service.test.ts
packages/opened-editor/__tests__/browser/opened-editor.service.test.ts
packages/opened-editor/src/browser/opened-editor.tsx
packages/outline/__tests__/browser/services/outline-model.service.test.ts
packages/outline/src/browser/services/outline-model.service.ts
packages/scm/src/browser/components/scm-resource-tree/index.tsx

refactor: 不重复初始化文件树

---

packages/core-browser/src/services/storage-service.ts
packages/keymaps/__tests__/browser/keymaps.service.test.ts
packages/keymaps/src/browser/keymaps.service.ts

refactor: 将部分耗时较高的操作延迟运行

---

packages/core-browser/src/core-preferences.ts
packages/file-service/src/node/file-service-watcher.ts

update watch exclude rule
Parcel Watcher 有一些BUG，但是Parcel Watcher本身是不支持glob的，所以只能退而求其次调整默认exclude策略，屏蔽掉node_modules目录。
- update watch exclude rule

feat: update watch exclude rule

---

packages/core-browser/src/contextkey/testing.ts
packages/extension/src/browser/vscode/api/main.thread.tests.ts
packages/extension/src/common/vscode/tests.ts
packages/extension/src/hosted/api/vscode/ext.host.api.impl.ts
packages/extension/src/hosted/api/vscode/ext.host.tests.ts
packages/testing/src/browser/icons/icons.ts
packages/testing/src/browser/test.service.ts
packages/testing/src/browser/testing.contribution.ts
packages/testing/src/common/commands.ts
packages/testing/src/common/index.ts
packages/testing/src/common/observableValue.ts
packages/types/vscode/typings/vscode.tests.d.ts

**背景:** 默认情况下 Testing 是没有提供刷新操作的，需要插件自己往 workbench.view.testing 贡献点上注册刷新按钮，但这会导致 UI 上的冲突（比如会出现俩刷新按钮）
所以在 TestController 提供了 refreshHandler 的 API 方法，一旦实现了该方法，那么就会在如图所示的地方只出现一个刷新按钮
实现 TestController.refreshHandler API

feat: implement TestController refreshHandler API

---

packages/components/src/recycle-tree/basic/types.ts
packages/extension/src/common/vscode/converter.ts
packages/extension/src/common/vscode/testing/testApi.ts
packages/testing/src/browser/components/testing.explorer.tree.tsx
packages/testing/src/browser/test-tree-view.model.ts
packages/testing/src/common/testCollection.ts
packages/types/vscode/typings/vscode.tests.d.ts

该 API 主要用于在展示树视图时排序所需要计算的字段，若为 null 则根据 label 字段排序
例如：
此时给 aaa.md 添加 'zzzzz' 的 sortText
实现 TestItem.sortText API

feat: implement test item sort text api

---

packages/monaco/src/browser/monaco-snippet-suggest-provider.ts

vscode中的snippets代码片段属性prefix支持数组，但是opensumi中不支持
调整 monaco 代码，使代码片段 prefix 属性支持数组

fix: 解决代码片段（Snippets）prefix 不支持数组的问题

---

packages/extension/src/browser/vscode/contributes/icon.ts
packages/extension/src/browser/vscode/contributes/index.ts
packages/theme/src/browser/icon.service.ts
packages/theme/src/common/theme.service.ts

feat: support icons contribution point

---

packages/theme/src/common/color-tokens/custom/button.ts

before:
fix the secondary button click background style

style: fix the secondary button click background

---

packages/components/src/recycle-tree/prompt/PromptHandle.ts

close #1896.
support dblclick when rename file

fix: support dblclick when rename file

---

CHANGELOG.md
README-zh_CN.md
README.md

增加 CHANGELOG.md 文件用于后续承载 ReleaseNotes 及 BreakingChanges 内容，同时进一步补充 README 信息

chore: update README and add CHANGELOG file

---

.github/workflows/issue-labeled.yml

chore: fix issue labeled syntax error

---

packages/file-service/package.json
tools/electron/package.json

修复旧版本 Parcel Watcher 段错误导致的 IDE 进程 Crash 问题。
Parcel Watcher 的修复PR： https://github.com/parcel-bundler/watcher/pull/103
之前的 parcel watcher 存在一个会导致 SegmentFault 的错误，这个段错误会导致IDE进程Crash。
在推进官方修复后，发了新版本，现在来集成新版本修复 IDE 的 Crash 问题。
- fix: parcel watcher version bump

fix: parcel watcher version bump

---

packages/components/src/dialog/index.tsx

keep dialog `message` field's className

fix(dialog): keep message component className

---

tools/playwright/src/tests/settings.test.ts

test: add settings view test

---

packages/components/src/scrollbars/index.tsx
packages/editor/src/browser/tab.view.tsx

修复在 2.20 版本中编辑器标签页中丢失的鼠标滚轮处理逻辑
close #1922 
support mousewheel on editor tabs

fix: support mousewheel on editor tabs

---

packages/file-service/src/browser/file-service-client.ts
packages/file-service/src/browser/watcher.ts
packages/utils/src/disposable.ts

以下为猜测：
小程序 IDE 出现过很多次退出无响应，观察日志发现：
有原生 module 在退出，然后尝试看了下代码，发现如果 watcher 不停掉的话，进程是不会退出的
现在的 watcher 逻辑并不是异步阻塞的
make watcher can be disposed

fix: make watcher can be disposed

---

packages/file-service/src/node/file-service-watcher.ts

Parcel Watcher 在 watch 的时候做了 try catch 以及自动重试，避免 watcher 抛出错误导致IDE进程崩溃。
同时对单次大于5000的批量时间做了屏蔽，避免前后端的突发过大负载。
线上偶现watch失败的问题，inotify add watch failed，需要对 watch 做 try catch 以及重试。
- feat: parcel watcher subscribe retry catch
- feat: add parcel watcher retry delay

fix: parcel watcher subscribe retry catch

---

packages/core-browser/src/core-preferences.ts
packages/file-service/src/node/disk-file-system.provider.ts
packages/file-service/src/node/file-service-watcher.ts

在使用 @parcel/wathcer 后，原有的 glob 表达式 `**/node_modules/*/**` 在转换为 ignore path 时存在转换失效问题，该 PR 针对该入参做了转化处理（集成侧不需要改动也可正常运行）
update unsupported watch exclude glob

fix: update unsupported watch exclude glob

---

packages/comments/src/browser/comments.service.ts
packages/editor/src/browser/workbench-editor.service.ts
packages/search/src/browser/search-tree.service.ts

已经删除的文件，出现在全局搜索的结果中，有两个问题导致：
1. 使用双击打开结果列表，其中第一次点击的引用留在 reference 中，导致 dispose 的执行不够彻底
2. 对于代码逻辑中，尝试打开已经删除的文件路径，要判断一下结果中是否标记为已删除，不然会导致一些逻辑无法清理干净
fix: make the search references clean up

fix: make the search references clean up

---

.github/workflows/e2e.yml
packages/debug/src/browser/view/console/debug-console.module.less
packages/debug/src/browser/view/console/debug-console.view.tsx
packages/debug/src/browser/view/variables/debug-variables.module.less
packages/debug/src/browser/view/variables/debug-variables.view.tsx
packages/debug/src/browser/view/watch/debug-watch.module.less
packages/debug/src/browser/view/watch/debug-watch.view.tsx
packages/extension/src/browser/vscode/contributes/views-welcome.ts
packages/opened-editor/src/browser/opened-editor-node.module.less
packages/opened-editor/src/browser/opened-editor-node.tsx
packages/outline/src/browser/outline-node.module.less
packages/outline/src/browser/outline-node.tsx
packages/scm/src/browser/components/scm-resource-tree/scm-tree-node.module.less
packages/scm/src/browser/components/scm-resource-tree/scm-tree-node.view.tsx
packages/scm/src/browser/scm-view-container.tsx
packages/scm/src/common/index.ts
tools/playwright/src/debug-view.ts
tools/playwright/src/diff-editor.ts
tools/playwright/src/editor.ts
tools/playwright/src/explorer-view.ts
tools/playwright/src/filetree-view.ts
tools/playwright/src/opened-editor-view.ts
tools/playwright/src/panel.ts
tools/playwright/src/scm-view.ts
tools/playwright/src/search-view.ts
tools/playwright/src/source-control-view.ts
tools/playwright/src/tests/scm.test.ts
tools/playwright/src/text-editor.ts
tools/playwright/src/tree-node.ts

test: add SCM e2e test

---

packages/search/__tests__/browser/replace.test.ts
packages/search/src/browser/replace.ts
packages/search/src/browser/search-tree.service.ts
packages/search/src/browser/search.service.ts

fix: 批量替换时已打开的文件未自动保存

---

.github/workflows/deploy.yml
package.json
packages/components/src/icon/iconfont/iconfont.html
packages/components/src/icon/iconfont/index.html

升级构建依赖 `offline-iconfont`, 感谢  @vagusX 支持 https://github.com/vagusX/offline-iconfont/pull/3.
自动化 Iconfont Page 部署及构建逻辑 
增加 index.html 重定向文件，保障原有访问路径可用

chore: update iconfont page resources

---

packages/monaco/src/browser/monaco-snippet-suggest-provider.ts

fix: monaco-editor snippets support prefix array

---

packages/components/src/notification/notification.less

close #1959
After:
improve notification markdown style

style: improve notification markdown style

---

packages/debug/src/browser/view/configuration/debug-configuration.module.less
packages/debug/src/browser/view/configuration/debug-configuration.view.tsx
packages/debug/src/browser/view/configuration/debug-toolbar.view.tsx

close #1964
improve debug toolbar z-index style

style: improve debug toolbar z-index style

---

packages/debug/src/browser/debug-contribution.ts

close #1966 
active debug view once when parent session is not changed

fix: active debug view once when parent session is not changed

---

packages/debug/src/browser/debug-style.less

表达式及 Log 断点在聚焦时均需要有断点样式来展示断点是否生效信息，如下所示：
之前：
conditional and log points should have a focused style

style: conditional and log points should have a focused style

---

packages/core-browser/package.json
packages/extension/src/browser/vscode/api/main.thread.language.ts
packages/extension/src/common/vscode/model.api.ts
packages/startup/entry/web-lite/lite-module/language-service/simple.service.ts

编译后有不同版本的 vscode-jsonrpc 存在。由于 vscode-languageserver-protocol 模块引入了另外一个 vscode-jsonrpc 包导致的多个同类的包。
现在用 `isDocumentFilter` 替代这个方法，优化编译后的包体积，减少大概 97KB，减少 0.9% 的体积。
  | bundle.js size (production)
-- | --
before | 10804079
after | 10706805
> 使用 tools/electron 来进行的编译
refactor: remove package vscode-languageserver-protocol

refactor: remove package vscode-languageserver-protocol

---

packages/terminal-next/src/browser/contribution/terminal.lifecycle.ts
packages/terminal-next/src/browser/terminal.controller.ts
packages/terminal-next/src/common/controller.ts

- dispose all task executor when exit IDE

fix: dispose all task executor when exit or refresh

---

packages/core-browser/src/components/tree/tree.module.less
packages/core-browser/src/preferences/preference-configurations.ts
packages/core-browser/src/react-providers/config-provider.tsx
packages/core-common/src/preferences/preference-scope.ts
packages/debug/src/browser/index.ts
packages/debug/src/browser/preferences/launch-folder-preference-provider.ts
packages/debug/src/browser/view/console/debug-console.module.less
packages/debug/src/browser/view/variables/debug-variables.module.less
packages/debug/src/browser/view/watch/debug-watch.module.less
packages/extension/src/browser/vscode/api/tree-view/tree-view-node.module.less
packages/file-tree-next/src/browser/file-tree-node.module.less
packages/opened-editor/src/browser/opened-editor-node.module.less
packages/outline/src/browser/outline-node.module.less
packages/preferences/src/browser/abstract-resource-preference-provider.ts
packages/preferences/src/browser/folder-file-preference-provider.ts
packages/preferences/src/browser/folders-preferences-provider.ts
packages/preferences/src/browser/index.ts
packages/scm/src/browser/dirty-diff/dirty-diff.module.less
packages/startup/entry/web-lite/lite-module/extension/utils.ts
packages/startup/entry/web-lite/render-app.tsx
packages/startup/entry/web/app.tsx
packages/task/src/browser/index.ts
packages/task/src/browser/task-preferences.provider.ts

close #1972 
support useVSCodeWorkspaceConfiguration config

feat: support useVSCodeWorkspaceConfiguration config

---

packages/monaco/src/browser/contrib/merge-editor/merge-editor.service.ts
packages/monaco/src/browser/contrib/merge-editor/model/decorations.ts
packages/monaco/src/browser/contrib/merge-editor/model/sticky-piece.ts
packages/monaco/src/browser/contrib/merge-editor/types.ts
packages/monaco/src/browser/contrib/merge-editor/view/editors/baseCodeEditor.ts
packages/monaco/src/browser/contrib/merge-editor/view/editors/currentCodeEditor.tsx
packages/monaco/src/browser/contrib/merge-editor/view/editors/incomingCodeEditor.tsx
packages/monaco/src/browser/contrib/merge-editor/view/editors/resultCodeEditor.tsx
packages/monaco/src/browser/contrib/merge-editor/view/grid.tsx
packages/monaco/src/browser/contrib/merge-editor/view/guideline-widget.ts
packages/monaco/src/browser/contrib/merge-editor/view/merge-editor.less
packages/monaco/src/browser/contrib/merge-editor/view/scroll-synchronizer.ts
packages/monaco/src/browser/contrib/merge-editor/view/stickiness-connect-manager.tsx

**基本实现**
通过左右 editor 内绘制的相邻的 decoration 位置，计算出高度和绝对定位 top 值，再利用 SVG 标签以及 [path](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/path) 标签来绘制路径区域
定义的基本模型为
```
width: // 默认是 monaco editor layout info 的 contentLeft
path: { // svg 标签要绘制的 path 路径上下左右 4 个端点
leftTop
rightTop
leftBottom
rightBottom
}
height: // path 路径最大的 bottom 点和最小的 top 点的差值
position: // 绝对定位 top 值（也就是 path 路径最小的 top 点）
```
计算方式见代码 `generatePiece` 函数
**滚动计算**
当 3 个视图都上下滚动时，由于代码行数的差异会存在左右滚动位置不同步的情况，此时 decoration 的位置也会上下变化
此时只需要根据滚动的 scrollTop 值来重新计算 position、height 和 path 路径即可
其中新的 position 和 height 计算方式与一开始的计算方式一样，只需要引入一个变量 scrollTop 即可
而 path 路径的重新绘制比较麻烦些，因为这会影响 path 路径的 4 个端点坐标
例: 当右侧 editor 的滚动区域大于左侧 editor 的滚动区域时
原 4个坐标
通过计算转换成新的 4个坐标
计算方式见代码 sticky-piece 模型的 movePosition 函数
**最终效果** …

feat: implement stickiness connect effect

---

packages/components/src/icon/icon.tsx
packages/components/src/icon/styles.less
packages/core-browser/src/components/actions/index.tsx
packages/core-browser/src/utils/label.tsx
packages/extension/src/browser/extension-management.service.ts

close #1983.
同时支持了动态图标表达式：
support more ActionButton icon expression

feat: support more ActionButton icon expression

---

packages/monaco/src/browser/contrib/merge-editor/model/decorations.ts
packages/monaco/src/browser/contrib/merge-editor/view/editors/baseCodeEditor.ts
packages/monaco/src/browser/contrib/merge-editor/view/editors/currentCodeEditor.tsx
packages/monaco/src/browser/contrib/merge-editor/view/editors/incomingCodeEditor.tsx
packages/monaco/src/browser/contrib/merge-editor/view/editors/resultCodeEditor.tsx

在后续的 accept current change 等操作中，需要将左侧的 margin 区域和中间的 margin 区域放在一起，这样交互上会更友好一些
交换 3-way 视图中 ours editor 的 margin 和 code 编辑区域的位置

feat: switch margin and code editor widget content

---

packages/core-browser/src/menu/next/menu.contrib.interface.ts
packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts
packages/monaco/__mocks__/monaco/editor/code-editor.ts
packages/scm/__tests__/browser/dirty-diff/dirty-diff-decorator.test.ts
packages/scm/__tests__/browser/dirty-diff/dirty-diff-model.test.ts
packages/scm/__tests__/browser/dirty-diff/dirty-diff-widget.test.ts
packages/scm/__tests__/browser/dirty-diff/index.test.ts
packages/scm/src/browser/dirty-diff/dirty-diff-decorator.ts
packages/scm/src/browser/dirty-diff/dirty-diff-model.ts
packages/scm/src/browser/dirty-diff/dirty-diff-util.ts
packages/scm/src/browser/dirty-diff/dirty-diff-widget.ts
packages/scm/src/browser/dirty-diff/dirty-diff.module.less
packages/scm/src/browser/dirty-diff/index.ts
packages/scm/src/browser/scm-color.ts
packages/scm/src/browser/scm.contribution.ts
packages/scm/src/common/dirty-diff.ts
packages/workspace-edit/src/browser/workspace-edit.service.ts

before
1. diff gutter 位置错误 
2. 无法区分 changetype，所有改动都识别为 modified
3. dirtyWidget 样式丑
after
1. 优化 diff guter 渲染的定位和样式，区分 add、delete、modified 三种状态
2. 优化 dirtyWidget ，根据当前 changeType 展示不同边框颜色，优化默认 icon (使用 vscode-codicon)
3. 添加关闭 dirtyDiff widget 快捷键 `esc`
https://user-images.githubusercontent.com/17701805/202342527-499494f8-2bf3-40ed-8c5b-8f6d0aa9b3b6.mp4
- 优化 diff guter 渲染的定位和样式，区分 add、delete、modified 三种状态
- 化 dirtyWidget 样式，根据当前 changeType 展示不同边框颜色
- 默认 icon (使用 vscode-codicon)
- 添加关闭 dirtyDiff widget 快捷键 `esc`
- 修复 `revertChange` 失败的问题

feat: improve dirty diff

---

packages/monaco/src/browser/contrib/merge-editor/merge-editor.service.ts
packages/monaco/src/browser/contrib/merge-editor/model/conflict-actions.ts
packages/monaco/src/browser/contrib/merge-editor/model/decorations.ts
packages/monaco/src/browser/contrib/merge-editor/model/line-range.ts
packages/monaco/src/browser/contrib/merge-editor/model/sticky-piece.ts
packages/monaco/src/browser/contrib/merge-editor/types.ts
packages/monaco/src/browser/contrib/merge-editor/view/actions-manager.ts
packages/monaco/src/browser/contrib/merge-editor/view/editors/baseCodeEditor.ts
packages/monaco/src/browser/contrib/merge-editor/view/editors/currentCodeEditor.tsx
packages/monaco/src/browser/contrib/merge-editor/view/editors/incomingCodeEditor.tsx
packages/monaco/src/browser/contrib/merge-editor/view/editors/resultCodeEditor.tsx
packages/monaco/src/browser/contrib/merge-editor/view/merge-editor.less
packages/monaco/src/browser/contrib/merge-editor/view/stickiness-connect-manager.tsx

同时调整了 3 个编辑器的 margin 区域的边距，使其容纳得下图标
渲染 3-way 视图下的 conflict actions 操作

feat: render conflict actions

---

packages/core-browser/src/services/storage-service.ts
packages/storage/__tests__/browser/storage.service.test.ts
packages/storage/src/browser/storage.contribution.ts
packages/terminal-next/src/browser/terminal.restore.ts

优化 ScopedStorage 冷启动速度，不再依赖 `workspaceService.whenReady` 逻辑，框架内启动速度提升约 50%
Before:
After:
同时修改 Terminal 恢复逻辑，采用 `ScopedBrowserStorageService` 进行浏览器存储管理。
局部浏览器缓存路径从 `scoped:file:///...:/recent` 修改为 `scoped:/....:/recent` 移除了多余的 `file://`，该修改会导致用户首次加载新版本时进入冷启动逻辑（字段改动导致之前的缓存失效），影响不大。
optimize scoped storage bootstrap speed

refactor: optimize scoped storage bootstrap speed

---

packages/editor/src/browser/editor.decoration.service.ts
packages/extension/src/browser/vscode/api/main.thread.treeview.ts
packages/extension/src/hosted/api/vscode/ext.host.treeview.ts
packages/theme/src/browser/icon.service.ts
packages/theme/src/common/theme.service.ts

Bookmarks 插件在升级到 13.0+ 版本后，采用了 base64 图标，原有不支持导致新版本插件显示异常
支持前：
支持后：
support base64 icon on editor glyphMargin and treeview

feat: support base64 icon on editor glyphMargin and treeview

---

packages/monaco/src/browser/monaco.resolved-keybinding.ts

fix(monaco): unexpected keyboard event mapped to a chord

---

packages/core-browser/__tests__/keyboard/keyboard-layout-service.test.ts
packages/core-browser/src/keyboard/keys.ts

在注册 electron 快捷键时，使用了非 ASCII 字符，导致 electron 启动报错，如下：
```bash
[54244:1123/165632.053824:ERROR:accelerator_util.cc(24)] The accelerator string can only contain ASCII characters
[54244:1123/165632.053864:ERROR:accelerator_util.cc(24)] The accelerator string can only contain ASCII characters
[54244:1123/165632.053962:ERROR:accelerator_util.cc(24)] The accelerator string can only contain ASCII characters
[54244:1123/165632.053988:ERROR:accelerator_util.cc(24)] The accelerator string can only contain ASCII characters
[54244:1123/165632.054029:ERROR:accelerator_util.cc(24)] The accelerator string can only contain ASCII characters
[54244:1123/165632.054062:ERROR:accelerator_util.cc(24)] The accelerator string can only contain ASCII characters
``` 
对应的 electron 源码在: …

fix(core-browser): accelerator string can only contain ASCII characters

---

packages/editor/src/browser/doc-model/saveParticipants.ts
packages/extension/__tests__/browser/main.language.test.ts
packages/extension/src/browser/vscode/api/main.thread.language.ts
packages/extension/src/common/vscode/ext-types.ts
packages/extension/src/common/vscode/languages.ts
packages/extension/src/hosted/api/vscode/ext.host.language.ts
packages/extension/src/hosted/api/vscode/language/code-action.ts
packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts

close #2022 
support onSaveCodeActions with ESLint extension

fix: support onSaveCodeActions with ESLint extension

---

packages/core-node/src/bootstrap/shell-path.ts

-  use bash resolve shell path by default

fix: use bash resolve shellpath

---

packages/debug/src/browser/debug-session.ts

fix: pause debug will not open stackframe source file

---

packages/debug/src/browser/view/frames/debug-call-stack-session.view.tsx

fix #2028 
原因为 CallStack View 处理 Threads 时没有有效处理回调函数导致的渲染问题。修复后可以正常响应断点暂停信息
focus frame while breakpoint pause by stopped

fix: focus frame while breakpoint pause by stopped

---

packages/monaco/src/browser/contrib/merge-editor/mapping-manager.service.ts
packages/monaco/src/browser/contrib/merge-editor/merge-editor.service.ts
packages/monaco/src/browser/contrib/merge-editor/model/decorations.ts
packages/monaco/src/browser/contrib/merge-editor/model/document-mapping.ts
packages/monaco/src/browser/contrib/merge-editor/model/line-range.ts
packages/monaco/src/browser/contrib/merge-editor/service/mapping-manager.service.ts
packages/monaco/src/browser/contrib/merge-editor/view/actions-manager.ts
packages/monaco/src/browser/contrib/merge-editor/view/editors/baseCodeEditor.ts
packages/monaco/src/browser/contrib/merge-editor/view/editors/resultCodeEditor.tsx
packages/monaco/src/browser/contrib/merge-editor/view/guideline-widget.ts
packages/monaco/src/browser/contrib/merge-editor/view/stickiness-connect-manager.tsx

在每次新增行或删减行时，重新计算 3 个视图中 document mapping 的对应关系，使其 diff 区域能对应上
https://user-images.githubusercontent.com/20262815/205592595-619da17b-c5f5-463e-b4ec-d630fbdd6183.mp4
支持在编辑 result 视图中的代码时动态更新 diff 区域范围

feat: implement editing result view code update range mapping

---

packages/core-browser/__tests__/services/clipboard.service.test.ts
packages/core-browser/src/services/clipboard.service.ts
packages/core-browser/src/services/storage-service.ts
packages/storage/src/browser/storage.contribution.ts
packages/terminal-next/src/browser/terminal.restore.ts

before:
remove errors from clipboard service

chore: remove errors from clipboard service

---

packages/extension-storage/src/browser/storage.ts

Windows 上调用 ExtensionContext.globalStoragePath 的地址有误：
原理可见：
又是一例 Uri.parse 和 Uri.file 的混用错误，会导致插件获取的 globalStoragePath 错误。
Fix invoke `ExtensionContext.globalStoragePath` error in Windows

fix(extension): windows get globalStorageUri error

---

packages/components/src/recycle-tree/tree/Tree.ts
packages/components/src/recycle-tree/tree/TreeNode.ts
packages/file-tree-next/src/browser/file-tree.service.ts
packages/file-tree-next/src/browser/services/file-tree-model.service.ts

进一步降低文件树刷新导致的用户输入框被阻断的问题
support cancel refresh when edit file

fix: support cancel refresh when edit file

---

packages/monaco/src/browser/contrib/merge-editor/merge-editor.service.ts
packages/monaco/src/browser/contrib/merge-editor/model/decorations.ts
packages/monaco/src/browser/contrib/merge-editor/model/document-mapping.ts
packages/monaco/src/browser/contrib/merge-editor/model/line-range.ts
packages/monaco/src/browser/contrib/merge-editor/view/editors/baseCodeEditor.ts
packages/monaco/src/browser/contrib/merge-editor/view/editors/currentCodeEditor.tsx
packages/monaco/src/browser/contrib/merge-editor/view/editors/incomingCodeEditor.tsx
packages/monaco/src/browser/contrib/merge-editor/view/editors/resultCodeEditor.tsx

before:
after:
实现彼此相连的 diff range 区域合并成一个

feat: implement contiguous region merge range

---

packages/monaco/src/browser/contrib/merge-editor/model/inner-range.ts
packages/monaco/src/browser/contrib/merge-editor/model/line-range.ts
packages/monaco/src/browser/contrib/merge-editor/types.ts
packages/monaco/src/browser/contrib/merge-editor/view/actions-manager.ts
packages/monaco/src/browser/contrib/merge-editor/view/editors/baseCodeEditor.ts
packages/monaco/src/browser/contrib/merge-editor/view/editors/resultCodeEditor.tsx
packages/utils/src/uuid.ts

允许 combination 的条件有以下几点
1. 该 diff 区域是由多个 lineRange 合并而成
2. 被合并的这些 lineRange 彼此之间仅仅只是表面接触，而没有相交关系。
e.g
`{ startLine: 1, endLine: 2 } ` 和 `{ startLine: 2, endLine: 3 }` 就是表面接触
`{ startLine: 1, endLine: 3 } ` 和 `{ startLine: 2, endLine: 4 }` 就是相交关系
这样才能保证 accept combination 之后左右两边的 diff 内容彼此不会被覆盖
实现 accept combination 操作

feat: implement accept combination conflict actions

---

packages/monaco/src/browser/contrib/merge-editor/mapping-manager.service.ts
packages/monaco/src/browser/contrib/merge-editor/merge-editor.service.ts
packages/monaco/src/browser/contrib/merge-editor/model/document-mapping.ts
packages/monaco/src/browser/contrib/merge-editor/model/line-range.ts
packages/monaco/src/browser/contrib/merge-editor/types.ts
packages/monaco/src/browser/contrib/merge-editor/utils.ts
packages/monaco/src/browser/contrib/merge-editor/view/actions-manager.ts
packages/monaco/src/browser/contrib/merge-editor/view/editors/baseCodeEditor.ts
packages/monaco/src/browser/contrib/merge-editor/view/editors/currentCodeEditor.tsx
packages/monaco/src/browser/contrib/merge-editor/view/editors/incomingCodeEditor.tsx
packages/monaco/src/browser/contrib/merge-editor/view/editors/resultCodeEditor.tsx
packages/monaco/src/browser/contrib/merge-editor/view/merge-editor.less
packages/monaco/src/browser/contrib/merge-editor/view/stickiness-connect-manager.tsx

feat: improve conflict action

---

packages/components/src/menu/style.less
packages/core-browser/src/bootstrap/inner-providers.ts
packages/editor/src/browser/menu/editor.menu.ts
packages/editor/src/browser/tab.view.tsx
packages/editor/src/browser/types.ts
packages/extension/src/browser/vscode/contributes/menu.ts

fixed #2067.
在编辑器顶部 `...` 菜单支持插件 `submenus` 注册及展示，效果如下：
Web：
Electron:
support submenus on editor/title

feat: support submenus on editor/title

---

packages/core-browser/src/monaco/merge-editor-widget.ts
packages/editor/src/browser/editor.contribution.ts
packages/editor/src/browser/merge-editor/merge-editor.provider.ts
packages/editor/src/browser/workbench-editor.service.ts
packages/editor/src/common/resource.ts
packages/extension/src/browser/extension.contribution.ts
packages/extension/src/browser/vscode/builtin-commands.ts
packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts
packages/monaco/src/browser/contrib/merge-editor/merge-editor-widget.tsx

支持从 git scm 插件打开 3-way merge editor

feat: support open from git scm

---

packages/core-browser/src/monaco/merge-editor-widget.ts
packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts
packages/monaco/package.json
packages/monaco/src/browser/contrib/merge-editor/mapping-manager.service.ts
packages/monaco/src/browser/contrib/merge-editor/merge-editor-widget.tsx
packages/monaco/src/browser/contrib/merge-editor/merge-editor.service.ts
packages/monaco/src/browser/contrib/merge-editor/model/document-mapping.ts
packages/monaco/src/browser/contrib/merge-editor/model/time-machine.ts
packages/monaco/src/browser/contrib/merge-editor/types.ts
packages/monaco/src/browser/contrib/merge-editor/view/editors/resultCodeEditor.tsx
packages/monaco/src/browser/contrib/merge-editor/view/grid.tsx
packages/monaco/src/browser/contrib/merge-editor/view/guideline-widget.ts
packages/monaco/src/browser/contrib/merge-editor/view/merge-editor.less
packages/monaco/src/browser/contrib/merge-editor/view/scroll-synchronizer.ts

https://user-images.githubusercontent.com/20262815/208357850-ab817832-a8e4-4a7b-b40b-8539ebc69f85.mp4
新增 title head 展示分支信息和 commit 以及新增 apply 按钮

feat: show title head info & implement the apply actions

---

packages/components/src/recycle-tree/tree/TreeNode.ts
packages/components/src/recycle-tree/types/tree-node.ts
packages/scm/src/browser/components/scm-provider-list.tsx
packages/scm/src/browser/components/scm-resource-tree/index.tsx
packages/scm/src/browser/components/scm-resource-tree/scm-tree-model.service.ts
packages/scm/src/browser/components/scm-resource-tree/scm-tree.service.ts

the tree node child maybe undefined

fix: the tree node child maybe undefined

---

packages/output/src/browser/output.service.ts
packages/output/src/browser/output.view.tsx

-  create output editor when panel is visible

fix: create output editor when panel visible

---

packages/editor/src/browser/doc-model/editor-document-model.ts

优化文件差量修改时Monaco编辑器的响应逻辑。
OpenSumi在查看日志文件这一类文件末尾会一直增加新文本的场景时，每次末尾文本的增加都会导致Monaco编辑器的全部刷新，进而造成整个编辑器的Log日志高亮闪烁。
因此需要在日志刷新写到编辑器之前增加一个diff逻辑，来保证这类在文件末尾不断新增的文本的日志场景能有不错的阅读体验，避免全局的编辑器闪烁。
视频演示：
Before：
https://user-images.githubusercontent.com/12879047/208387442-9d7dca15-0a64-4d75-82b9-db52d1ad68f5.mp4
After:
https://user-images.githubusercontent.com/12879047/208387759-52610f97-a197-4b6d-93e9-6fb792b15bf4.mp4
- feat: optimize editor updateContent logic

feat: optimize editor updateContent logic

---

packages/debug/src/browser/view/console/debug-console.view.tsx

- fix: create debug console editor when panel visible

fix: create debug console editor when panel visible

---

packages/keymaps/__tests__/browser/keymaps.service.test.ts
packages/keymaps/src/browser/keymaps.service.ts
packages/keymaps/src/browser/keymaps.view.tsx
packages/keymaps/src/common/keymaps.ts

- fix: update keybindings when keymap view rendered

fix: update keybindings when keymap view rendered

---

packages/comments/__test__/browser/comment-thread.test.ts
packages/comments/__test__/browser/comment.service.test.ts
packages/comments/__test__/browser/comments-feature.registry.test.ts
packages/comments/src/browser/comments-feature.registry.ts
packages/comments/src/browser/comments-panel.view.tsx
packages/comments/src/browser/comments-thread.ts
packages/comments/src/browser/comments-zone.view.tsx
packages/comments/src/browser/comments.contribution.ts
packages/comments/src/browser/comments.service.ts
packages/comments/src/browser/index.ts
packages/comments/src/browser/tree/comment-node.tsx
packages/comments/src/browser/tree/tree-model.service.ts
packages/comments/src/browser/tree/tree-node.defined.ts
packages/comments/src/browser/tree/tree-node.module.less
packages/comments/src/common/index.ts
packages/extension/__tests__/hosted/api/vscode/ext.host.statusbar.test.ts
packages/extension/src/browser/vscode/api/main.thread.comments.ts
packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts
tools/playwright/src/tests/explorer-view.test.ts

统一评论面板 Tree 组件样式，修复部分样式问题，同时移除废弃的 DeprecatedRecycleTree 组件
相关 Issue: https://github.com/opensumi/core/issues/592
Before：
After:
remove DeprecatedRecycleTree on comment module

refactor: remove DeprecatedRecycleTree on comment module

---

packages/components/src/icon/iconfont/iconfont.css
packages/components/src/popover/index.tsx
packages/core-browser/__tests__/utils/parse.test.ts
packages/core-browser/src/style/icon/icon.ts
packages/core-browser/src/style/icon/index.less
packages/core-browser/src/utils/parse.ts
packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts
packages/markers/src/browser/markers-contribution.ts
packages/status-bar/src/browser/status-bar-item.view.tsx
packages/status-bar/src/browser/status-bar.module.less

Tooltip:
限制最大数字 100：
Support show problem count in status bar

feat: support markers status

---

packages/core-browser/src/common/common.command.ts
packages/main-layout/src/browser/main-layout.contribution.ts
packages/quick-open/src/browser/quick-open.contribution.ts

fix: quick open argument

---

packages/file-service/__tests__/browser/file-service-client.test.ts

chore: fix unstable fileServiceClient unit test

---

packages/extension/src/hosted/api/vscode/ext.host.api.webview.ts
packages/extension/src/hosted/api/vscode/ext.host.window.api.impl.ts

部分插件在加载 webview 资源时会指定 style-src 属性，基于 webview 的 cspSource 计算得出，但默认没有加入当前插件的路径，导致在 electron 端会因为 csp 错误加载失败
因插件 webview 中资源都会被转换为 vscode-resource 协议，所以需要将 vscode-resource 协议下的插件路径加入到 style-src 中
- fix webview cspSrouce value

fix: webview cspSource

---

packages/editor/src/browser/monaco-contrib/tokenizer/textmate.service.ts

重复调用 setTheme 会导致编辑器重复触发 tokenize
- fix unnecessary re-tokenizer

fix: unnecessary re-tokenizer

---

packages/addons/src/browser/file-search.contribution.ts
packages/editor/src/browser/quick-open/workspace-symbol-quickopen.ts
packages/search/src/browser/tree/search-tree.service.ts
packages/workspace/__tests__/browser/workspace-service.test.ts
packages/workspace/src/browser/workspace-service.ts
packages/workspace/src/common/mocks/workspace-service.ts
packages/workspace/src/common/workspace.interface.ts

Before：
After：
improve file search path on workspace folders

feat: improve file search path on workspace folders

---

packages/i18n/src/common/en-US.lang.ts
tools/playwright/src/explorer-view.ts
tools/playwright/src/tests/explorer-view.test.ts

update opened editor group name

chore: update opened editor group name

---

packages/search/src/browser/search.replace.widget.tsx
packages/search/src/browser/search.service.ts
packages/search/src/browser/search.view.tsx

由于搜索面板的按键和输入操作都会触发重新搜索，故基本上都是会带来视图上的更新
After:
https://user-images.githubusercontent.com/9823838/209632159-37933290-db68-4827-aa34-90ee9607bd3f.mp4
partial update view

fix: partial update view

---

packages/startup/entry/sample-modules/editor-empty-component.module.less

Before:
After:
improve empty editor component style

style: improve empty editor component style

---

packages/search/src/browser/search.replace.widget.tsx
packages/search/src/browser/search.rules.widget.tsx
packages/search/src/browser/search.service.ts
packages/search/src/browser/search.view.tsx
packages/search/src/browser/tree/tree-node.module.less
tools/playwright/src/search-view.ts
tools/playwright/src/tests/search-view.test.ts

ref #2115.
fix search rules display logic

fix: search rules display logic

---

packages/file-tree-next/src/browser/file-tree-contribution.ts

该问题会导致筛选输入框无法正常编辑的问题
disable some keybindings on filetree filter mode

fix: disable some keybindings on filetree filter mode

---

packages/core-common/src/reference.ts
packages/search/src/browser/search.service.ts
packages/search/src/node/content-search.service.ts

部分插件可能存在不正确的文档打开路径，导致在 DocManager 中创建了不合理路径（如  `file:///a//b.js` ） 的 docRef，导致文档中搜索出的结果出现重复。
如 Bookmarks 插件中存在明显的字段拼接错误问题，极易复现该问题
通过对 Reference 引用 Key 的唯一化处理解决该问题
fix duplicate search results

fix: duplicate search results

---

packages/debug/src/browser/editor/debug-breakpoint.module.less

before: 
after:
修复多行表达式断点的样式问题

fix: debug condition breakpoint style

---

packages/editor/__tests__/browser/editor.collection.test.ts
packages/editor/src/browser/editor-collection.service.ts
packages/editor/src/common/editor.ts

`onDidChangeModel` 中即使没有来自 contribution 提供的 options 也会调用一次 `updateOptions`,
after
- fix: unnecessary editor update options

fix: unnecessary editor update options

---

packages/search/__tests__/browser/replace.test.ts
packages/search/src/browser/replace.ts
packages/search/src/browser/search.contribution.ts
packages/search/src/browser/search.input.widget.tsx
packages/search/src/browser/search.service.ts
packages/search/src/browser/search.view.tsx
packages/search/src/browser/tree/search-node.tsx
packages/search/src/browser/tree/search-tree.service.ts
packages/search/src/browser/tree/search-tree.view.tsx
packages/search/src/common/content-search.ts

fixed #1962.
同时修复通过编辑器选中文本进行搜索的交互问题。
support search and replace value by regexp

feat: support search and replace value by regexp

---

packages/addons/src/browser/file-search.contribution.ts
packages/core-browser/src/core-preferences.ts

默认添加的这个 `*.git*` 不仅排除 git 目录，也会排除所有包含 `.git` 的文件，实际上只需要 `*.git/` 即可
- do not exclude `.gitignore`

fix: do not exclude .gitignore

---

tools/playwright/src/debug-view.ts
tools/playwright/src/terminal.ts
tools/playwright/src/tests/debug.test.ts

新增针对 'Javascript Debug Terminal' 测试案例，同时优化调试面板测试
#1475.
add Javascript Debug Terminal test case

test: add Javascript Debug Terminal test case

---

packages/search/__tests__/browser/search.service.test.ts
packages/search/src/browser/search.input.widget.tsx
packages/search/src/browser/search.module.less
packages/search/src/browser/search.rules.widget.tsx
packages/search/src/browser/search.service.ts
packages/search/src/browser/search.view.tsx
packages/search/src/browser/tree/tree-model.service.ts
packages/search/src/common/content-search.ts
tools/playwright/src/scm-view.ts
tools/playwright/src/search-view.ts
tools/playwright/src/tests/search-view.test.ts
tools/playwright/src/tests/workspaces/search/index.js
tools/playwright/src/tests/workspaces/search/index2.js
tools/playwright/src/utils/key.ts

新增如下测试：
https://user-images.githubusercontent.com/9823838/210079329-a1f0eb04-1076-43da-966a-3567407a4159.mp4
同时移除了搜索面板状态中冗余且无效的 `isSearchFocus` 状态存储，从根源处解决 #1203 问题。
#1475.
add search e2e test case

test: add search e2e test case

---

packages/search/src/browser/search.view.tsx
packages/search/src/browser/tree/search-node.tsx
packages/search/src/browser/tree/search-tree.view.tsx

正则及普通字段搜索没有处理大小写情况的搜索高亮
highlight search content when ignore case

fix: highlight search content when ignore case

---

packages/debug/src/browser/debug-contribution.ts

register debug editor decoration type when the browser is idle

feat: register debug editor decoration type when the browser is idle

---

packages/components/src/dialog/styles.less

style: dialog message title center

---

packages/monaco/src/browser/contrib/merge-editor/model/document-mapping.ts
packages/monaco/src/browser/contrib/merge-editor/model/line-range.ts
packages/monaco/src/browser/contrib/merge-editor/view/actions-manager.ts
packages/monaco/src/browser/contrib/merge-editor/view/editors/resultCodeEditor.ts

例如: 如果 diff 区域是在编辑器的最后一行，就会出现如下情况
https://user-images.githubusercontent.com/20262815/210696384-29f02f88-c31f-420b-ba01-6c060bdd2ee6.mp4
现在调整了 applyEdits 时的 range 计算方式
https://user-images.githubusercontent.com/20262815/210696556-5bf37922-6629-4b26-83b1-667b0e17e6c6.mp4
修复合并编辑器的解决冲突操作不正确的问题

fix: merge editor conflict action error

---

packages/components/src/popover/styles.less

修复 popover 组件顶部/底部的边距
before:
after:

style: update the padding at the top/bottom of popover component

---

packages/editor/src/browser/monaco-contrib/tokenizer/textmate.service.ts
packages/editor/src/browser/preference/schema.ts
packages/extension/src/browser/vscode/api/main.thread.doc.ts
packages/extension/src/browser/vscode/api/main.thread.language.ts
packages/file-scheme/__tests__/browser/contribution.test.ts
packages/file-scheme/src/browser/file-scheme.contribution.ts

调整 OpenSumi 内可打开的最大文件大小以及语法高亮限制。
目前 `editor.languageFeatureEnabledMaxSize`  及 `editor.docExtHostSyncMaxSize` 的设计与 `editor.maxTokenizationLineLength` 存在一些重复性设计，目前调整至与 `editor.largeFile` 保持一致，后续可以考虑移除这两个配置。
update large file size limit

chore: update large file size limit

---

packages/quick-open/src/browser/quick-open.service.tsx

close: #1958
- https://github.com/opensumi/core/issues/1958
After:
trim user input in prefix quickopen

fix: prefix quick open should trim input

---

packages/comments/src/browser/tree/tree-node.module.less
packages/components/src/recycle-tree/basic/styles.less
packages/debug/src/browser/view/console/debug-console.module.less
packages/debug/src/browser/view/variables/debug-variables.module.less
packages/debug/src/browser/view/watch/debug-watch.module.less
packages/extension/src/browser/vscode/api/tree-view/tree-view-node.module.less
packages/file-tree-next/src/browser/file-tree-node.module.less
packages/markers/src/browser/markers-tree.view.tsx
packages/markers/src/browser/tree/tree-node.module.less
packages/opened-editor/src/browser/opened-editor-node.module.less
packages/opened-editor/src/browser/opened-editor.tsx
packages/outline/src/browser/outline-node.module.less
packages/outline/src/browser/services/outline-model.service.ts
packages/preferences/src/browser/preferences.module.less
packages/scm/src/browser/components/scm-resource-tree/index.tsx
packages/scm/src/browser/components/scm-resource-tree/scm-tree-model.service.ts
packages/scm/src/browser/components/scm-resource-tree/scm-tree-model.ts
packages/scm/src/browser/components/scm-resource-tree/scm-tree-node.module.less
packages/scm/src/browser/components/scm-resource-tree/scm-tree-node.view.tsx
packages/search/src/browser/tree/tree-node.module.less

移除了不同视图下的冗余样式，修复 Marker / OpenedEditor 等面板在 Light+ 主题下异常展示问题
fixed #2179 
remove some useless tree style

style: remove some useless tree style

---

packages/core-browser/src/core-preferences.ts
packages/file-service/package.json
packages/file-service/src/node/file-service-watcher.ts
tools/electron/package.json
yarn.lock

@parcel/watcher release v2.1.0 to support glob expression https://github.com/parcel-bundler/watcher/releases/tag/v2.1.0.
The `**/node_modules/**` pattern will ignore all `node_modules` events containing itself.
The `**/node_modules/*/**` doesn't work.
It's better to use `**/node_modules/**/*` instead of `**/node_modules/**` or `**/node_modules/*/**`.
upgrade @parcel/watcher to support glob expression

feat: upgrade @parcel/watcher to support glob expression

---

packages/markers/src/browser/markers-contribution.ts

do not display info icon if there is no info

feat(status-bar): do not display info icon if there is no info

---

packages/editor/src/browser/doc-model/editor-document-model.ts
tools/playwright/package.json
tools/playwright/src/editor.ts
tools/playwright/src/tests/editor/undoRedo.test.ts
tools/playwright/src/text-editor.ts
yarn.lock

close: #1906 
研究发现：
输入第二个字符按保存后，monaco editor 并没有把这个变更 push 到 editStack 中。
但是这个时候，点击一下编辑器，这个变更就被 push 到 stack 里了。
也就是说，保存的时候补偿一个 pushStack 应该就好了
add missing edit stack when save

fix(editor): add missing edit stack when save

---

packages/collaboration/__tests__/browser/textmodel-binding.test.ts
packages/collaboration/src/browser/collaboration.service.ts
packages/collaboration/src/node/y-websocket-server.ts
packages/core-browser/src/react-providers/config-provider.tsx

新增 collaborationWsPath 配置，解决上游集成方协同模块的通信问题

fix: support collaborationWsPath config

---

packages/core-browser/src/preferences/preference-service.ts

ref https://github.com/opensumi/core/pull/2176.
get valid preference value from the user scope

fix: get valid preference value from the user scope

---

packages/collaboration/src/browser/collaboration.contribution.ts
packages/collaboration/src/browser/collaboration.service.ts
packages/collaboration/src/common/types.ts

由于 initialize 的时序太靠后了（在 onDidStart 里）
导致在刷新之后，监听不到首次打开的文件发出的 EditorDocumentModelCreationEvent 事件
修复协同编辑模块的初始化时序问题

fix: collaboration initialize

---

packages/core-browser/src/preferences/preference-service.ts
packages/core-browser/src/preferences/types.ts
packages/electron-basic/__mocks__/index.ts
packages/electron-basic/src/browser/electron-preference.contribution.ts
packages/electron-basic/src/browser/header/header.service.ts
packages/electron-basic/src/browser/index.ts
packages/electron-basic/src/common/header.ts
packages/electron-basic/src/common/i18n/en-US.lang.ts
packages/electron-basic/src/common/i18n/setup.ts
packages/electron-basic/src/common/i18n/zh-CN.lang.ts

支持 setting.json 设置 window.title 标题模板，比如 `${dirty}${activeEditorShort}${separator}${rootName}` 或者`${dirty}${activeEditorShort}${separator}${appName}`
https://user-images.githubusercontent.com/2226423/211964057-4fc2330d-9cb9-4f9b-a643-d6a640217b8a.mov
支持通过 window.title 控制窗口标题

feat: support electron titlebar string template

---

packages/core-browser/__tests__/external-preference.test.ts
packages/core-browser/src/bootstrap/app.ts
packages/core-browser/src/core-preferences.ts
packages/core-browser/src/preferences/early-preferences.ts
packages/core-common/src/localize.ts
packages/editor/src/browser/preference/schema.ts
packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts
packages/preferences/src/browser/preference-settings.service.ts
packages/search/src/browser/search-preferences.ts
packages/startup/entry/web/app.tsx
packages/task/src/browser/task-executor.ts
packages/types/manifest.json

Before:
- 修复部分设置面板文案无正确国际化问题
- 移除 Web 实例中对于编辑器语言的默认设置，让启动案例可正常响应中英文语言切换效果
- 调整编辑器内的 Scheme 定义，让定义更规范，同时支持动态化展示
show correct i18n text on the settings panel

fix: show correct i18n text on the settings panel

---

packages/components/src/scrollbars/index.tsx
packages/components/src/scrollbars/styles.less
packages/components/src/virtual-list/index.tsx

修复滚动条无法拖动问题
update default scroller bar thumb size to 10

fix: update default scroller bar thumb size to 10

---

packages/core-browser/src/monaco/merge-editor-widget.ts
packages/editor/src/browser/merge-editor/merge-editor.provider.ts
packages/editor/src/browser/workbench-editor.service.ts
packages/monaco/__tests__/browser/merge-editor/merge-editor.service.test.ts
packages/monaco/src/browser/contrib/merge-editor/merge-editor-widget.tsx
packages/monaco/src/browser/contrib/merge-editor/merge-editor.service.ts
packages/monaco/src/browser/contrib/merge-editor/view/editors/baseCodeEditor.ts
packages/monaco/src/browser/contrib/merge-editor/view/editors/currentCodeEditor.ts
packages/monaco/src/browser/contrib/merge-editor/view/merge-editor.module.less

fix: merge editor state restore

---

packages/core-browser/src/keybinding/keybinding.ts
packages/editor/README.md
packages/editor/src/browser/preference/schema.ts
packages/electron-basic/package.json
packages/monaco/src/browser/monaco.contribution.ts
yarn.lock

close #2239 
在快捷键更新之后，需要通过 monaco 内的 `addDynamicKeybinding` 方法去覆盖实现，从而达到卸载对应快捷键的同时，覆盖快捷键在编辑器内的展示。
update monaco keybindings after keybinding changed

fix: update monaco keybindings after keybinding changed

---

packages/components/src/dropdown/dropdown.tsx
packages/core-browser/__tests__/external-preference.test.ts
packages/core-browser/src/bootstrap/app.ts
packages/core-browser/src/core-preferences.ts
packages/core-common/src/const/index.ts
packages/core-common/src/const/locale-types.ts
packages/debug/src/browser/view/console/debug-console.contribution.ts
packages/extension/src/browser/extension.ts
packages/file-service/__tests__/node/file-service-watcher.test.ts
packages/i18n/__tests__/dataValidity.test.ts
packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/types.ts
packages/i18n/src/common/zh-CN.lang.ts
packages/monaco/src/browser/monaco.contribution.ts
packages/monaco/src/browser/monaco.resolved-keybinding.ts
packages/startup/entry/sample-modules/editor-empty-component.contribution.tsx
packages/startup/entry/web-lite/app.tsx
packages/startup/entry/web/app.tsx
tools/dev-tool/src/injector-helper.ts
tools/dev-tool/src/mock-injector.ts

原有 KeybindingRegistry 实例存在问题，同时修改卸载 Monaco 默认快捷键的逻辑
unregister default monaco keybindings

fix: unregister default monaco keybindings

---

packages/electron-basic/src/browser/header/header.service.ts

close #2225
标题栏的名称在文件删除后，新建同名文件删除标记不会更新。
修复标题栏的文件删除标记不会更新

fix: title bar delete flag not update

---

packages/electron-basic/src/browser/header/header.module.less
packages/electron-basic/src/browser/header/header.view.tsx

修复 Windows 环境 Header Bar 高度异常
正常场景
修复 Windows 环境 Header Bar 高度异常

fix: electron header bar default height

---

packages/editor/src/browser/workbench-editor.service.ts

fix: editor tag loading state

---

packages/collaboration/src/browser/collaboration.contribution.ts
packages/collaboration/src/browser/collaboration.service.ts
packages/collaboration/src/common/types.ts

https://github.com/opensumi/core/issues/2238
问题原因是在打开文件时，协同模块会根据 yTextMap 内容更新文档，文件窗口关闭后通过其他方式直接修改文件后，yTextMap 内容未更新，导致打开文件时，依然是上次关闭的内容

fix: reset yTextMap when file updated by system

---

scripts/download.js

before：
插件市场没有对应的插件，并没有正确的错误提示
after：
当下载插件失败时候将错误抛出

chore: show extension download error

---

packages/menu-bar/src/browser/menu-bar.view.tsx

Issue: https://github.com/opensumi/core/issues/1814
feat: menubar component will reset focus after click

feat: menubar component will reset focus after click

---

packages/quick-open/src/browser/components/highlight-label/index.tsx
packages/quick-open/src/browser/quick-open.view.tsx
packages/quick-open/src/browser/styles.module.less

before:
after:
多 item label 节点
带 icon 图标时
带 icon 图标且搜索结果在 description 时
搜索 detail 内容时
修复 quick open 搜索高亮时的空格消失问题

fix: quick open hightlight label whitespace

---

packages/editor/src/browser/doc-model/saveParticipants.ts
packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts
packages/preferences/src/browser/preference-settings.service.ts

https://github.com/opensumi/core/issues/2218
fix: 修复 Files > Trim Final Newlines 不生效问题

fix: support Trim Final NewLines configuration

---

packages/terminal-next/src/browser/terminal.view.ts

修复终端无法重命名的问题
- #1707 
- Fix terminal rename bug #1707

fix: terminal rename fix

---

packages/comments/src/browser/comments.service.ts
packages/comments/src/browser/tree/comment-node.tsx
packages/comments/src/browser/tree/tree-model.service.ts
packages/comments/src/browser/tree/tree-node.defined.ts
packages/comments/src/common/index.ts

1. 将 resolveChildren 里对每个 tree 节点的处理抽离成独立函数，方便上游 override
2. CommentContentNode 增加 isAllowToggle 字段，用于判断是否允许 expand 的行为
支持上游集成方控制评论模块的树组件渲染行为

feat: support upstream control tree node render behavior

---

packages/main-layout/src/browser/tabbar/bar.view.tsx

fix: scm badge is too large to display the problem

---

packages/quick-open/src/browser/styles.module.less

fixed #1742
修复 QuickPick 面板 Input上下无间距的问题

fix:  add margins to the QuickOpen input

---

packages/editor/src/browser/editor-collection.service.ts

monaco diff editor 的只读逻辑是根据 modified model 的 readonly 字段决定的，原先这里的逻辑并没有覆盖到
修复 diff 视图下 modified model 的只读逻辑不生效的问题

fix: modified readonly logic of diff editor

---

packages/extension/src/hosted/api/vscode/ext.host.api.impl.ts

依赖对 Notebook 的空实现，目前已经可以最近支持 ESLint 插件使用（依赖内核 1.68.0）版本，同时 `Tab API` 及 `ProductIconTheme` 能力在 1.75.0 之后版本才完全完成，建议后续直接向最终版本去做实现。
参考：
- https://github.com/microsoft/vscode/commit/60d21965c76373a784fe8042f8e6108708bbac62
- https://github.com/microsoft/vscode/commit/aa69f3d7623c464aba726d12ea0d83428f43e8b9
update extension engine version to 1.68.0

chore: update extension engine version to 1.68.0

---

packages/editor/__tests__/browser/resource.test.ts
packages/editor/src/browser/doc-model/editor-document-model.ts
packages/editor/src/browser/doc-model/types.ts
packages/editor/src/browser/editor-collection.service.ts
packages/editor/src/browser/editor.module.less
packages/editor/src/browser/resource.service.ts
packages/editor/src/browser/tab.view.tsx
packages/editor/src/common/resource.ts
packages/opened-editor/__tests__/browser/opened-editor.service.test.ts

code editor
diff editor
只读文件的 tab 增加 lock 图标

feat: read-only resource render lock icon

---

packages/file-tree-next/src/browser/file-tree-node.module.less

FileTreeNode css will cover decoreation style, change it priority
fix: change fileTreeNode color style priority

fix: FileTreeNode decoration color style dose not take effect

---

packages/components/src/recycle-tree/tree/TreeNode.ts
packages/extension/src/browser/vscode/api/tree-view/tree-view.node.defined.ts

在使用 Gitlens 12+ 版本情况下，List 及 Tree 模式下，使用的 TreeItem.id 会出现重复的路径问题，最终导致 TreeView 刷新获取到的路径存在异常问题。
这里的修复去掉了对于 TreeViewItem.id 的依赖，转而使用不等的内置 ID 进行节点创建。
fix treeview node duplicated when switching tree mode

fix: treeview node duplicated when switching tree mode

---

CHANGELOG.md
packages/debug/src/browser/contextkeys/debug-contextkey.service.ts
packages/debug/src/browser/debug-session-manager.ts
packages/debug/src/browser/editor/debug-editor-contribution.ts
packages/debug/src/browser/view/console/debug-console.service.ts
packages/debug/src/browser/view/frames/debug-call-stack-session.view.tsx
packages/debug/src/browser/view/frames/debug-call-stack-thread.view.tsx
packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts

close #2321.
对齐 Task Label 格式，以兼容 VS Code 下可正常使用的 Task 命令声明
support normal prelunchTask on debug

fix: support normal prelunchTask on debug

---

packages/editor/src/browser/preference/contribution.ts
packages/outline/src/browser/outline-node.tsx

close #2315.
After:
improve outline treenode style

style: improve outline treenode style

---

packages/editor/src/browser/workbench-editor.service.ts

- notifyBodyChanged 提前  后面触发会导致 iframe webview 组件刷新在切换同名的customEditor时会有以下问题 
https://user-images.githubusercontent.com/31676999/220272635-e8d8b6f8-41a9-4821-8597-fd98bd1bda2a.mov
-  fix #2297
修复同名 customEditor 切换问题
修复 workbench.editorAssociations 贡献点失效

fix: customEditor display problem

---

packages/components/src/icon/iconfont/iconfont.css
packages/core-browser/src/style/icon/index.less

之前所有 kticon 加上块级元素，导致上游集成样式乱了
应该是为了底部 status icon 的展示效果改的：statusbar 上的 kticon 它不会自己根据高度垂直居中
当时参考的 codicon 的 style:
fix styles: `.kticon` wrong display value

fix(styles): fix kticon wrong display value

---

packages/components/src/recycle-tree/RecycleTree.tsx
packages/components/src/recycle-tree/TreeNodeRendererWrap.ts
packages/debug/src/browser/view/console/debug-console.module.less
packages/debug/src/browser/view/console/debug-console.view.tsx
packages/markers/src/browser/markers-tree.view.tsx
packages/markers/src/browser/tree/marker-node.tsx
packages/markers/src/browser/tree/tree-node.module.less

close #2335 
DebugConsole:
Problems:
support dynamic treenode height on RecycleTree component

fix: support dynamic treenode height on RecycleTree component

---

packages/terminal-next/src/node/pty.ts

close: https://github.com/opensumi/core/issues/2332
修复 node pty 对于 cwd 的参数无兜底处理的问题

fix: pty parse cwd error

---

packages/extension/src/node/extension.host.manager.ts
packages/extension/src/node/extension.service.client.ts

之前在处理这个 docker 中会产生僵尸进程的时候写的代码 https://github.com/opensumi/core/issues/2166
treeKill 默认发的是 SIGTERM，有些进程是不会立刻退出的。
use `SIGKILL` signal kill extension process

chore: use `SIGKILL` signal kill extension process

---

packages/core-browser/src/components/actions/styles.module.less

文件树的文字大小是13px，右键菜单默认是14px，修改成跟菜单一样的变量
右键文件树菜单的字体太大

fix: improve context menu content fontsize

---

packages/components/src/recycle-tree/RecycleTree.tsx

这里代码误删导致默认值失效 https://github.com/opensumi/core/pull/2339/files#diff-705c7d0425e21b23f762710ebf99c06781b1a9525a9fad679a19a989bd69f118L868
fix default treenode overflow style

style: fix default treenode overflow style

---

packages/core-node/src/bootstrap/shell-path.ts

Reverts opensumi/core#2021
如果用戶使用的是 zsh 比如 .zshrc 配置的內容，使用 /bin/bash 将会丢失相关的 PATH 信息。

Revert "fix: use bash resolve shellpath"

---

packages/electron-basic/src/browser/header/header.service.ts

Electron 中的 title bar 不会随着文件的切换变更改变文件名称。
修复 Electron 标题栏文件名称没有自动切换的问题

fix: title bar not change with the file

---

packages/search/src/browser/search.view.tsx

修复了在展开「显示搜索条件」后搜索，然后关闭展示搜索条件之后，展示搜索结果的RecycleTree高度不会自适应变化的BUG。
- search tree height not change reactively
- fix: search tree height not change reactively

fix: search tree height not change reactively

---

packages/editor/__tests__/browser/resource.test.ts
packages/editor/src/browser/diff/index.ts
packages/editor/src/browser/fs-resource/fs-resource.ts
packages/editor/src/browser/tab.view.tsx
packages/editor/src/common/resource.ts

resolve #2296
file resource:
diff resource:
feat: editor tab title display file path

feat: editor tab title display file path

---

packages/addons/src/browser/file-search.contribution.ts
packages/extension/src/browser/vscode/api/main.thread.workspace.ts
packages/extension/src/hosted/api/vscode/ext.host.workspace.ts
packages/file-search/__tests__/node/file-search.service.test.ts
packages/file-search/src/node/file-search.service.ts

fixed #2331 
get correctly fsPath on Windows findFiles

fix: get correctly fsPath on Windows findFiles

---

packages/core-browser/src/react-providers/slot.tsx
packages/core-browser/src/style/normalize.less
packages/core-browser/src/utils/label.tsx
packages/startup/entry/sample-modules/menu-bar/menu-bar.contribution.ts
packages/startup/entry/web/app.tsx
packages/status-bar/src/browser/status-bar-item.view.tsx
packages/status-bar/src/browser/status-bar.service.ts
packages/status-bar/src/browser/status-bar.view.tsx
packages/toolbar/src/browser/toolbar.view.tsx

warnings from #2340 changed.
remove status bar warnings

fix: remove status bar warnings

---

packages/extension/__tests__/browser/main.thread.workspace.test.ts
packages/extension/src/hosted/api/vscode/ext.host.workspace.ts

close https://github.com/opensumi/core/issues/2424
compatibility with the experimental API vscode.workspace.registerTimelineProvider

feat: compatibility with the experimental API registerTimelineProvider

---

packages/core-common/src/log.ts
packages/extension/src/browser/vscode/api/debug/extension-debug-service.ts
packages/extension/src/browser/vscode/api/main.thread.connection.ts
packages/extension/src/browser/vscode/api/main.thread.debug.ts
packages/extension/src/browser/vscode/api/main.thread.log.ts

一般情况下，插件进程的日志会写入到 logDir/20230315/extHost.log 文件中，但由于 OpenSumi 在插件实现上有自己的 browser 层，会导致情况特殊，browser 写入的日志是通过 Node 进程写入的。
插件中 browser 层的日志是通过 Node 进程也同时写入到 extHost.log 中，在两个进程同时打开文件句柄，会导致 Windows 环境下的写锁保护机制报错，导致日志写入失败。
解决方法：插件的 Browser 使用另外一个命名空间，和插件进程区分开，保证不同的集成不会写入同一个文件，同时也能保证逻辑清晰。
closed #2383 
修复插件浏览器层的日志和插件进程的命名空间冲突

fix: namespace conflicts between extHost and extBrowser

---

packages/core-common/src/command.ts
packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts
packages/outline/__tests__/browser/services/outline-model.service.test.ts
packages/outline/src/browser/outline.contribution.ts
packages/outline/src/browser/outline.tsx
packages/outline/src/browser/services/outline-event.service.ts
packages/outline/src/browser/services/outline-model.service.ts
packages/outline/src/browser/services/outline-model.ts
packages/outline/src/browser/services/outline-tree.service.ts
packages/utils/__tests__/lru-map.test.ts
packages/utils/src/disposable.ts
packages/utils/src/lru-map.ts
packages/utils/src/map.ts
scripts/module-jest.ts

尝试修了一些 Outline Model 上存在的问题：
以前：
现在：
https://user-images.githubusercontent.com/13938334/225852539-f62f3832-fff7-463c-b59f-2ea00706698d.mp4
refactor some outline code

fix: ensure outline is displayed properly

---

packages/file-scheme/__tests__/browser/contribution.test.ts
packages/file-scheme/src/browser/file-scheme.contribution.ts

在 web 场景下，我们加载一个 500m 的文件会导致页面崩溃，设置 largeFile 后，刷新页面偶现这个配置项不生效。
ensure preference ready before render editor

fix: ensure preference ready before render editor

---

packages/file-service/__tests__/node/file-service-watcher.test.ts

#2354 
* change file server watcher to private for every case

refactor: refactor file-watcher test case

---

packages/extension/src/node/extension.service.ts

fix: revert extension host tree kill

fix: revert extension host tree kill

---

packages/editor/src/browser/editor-collection.service.ts

fix: should set renderMarginRevertIcon=false when diffEditor is readOnly

---

packages/debug/src/browser/model/debug-stack-frame.ts
packages/debug/src/browser/view/frames/debug-call-stack-frame.view.tsx
packages/debug/src/browser/view/frames/debug-call-stack-session.view.tsx
packages/debug/src/browser/view/frames/debug-call-stack-thread.view.tsx
packages/debug/src/browser/view/frames/debug-call-stack.module.less
packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts

close #2445 
support skipFiles on debug call stack frames view

feat: support skipFiles on debug call stack frames view

---

packages/debug/src/browser/model/debug-thread.ts

https://github.com/opensumi/core/issues/2465
当前 frame存在ID 相同时 为其设置一个 uuid

fix: call stack stop at incorrect line because call frame with sameid

---

packages/debug/src/browser/debug-contribution.ts

原有自动选择上次选中调试配置功能由于时序问题失效
修复后：
https://user-images.githubusercontent.com/9823838/227414349-453a5d12-8545-4d63-96d3-193aa8a919cd.mp4
fix auto select the latest debug configuration

fix: auto select the latest debug configuration

---

packages/file-service/src/browser/file-service-client.ts

close https://github.com/opensumi/ide-electron/issues/64
electron 环境卸载插件调用了 fileService.delete， delete 实现中判断如果是 electron 并且设置了 moveToTrash 就会使用 electron 的 api 删除文件。但如果没有设置 moveToTrash 标记，就会走原始的删除文件。原始的删除文件在 mac 下会报错， 找不到 app/node/macos-trash 可执行文件。
在 ide-electron 环境中，删除插件其实移到 Trash 可能更好，避免一些误操作导致文件无法恢复。
修复 ide-electron 环境卸载插件失败的问题

fix: uninstall extension failed in electron

---

packages/connection/src/common/rpcProtocol.ts

fix: #2516 
这个问题是 `writeFile` 的第二个参数支持的是 `Uint8Array` ，传入 `Buffer` 的时候类型校验不会报错。`rpc` 传递消息时通过 `JSON.stringify()` 进行转换后会变成 `{ type: 'Buffer', data: [] }`，`provider` 内处理时会报错。所以在类型转换时增加对 `Buffer` 的兼容
fix: rpcTransfer add buffer support

fix: Add support for buffer type conversion in ObjectTransfer module

---

packages/editor/src/browser/preference/converter.ts
packages/editor/src/browser/preference/schema.ts
packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts
packages/preferences/src/browser/preference-settings.service.ts

close: #2303 
支持 editor.unicodeHighlight.ambiguousCharacters 配置，默认开启

feat: support setting: editor.unicodeHighlight.ambiguousCharacters

---

packages/extension/src/hosted/api/vscode/env/workerEnvApiFactory.ts
packages/extension/src/hosted/api/worker/worker.host.api.impl.ts

close: #2531 
worker-host env 增加 language 属性

feat: work host env 增加 language

---

packages/components/src/recycle-tree/basic/tree-node.tsx
packages/components/src/recycle-tree/basic/types.ts
packages/debug/__tests__/browser/view/breakpoint/debug-breakpoints.service.test.ts
packages/debug/src/browser/breakpoint/breakpoint-marker.ts
packages/debug/src/browser/view/breakpoints/debug-breakpoints-tree.model.ts
packages/debug/src/browser/view/breakpoints/debug-breakpoints.module.less
packages/debug/src/browser/view/breakpoints/debug-breakpoints.service.ts
packages/debug/src/browser/view/breakpoints/debug-breakpoints.view.tsx

改进调试面板的断点视图列表，支持以树视图展示
根节点是文件，子节点是该文件下的所有断点列表
before:
after:
同时由于需要展示断点所在行的内容，就需要获取文档引用，在展示列表时，获取文档的引用操作改为异步获取，不影响断点列表的渲染
support displaying debug breakpoints in a tree view

feat: support displaying debug breakpoints in a tree view

---

packages/extension/src/browser/extension.service.ts
packages/extension/src/node/extension.service.ts

fix: #2311 
* clear old listen option when extServer closed
* rerun view extension contributes

fix: clear old listen and initView when extension restart

---

packages/file-service/src/node/file-service-watcher.ts

这里存在逻辑错误，当批量事件中有某一项命中了 ignored 逻辑时，return 语句会直接退出 for of 循环，导致后续的事件项未被处理。
这个逻辑错误会导致在 linux 系统下依赖了文件变更监听的功能一定概率不能正常工作

fix: return statement will break for..of loop

---

packages/file-tree-next/src/browser/file-tree-contribution.ts

Copy path & copy relative path from editor tab is not working with diff uri:
fix: copy diff uri path at editor tab

fix: copy diff uri path at editor tab

---

packages/core-common/src/json-schema.ts
packages/extension/src/browser/vscode/contributes/debuggers.ts

before
after
修复 launch.json 配置代码补全的部分国际化显示异常问题

fix: markdownDescription i18n in launch.json

---

packages/extension/__tests__/browser/main.thread.editor.test.ts
packages/extension/src/browser/vscode/api/main.thread.editor.ts

在分栏且编辑器光标变化时，插件中获取到的 activeTextEditor  没有正确更新，会导致这种情况下 `Accept Change` 错误的修改了非当前编辑器的内容
https://user-images.githubusercontent.com/17701805/227469569-f180af37-1f79-4a13-bbec-63b75e201e5f.mp4
- Update the active editor when the editor cursor changes.

fix: update the active editor when the editor cursor changes

---

packages/components/src/recycle-tree/tree/TreeNode.ts
packages/components/src/recycle-tree/tree/model/treeState/TreeStateManager.ts
packages/file-tree-next/__tests__/browser/file-tree-model.service.test.ts
packages/outline/__tests__/browser/services/outline-model.service.test.ts
tools/playwright/src/tests/explorer-view.test.ts

修复文件树上折叠全部功能在压缩目录下功能不符预期问题，同时修复极端场景下，文件树文件定位可能出现的异常问题
fix collapsed tree node on compact mode

fix: collapsed tree node on compact mode

---

packages/debug/src/browser/debug-contribution.ts
packages/debug/src/browser/view/configuration/debug-configuration.module.less
packages/debug/src/browser/view/configuration/debug-configuration.view.tsx
packages/debug/src/browser/view/configuration/debug-toolbar.view.tsx

借助 menubar 的高度自定义能力，我们将 debug configuration 和 debug toolbar 实现了组件化，集成方可以将其作为单独的 react 组件导入到自定义的 menubar contribution 中，类似这样
```typescript
export const MenuBarView = () => (
<div className={styles.menu_bar_debug}>
<DebugControllerView />
<DebugToolbarView float={false} />
</div>
);
```
效果如下
-----
1. 这两个组件后续如果有一些改动需要考虑是否有 breakchange，我在注释里通过 @API 来标识该组件是支持用户作为 API 组件导入的
2. 代码示例和最佳实践文档需要更新
支持 debug configuration 和 debug toolbar 的组件化

feat: support debug configuration and toolbar view component

---

packages/preferences/src/browser/preferences.module.less
packages/theme/src/browser/workbench.theme.service.ts
packages/theme/src/common/color-tokens/custom/index.ts
packages/theme/src/common/color-tokens/custom/monaco.ts

fixed https://github.com/opensumi/core/issues/2520
修复浅色主题下highlights文字颜色问题

fix: foreground color of the match highlights on actively focused items

---

packages/core-browser/src/application/application.service.ts
packages/core-common/src/types/application.ts
packages/extension/src/browser/extension-node.service.ts
packages/extension/src/browser/extension.contribution.ts
packages/remote-opener/src/browser/remote.opener.contribution.ts
packages/terminal-next/__tests__/browser/inject.ts
packages/terminal-next/src/browser/terminal.controller.ts
packages/terminal-next/src/browser/terminal.service.ts

[OpenSumi 2023 Roadmap - 移除对 isElectronRenderer 的依赖](https://github.com/opensumi/core/wiki/2023-Roadmap)
这是属于先行的测试改造部分，RFC 还在编写中
Refactored clientId retrieval code into a single function.

refactor: consolidated clientId retrieval code

---

packages/core-common/src/command.ts
packages/editor/src/browser/monaco-contrib/command/command.service.ts

如果 execCommand 执行了一个 command A, 这个 command A 的内部又执行了一次 command B，此时应该是要报出 B 找不到，实际上会报错 A 命令找不到。
execute command will throw wrong error

fix: execute command will throw wrong error

---

packages/testing/src/browser/outputPeek/test-peek-widget.less

fixed: https://github.com/opensumi/core/issues/2700
fix: 修复monaco action bar 图标显示不居中的问题

fix: monaco Action Bar style

---

packages/connection/src/common/connect.ts
packages/connection/src/common/proxy.ts
packages/core-common/src/types/file.ts
packages/file-service/src/common/files.ts
packages/file-service/src/node/disk-file-system.provider.ts

**This PR may bring a breaking change.**
I found that the return value of the function(FileServiceClient.stat) is incorrect while troubleshooting an issue:
the `[]` is the fallback value returned by the RPC boardcast func if it receive no response.
but actually we should throw error if no remote service handled the call.
and the `stat` function actually will eat some errors itself, which is also a bad design.
Throw error if get file stat error(or RPC error)

feat: throw error if get file stat error

---

packages/components/src/scrollbars/index.tsx
packages/editor/src/browser/navigation.view.tsx

开启react-custom-scrollbars组建 universal 的属性
fix: https://github.com/opensumi/core/issues/2806
bugfix: 修复navigation下拉菜单scrollbars样式渲染问题

fix: navigation menu style rendering problem

---

packages/extension-manager/src/browser/extension/extension.module.less

close: https://github.com/opensumi/core/issues/2822
修改前：
修改后：
fix: 调整插件面板中插件的最小高度

fix: plugin panel height adjustment

---

packages/core-browser/src/react-providers/config-provider.tsx
packages/extension/src/browser/shadowRoot.tsx

npmmirror supported browse files now, so we can change cdn url to npmmirror
support use npmmirror cdn url

feat: support use npmmirror cdn url

---

packages/comments/src/browser/comments-body.tsx
packages/core-browser/src/markdown/index.tsx

close: #2256 
直接移除了 santize 选项。
remove sanitize in marked options

chore: remove sanitize in marked options

---

packages/main-layout/src/browser/tabbar/styles.module.less

fix: https://github.com/opensumi/core/issues/2887
开发环境没发现是因为只有一个图标，在全局有个公共样式会影响到多个图标的情况
fix: 修复左侧sidebar右下角图标偏移

fix: left panel style lower right menu style

---

packages/components/src/input/ValidateInput.tsx
packages/extension/__tests__/hosted/api/vscode/ext.host.quickopen.test.ts
packages/extension/src/common/vscode/ext-types.ts
packages/extension/src/hosted/api/vscode/ext.host.quickopen.ts
packages/types/vscode/typings/vscode.quickpick.d.ts

插件调用 createInputBox 展示输入框，如果曾经设置过 error 信息，就无法取消该 error 信息了：
之前的代码写错了，应该是把 data[k] 重设为 null
Fix: extension api `createInputBox` cannot reset validateMessage to undefined

fix(ext): extension cannot reset validateMessage to undefined

---

packages/terminal-next/__tests__/browser/mock.service.ts
packages/terminal-next/__tests__/node/terminal.service.client.test.ts
packages/terminal-next/src/browser/contribution/terminal.command.ts
packages/terminal-next/src/browser/terminal.client.ts
packages/terminal-next/src/browser/terminal.controller.ts
packages/terminal-next/src/browser/terminal.internal.service.ts
packages/terminal-next/src/browser/terminal.service.ts
packages/terminal-next/src/common/pty.ts
packages/terminal-next/src/common/service.ts
packages/terminal-next/src/node/pty.manager.ts
packages/terminal-next/src/node/pty.proxy.remote.exec.ts
packages/terminal-next/src/node/pty.proxy.ts
packages/terminal-next/src/node/pty.ts
packages/terminal-next/src/node/shell.ts
packages/terminal-next/src/node/terminal.service.client.ts
packages/terminal-next/src/node/terminal.service.ts

Support infer the terminal cwd when split the terminal

feat: infer second terminal cwd from the first one

---

packages/components/src/select/index.tsx
packages/preferences/src/browser/preference-settings.service.ts
packages/preferences/src/browser/preferenceItem.view.tsx
packages/utils/__tests__/event.test.ts
packages/utils/src/event.ts

#2880 的后续修复
Preference Panel: rerender Select component if localized string changed

fix(preference): rerender Select component if localized string changed

---

packages/components/src/select/index.tsx
packages/components/src/select/style.less
yarn.lock

原来的 select component 会给每一项的任意层级的子 span 都设置上不合理的样式
remove select component unreasonable span selector

fix(component): remove select component unreasonable span selector

---

packages/editor/src/browser/editor.module.less

fix: https://github.com/opensumi/core/issues/2933
fix: 修复编辑器Tab菜单无法滚动的问题

fix: editor tab cannot be scrolled

---

packages/terminal-next/src/browser/contribution/terminal.view.ts

这四个按钮不见了：
Fix missing action buttons on the terminal panel

fix: terminal panel registered wrong view id

---

packages/components/src/select/style.less

Revert "fix: fix select component style"

---

packages/components/src/select/index.tsx
packages/components/src/select/style.less
yarn.lock

Revert "fix(component): remove select component unreasonable span selector"

---

packages/core-browser/src/components/layout/split-panel.tsx
packages/core-browser/src/components/resize/resize.tsx
packages/explorer/src/browser/explorer-contribution.ts
packages/main-layout/src/browser/accordion/accordion.service.ts
packages/main-layout/src/browser/accordion/accordion.view.tsx
packages/main-layout/src/browser/accordion/section.view.tsx
packages/main-layout/src/browser/layout.service.ts
packages/main-layout/src/browser/main-layout.contribution.ts
packages/main-layout/src/browser/tabbar/panel.view.tsx
packages/main-layout/src/common/main-layout.definition.ts

fix: fix left panel display

---

packages/core-electron-main/src/bootstrap/services/ui.ts
packages/core-electron-main/src/bootstrap/window.ts
packages/startup/package.json
tools/electron/package.json
yarn.lock

更新到 electron22 后构建时类型报错
close: #3048
close: #3047
Drop electron 13 support, the minimum recommended version is 18.3.0

feat: drop electron 13 support

---

packages/core-browser/src/toolbar/components/button.tsx
packages/core-browser/src/toolbar/types.ts

这段代码修复了 ToolbarAction 的 delegate 中获取错误状态的问题。它通过修改 setState() 函数和 getState() 函数来确保获取正确的状态并将状态更新到界面上。同时，还修复了一些变量类型的错误。
fix get wrong state in toolbar action delegate

fix: get wrong state in toolbar action delegate

---

.github/workflows/check.yml
.github/workflows/ci.yml
.github/workflows/e2e.yml
.github/workflows/release-rc.yml
.github/workflows/release.yml

我们的 ci 还都是 nodejs 14，今天发现跑 lerna 会挂掉，升级到 16 解决

ci: use nodejs 16.x

---

packages/core-browser/src/toolbar/toolbar.tsx

toolbar 有个功能是当距离不够时自动变成 DropDown，但是它没有响应 props 的改变
toolbar width should change when props change

fix: toolbar width should change when props change

---

packages/terminal-next/src/browser/component/terminal.module.less
packages/terminal-next/src/browser/component/terminal.view.tsx

fix: https://github.com/opensumi/core/issues/3038
fix：终端搜索框placeholder颜色不正确

fix: search box placeholder color

---

packages/opened-editor/src/browser/opened-editor-node.module.less

fix: https://github.com/opensumi/core/issues/3102
feat: 打开的编辑器的文件树选中状态下展示删除操作

style: open editor displays the delete button in its selected state

---

packages/ai-native/src/browser/components/Icon.tsx
packages/ai-native/src/browser/override/layout/layout.module.less
packages/ai-native/src/browser/override/layout/menu-bar/menu-bar.view.tsx
packages/ai-native/src/browser/override/layout/tabbar.view.tsx
packages/main-layout/src/browser/tabbar/bar.view.tsx

左侧底部菜单支持自定义组件渲染，并固定弹出菜单的位置，不再跟随鼠标位置

feat: support anchor extra ctx menu

---

packages/ai-native/src/browser/ai-chat.module.less
packages/ai-native/src/browser/ai-chat.service.ts
packages/ai-native/src/browser/ai-chat.view.tsx
packages/ai-native/src/browser/ai-editor.contribution.ts
packages/ai-native/src/browser/components/ChatMarkdown.tsx
packages/ai-native/src/browser/components/components.module.less

chore: improve chat prompt

---

packages/ai-native/src/browser/inline-completions/completeProvider.ts
packages/ai-native/src/browser/override/layout/menu-bar/menu-bar.module.less

调整左上角图标样式 & 移动光标时隐藏 inline completion 的 statusbar 状态

fix: editor selection hide status bar

---

.github/workflows/check.yml
.github/workflows/ci.yml
.github/workflows/e2e.yml
.github/workflows/release.yml
packages/core-node/src/connection.ts

in the electron version, if some secrity software connect our ipc socket and then leave, the server will dispose all service, this is an wrong behaviour.
[electron] avoid incorrect dispose of connection

fix(electron): avoid incorrect dispose of connection

---

tools/playwright/configs/playwright.config.ts
tools/playwright/package.json
tools/playwright/src/tests/debug.test.ts
tools/playwright/src/tests/editor.test.ts
tools/playwright/src/tests/editor/undoRedo.test.ts
tools/playwright/src/tests/explorer-view.test.ts
tools/playwright/src/tests/extension.test.ts
tools/playwright/src/tests/file-search.test.ts
tools/playwright/src/tests/keymaps.test.ts
tools/playwright/src/tests/language.test.ts
tools/playwright/src/tests/output.test.ts
tools/playwright/src/tests/scm.test.ts
tools/playwright/src/tests/search-view.test.ts
tools/playwright/src/tests/settings.test.ts
yarn.lock

I want to debug the e2e test case, but vscode playwright extension can only work in the latest playwright version, so we need upgrade playwright

ci: upgrade playwright version

---

packages/connection/__test__/common/buffers.test.ts
packages/connection/__test__/common/stream-decoder.test.ts
packages/connection/__test__/node/ws-channel.test.ts
packages/connection/src/common/connection/buffers.ts
packages/connection/src/common/connection/drivers/stream-decoder.ts

优化流式传输 packet 时的性能：
1. 减少在解析大 payload 时需要 alloc 的次数
2. 使用 cursor 维持住当前对 buffer 的查询，每次不需要从头开始查
optimize stream packet parse performance

feat: optimize stream packet parse performance

---

.github/PULL_REQUEST_TEMPLATE.md

remove github copilot for prs supported

chore: remove github copilot for prs supported

---

packages/comments/src/browser/comments-thread.ts
packages/comments/src/common/index.ts
packages/extension/src/browser/vscode/api/main.thread.comments.ts

修改原有代码中不合理的 `thread.commands = [...]` 更新视图的方式，后续需通过如下方式更新评论列表
```
thread.updateComments([...]); // 包裹了 @action 方法
```
fix comment thread update logic

fix: comment thread update

---

packages/core-browser/src/preferences/settings.ts
packages/core-browser/src/react-hooks/injectable-hooks.tsx
packages/preferences/src/browser/preference-settings.service.ts
packages/preferences/src/browser/preferences.view.tsx

just a try
remove mobx from preference panel

refactor: remove mobx from preference panel

---

configs/ts/references/tsconfig.ai-native.json
configs/ts/tsconfig.build.json
configs/ts/tsconfig.resolve.json
packages/ai-native/package.json
packages/ai-native/src/browser/index.ts
packages/ai-native/src/node/index.ts
packages/core-browser/src/ai-native/ai-config.service.ts
packages/core-browser/src/ai-native/index.ts
packages/core-browser/src/index.ts
packages/core-browser/src/react-providers/config-provider.tsx
packages/core-common/src/types/ai-native.ts
packages/core-common/src/types/index.ts
packages/core-node/src/ai-native/base-back.service.ts
packages/core-node/src/ai-native/index.ts
packages/core-node/src/index.ts
yarn.lock

chore: initialization ai native module

---

packages/connection/src/common/rpc/connection.ts
packages/utils/src/uri.ts

when gitlens open diff editor, an error will shown:
the error directly caused by SumiConnection, but the deep reason is that `URI` didn't support serialization

fix: uri should support serialize to json

---

package.json
packages/core-browser/src/components/layout/default-layout.tsx
packages/main-layout/src/browser/layout.service.ts
packages/main-layout/src/browser/tabbar-handler.ts
packages/main-layout/src/browser/tabbar/bar.view.tsx
packages/main-layout/src/browser/tabbar/panel.view.tsx
packages/main-layout/src/browser/tabbar/renderer.view.tsx
packages/main-layout/src/browser/tabbar/tabbar.service.ts
packages/startup/entry/web/layout.tsx
yarn.lock

close #3365 
fix default layout config

fix: fix default layout state

---

packages/status-bar/src/browser/status-bar.module.less

fix: remove deprecated usage of less import statement

---

packages/main-layout/src/browser/tabbar/renderer.view.tsx
packages/main-layout/src/browser/tabbar/tabbar.service.ts
packages/output/src/browser/output.service.ts
packages/output/src/browser/output.view.tsx

原有的修改会导致纯前端环境下渲染时序问题，让 viewReady 提前 resolve
fix restore layout state on web lite

fix: restore layout state on web lite

---

packages/design/src/browser/style/design.module.less

fix: design title actions style

---

packages/extension/src/browser/vscode/api/main.thread.scm.ts
packages/extension/src/common/vscode/scm.ts
packages/extension/src/hosted/api/vscode/ext.host.scm.ts
packages/scm/src/common/scm.service.ts
packages/scm/src/common/scm.ts
packages/types/vscode.d.ts
packages/types/vscode/typings/vscode.proposed.scm.d.ts
packages/types/vscode/typings/vscode.proposed.scmInputBoxActionButton.d.ts

ISSUE: https://github.com/opensumi/core/discussions/3227

feat: support SourceControlInputBox extension api

---

packages/editor/src/browser/diff/compare.ts

fix: https://github.com/opensumi/core/pull/3414#pullrequestreview-1947855463
修改调用之后发现下面有重复的调用，所以把这个注册删除了

chore: remove duplicate code

---

packages/monaco/src/browser/index.ts
packages/monaco/src/browser/monaco.service.ts

close: #3089
Fix rename widget cannot show key code

fix: rename widget show keycode

---

packages/ai-native/src/browser/ai-chat.view.tsx
packages/ai-native/src/browser/ai-core.contribution.ts
packages/ai-native/src/browser/override/layout/main-slot-renderer.tsx
packages/ai-native/src/browser/override/layout/menu-bar/menu-bar.service.ts
packages/ai-native/src/browser/override/layout/menu-bar/menu-bar.view.tsx
packages/ai-native/src/common/index.ts

Ai Chat面板关闭后，重新刷新页面还是默认展开
修复Ai Chat面板关闭后下载进来还是默认展开的问题

fix: ai chat panel cannot be persisted after closing the panel

---

.github/dependabot.yml
.github/workflows/check.yml
.github/workflows/ci.yml
.github/workflows/deploy.yml
.github/workflows/e2e.yml
.github/workflows/release-rc.yml
.github/workflows/release.yml
package.json
packages/comments/package.json
packages/comments/src/browser/comments-textarea.view.tsx
packages/core-browser/package.json
packages/terminal-next/src/browser/component/resize.view.tsx
tools/dev-tool/cli/rebuild-native.js
tools/dev-tool/package.json
yarn.lock

chore: update deps

---

packages/editor/src/browser/editor-collection.service.ts

相关 #1483
在代码折叠情况下，无需自动对齐编辑器至第一个变更区域
improve diff editor first region position

fix: improve diff editor first region position

---

packages/design/src/browser/style/global.less

fix: monaco hover widget styles

---

packages/extension/src/browser/vscode/contributes/icon.ts
packages/extension/src/browser/vscode/contributes/productIconTheme.ts
packages/theme/src/browser/product-icon.service.ts
packages/theme/src/browser/theme.contribution.ts
packages/theme/src/common/theme.service.ts

- fix product icons contribution not initial after icons contribution

fix: product icons contribution not initial

---

packages/file-tree-next/__tests__/browser/file-tree-model.service.test.ts
packages/file-tree-next/__tests__/browser/file-tree.test.ts
packages/file-tree-next/src/browser/services/file-tree-model.service.ts

如果之前用户点击pannel 放大按钮，把teminal 终端放到最大时，回头点击文件树中的文件，
一般情况下，还是期望直接看到文件内容的， 所以 点击文件树时，把放大的pannel 重新缩小
when click file node, resize the bottom panel

feat: when click file node, resize the bottom panel

---

packages/output/src/browser/output.service.ts

Hide editor readonly popup on output view.
Hide editor readonly popup on output view

fix: hide editor readonly popup on output view

---

packages/editor/src/browser/menu/open-type-menu.contribution.ts

当打开 workspace 时默认打开的文件，有多种打开方式时，右上角的“打开方式”不会显示，需要进行一次切换才能显示。
阅读对应代码，发现之前是通过 workbenchEditorService 的 onActiveResourceChange 事件注册打开方式。而第一次打开 workspace 时，不会触发该事件，导致 menu 没有注册。
因此这边在初始化的时候，额外调用一次，作为初始状态。
在我们的项目中，可以稳定复现，添加上述逻辑后，问题修复。
其他修复方式：
可以修改`workbench-editor.service.ts`，使其在`restoreState`操作中，也触发一下这个事件。这种解决办法的改动较大，担心有额外牵连（`@opensumi/ide-core-browser`里面有一个类似的情况，由于其中的 `src/preferences/preference-provider.ts`会在拿到注入的默认值时，会调用一次`PreferencesChangedEvent`，导致 preference contribution 会在注入到 DI 之前就运行一次，导致 console 会有`no Provider`的报错，不过暂时不影响实际运行）。
目前改动方式，没有看到什么问题，因此我没有选择。
复现办法：
在工作区，打开一个注册了多种打开方式的文件，然后关闭整个工作区项目，然后重新打开。
fix: restore resource missing editor open types menu

fix: restore resource missing editor open types menu

---

packages/ai-native/src/browser/ai-core.contribution.ts
packages/ai-native/src/browser/chat/chat.view.tsx
packages/ai-native/src/browser/layout/ai-layout.tsx
packages/ai-native/src/browser/layout/layout-config.ts
packages/ai-native/src/browser/layout/menu-bar/menu-bar.view.tsx
packages/ai-native/src/browser/layout/tabbar.view.tsx
packages/ai-native/src/common/index.ts
packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts
packages/main-layout/__tests__/browser/layout.service.test.tsx
packages/main-layout/src/browser/tabbar/bar.view.tsx
packages/main-layout/src/browser/tabbar/panel.view.tsx
packages/main-layout/src/browser/tabbar/renderer.view.tsx
packages/main-layout/src/browser/tabbar/tabbar.service.ts

新增默认的 AI Layout 组件，使用后效果如下
同时支持右侧 Chat 面板的显隐

feat: support ai layout renderer

---

packages/debug/__tests__/browser/tree/debug-tree-node.define.test.ts
packages/debug/__tests__/browser/view/console/debug-console-tree.model.service.test.ts
packages/debug/__tests__/browser/view/variables/debug-variables-tree.model.service.test.ts
packages/debug/src/browser/debug-session.ts
packages/debug/src/browser/tree/debug-tree-node.define.ts
packages/debug/src/browser/view/console/debug-console-session.ts
packages/debug/src/browser/view/console/debug-console-tree.model.service.ts

修复调试 NodeJS 情况下，代码的 Console 无法正常输出的问题。
show all types debug session output

fix: show all types debug session output

---

packages/editor/src/browser/monaco-contrib/tokenizer/textmate.service.ts

textmateService 注册多个同名 languageId 的 language 配置时，有一定几率使用其他同名 language id 的 language 配置。
registerLanguages 里面的 forEach 是 async 函数，因此不能保证在当前函数内，使用 this.languageConfiguration.get(langId) 得到的 language 配置，就是当前注册的 language，所以至少 Location 应该也从 languageConfigLocation 中读取来保证一致。
最好还应该把 languages.forEach 里面 async 移除，因为里面除了 addDispose 内需要使用 async 外，其实并不是 async 函数。这样整个代码不会有跨越 await 的问题。
该问题不是很好复现，似乎跟机器性能有关。
fix when language has multiple language config, location will not match the correct language config.

fix: language config maybe not match its location

---

packages/monaco/src/browser/monaco.contribution.ts

修复部分 monaco 快捷键缺少 when 导致的异常触发问题
fix monaco keybinding registry

fix: monaco keybinding registry

---

.github/workflows/ci.yml
package.json
yarn.lock

ci: use node 18.x

---

packages/editor/src/browser/merge-editor/merge-editor.provider.ts
packages/editor/src/browser/types.ts
packages/editor/src/browser/workbench-editor.service.ts
packages/editor/src/common/editor.ts
packages/extension/src/browser/vscode/api/main.thread.api.webview.ts
packages/extension/src/browser/vscode/api/main.thread.editor-tabs.ts
packages/extension/src/browser/vscode/contributes/customEditors.tsx
packages/extension/src/common/vscode/editor-tabs.ts
packages/extension/src/common/vscode/ext-types.ts
packages/extension/src/common/vscode/index.ts
packages/extension/src/hosted/api/vscode/ext.host.api.impl.ts
packages/extension/src/hosted/api/vscode/ext.host.editor-tabs.ts
packages/extension/src/hosted/api/vscode/ext.host.window.api.impl.ts
packages/types/vscode/typings/vscode.editor.d.ts
packages/utils/src/functional.ts
packages/utils/src/types.ts
packages/webview/src/browser/types.ts
packages/webview/src/browser/webview.service.ts

implements extension Tab APIs to #3227
implements extension Tab APIs

feat: implement Tab APIs

---

packages/core-electron-main/src/bootstrap/window.ts

…nces don't have these fields
如果 loadWorkspace API 的 options 参数中包含 webPreferences 字段的话，目前这个 options 的 webPreferences 直接覆盖原有的所有内容，导致启动前端 preload 等失败。 options 的 webPreferences 应该放到默认参数里面的，进行展开操作。
fix: default webPreference filed should be left if options webPreferences don't have these fields

fix(electron): keep defaultWebPreferences field

---

packages/core-browser/src/style/monaco-hover.less
packages/core-browser/src/style/monaco-override.less
packages/core-browser/src/style/override.less

After:
improve monaco hover widget style

style: improve monaco hover widget style

---

packages/main-layout/src/browser/layout.service.ts
packages/main-layout/src/browser/tabbar/renderer.view.tsx
packages/main-layout/src/browser/tabbar/tabbar.service.ts

remove useless runInAction function

fix: more stable layout view restore process

---

packages/extension/__mocks__/extension.service.client.ts
packages/extension/__tests__/browser/extension-service/extension.service.test.ts
packages/extension/src/browser/extension.contribution.ts
packages/extension/src/browser/extension.service.ts
packages/extension/src/common/extension.ts
packages/extension/src/node/extension.service.client.ts
packages/extension/src/node/extension.service.ts
packages/utils/src/async.ts

allow config ext restart policy

feat: allow config ext process restart policy

---

packages/overlay/src/browser/message.service.tsx

- https://github.com/opensumi/core/pull/1744/files#r1565843142

fix: message open duration should be ms

---

packages/ai-native/src/browser/chat/chat.view.tsx
packages/ai-native/src/browser/components/ChatThinking.tsx
packages/ai-native/src/browser/components/StreamMsg.tsx
packages/ai-native/src/browser/components/StreamReplyRender.tsx

fix: chat thinking render

---

packages/connection/__test__/common/multiplexer.test.ts
packages/connection/__test__/node/index.test.ts
packages/connection/src/common/rpc/multiplexer.ts

if rpc id has a slash, rpc wouldn't work:
```
Error handling request extension_extend_service:kaitian.@opensumi/runner/$fetch with args  [] Error: Unknown actor extension_extend_service:kaitian.@opensumi
```

fix: multiplexer rpc id can have slash

---

packages/ai-native/src/browser/ai-core.contribution.ts
packages/core-browser/src/ai-native/command.ts
packages/core-browser/src/core-preferences.ts
packages/core-common/src/settings/ai-native.ts
packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts

新增 ai.native.chat.visible.type 配置项，用于控制 chat 面板默认的展示方式
always 表示总是默认展开，never 表示总是默认收起，default 表示跟随 localstorage 走

feat: support chat visible preference

---

packages/ai-native/src/browser/ai-core.contribution.ts
packages/ai-native/src/browser/ai-editor.contribution.ts
packages/ai-native/src/browser/widget/inline-chat/inline-chat-controller.tsx
packages/ai-native/src/browser/widget/inline-chat/inline-chat.feature.registry.ts
packages/ai-native/src/browser/widget/inline-chat/inline-chat.service.ts
packages/ai-native/src/browser/widget/inline-chat/inline-content-widget.tsx
packages/core-browser/src/core-preferences.ts
packages/core-browser/src/monaco/index.ts
packages/core-common/src/settings/ai-native.ts
packages/core-common/src/types/ai-native/reporter.ts
packages/extension/__tests__/browser/extension-service/extension-service-mock-helper.ts
packages/extension/__tests__/browser/extension-service/extension.worker.service.test.ts
packages/extension/src/browser/vscode/api/main.thread.api.impl.ts
packages/extension/src/hosted/ext.host.ts
packages/extension/src/hosted/ext.process-base.ts
packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts
packages/monaco/src/browser/ai-native/BaseInlineContentWidget.tsx
packages/monaco/src/browser/monaco.contribution.ts
packages/monaco/src/browser/telemetry.service.ts
packages/terminal-next/src/common/pty.ts

feat(telemetry): add code actions and rename candidates event track

---

packages/extension/src/hosted/api/vscode/language/diagnostics.ts
packages/types/vscode/typings/vscode.language.d.ts

修复了之前 DiagnosticCollection 不支持 Iterable 导致的插件处理诊断信息时的问题，有一定概率导致 Java 语言服务的错误诊断显示问题。
Java 插件运行过程中报错，可能会导致语言服务错误诊断展示错误，或者小概率的语言服务挂掉。修复了 DiagnosticCollection 无法被 for of 循环的的问题。
- fix: diagnostics api iterable fix, support for of iteration
- fix: use empty array instead of undefined

fix: diagnostics api iterable fix

---

packages/components/src/modal/Modal.tsx
packages/editor/src/browser/preference/converter.ts
packages/editor/src/browser/preference/schema.ts

follow: https://github.com/opensumi/core/pull/2956
add experimental sticky scroll option with defaults

fix(diff-editor): add experimental sticky scroll option with defaults

---

packages/editor/src/browser/diff/compare.ts
packages/editor/src/browser/diff/index.ts
packages/editor/src/browser/editor-collection.service.ts
packages/editor/src/browser/editor.contribution.ts
packages/editor/src/browser/workbench-editor.service.ts
packages/extension/src/browser/extension.contribution.ts
packages/file-tree-next/src/browser/file-tree-contribution.ts

close #3561.
https://github.com/opensumi/core/assets/9823838/9f7d05ac-e2bd-42c6-b430-94097bbb8c69
optimize diff editor model caching and disposal handing

fix(diff-editor): optimize diff editor model caching and disposal handing

---

packages/components/src/recycle-tree/basic/tree-service.ts

解决设置面板焦点 Tree 选中态清理不完全问题
optimize decoration clearing logic in tree service

fix: optimize decoration clearing logic in tree service

---

packages/extension/__tests__/browser/extension-service/__snapshots__/extension.service.test.ts.snap
packages/extension/__tests__/browser/extension-service/extension.service.test.ts
packages/extension/__tests__/common/__snapshots__/require-interceptor.test.ts.snap
packages/extension/__tests__/common/require-interceptor.test.ts
packages/extension/src/browser/extension-view.service.ts
packages/extension/src/browser/require-interceptor.contribution.ts

我们拦截了 browser 里的 require, 如果一个插件 require 了 react-dom，我们会返回 react-dom/client 的内容给它，会导致它报错。
fix require interceptor return `react-dom/client` when using `react-dom`

fix: require interceptor handle react error

---

packages/extension/__tests__/browser/main.thread.output.test.ts
packages/extension/src/browser/vscode/api/main.thread.api.impl.ts
packages/extension/src/browser/vscode/api/main.thread.output.ts
packages/extension/src/common/vscode/window.ts
packages/extension/src/hosted/api/vscode/ext.host.output.ts
packages/extension/src/hosted/api/vscode/ext.host.window.api.impl.ts
packages/output/src/browser/output.channel.ts
packages/types/vscode/typings/vscode.editor.d.ts
packages/types/vscode/typings/vscode.window.d.ts

1. we should bind `LogOutputChannel`'s log methods.
2. implements set language id

feat: support set language id for output channel

---

packages/extension/src/browser/sumi/contributes/menubar.ts

feat: render ext icon in menubar

---

packages/core-browser/src/bootstrap/app.ts
packages/core-browser/src/common/common.define.ts
packages/core-browser/src/preferences/early-preferences.ts
packages/core-browser/src/preferences/preference-provider.ts
packages/core-common/src/preferences/preference-scope.ts
packages/startup/entry/web/render-app.tsx
packages/storage/__tests__/browser/storage.service.test.ts
packages/storage/src/browser/storage.ts
packages/terminal-next/src/browser/terminal.restore.ts
packages/theme/src/browser/theme.contribution.ts
packages/theme/src/browser/workbench.theme.service.ts
packages/theme/src/common/theme.service.ts
packages/utils/src/disposable.ts

现在有 AI 模式和非 AI 模式两种，AI 模式的主题是不一样的，所以不希望 AI 模式的主题存到 localStorage 中被非 AI 模式读取到

feat: early preference support configure prefix

---

packages/electron-basic/src/browser/header/header.view.tsx

Electron's Header Component won't work  in full screen mode, complaining about fewer hooks rendered. This PR fixes it.
Fixes electron header rendering error in full screen mode

fix: fixes electron header rendering error in full screen mode

---

packages/connection/__test__/common/rpc/registry.test.ts
packages/connection/src/common/rpc-service/registry.ts

发现某应用的 terminal 打不开，调查后发现是前端的 TerminalService RPC 没有注册上：
真正的原因是这个 TermrinalService 是一个 class，但是被编译成了 function XXX，所以 OpenSumi 里获取这个 rpc 有哪些方法的逻辑走错了。
后端有数据输出的时候会调用前端的 onData，前端没有注册这个方法，后端调不过来，前端就不展示了
fix service registry cannot register transpiled class

fix: service registry cannot register transpiled class

---

packages/extension/src/common/vscode/converter.ts
packages/extension/src/common/vscode/ext-types.ts
packages/extension/src/hosted/api/vscode/env/envApiFactory.ts
packages/extension/src/hosted/api/vscode/env/ext.host.env.ts
packages/extension/src/hosted/api/vscode/env/telemetry-ext.ts
packages/extension/src/hosted/api/vscode/ext.host.file-system.ts
packages/extension/src/hosted/api/vscode/ext.host.window.api.impl.ts
packages/extension/src/hosted/api/vscode/ext.host.workspace.ts
packages/types/vscode.d.ts
packages/types/vscode/typings/vscode.env.d.ts
packages/types/vscode/typings/vscode.proposed.env.d.ts
packages/types/vscode/typings/vscode.proposed.terminalDataWriteEvent.d.ts

适配最新版 vscode-python 插件，由于 pylance 是闭源状态，无法知道其 API，用 vscode-python + pyright + python-debuger 插件来承接 python 需求，使用方式：
1. 安装 python 插件列表：
- vscode-python 2024.5.11021008
- pyright: 1.1.360
- python-debuger: 2024.5.11001012
2. 配置需要关闭 vscode-python 默认语言服务配置：
```json
{
"python.languageServer": "None"
}
```
后续语言服务由 pyright 提供
3. 修改插件进程 vscode 版本
运行最新的 language-client 需要将插件进程 VS Code 版本调制最新
> customVSCodeEngineVersion: 1.86.0
feat: 空实现部分 API 已适配最新版本 Python 插件

feat: adapt to the latest version of python extension

---

packages/components/src/markdown/render.tsx
packages/components/src/markdown/styles.less
packages/components/src/popover/index.tsx
packages/components/src/popover/styles.less
packages/components/src/style/base.less
packages/core-browser/src/design/rule.ts
packages/core-browser/src/markdown/index.tsx
packages/core-browser/src/utils/label.tsx
packages/status-bar/src/browser/status-bar-item.view.tsx
packages/theme/src/common/rule.ts

Before:
After:
support codicon transform on popover content

feat: support codicon transform on popover markdown content

---

packages/components/src/notification/index.tsx
packages/connection/src/browser/ws-channel-handler.ts
packages/connection/src/common/connection/drivers/reconnecting-websocket.ts
packages/connection/src/common/connection/drivers/stream.ts
packages/connection/src/common/rpc-service/center.ts
packages/connection/src/node/common-channel-handler.ts
packages/connection/src/node/ws.ts
packages/core-browser/src/bootstrap/connection.ts
packages/extension/src/browser/extension.service.ts
packages/extension/src/common/extension.ts
packages/extension/src/node/extension.service.ts
packages/overlay/src/browser/message.service.tsx
packages/overlay/src/common/index.ts
packages/utils/src/async.ts
packages/utils/src/cancellation.ts
packages/utils/src/map.ts
packages/utils/src/progress.ts

1. 修复 main 分支上的重连 node service 
2. 修复偶现重启 ext host 不工作
Fix reconnect node service does not work
Fix restart ext host does not work

fix: reconnecting ws channel not work

---

packages/connection/src/common/rpc/multiplexer.ts
packages/core-browser/src/react-providers/config-provider.tsx
packages/extension/__tests__/browser/main.thread.task.test.ts
packages/extension/__tests__/hosted/api/vscode/ext.host.comments.test.ts
packages/extension/__tests__/hosted/api/vscode/ext.host.task.test.ts
packages/extension/src/browser/extension-command-management.ts
packages/extension/src/browser/extension-node.service.ts
packages/extension/src/browser/extension-worker.service.ts
packages/extension/src/browser/extension.service.ts
packages/extension/src/browser/sumi/main.thread.api.impl.ts
packages/extension/src/browser/vscode/api/main.thread.api.impl.ts
packages/extension/src/browser/vscode/api/main.thread.api.shared-impl.ts
packages/extension/src/browser/vscode/api/main.thread.commands.ts
packages/extension/src/browser/vscode/api/main.thread.comments.ts
packages/extension/src/browser/vscode/api/main.thread.tasks.ts
packages/extension/src/common/extension.service.ts
packages/extension/src/common/vscode/index.ts

我们有两个 ext host: worker 和 node，每次给这俩发消息，同一个内容要序列化两遍，实际上只需要序列化一次发一遍就好。
比如说： #3614 这里面提到的，fireModelOpenedEvent，打开一个 10M 文件，会对这个 10M 文件序列化两遍
要改动的话会非常大，这里先做一下 refactor

refactor: update ext protocol registration

---

package.json
packages/ai-native/package.json
packages/ai-native/src/browser/languages/service.ts
packages/ai-native/src/browser/widget/inline-chat/inline-content-widget.tsx
packages/ai-native/src/browser/widget/inline-diff/inline-diff-widget.tsx
packages/core-browser/src/application/runtime/constants.ts
packages/monaco/src/browser/ai-native/BaseInlineContentWidget.tsx
yarn.lock

web-tree-sitter 之前用的是 ^ 号版本，会导致构建的 wasm 和版本对不上，要锁一下。
fix tree-sitter not work

fix: lock tree-sitter version

---

packages/ai-native/src/browser/ai-editor.contribution.ts

修复 inline diff editor 的首行代码缩进问题

fix: inline diff editor format

---

packages/connection/src/common/rpc/connection.ts

fix: https://github.com/opensumi/core/issues/3621
fix: 删除报错日志 Error handling request xxx with args

fix: delete request error log

---

packages/core-browser/src/react-providers/slot.tsx
packages/design/src/browser/menu-bar/menu-bar.module.less
packages/design/src/browser/menu-bar/menu-bar.view.tsx
packages/startup/entry/web/app.tsx
packages/startup/entry/web/prod/app.tsx
packages/startup/entry/web/render-app.tsx
packages/startup/src/browser/menu-bar-help-icon.tsx
packages/startup/src/browser/startup.contribution.ts
tools/electron/src/browser/index.ts

右侧 menubar 的布局应该为 flex
before:
after:

fix(style): update menubar right style

---

packages/scm/src/browser/components/scm-resource-tree/index.tsx
packages/scm/src/browser/components/scm-resource-tree/scm-tree-model.service.ts
packages/scm/src/browser/scm-model.ts
packages/scm/src/browser/scm-view-container.tsx

…for better resource management
移除了 `SCMResourceTree` 中对 mobx 的依赖逻辑
调整初始化时序移除警告
optimize SCM tree component initialization and remove warnings

refactor: optimize SCM tree component initialization and remove warnings

---

packages/editor/src/browser/diff/index.ts
packages/editor/src/browser/doc-model/editor-document-model-service.ts
packages/editor/src/browser/merge-editor/merge-editor.provider.ts
packages/extension/src/browser/activation.service.ts
packages/extension/src/browser/extension.service.ts
packages/file-service/__mocks__/file-service-client.ts
packages/file-service/src/browser/file-service-client.ts
packages/file-service/src/common/file-service-client.ts
packages/file-service/src/common/files.ts

调整等待 file system provider 激活的逻辑
从插件的 metadata 元数据信息里扫描一遍 activateEvents 里的 onFileSystem 信息，来作为是否需要等待 file system provider 激活的判断依据，如果对应 schema 不在 activateEvents 里，则直接返回 not found

fix: diff editor support revive

---

packages/ai-native/src/browser/interface-navigation/interface-navigation.contribution.ts

优化 Typescript 场景下的 Interface 跳转功能，改成了只对 Interface 定义处增加快速跳转图标，取消了接口内部声明的跳转图标，避免编辑器左侧内容的混乱。
之前代码中对 Typescript 所有成员都有 Interface 快速跳转图标，但是在 Typescript 的场景中，接口成员很多并且相比 Java 而言空行和注释偏少，同时 Typescript 中对 Interface 用法也和 Java 有所不同，因此对 Typescript 做了逻辑精简。
- feat: optimize typescript interface navigation

feat: optimize typescript interface navigation

---

packages/connection/__test__/common/fury-extends/any.test.ts
packages/connection/src/browser/ws-channel-handler.ts
packages/connection/src/common/fury-extends/any.ts
packages/connection/src/common/rpc-service/center.ts
packages/connection/src/common/rpc-service/registry.ts
packages/connection/src/common/rpc/connection.ts
packages/connection/src/common/rpc/message-io.ts
packages/connection/src/common/rpc/multiplexer.ts
packages/extension/src/browser/extension.service.ts
packages/extension/src/node/extension.host.proxy.manager.ts
packages/extension/src/node/extension.service.client.ts
packages/startup/entry/web-lite/lite-module/extension/index.ts
packages/utils/src/async.ts
packages/utils/src/decorators.ts

1. 插件进程重启中的通知现在只会在真正重启的时候出现
2. 移除后端通知进程不存在的逻辑，改为后端通知后前端直接重启
3. 确保后端通知到前端重启
optimize extension host restart logic

feat: optimize extension host restart logic

---

packages/startup/entry/web/app.tsx

remove unused StartupModule from web app entry

chore: remove unused StartupModule from web app entry

---

packages/core-browser/src/common/common.contribution.ts
packages/core-browser/src/menu/next/base.ts
packages/design/src/browser/menu-bar/menu-bar.contribution.tsx

之前的菜单会被注册多次：
fix menu bar items for design mode will be registered multiple times

fix: menu bar items for design mode will be registered multiple times

---

packages/ai-native/src/browser/ai-terminal/component/terminal-command-suggest-controller.module.less
packages/ai-native/src/browser/ai-terminal/ps1-terminal.service.tsx
packages/core-browser/src/design/rule.ts

修复了终端 AI 自然语言生成命令时的布局 Z-Index 问题：
另外就是终端「输入 # 来获取 AI 建议命令」这个文本的点击事件，可能会造成用户的误触与误解，因此去掉这个点击事件，现在只会被键盘的 「#」 触发。
新版 Xterm.js 里面的底层 CSS 代码中，z-index 是 7，我们需要改到更大的，避免 z-index 问题。
update terminal ai suggest z-index and remove click event

fix: terminal ai suggest z-index fix, remove click event

---

packages/extension/src/browser/activation.service.ts
packages/extension/src/browser/extension.service.ts

重启进程的时候，会重新发送所有 activation event，但是是使用的 Promise.all 发送的，如果此时某个插件激活失败，会导致整体重连失败。
fix activating extension should not abort the whole restart progress

fix: activating extension should not abort the whole restart progress

---

packages/connection/__test__/browser/index.test.ts
packages/connection/__test__/node/index.test.ts
packages/connection/src/browser/ws-channel-handler.ts
packages/connection/src/common/rpc/multiplexer.ts
packages/connection/src/common/server-handler.ts
packages/connection/src/common/ws-channel.ts
packages/extension/src/node/extension.service.ts

WSChannel 在连接开始和重连都会有丢消息的可能性。
1. Browser 层和 Node 连接， Node 和 Ext 未连接，此时 Browser 发给 Ext 的信息全部被丢弃。
2. 重连时，onReconnect 时机太早，此时仅仅时 websocket 重连成功，WSChannel 还没有协商重连成功。
fix WSChannel timing issues

fix: wschannel timing issues

---

packages/extension/src/browser/vscode/api/tree-view/tree-view.model.service.ts

add null check before calling collapseNode and expandNode

fix: add null check before calling collapseNode and expandNode

---

packages/debug/src/browser/view/configuration/debug-configuration.service.ts

修复了 DebugConfigurationService 里面 mobx 的不规范用法，其中一处 observable 变量的设置没有经过 action
- fix: mobx action fix in debugConfigurationService

fix: mobx action fix in debugConfigurationService

---

packages/scm/__tests__/browser/dirty-diff/dirty-diff-model.test.ts
packages/scm/src/browser/dirty-diff/dirty-diff-model.ts

dirty diff editor 不开启 hideUnchangedRegions

fix: dirty-diff editor hide unchanged regions

---

packages/design/src/browser/index.ts
packages/theme/src/browser/theme.contribution.ts
packages/theme/src/browser/workbench.theme.service.ts
packages/theme/src/common/mocks/theme.service.ts
packages/theme/src/common/theme.service.ts

fix: ensure valid theme

---

packages/main-layout/src/browser/tabbar/bar.view.tsx

场景是这样, opensumi 只是我们的一个 tab，但这个 tab 会提前渲染，这个时候 tabbar 的高度是 0（应该是有 bug），然后我们切换到这个 tab 的时候，这个 tab 的高度是没变的
allow configure tabbar max visible counts

feat: allow configure tabbar max visible counts

---

packages/design/src/browser/index.ts
packages/design/src/browser/theme/override.token.ts
packages/theme/src/browser/theme.contribution.ts
packages/theme/src/common/utils.ts

由于主题加载的时机存在时序问题，无法在生命周期的最开始设置 design 主题。
所以改成了当引入 design module 之后会将默认的 dark 和 light 主题的 colorRegistry 设置成对应的 design 主题的 color 色值
引入 design 模块之后使用 design 主题进行预渲染

fix: design theme preload

---

packages/extension/src/browser/vscode/api/main.thread.treeview.ts
packages/extension/src/browser/vscode/api/tree-view/tree-view.model.service.ts
packages/extension/src/common/vscode/treeview.ts
packages/extension/src/hosted/api/vscode/ext.host.treeview.ts

ExtensionTreeNode 那里有时序问题。如果 ExtTree 更新了，会通知前端刷新，但没有确保时序，插件进程以为树刷新好了，就执行后续操作，比如 reveal(treeItem), 但是这个 treeItem 还没被加载进来。
同时 reveal 没有确保能 reveal 到某个子节点。
ext tree view reveal an element is not work

fix(ext-tree-view): reveal an element is not work

---

packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts
packages/testing/src/browser/components/testing.explorer.tree.tsx
packages/testing/src/browser/components/testing.module.less
packages/testing/src/browser/outputPeek/test-message-container.tsx
packages/testing/src/browser/outputPeek/test-peek-widget.tsx
packages/testing/src/browser/outputPeek/test-tree-container.tsx
packages/testing/src/browser/testing.contribution.ts
packages/testing/src/common/test-result.ts

适配了新版的 Java Test 插件，全面升级了 IDE 测试能力。
- 支持了 IDE 底部区域展示单独的 Test Results 视图（默认隐藏，运行测试样例后出现）
- 支持了点击测试展示测试输出，支持了 appendOutput API
- 支持了点击测试结果展示错误信息 / diff 对比
- 支持了测试列表中展示 codicon
- 修复了某些情况下测试结果无法预览的问题
OpenSumi Java 开发支持，需要对 Java 语言服务，Java Debug 和 Java Test 做一次全面升级，前两者最近两年改动相对较少，但是 Test API 以及上层交互设计这两年改动较多，所以需要做一次全面升级。
- feat: support test results panel, icons in test view

feat: support test results panel, icons in test view

---

packages/terminal-next/src/common/preference.ts

修复了终端在页面刷新后无法恢复的问题 
Terminal Persistent 设置项不一致导致的问题。
- fix: terminal not restore

fix: terminal not restore

---

packages/core-browser/src/layout/constants.ts
packages/core-common/src/types/ai-native/index.ts
packages/design/src/browser/design.contribution.ts
packages/startup/entry/web/app.tsx

layout 视图只允许通过 layoutConfig 去配置，design 模块不允许去修改
design 模块的 useMenubarView 配置不注册 top layout 视图

fix: design module no register top layout

---

packages/core-browser/src/style/monaco-override.less

Before:
After:
adjust find-widget close button position in monaco editor

style: adjust find-widget close button position in monaco editor

---

packages/ai-native/src/browser/ai-core.contribution.ts
packages/ai-native/src/browser/index.ts
packages/core-browser/src/ai-native/ai-config.service.ts
packages/core-browser/src/browser-module.ts

现在 ai 模块会在 initialize 阶段开启所有 ai 功能，用户传入到 ClientApp 的参数 AINativeConfig.capabilities 是不生效的。
should not change user defined ai capabilities

fix: should not change user defined ai capabilities

---

packages/core-browser/src/preferences/preference-service.ts
packages/core-browser/src/preferences/types.ts
packages/terminal-next/__tests__/browser/mock.service.ts

Adds an export definition for a method in PreferenceService

feat: update preference service typing

---

packages/ai-native/src/browser/widget/inline-chat/inline-chat.handler.ts
packages/ai-native/src/browser/widget/inline-diff/inline-diff-widget.tsx

当流式输出过快的时候会偶现 inline diff widget 底部出现空白
修复 inline diff widget 偶现的底部空白问题

fix: inline diff widget layout

---

packages/connection/src/common/rpc-service/center.ts
packages/core-browser/src/bootstrap/connection.ts
packages/core-browser/src/react-providers/config-provider.tsx
packages/core-common/src/reporter.ts
packages/core-common/src/types/reporter.ts
packages/startup/entry/web/app.tsx
packages/startup/entry/web/render-app.tsx
packages/utils/src/functional.ts

增加 rpc 的埋点上报渠道
add rpc timing event track

feat: add rpc timing event track

---

packages/design/src/browser/override/editor-tab.service.tsx
packages/design/src/browser/style/design.module.less
packages/design/src/browser/style/global.less
packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts

simplify EditorTabCloseComponent and adjust button styles

style:  adjust tabbar close popover styles

---

packages/file-service/src/node/disk-file-system.provider.ts
packages/utils/src/file-uri.ts

之前如果复制文件到父级，会导致文件丢失（执行 fs-extra.move 后，它内部会删除源文件）
vscode 有一层前置检查：
加入一次前置检查
fix: validate copy and move operations

fix: validate copy and move operations

---

packages/ai-native/src/browser/layout/tabbar.view.tsx

当无注册的右侧面板时，隐藏分割线
conditionally show HorizontalVertical component based on visible

fix: conditionally show HorizontalVertical component based on visible

---

packages/design/src/browser/style/design.module.less
packages/design/src/browser/theme/default-theme.ts

由于 editor.background 设置了 0.15 透明度，导致刷新后出现白色闪烁，使用不带透明度色值解决这一问题
update default editor background color to #181818

fix: update default editor background color to #181818

---

packages/ai-native/src/browser/ai-core.contribution.ts
packages/ai-native/src/browser/ai-editor.contribution.ts
packages/ai-native/src/browser/contrib/base/index.ts
packages/ai-native/src/browser/contrib/code-action/code-action.handler.ts
packages/ai-native/src/browser/contrib/inline-completions/completeProvider.ts
packages/ai-native/src/browser/contrib/inline-completions/inline-completions.handler.ts
packages/ai-native/src/browser/contrib/inline-completions/model/competionModel.ts
packages/ai-native/src/browser/contrib/interface-navigation/interface-navigation.contribution.ts
packages/ai-native/src/browser/contrib/rename/rename.handler.ts
packages/ai-native/src/browser/index.ts
packages/ai-native/src/browser/preferences/index.ts
packages/ai-native/src/browser/preferences/schema.ts
packages/ai-native/src/browser/widget/inline-chat/inline-chat.handler.ts
packages/core-browser/src/core-preferences.ts
packages/core-common/src/settings/ai-native.ts
packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts
packages/startup/entry/sample-modules/ai-native/ai.back.service.ts

修复内联补全偶现不出现（快速敲击时必现不出现）
重构了注册 monaco 相关能力的逻辑
Fix inline completion occasionally not appearing
optimize monaco contrib registration

refactor(ai-native): optimize monaco contrib registration

---

packages/ai-native/src/browser/layout/ai-layout.tsx
packages/design/src/browser/menu-bar/menu-bar.module.less

不应该硬编码层级关系，将层级关系由子组件自行控制
adjust z-index values for layout components

style: adjust z-index values for layout components

---

packages/design/src/browser/style/global.less

remove unnecessary overflow:hidden from menubar in global style

style: remove unnecessary overflow:hidden from menubar in global style

---

packages/core-browser/__mocks__/logger.ts
packages/core-browser/src/bootstrap/app.ts
packages/core-browser/src/bootstrap/connection.ts
packages/core-browser/src/bootstrap/inner-providers.ts
packages/core-browser/src/logger/browser-logger.ts
packages/core-common/src/log.ts
packages/logs-core/__tests__/browser/log-manage.test.ts
packages/logs-core/__tests__/browser/log.service.test.ts
packages/logs-core/src/browser/index.ts
packages/logs-core/src/browser/log-manager.ts
packages/logs-core/src/browser/log.service.ts
packages/logs-core/src/common/log-core.ts
packages/logs-core/src/node/log.service.ts

从埋点来看，我们的 log debug 必定会上报给后端，实际上后端已经设置成了 info，会丢弃掉这次 log 请求，这个会带来通信成本
avoid send too many log request

feat: avoid send too many log request

---

packages/ai-native/src/browser/layout/tabbar.view.tsx
packages/core-browser/src/components/ai-native/enhanceIcon/index.tsx

支持仅注册了 command 命令的按钮展示及执行
improve handling extra menu nodes on left tabbar

fix: improve handling extra menu nodes on left tabbar

---

packages/connection/src/common/rpc/message-io.ts
packages/extension/src/browser/extension-worker.service.ts
packages/extension/src/hosted/worker.host.ts

3.1 把 worker host 弄挂了，应该是只会导致一些 api 挂掉（provideDocumentSymbols， provideDocumentHighlights）
-  https://github.com/opensumi/core/pull/3729
原因是，与 worker-host 的通信改成不进行序列化之后，Uri、URI 发过去会变成纯对象，纯对象 toString 后就变成 [Object object] 了
我们的序列化方案处理了 Uri、URI 发到对端后还是 Uri、URI
use ext message io for worker

fix: use ext message io for worker

---

packages/ai-native/src/browser/widget/light-bulb/index.ts
packages/debug/__tests__/browser/view/configuration/debug-configuration.service.test.ts
packages/editor/src/browser/component.ts
packages/editor/src/browser/fs-resource/fs-editor-doc.ts
packages/editor/src/browser/fs-resource/fs-resource.ts
packages/editor/src/browser/preference/schema.ts
packages/editor/src/browser/types.ts
packages/extension/src/browser/vscode/api/main.thread.doc.ts
packages/file-scheme/__tests__/browser/contribution.test.ts
packages/file-scheme/src/browser/external.view.tsx
packages/file-scheme/src/browser/file-scheme.contribution.ts
packages/file-scheme/src/browser/prevent.view.tsx
packages/file-scheme/src/browser/style.module.less
packages/file-service/package.json
packages/file-service/src/common/file-ext.ts
packages/file-service/src/node/shared/file-type.ts
packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts
packages/preferences/__tests__/browser/preference-settings.test.ts
packages/utils/src/buffer.ts
packages/workspace/__tests__/browser/workspace-service.test.ts
yarn.lock

如果用户不小心点击了 node 的 binary 文件，我们原来的识别无法识别到它是一个二进制文件。
现在复用了检测二进制的逻辑（和 vscode 保持一致）
prevent accidentally opening binary file

feat: prevent accidentally opening binary file

---

packages/connection/__test__/browser/index.test.ts
packages/connection/__test__/common/fury-extends/one-of.test.ts
packages/connection/src/common/channel/types.ts
packages/connection/src/common/rpc-service/center.ts
packages/connection/src/common/serializer/fury.ts
packages/connection/src/common/server-handler.ts
packages/connection/src/common/ws-channel.ts
packages/core-node/src/connection.ts
packages/extension/src/browser/extension-worker.service.ts
packages/terminal-next/src/node/terminal.service.client.ts
packages/terminal-next/src/node/terminal.service.ts
packages/utils/__tests__/event.test.ts
packages/utils/src/event.ts
packages/utils/src/linked-list.ts
packages/utils/src/strings.ts

又梳理了一下重连会带来的一些问题
1. rpc service center 和 channel 的 dispose 没有完全清理干净
2. 新建 channel 没有删掉旧的, 旧 channel 仍然可以收到消息
3. 重连会多次创建 Worker，导致通信很多报错
4. EventQueue 逻辑有问题，当没有接收方的时候，没有存消息到队列中
fix server's incorrect dispose of service center

fix: server's incorrect dispose of service center

---

packages/editor/src/browser/editor-collection.service.ts
packages/editor/src/browser/workbench-editor.service.ts

这行代码会导致 diff 状态下，git 插件读取的数据不是最新的本地文件，因为它会命中缓存，不会去获取 provideEditorDocumentModelContent 了
原因是之前为了缓存 diff 编辑器的状态，每次不会 dispose 这个 editor ref，下次进来就命中缓存。
monaco saveState 和 restoreState 都没保存已经展开的那些数据，感觉只能先搁置 restore 这个状态了，先把 bug 修复吧
fix diff editor cannot should latest file content

fix: diff editor display error model content

---

packages/core-browser/src/react-providers/slot.tsx

我们的 AINativeModule 会在 initialize 阶段注入 Chat 面板，渲染也会保证在 appInitialized 后渲染面板。
但是有哪些面板的获取是在渲染过程中获取的，应该改为在 appInitialized 后获取。
lazy get layout modules

fix: lazy get layout modules

---

packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts
packages/monaco/src/browser/contrib/merge-editor/view/grid.tsx

我们在 web 端加载代码的插件是 webscm，切换到 merge editor 后切换不回 text editor 了
some scm provider cannot switch merge editor to text editor

fix(merge-editor): some scm provider cannot switch to text editor

---

packages/core-browser/src/components/layout/split-panel.service.ts
packages/editor/src/browser/tab.view.tsx
packages/main-layout/src/browser/accordion/section.view.tsx

支持在在折叠的面板上下均可拖拽 Resize 的能力
https://github.com/opensumi/core/assets/9823838/2b78ee2a-8d90-42d1-afda-6b9476355587
skip locked panels during resize check

fix: skip locked panels during resize check

---

packages/overlay/src/browser/dialog.service.ts

在 codeblitz 上，必现 dialog buttons 出不来：
fix dialog buttons cannot show

fix: dialog buttons cannot show

---

packages/ai-native/src/browser/widget/inline-chat/inline-chat-controller.ts
packages/ai-native/src/browser/widget/inline-diff/inline-diff-previewer.ts
packages/ai-native/src/browser/widget/inline-stream-diff/inline-stream-diff.handler.tsx

之前处理模型回答的代码块逻辑有问题，现调整成更合理的方式
修复 inline chat 流式渲染偶现代码块不完整的问题

fix: inline chat code blocks controller

---

packages/ai-native/src/browser/widget/inline-diff/inline-diff-previewer.ts
packages/ai-native/src/browser/widget/inline-stream-diff/inline-stream-diff.handler.tsx
packages/ai-native/src/browser/widget/inline-stream-diff/inline-stream-diff.module.less
packages/ai-native/src/browser/widget/inline-stream-diff/live-preview.decoration.tsx

zone 表示用户选中的代码区域，我们会在这个区域范围内进行流式 diff 渲染
之前的处理方式是采用 monaco 的 decoration 来进行 rang 范围计算，但这种方式偶尔会有问题，会导致流式渲染的区域超过这个 zone 的范围，不仅 diff 的对比不正确，更会导致未选中的代码部分被覆写
现在重新调整了 zone 的计算方式，在每次要 handleEdits 时实时的根据 newFullRangeTextLines 内容长度重新计算 zone
修复 inline live 模式下流式 diff 渲染时会出现溢出覆写的情况

fix: inline live diff zone range

---

packages/ai-native/src/browser/ai-core.contribution.ts
packages/ai-native/src/browser/contextkey/ai-native.contextkey.service.ts
packages/ai-native/src/browser/model/enhanceDecorationsCollection.ts
packages/ai-native/src/browser/widget/inline-diff/inline-diff-previewer.ts
packages/ai-native/src/browser/widget/inline-stream-diff/inline-stream-diff.handler.tsx
packages/ai-native/src/browser/widget/inline-stream-diff/inline-stream-diff.module.less
packages/ai-native/src/browser/widget/inline-stream-diff/inline-stream-diff.service.ts
packages/ai-native/src/browser/widget/inline-stream-diff/live-preview.decoration.tsx
packages/core-browser/src/ai-native/command.ts
packages/core-browser/src/contextkey/ai-native.ts
packages/monaco/src/browser/ai-native/BaseInlineContentWidget.tsx
packages/theme/src/common/color-tokens/ai-native.ts
packages/theme/src/common/color-tokens/index.ts

https://github.com/opensumi/core/assets/20262815/8158b47b-2a26-4093-bd8a-534b6d8f07e3
live 模式的 inline diff 支持采纳或弃用部分变更

feat: support partial edit widget

---

packages/editor/src/browser/doc-model/editor-document-model.ts
packages/editor/src/browser/doc-model/types.ts
packages/extension/src/browser/vscode/api/main.thread.doc.ts
packages/extension/src/common/vscode/doc.ts
packages/extension/src/hosted/api/vscode/doc/doc-manager.host.ts

现状是 ext 层 document 的 dirty 状态会和 browser 层不同步。
如果此时 browser 层的文本是非 dirty 的，也就意味着它不会向插件层发送 Save 事件，这里我们在 onWillSave 的时候发一个事件去同步当前的状态。
这样至少保证了用户按 ctrl+s 的时候，状态能同步到 ext host
fix extesnion document state may not sync from main thread

fix: sync dirty state when will save document

---

packages/core-browser/src/layout/constants.ts
packages/design/src/browser/design.contribution.ts
packages/design/src/browser/override/editor-tab.service.tsx
packages/design/src/browser/style/design.module.less

DesignModule 加载后会覆盖用户设置的 layoutViewSize 这个配置项。
下图就是调成 100 的效果。
support change editor tabbar height

feat: support change editor tabbar height

---

packages/terminal-next/src/common/preference.ts
packages/utils/src/platform.ts

Node.js v21 后新增了 navigator 符号：

fix: platform detection after Node.js 21

---

packages/file-service/src/node/shared/file-type.ts
packages/utils/src/encoding.ts

detectEncodingFromBuffer 使用的是 readStream，这个在经过 fileType 时已经 pipeline，在 node>=20 时无任何事件触发，导致打开大文件时完全卡住，优化了 stream 的写法

fix: getFileType is not work after Node.js 20

---

packages/ai-native/src/browser/widget/inline-chat/inline-chat.handler.ts
packages/core-common/src/types/ai-native/reporter.ts

fix: update data reporting parameter

---

packages/ai-native/src/browser/contrib/intelligent-completions/intelligent-completions.controller.ts

修复了在 alwaysVisible 配置开启后，按 tab 不会采纳内敛补全的行为

fix: tab keybinding invalid when always visible

---

packages/terminal-next/src/node/pty.ts

开启 bash integration 的时候 Bash 无法启动
bash 启动时，long option 必须放在 option 之前

fix(pty): cannot run bash with bash integration

---

packages/ai-native/src/browser/chat/chat.view.tsx

fix: slash command unseen

---

packages/extension/src/common/vscode/tasks.ts
packages/task/src/browser/task-executor.ts
packages/task/src/common/task.ts
packages/types/vscode/typings/vscode.tasks.d.ts

Support VSCode API: TaskPresentationOptions

feat: support VSCode API: TaskPresentationOptions

---

packages/editor/src/browser/preference/schema.ts
packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts
packages/preferences/src/browser/preference-settings.service.ts

chore:  support editor hover preference

---

packages/ai-native/src/browser/model/enhanceDecorationsCollection.ts
packages/ai-native/src/browser/model/styles.module.less
packages/ai-native/src/browser/widget/inline-chat/inline-chat-editor.controller.ts
packages/ai-native/src/browser/widget/inline-diff/inline-diff-previewer.ts
packages/ai-native/src/browser/widget/inline-diff/inline-diff.controller.ts
packages/ai-native/src/browser/widget/inline-input/inline-input.controller.ts
packages/ai-native/src/browser/widget/inline-stream-diff/inline-stream-diff.handler.tsx
packages/ai-native/src/browser/widget/inline-stream-diff/live-preview.component.tsx
packages/ai-native/src/browser/widget/inline-stream-diff/live-preview.decoration.tsx
packages/monaco/src/browser/ai-native/BaseInlineContentWidget.tsx

之前在切换文件时是通过临时存储一份 snapshot 快照数据然后销毁原有实例，在每次恢复 inline diff 的时候又重新创建一个实例然后 attach 这个 snapshot，这种思路不好，容易遗漏一些数据层面的存储。
现重构成，切换文件时不销毁实例（除非主动销毁），仅销毁渲染层，然后每次在恢复的时候由于数据层不变，只需要恢复渲染层即可，而且这样也能实现在流式的过程当中切换文件不会导致中断。
https://github.com/user-attachments/assets/b7981a23-e78c-4a0e-9948-ac5928bb12f9
切换文件时不中断 inline diff 的流式数据

refactor: inline diff data layer & render layer

---

packages/ai-native/src/browser/ai-core.contextkeys.ts
packages/ai-native/src/browser/contrib/inline-completions/inline-completions.controller.ts
packages/ai-native/src/browser/contrib/intelligent-completions/index.ts
packages/ai-native/src/browser/contrib/intelligent-completions/intelligent-completions.contribution.ts
packages/ai-native/src/browser/contrib/intelligent-completions/intelligent-completions.controller.ts
packages/ai-native/src/browser/contrib/intelligent-completions/view/code-edits-previewer.ts
packages/ai-native/src/browser/contrib/intelligent-completions/view/default.ts
packages/core-browser/src/contextkey/ai-native.ts

fix: content same will not render NES

---

packages/ai-native/src/node/base-language-model.ts

clientId 非必传，如果没有传入 clientId，则不使用工具
- feat: clientId no longer required in base language model

feat: clientId no longer required in base language model

---

packages/core-browser/src/style/override.less

Before:
After:
add color style for codicon keyboard tab icon

style: add color style for codicon keyboard tab icon

---

packages/ai-native/src/browser/contrib/intelligent-completions/intelligent-completions.controller.ts
packages/ai-native/src/browser/contrib/intelligent-completions/view/default.ts

修复 default 模式的 code edits discard 问题

fix: code edits default previewer discard

---

packages/ai-native/src/browser/chat/apply.service.ts
packages/ai-native/src/browser/mcp/base-apply.service.ts
packages/ai-native/src/browser/mcp/tools/handlers/EditFile.ts

fix: add user's intention in apply prompt & fix getDiagnosticInfos error
fix: add user's intention in apply prompt & fix getDiagnosticInfos error

fix: edit instruction

---

packages/ai-native/src/browser/mcp/mcp-server.feature.registry.ts
packages/ai-native/src/browser/mcp/tools/createNewFileWithText.ts
packages/ai-native/src/browser/mcp/tools/editFile.ts
packages/ai-native/src/browser/mcp/tools/fileSearch.ts
packages/ai-native/src/browser/mcp/tools/getDiagnosticsByPath.ts
packages/ai-native/src/browser/mcp/tools/getOpenEditorFileDiagnostics.ts
packages/ai-native/src/browser/mcp/tools/grepSearch.ts
packages/ai-native/src/browser/mcp/tools/listDir.ts
packages/ai-native/src/browser/mcp/tools/readFile.ts
packages/ai-native/src/browser/mcp/tools/runTerminalCmd.ts
packages/ai-native/src/browser/types.ts

feat: support builtin mcp tool order
内置工具顺序按照 Cursor 来实现：
1. codebase_search
1. read_file
1. run_terminal_cmd
1. list_dir
1. grep_search
1. edit_file
1. file_search
feat: support builtin mcp tool order

feat: support builtin mcp tool order
