opensumi/core

packages/editor/src/browser/preference/schema.ts
packages/editor/src/browser/view/suggest-widget.ts
packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts
packages/preferences/src/browser/preference-settings.service.ts

feat: support suggest details visible by default

---

packages/extension/src/browser/vscode/api/main.thread.language.ts

安装 beautify插件，然后在任意文件选择 format 都会出现这个 beautify
- https://github.com/opensumi/core/issues/852
- https://github.com/opensumi/core/pull/853
- https://github.com/opensumi/core/pull/1231
透传 Selector 给 Monaco Editor

feat: pass through language selector

---

packages/extension/src/browser/vscode/api/main.thread.language.ts
packages/extension/src/common/vscode/ext-types.ts
packages/extension/src/common/vscode/languages.ts
packages/extension/src/hosted/api/vscode/ext.host.language.ts
packages/extension/src/hosted/api/vscode/language/inlineCompletion.ts
packages/types/vscode/typings/vscode.language.d.ts

https://user-images.githubusercontent.com/20262815/185881472-16ed597e-7a60-468c-8dd0-4ada5027b906.mp4
支持 InlineCompletion API

feat: implement inlineCompletion API

---

packages/core-browser/src/common/common.command.ts
packages/editor/src/browser/editor.contribution.ts
packages/file-tree-next/src/browser/file-tree-contribution.ts
packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts

support copy path menu on EditorTitleContext

feat: support copy path menu on EditorTitleContext

---

packages/components/src/checkbox/index.tsx
packages/components/src/input/Input.tsx
packages/components/src/input/TextArea.tsx

chore: remove warnings while using CheckBox component

---

packages/core-browser/src/react-providers/config-provider.tsx
packages/extension/src/browser/extension.service.ts

- AppConfig 添加忽略 workerhost 跨域选项

feat: add ignore worker host cors option

---

packages/editor/src/browser/tab.view.tsx

close #1596.
after:
https://user-images.githubusercontent.com/9823838/187336507-842a4b3c-40cb-4c6a-8f74-c48260b54c90.mp4
fix editor title menu argv render logic

fix: editor title menu argv render logic

---

packages/file-service/__tests__/node/file-service-watcher.test.ts

test: improve watcher unit test

---

packages/editor/src/browser/tab.view.tsx

fix: scm diff editor open file invalid

---

packages/task/src/browser/task-executor.ts
packages/task/src/browser/task.schema.ts
packages/terminal-next/__tests__/browser/controller.test.ts
packages/terminal-next/__tests__/browser/terminal.service.test.ts
packages/terminal-next/src/browser/contribution/terminal.command.ts
packages/terminal-next/src/browser/terminal.controller.ts
packages/terminal-next/src/common/controller.ts
packages/terminal-next/src/common/pty.ts
packages/utils/src/event.ts

this close: #1531 
- suppress logging exit message twice
- do not restore task terminal

fix: do not restore task terminal

---

packages/file-service/__tests__/node/file-service-watcher.test.ts

chore: improve watcher test

---

packages/editor/src/browser/workbench-editor.service.ts

fix: get correct diffeditor for generate menu args

---

.github/workflows/ci.yml
packages/file-service/__tests__/node/file-service-watcher.test.ts

chore: skip watcher test on GitHub macos workflow

---

packages/debug/src/browser/view/console/debug-console.module.less
packages/debug/src/browser/view/console/debug-console.service.ts

将默认高度从 26 调整为 18
更精致
调整调试控制台的高度，修复高度过高的异常问题

fix: debug console highly abnormal

---

packages/components/src/notification/notification.less
packages/components/src/notification/notification.tsx

style: improve notification button style

---

packages/theme/src/browser/icon.service.ts

close #1618.
background icon size should be contain

style: background icon size should be contain

---

packages/comments/package.json
packages/comments/src/browser/comments-body.tsx
packages/comments/src/browser/comments-item.view.tsx
packages/components/__tests__/recycle-tree/prompt/index.test.ts
packages/components/package.json
packages/components/src/input/validate-input.less
packages/components/src/recycle-tree/prompt/PromptHandle.ts
packages/components/src/utils/index.ts
packages/components/src/utils/marked.ts
packages/core-browser/package.json
packages/core-browser/src/markdown/index.tsx
packages/extension/src/common/vscode/converter.ts
packages/markdown/package.json
packages/markdown/src/browser/markdown.service.ts
packages/overlay/package.json
packages/testing/src/common/testingStates.ts

close #1619.
after:
improve validate input style

style: improve validate input style

---

packages/extension/src/common/vscode/converter.ts
packages/extension/src/common/vscode/ext-types.ts
packages/types/vscode/typings/vscode.proposed.d.ts

1.65 版本以上的 inlayHint 参数换了个位置
https://github.com/microsoft/vscode/commit/627d46551dad2dce8496eef929347f85ed91ff49
- 更新 InlayHint 构造参数

fix: inlay hint paramters update

---

packages/components/src/badge/styles.less
packages/core-browser/src/services/status-bar-service.ts
packages/debug/src/browser/debug-contribution.ts
packages/debug/src/browser/view/breakpoints/debug-breakpoints.module.less
packages/status-bar/__tests__/browser/status-bar.service.test.ts
packages/status-bar/src/browser/status-bar.contribution.ts
packages/status-bar/src/browser/status-bar.service.ts
packages/status-bar/src/browser/status-bar.view.tsx
packages/theme/src/common/color-tokens/custom/panel.ts

close #1631.
improve HC color theme and statusbar style

style: improve HC color theme and statusbar style

---

packages/components/src/select/index.tsx
packages/task/src/browser/task.service.ts

fix: output name not visible

---

packages/file-scheme/__tests__/browser/contribution.test.ts

https://github.com/opensumi/core/issues/1622#issuecomment-1239096927
test: add test for `file-scheme.contribution`

test: add test for `file-scheme.contribution`

---

packages/comments/src/browser/comments-item.view.tsx
packages/comments/src/browser/comments.module.less
packages/comments/src/common/index.ts
packages/extension/__tests__/hosted/api/vscode/ext.host.comments.test.ts
packages/extension/src/browser/vscode/api/main.thread.comments.ts
packages/extension/src/hosted/api/vscode/ext.host.comments.ts
packages/types/vscode/typings/vscode.comments.d.ts
packages/utils/src/date.ts

resolve #1411
implement comment timestamp

feat: implement comment timestamp

---

packages/file-tree-next/src/browser/services/file-tree-api.service.ts
packages/file-tree-next/src/common/index.ts
packages/workspace-edit/src/browser/workspace-edit.service.ts
packages/workspace-edit/src/common/index.ts

feat: create files with options take the content

---

packages/editor/src/browser/editor.contribution.ts
packages/editor/src/browser/history/index.ts
packages/editor/src/browser/preference/schema.ts
packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts

close #1589.
support navigate editor history by mouse 3/4

feat: support navigate editor history by mouse 3/4

---

packages/editor/src/browser/doc-model/save-task.ts

save task should be resolve after canceled

fix: save task should be resolve after canceled

---

packages/core-browser/src/components/layout/styles.module.less

before:
after:
- fit editor hover content widget z-index

style: fit editor hover content widget z-index

---

packages/startup/entry/web-lite/lite-module/extension/utils.ts

Revert "fix: startup utils typo"

---

packages/core-browser/src/components/actions/index.tsx
packages/core-browser/src/menu/next/menu-id.ts
packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts
packages/preferences/src/browser/index.less
packages/preferences/src/browser/preference-contribution.ts
packages/preferences/src/browser/preference-widgets.ts
packages/preferences/src/common/commands.ts

https://user-images.githubusercontent.com/20262815/192206568-595248e2-73f1-4339-be6f-57ebb244692b.mp4
User setting.json 配置文件支持可枚举项的下拉框选择

feat: support setting json glyphmargin edit

---

packages/extension/src/hosted/api/vscode/ext.host.api.impl.ts

upgrade vscode engine to 1.63.2

chore: upgrade vscode engine to 1.63.2

---

package.json
packages/core-common/src/node/cli.ts
packages/extension/__mocks__/initRPCProtocol.ts
packages/extension/package.json
packages/extension/src/hosted/ext.process-base.ts
packages/remote-cli/package.json
packages/remote-cli/src/index.ts
packages/remote-cli/tsconfig.json
packages/utils/__tests__/argv.test.ts
packages/utils/src/argv.ts
scripts/rebuild-native.js
scripts/run-tests.ts
tools/electron/package.json
tools/electron/scripts/rebuild-native.js
tools/electron/src/node/server.ts

Close: #1723
因为 Yargs 会导致打包困难。。。
两者的结果几乎是一样的
Remove yargs dependency

chore: remove yargs

---

packages/components/src/button/style.less
packages/components/src/dialog/styles.less
packages/components/src/icon/styles.less
packages/core-browser/src/components/actions/styles.module.less
packages/debug/src/browser/components/debug-action/index.module.less
packages/editor/src/browser/editor.module.less
packages/keymaps/src/browser/keymaps.module.less
packages/main-layout/src/browser/accordion/styles.module.less
packages/quick-open/src/browser/styles.module.less
packages/terminal-next/src/browser/component/tab.module.less
packages/theme/src/common/color-tokens/custom/icon.ts

style: improve tabs and breadcrumb icon style

---

packages/extension/src/hosted/api/vscode/ext.host.workspace.ts

chore: empty workspace notebook API implementation

---

packages/extension/src/browser/components/extension-tree-view-node.tsx
packages/extension/src/browser/components/extension-tree-view.tsx
packages/extension/src/browser/vscode/api/main.thread.treeview.ts
packages/extension/src/browser/vscode/api/tree-view/tree-view.node.defined.ts

- extension treeview 支持通过 FileDecorationProvider  注册装饰块

feat: extension treeview support decorations

---

packages/components/src/notification/index.tsx
packages/components/src/notification/notification.less
packages/components/src/notification/notification.tsx
packages/overlay/src/browser/message.service.tsx

patch  https://github.com/opensumi/core/pull/1735#pullrequestreview-1121606461.
`rc-notification` 组件的 duration 单位是 秒，这里处理有点问题
fix uncontrol notification style and duration

fix: notification style and duration

---

packages/extension/src/hosted/api/vscode/language/inlay-hints.ts

fix 修复 releaseHints 返回值错误的问题

---

packages/remote-cli/package.json

chore: update remote-cli deps

---

tools/playwright/src/tests/editor.test.ts
tools/playwright/src/text-editor.ts

test: add close all tabs test case

---

packages/collaboration/package.json

chore: update @opensumi/ide-collaboration deps to v2.20.4

---

tools/playwright/src/editor.ts
tools/playwright/src/tests/editor.test.ts
tools/playwright/src/text-editor.ts
tools/playwright/src/tree-node.ts

test: implement file tree automatic location test case

---

.github/stale.yml
.github/workflows/issue-labeled.yml
.github/workflows/pre-release.yml

chore: add issue labeled action

---

packages/file-tree-next/src/browser/services/file-tree-model.service.ts

https://user-images.githubusercontent.com/9823838/195307649-5de20730-1808-4f24-97ba-7eb014eca8f3.mp4
can copy the directory by itself on the filetree

fix: can copy the directory by itself on the filetree

---

tools/playwright/src/explorer-view.ts
tools/playwright/src/filetree-view.ts
tools/playwright/src/tests/editor.test.ts
tools/playwright/src/tests/explorer-view.test.ts

test: new file/folder from toolbar

---

packages/search/__tests__/browser/search-history.test.ts
packages/search/package.json
packages/search/src/browser/search-history.ts
packages/search/src/common/content-search.ts
packages/search/src/node/content-search.service.ts

this close: #1672
auto search value when history triggered

fix(search): arrow up key doesn't trigger search

---

packages/theme/src/common/color-tokens/custom/select.ts

fix `--kt-sekectDropdown-teamForeground` style

style: fix --kt-sekectDropdown-teamForeground style

---

packages/terminal-next/package.json
packages/terminal-next/src/browser/terminal.preference.ts
packages/terminal-next/src/browser/xterm.ts
packages/utils/src/platform.ts

feat: terminal use webgl renderer

---

packages/extension/src/browser/vscode/contributes/configuration.ts

chore: 配置项枚举值描述支持国际化

---

packages/editor/__tests__/browser/breadcrumb.test.ts
packages/editor/src/browser/breadcrumb/default.ts
packages/workspace/src/common/workspace.definition.ts

feat: 编辑器面包屑导航支持已注册的文件协议

---

packages/editor/src/browser/editor.contribution.ts

fix: setDocumentEdited only in electron

---

tools/playwright/configs/playwright.ci.config.ts
tools/playwright/src/tests/editor.test.ts

chore: add ui test retry times

---

packages/core-browser/src/components/actions/index.tsx
packages/extension/src/hosted/api/vscode/ext.host.command.ts
packages/scm/src/browser/components/scm-resource-input.module.less

https://user-images.githubusercontent.com/9823838/196595552-95b8b528-a4d2-455e-b537-7de8aa2ed98c.mp4
support smart commit with 1.69.0 git extension

fix: support smart commit with 1.69.0 git extension

---

packages/search/src/browser/search.contribution.ts
packages/search/src/common/content-search.ts

fix: 移除 search 模块不必要的依赖

---

packages/extension/__tests__/hosted/api/vscode/ext.host.decoration.test.ts

chore: fix decoration unit test

---

packages/terminal-next/src/browser/contribution/terminal.command.ts
packages/terminal-next/src/browser/contribution/terminal.menu.ts
packages/terminal-next/src/browser/contribution/terminal.view.ts
packages/terminal-next/src/browser/terminal.controller.ts
packages/terminal-next/src/common/index.ts

remove incorrect module dependencies

fix(dep): remove incorrect module dependencies

---

.github/labeler.yml
packages/editor/src/browser/workbench-editor.service.ts

close #1821.
get correct unsaved files number

fix: get correct unsaved files number

---

packages/core-browser/src/components/actions/index.tsx
packages/main-layout/src/browser/tabbar/panel.view.tsx
packages/main-layout/src/browser/tabbar/renderer.view.tsx

chore: update layout ids

---

packages/editor/src/browser/workbench-editor.service.ts

- fix: reveal range in center by default

fix: reveal range in center by default

---

configs/vscode-extensions.json
packages/core-browser/src/components/resize/resize.module.less
packages/editor/src/browser/editor.module.less
packages/main-layout/src/browser/accordion/titlebar.view.tsx
tools/electron/config/vscode-extensions.json

close #1840.
put resize handle hover line to the top

style: put resize handle hover line to the top

---

tools/playwright/src/tests/explorer-view.test.ts

test: filter files on the filetree

---

packages/addons/src/browser/connection-rtt-contribution.ts
packages/variable/src/browser/variable-resolver.contribution.ts

fix some commands i18n text
before:

chore: fix some commands i18n text

---

packages/main-layout/src/browser/accordion/accordion.service.ts

views 注册时的排序逻辑，会造成运行耗时较长，但实际上许多 view 注册时并没有提供 priority 参数，splice 操作会引起界面重新渲染，同时不必要的耗时也比较长
- 优化 appendView 的渲染性能

chore: improve append view performance

---

packages/extension/src/browser/extension.service.ts

fix: submenus error

---

packages/editor/src/browser/monaco-contrib/command/command.service.ts

fixed #1747 
- 修复 peekView 内获取到错误编辑器实例的问题

fix: 修复 peekView 内获取到错误编辑器实例的问题

---

packages/extension/src/browser/extension.service.ts

- 修复 `workspaceContains` activateEvents 不生效的问题

fix: workspace contains activate extension event

---

packages/extension/src/browser/extension-management.service.ts
packages/extension/src/common/index.ts

fix: activate extension when enable/install extension

---

packages/core-common/src/const/application.ts

https://marketplace.smartide.cn 源经常性挂，影响使用

chore: use stable extension marketplace registry

---

packages/file-search/src/node/file-search.service.ts

close #1894.
After:
improve file search results order

feat: improve file search results order

---

packages/search/src/browser/search-tree.service.ts
packages/search/src/browser/search-tree.view.tsx
packages/search/src/browser/search.module.less

close #1898.
close #1312.
After:
- always highlight search results

fix: always highlight search results

---

.github/workflows/issue-labeled.yml

chore: fix issue labeled

---

packages/extension/src/browser/vscode/contributes/snippets.ts
packages/monaco/src/browser/monaco-snippet-suggest-provider.ts
packages/monaco/src/browser/monaco.contribution.ts

close #1918 
- fix register code snippets timing

fix(snippets): register code snippets timing

---

.github/workflows/issue-labeled.yml

chore: fix issue labeled config

---

packages/workspace/src/browser/workspace-service.ts

fix: workspace dir async watch

---

packages/extension/src/browser/extension.service.ts

- fix: do not active disabled extension

fix: do not active disabled extension

---

packages/extension/src/browser/sumi/contributes/browser-views.ts

fix: browser views contribution

---

.github/workflows/deploy.yml

chore: add iconfont page deploy workflow

---

packages/editor/src/browser/monaco-contrib/tokenizer/textmate.service.ts

目前所有语言插件在注册后会立即加载 `languageConfifuration` 定义，实际上并不是所有语言在一开始都处于激活状态，甚至约 80% 的语言并不会在同一个项目内出现。但过早的加载语言定义反而会因为过多的 io 操作导致整体加载变慢。
> 在安装 70+ 个语言插件后，首屏需要加载的语言定义文件log
解决方式是按需加载语言，确切来说，当第一次加载时仅注册语言的基本定义，仅包含id、aliases、extensions、mimetype 等基本属性，让编辑器可以`认识`某个语言。而在该语言被激活(对应的文件被打开)时，才加载语言定义文件(包括基础的文法定义、配置等)。
> 按需加载的情况下，首屏仅加载两个语言定义
- refactor: lazy load language configuration

refactor: lazy load language configuration

---

packages/editor/src/browser/doc-model/editor-document-model-service.ts

- refactor: update prefered options after textModel is created

refactor: update prefered options after textmodel is created

---

packages/debug/src/browser/editor/debug-breakpoint-zone-widget.tsx
packages/debug/src/browser/editor/debug-breakpoint.module.less
packages/debug/src/browser/view/breakpoints/debug-breakpoints.service.ts
packages/debug/src/browser/view/console/debug-console.module.less

close #1968 
After:
improve debug expression input style

style: improve debug expression input style

---

packages/search/__tests__/browser/search-tree.service.test.ts
packages/search/__tests__/browser/search.service.test.ts
packages/search/src/browser/search.service.ts

- fix: do not search deleted resource

fix: do not search deleted resource

---

packages/core-browser/src/common/common.command.ts
packages/editor/src/browser/editor.contribution.ts

-  trigger editor find widget when no actived element

feat: trigger editor find widget when no actived element

---

packages/components/src/scrollbars/index.tsx
packages/editor/src/browser/tab.view.tsx

fix: optimize tabbar scroll

---

packages/core-browser/src/keyboard/keyboard-layout-service.ts
packages/core-browser/src/menu/next/renderer/ctxmenu/electron.ts
packages/monaco/src/browser/monaco.contribution.ts

fix: support electron accelerator

---

packages/monaco/src/browser/contrib/merge-editor/model/computer-diff.ts
packages/monaco/src/browser/contrib/merge-editor/model/decorations.ts
packages/monaco/src/browser/contrib/merge-editor/model/line-range.ts
packages/monaco/src/browser/contrib/merge-editor/utils.ts
packages/monaco/src/browser/contrib/merge-editor/view/editors/baseCodeEditor.ts
packages/monaco/src/browser/contrib/merge-editor/view/editors/currentCodeEditor.tsx
packages/monaco/src/browser/contrib/merge-editor/view/editors/incomingCodeEditor.tsx
packages/monaco/src/browser/contrib/merge-editor/view/editors/resultCodeEditor.tsx
packages/monaco/src/browser/contrib/merge-editor/view/merge-editor.less
packages/theme/src/common/color-tokens/editor.ts

before:
after:
实现 3 diff 的 inner changes decoration 渲染

feat: implement inner changes decoration render

---

packages/file-service/src/browser/watcher.ts
packages/preferences/src/browser/abstract-resource-preference-provider.ts

https://user-images.githubusercontent.com/9823838/202067664-ed14c513-4491-4104-93cb-c38c830eabb9.mp4
support detect configuration change from the parent directory

feat: support detect configuration change from the parent directory

---

packages/file-tree-next/src/browser/services/file-tree-model.service.ts

fix: copy files cross window

---

packages/core-browser/src/components/actions/index.tsx
packages/scm/src/browser/components/scm-resource-input.module.less

close #2008 
improve Git ActionButton disabled style

style: improve Git ActionButton disabled style

---

packages/monaco/src/browser/contrib/merge-editor/model/decorations.ts
packages/monaco/src/browser/contrib/merge-editor/model/inner-range.ts
packages/monaco/src/browser/contrib/merge-editor/model/line-range.ts
packages/monaco/src/browser/contrib/merge-editor/model/sticky-piece.ts
packages/monaco/src/browser/contrib/merge-editor/service/mapping-manager.service.ts
packages/monaco/src/browser/contrib/merge-editor/types.ts
packages/monaco/src/browser/contrib/merge-editor/utils.ts
packages/monaco/src/browser/contrib/merge-editor/view/editors/baseCodeEditor.ts
packages/monaco/src/browser/contrib/merge-editor/view/editors/currentCodeEditor.tsx
packages/monaco/src/browser/contrib/merge-editor/view/editors/incomingCodeEditor.tsx
packages/monaco/src/browser/contrib/merge-editor/view/editors/resultCodeEditor.tsx
packages/monaco/src/browser/contrib/merge-editor/view/guideline-widget.ts
packages/monaco/src/browser/contrib/merge-editor/view/merge-editor.less
packages/monaco/src/browser/contrib/merge-editor/view/stickiness-connect-manager.tsx

feat: implement dashed decorations render

---

packages/extension/src/browser/components/extension-tree-view.module.less
packages/extension/src/browser/components/extension-tree-view.tsx
packages/extension/src/hosted/api/vscode/ext.host.treeview.ts
packages/file-tree-next/src/browser/file-tree.tsx
packages/main-layout/src/browser/accordion/section.view.tsx
packages/main-layout/src/browser/accordion/styles.module.less

close #2029 
fix get references/implements by reference extension

fix: get references/implements by reference extension

---

.github/workflows/release.yml

chore: use default commitish

---

packages/main-layout/src/browser/accordion/accordion.service.ts
packages/main-layout/src/browser/quick-open-view.ts
tools/playwright/src/explorer-view.ts
tools/playwright/src/outline-view.ts
tools/playwright/src/tests/explorer-view.test.ts
tools/playwright/src/view.ts

close #2043 
支持如下两个测试案例：
add layout e2e test

test: add layout e2e test

---

packages/monaco/src/browser/contrib/merge-editor/model/decorations.ts
packages/monaco/src/browser/contrib/merge-editor/view/merge-editor.less
packages/monaco/src/browser/contrib/merge-editor/view/stickiness-connect-manager.tsx
packages/theme/src/common/color-tokens/editor.ts

同时给加了对应边框
美化 merge editor diff 区域的背景色和边框色

style: beauty merge editor diff range

---

packages/core-browser/src/menu/next/menu.contrib.interface.ts
packages/scm/src/browser/dirty-diff/dirty-diff-decorator.ts
packages/scm/src/browser/dirty-diff/dirty-diff-model.ts
packages/scm/src/browser/dirty-diff/dirty-diff-util.ts
packages/scm/src/browser/dirty-diff/dirty-diff-widget.ts
packages/scm/src/browser/dirty-diff/dirty-diff.module.less
packages/workspace-edit/src/browser/workspace-edit.service.ts

fix: dirty diff issue

---

packages/components/src/dialog/styles.less
packages/components/src/notification/notification.less
packages/components/src/notification/notification.tsx
packages/file-tree-next/src/browser/dialog/file-dialog.module.less
packages/file-tree-next/src/browser/dialog/file-dialog.view.tsx
packages/file-tree-next/src/browser/dialog/window-dialog.service.tsx
tools/playwright/package.json

close #2059 
After:
红色底色用于区分对齐情况
improve file dialog and notification style

style: improve file dialog and notification style

---

packages/components/src/scrollbars/index.tsx
packages/editor/src/browser/editor.module.less

close #2007.
同时支持 `thumbSize` 属性用于修改滚动条滑块大小
fix scroller can not reach bottom

fix: scroller can not reach bottom

---

packages/components/src/recycle-list/RecycleList.tsx
packages/debug/src/browser/debug-configuration-manager.ts
packages/debug/src/browser/debug-session-manager.ts
packages/debug/src/browser/view/frames/debug-call-stack-frame.view.tsx
packages/debug/src/browser/view/frames/debug-call-stack-session.view.tsx
packages/debug/src/browser/view/frames/debug-call-stack-thread.view.tsx

close #1942 
fix debug on multiple processes

fix: debug on multiple processes

---

packages/editor/src/browser/editor-collection.service.ts
packages/monaco/src/browser/contrib/merge-editor/merge-editor-widget.tsx
packages/monaco/src/browser/contrib/merge-editor/merge-editor.service.ts
packages/monaco/src/browser/contrib/merge-editor/view/editors/baseCodeEditor.ts

fix: merge editor options

---

configs/opentrs-extensions.json
configs/vscode-extensions.json
tools/electron/config/vscode-extensions.json

chore: update defualt theme

---

packages/monaco/src/browser/contrib/merge-editor/merge-editor.service.ts
packages/monaco/src/browser/contrib/merge-editor/view/actions-manager.ts

before:
https://user-images.githubusercontent.com/20262815/207570182-adfb6450-5b2c-427b-b4b5-48b7b02bb81d.mp4
after:
https://user-images.githubusercontent.com/20262815/207570246-f78b7b37-f78f-4229-81f4-f6d207c61a42.mp4
修复在编辑代码后 accept combination 操作会导致 applyEdits 错位的问题

fix: accept combination apply edits error

---

README-zh_CN.md
README.md

chore: update web lite sample link

---

packages/extension/src/browser/vscode/contributes/configuration.ts

- fix: register configuration timing

fix: register configuration timing

---

packages/editor/src/browser/monaco-contrib/tokenizer/textmate-tokenizer.ts
packages/editor/src/browser/monaco-contrib/tokenizer/textmate.service.ts

- fix: active embedded language on demand

fix: active embedded language on demand

---

packages/monaco/package.json

chore: update monaco editor version

---

packages/core-browser/src/common/common.command.ts
packages/file-tree-next/__tests__/browser/file-tree-model.service.test.ts
packages/file-tree-next/src/browser/file-tree-contribution.ts
packages/file-tree-next/src/browser/services/file-tree-model.service.ts

fixed #1322.
support space keybinding on filetree

feat: support space keybinding on filetree

---

scripts/rebuild-native.js
tools/electron/scripts/rebuild-native.js

fix: copy dir with recursive in rebuild-native script

---

packages/file-service/src/node/disk-file-system.provider.ts

fix: save file diff error

---

packages/core-browser/src/common/common.command.ts
packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts
packages/terminal-next/src/browser/component/tab.module.less
packages/terminal-next/src/browser/contribution/terminal.command.ts
packages/terminal-next/src/browser/contribution/terminal.keybinding.ts
packages/terminal-next/src/browser/terminal.controller.ts
packages/terminal-next/src/common/controller.ts

支持切换终端的 <code>ctrl+`</code> 快捷键，同时修复添加终端的按钮样式
support toggle terminal keybinding

feat: support toggle terminal keybinding

---

packages/editor/src/browser/preference/schema.ts

- enable editor minimap by default

feat: enable editor minimap by default

---

packages/editor/src/browser/workbench-editor.service.ts

fix: debounce editor layout

---

packages/extension/src/browser/sumi/contributes/browser-views.ts

fix: append browser views return

---

yarn.lock

chore: yarn lock

---

packages/i18n/src/common/en-US.lang.ts
packages/main-layout/src/browser/accordion/styles.module.less
packages/scm/src/browser/components/scm-resource-input.module.less

After:
close #2156 
improve button overflow style

style: improve button overflow style

---

packages/extension/src/common/index.ts

fix: first install of the extension does not work

---

packages/scm/src/browser/components/scm-provider-list.module.less
packages/scm/src/browser/components/scm-provider-list.tsx
packages/scm/src/browser/components/scm-resource-tree/index.tsx
packages/scm/src/browser/components/scm-resource-tree/scm-tree-model.service.ts
packages/scm/src/browser/components/scm-resource-tree/scm-tree-node.view.tsx
packages/scm/src/browser/components/scm-resource-tree/scm-tree.service.ts
packages/scm/src/browser/scm-model.ts
packages/scm/src/browser/scm-view-container.tsx

优化工作区模式下的 SCM 面板操作，让数据同步更及时，减少异常情况出现
https://user-images.githubusercontent.com/9823838/210753071-cf3efb69-d69d-4b7b-93ee-50a863b2cb91.mp4
improve SCM experience on the workspace project

fix: improve SCM experience on the workspace project

---

packages/debug/src/browser/view/variables/debug-variables.contribution.ts
packages/editor/__tests__/browser/editor-service.test.ts
packages/editor/__tests__/browser/editor.feature.test.ts
packages/editor/__tests__/browser/test-providers.ts
packages/editor/src/browser/diff/index.ts
packages/editor/src/browser/editor.override.ts
packages/editor/src/browser/editor.view.tsx
packages/editor/src/browser/history/index.ts
packages/editor/src/browser/merge-editor/merge-editor.contribution.ts
packages/editor/src/browser/workbench-editor.service.ts
packages/editor/src/common/editor.ts
packages/electron-basic/src/browser/welcome/contribution.ts
packages/extension-manager/src/browser/vsx-extension.contribution.ts
packages/extension/__tests__/browser/main.thread.editor.test.ts
packages/extension/src/browser/extension.contribution.ts
packages/extension/src/browser/sumi-browser/contribution/editor.ts
packages/extension/src/browser/vscode/api/main.thread.doc.ts
packages/extension/src/browser/vscode/api/main.thread.editor.ts
packages/extension/src/browser/vscode/contributes/customEditors.tsx
packages/extension/src/browser/vscode/contributes/walkthroughs.tsx
packages/file-scheme/__tests__/browser/contribution.test.ts
packages/file-scheme/src/browser/file-scheme.contribution.ts
packages/file-tree-next/src/browser/file-tree-contribution.ts
packages/keymaps/src/browser/keymaps.contribution.ts
packages/markdown/src/browser/contribution.ts
packages/preferences/src/browser/preference-contribution.ts
packages/scm/src/browser/dirty-diff/index.ts
packages/testing/src/browser/testing.contribution.ts
packages/webview/src/browser/webview.service.ts

refactor: add editor open type enum

---

packages/addons/src/browser/toolbar-customize/toolbar-customize.tsx
packages/core-browser/src/core-preferences.ts
packages/core-browser/src/preferences/preference-contribution.ts
packages/core-browser/src/preferences/preference-proxy.ts
packages/core-browser/src/preferences/preference-service.ts
packages/core-browser/src/preferences/types.ts
packages/core-common/src/preferences/preference-schema.ts
packages/editor/src/browser/monaco-contrib/tokenizer/textmate.service.ts
packages/file-tree-next/__tests__/browser/file-tree.service.test.ts
packages/file-tree-next/src/browser/file-tree.service.ts
packages/preferences/__tests__/browser/preference-service.test.ts
packages/terminal-next/__tests__/browser/mock.service.ts
packages/theme/src/browser/workbench.theme.service.ts
packages/types/manifest.json
packages/utils/src/types.ts

支持通过简单的配置项获取到合法的值，在对传入配置值有合法性要求的场景可以使用。
support get valid preference from service

feat: support get valid preference from service

---

packages/file-service/src/common/file-ext.ts

feat: add more image types

---

packages/file-tree-next/src/browser/dialog/file-dialog.module.less
packages/file-tree-next/src/browser/dialog/file-dialog.view.tsx

fixed https://github.com/opensumi/core/pull/2169#issuecomment-1377053124.
fix file dialog style

style: fix file dialog style

---

packages/core-browser/src/layout/layout-hooks.ts

fix: resizeObserver unobserve error

---

packages/file-service/src/common/file-ext.ts
packages/file-service/src/node/disk-file-system.provider.ts
packages/file-service/src/node/file-service.ts
packages/file-service/src/node/shared/file-type.ts
packages/startup/entry/web-lite/lite-module/file-provider/browser-fs-provider.ts
packages/terminal-next/__tests__/browser/inject.ts

根据 mime 判断是否为 image。
get file type by mime

feat: get file type by mime

---

packages/core-browser/src/preferences/preference-contribution.ts
packages/core-common/src/editor.ts
packages/core-common/src/json-schema.ts
packages/debug/src/browser/debug-configuration-manager.ts
packages/debug/src/common/debug-schema-updater.ts
packages/file-scheme/src/browser/file-doc.ts
packages/monaco/src/browser/schema-registry.ts
packages/output/src/browser/output-contribution.ts
packages/preferences/src/browser/preference-contribution.ts
packages/task/src/browser/task.schema.ts
packages/utils/__tests__/objects.test.ts
packages/utils/src/objects.ts

close: #1385 
settings.json will be considered as `jsonc` language

fix: settings.json should be jsonc

---

packages/markers/src/browser/markers-tree.view.tsx
packages/markers/src/browser/tree/marker-node.tsx

fix the marker outer area click error

fix: fix the marker outer area click error

---

packages/extension-manager/src/browser/extension/extension.module.less
packages/extension-manager/src/browser/extension/index.tsx
packages/extension-manager/src/browser/vsx-extension.module.less
packages/types/manifest.json

Before:
After:
improve extension manager style

style: improve extension manager style

---

packages/components/src/recycle-tree/basic/styles.less
packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts
packages/preferences/src/browser/preference-contribution.ts
packages/preferences/src/browser/preference-settings.service.ts
packages/preferences/src/browser/preferences.module.less
packages/theme/src/common/color-tokens/input.ts

1. fix style issue on light theme
before:
after:
add missing i18n of some preference
fix style issue on light theme
fix some section do not show

fix: fix some preference panel issues

---

.github/workflows/e2e.yml
packages/debug/src/browser/view/breakpoints/debug-breakpoints.module.less
packages/main-layout/src/browser/accordion/styles.module.less

Before:
After:
fix the toggle icon style on the panel header

style: fix the toggle icon style on the panel header

---

packages/core-browser/src/react-hooks/injectable-hooks.tsx
packages/search/src/browser/index.ts
packages/search/src/browser/search.service.ts

fix: dispose error

---

packages/extension/src/browser/vscode/api/main.thread.terminal.ts
packages/terminal-next/src/browser/terminal.controller.ts
packages/terminal-next/src/common/pty.ts
packages/types/vscode/typings/vscode.d.ts

this close: https://github.com/opensumi/core/issues/1406
add empty implementation for `Terminal Location API`

feat: add empty implementation for `Terminal Location` API

---

.github/workflows/release.yml
packages/file-service/src/node/file-service.ts
packages/types/manifest.json
scripts/build.ts

commit `manifest.json` changes before publishing the patch version.

chore: update release workflow

---

packages/collaboration/src/browser/collaboration.contribution.ts

fix: remove collaboration preference code

---

CHANGELOG.md
packages/editor/src/browser/types.ts
packages/editor/src/common/editor.ts

update Changelogs for v2.22.0
update editor open types

chore: update editor open types

---

packages/core-common/src/types/file.ts
packages/file-service/src/node/disk-file-system.provider.ts
packages/file-tree-next/src/browser/file-tree.service.ts
packages/file-tree-next/src/browser/services/file-tree-api.service.ts

fixed #2227 .
compact folder on symbol link folders

fix: compact folder on symbol link folders

---

packages/core-browser/src/components/layout/layout.ts
packages/preferences/src/browser/preference-contribution.ts
packages/preferences/src/browser/preference-settings.service.ts
packages/preferences/src/browser/preferenceItem.view.tsx
packages/preferences/src/browser/preferences.view.tsx

close: #2224 
Fix `Extension` button occasionally does not show in the preference panel.

fix(preference): `Extension` button occasionally does not show

---

packages/addons/src/browser/file-search.contribution.ts
packages/editor/src/browser/quick-open/workspace-symbol-quickopen.ts
packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts
packages/quick-open/src/browser/styles.module.less

样式优先级发生了变化，某处的修改导致 kt-icon 优先级被提升，这里本身样式上的约束效果较弱，提升一下 CSS 权重即可
fixed #2233 
improve quick open action buttons style

style: improve quick open action buttons style

---

packages/collaboration/src/browser/collaboration.contribution.ts
packages/collaboration/src/browser/collaboration.service.ts
packages/collaboration/src/common/types.ts

pick 这两个 pr https://github.com/opensumi/core/pull/2221 和 https://github.com/opensumi/core/pull/2207
修复协同编辑模块的初始化时序问题以及删除对用户配置项的影响

chore: pick 2.21 collaboration module

---

README-zh_CN.md
README.md

chore: add E2E test badge

---

packages/terminal-next/src/browser/component/terminal.view.tsx

Resolve issue #2244 
wrap input placeholder inside localize

fix: localize terminal find placeholder

---

packages/editor/src/browser/editor-collection.service.ts
packages/editor/src/browser/workbench-editor.service.ts

protected diff editor doc model ref

chore: protected diff editor doc model ref

---

packages/electron-basic/src/browser/welcome/welcome.tsx
packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts

fixed #2250 .
detect path stat before open workspace

fix: detect path stat before open workspace

---

CHANGELOG.md

docs: nsfw break change

---

.github/workflows/e2e.yml
.github/workflows/release.yml
packages/types/manifest.json

chore: fix manifest generate

---

packages/editor/src/browser/workbench-editor.service.ts

fix: 修复打开大文件时编辑器加载慢的问题

---

packages/comments/src/browser/tree/tree-model.service.ts

fix: comments threads event listener

---

packages/core-browser/src/monaco/merge-editor-widget.ts

- 修复 1.69 版本 git 插件下 3-way-merge 无法加载的问题

fix: merge editor argument

---

package.json

remove engines required on package.json

chore: remove engines required on package.json

---

NOTICE.md
README-zh_CN.md
README.md

chore: update license notice

---

tools/playwright/src/tests/debug.test.ts

修复 JavaScript Debug Terminal 调试失败后重试逻辑无效的问题，提升 E2E 测试成功率
improve terminal debug test

chore: improve terminal debug test

---

packages/collaboration/__tests__/browser/collaboration-contribution.test.ts
packages/collaboration/__tests__/browser/collaboration-service.test.ts

https://github.com/opensumi/core/pull/2260
* add test case

tests: add collaboration module test case

---

packages/editor/src/common/mocks/workbench-editor.service.ts
packages/opened-editor/__tests__/browser/opened-editor-model.service.test.ts
packages/opened-editor/__tests__/browser/opened-editor.service.test.ts
packages/opened-editor/src/browser/opened-editor-node.define.ts
packages/opened-editor/src/browser/opened-editor-node.module.less
packages/opened-editor/src/browser/opened-editor-node.tsx
packages/opened-editor/src/browser/services/opened-editor-model.service.ts
packages/opened-editor/src/browser/services/opened-editor-model.ts
packages/opened-editor/src/browser/services/opened-editor-tree.service.ts
tools/playwright/src/explorer-view.ts

close #2313.
sync file dirty status after spliting files

fix: sync file dirty status after spliting files

---

packages/components/src/recycle-tree/tree/TreeNode.ts
packages/scm/src/browser/components/scm-resource-tree/index.tsx
packages/scm/src/browser/components/scm-resource-tree/scm-tree-model.service.ts
packages/scm/src/browser/components/scm-resource-tree/scm-tree-model.ts
packages/scm/src/browser/components/scm-resource-tree/scm-tree-node.ts
packages/scm/src/browser/components/scm-resource-tree/scm-tree.service.ts

Before:
After:
improve SCM Treeview style and UX

fix: improve SCM Treeview style and UX

---

packages/core-browser/src/react-providers/config-provider.tsx
packages/extension/src/browser/extension-node.service.ts
packages/extension/src/common/extension.ts
packages/extension/src/node/extension.service.ts

新增 inspectExtensionHost config 配置项，允许设置插件进程 inspect 时的 host 地址

feat: support inspectExtensionHost config

---

packages/collaboration/src/browser/collaboration.service.ts
packages/collaboration/src/browser/color.ts

close: #2318 
更改默认配置色，避免白色主题字体不清

fix(collaboration): change default color

---

tools/electron/build/webpack.extension-host.config.js
tools/electron/build/webpack.main.config.js
tools/electron/build/webpack.node.config.js
tools/electron/build/webpack.webview.config.js
tools/electron/yarn.lock

chore: add external module nsfw for electron

---

packages/editor/src/browser/types.ts

原有的注释文案不太容易理解且会在编译后被移除
update render mode comment

chore: update render mode comment

---

packages/extension/src/node/extension.host.manager.ts
packages/extension/src/node/extension.service.client.ts

Revert "chore: use `SIGKILL` signal kill extension process"

---

packages/search/src/browser/tree/search-node.tsx
packages/search/src/browser/tree/tree-node.defined.ts

fixed https://github.com/opensumi/core/issues/2325
修复搜索面板highlight展示问题

fix: highlight range of search result is wrong

---

packages/components/src/recycle-tree/tree/TreeNode.ts
packages/debug/src/browser/tree/debug-tree-node.define.ts

修复 https://github.com/opensumi/core/pull/2324 引入的部分逻辑判断问题
fix adding changes on SCM with the tree model

fix: adding changes on SCM with the tree model

---

packages/file-tree-next/src/browser/file-tree.service.ts
packages/file-tree-next/src/browser/services/file-tree-api.service.ts
packages/file-tree-next/src/browser/services/file-tree-dnd.service.ts
packages/file-tree-next/src/browser/services/file-tree-model.service.ts
packages/file-tree-next/src/common/index.ts

fixed #2378.
fix show files on symbol link folders

fix: show files on symbol link folders

---

packages/extension/src/node/extension.service.ts

Remove unused value in extension.service.ts
Remove unused value in extension.service.ts

chore: remove unused value in extension.service.ts

---

packages/core-common/src/reference.ts
packages/extension/src/hosted/api/vscode/doc/doc-manager.host.ts

close #2367.
相关 #2123，解决不规范 URL 导致的 Document 实例无法正常获取到的问题。
get the correct document instance from bookmarks url

fix: get the correct document instance from bookmarks url

---

packages/core-browser/src/style/codicons/codicon-animations.css
packages/core-browser/src/utils/label.tsx
packages/markers/src/browser/markers-contribution.ts
packages/status-bar/src/browser/status-bar-item.view.tsx
packages/status-bar/src/browser/status-bar.module.less

fix #1977
feat: statusbar pophover support icon

feat: statusbar pophover support icon

---

packages/extension/src/browser/vscode/contributes/localization.ts

由于 localizations 贡献点的 contribute 被提前 resolve 了
导致其插件的 nls 翻译文件还未加载完成就开始了 LifeCyclePhase.Starting 生命周期的加载。
像 SCM 面板中的菜单是通过 commands 贡献点注册上去的，文案翻译也是在这里开始，但此时 localizations 贡献点还在加载当中，导致找不到 i18n 文案
修复后:
修复 localizations contribution 生命周期的问题

fix: localization lifecycle

---

packages/file-service/src/node/file-service-watcher.ts

关联 issues：https://github.com/opensumi/core/issues/2305
修复多 client 的情况下文件监听系统不生效的情况

fix: multiple client file watcher

---

tools/playwright/src/scm-view.ts
tools/playwright/src/source-control-view.ts
tools/playwright/src/tests/scm.test.ts

补充 scm list view mode 的 e2e 测试用例

test: scm list view mode e2e

---

.vscode/launch.json
packages/core-browser/src/common/container-id.ts
packages/debug/src/browser/view/console/debug-console-session.ts
packages/debug/src/browser/view/console/debug-console-tree.model.service.ts
packages/debug/src/browser/view/console/debug-console.service.ts
packages/debug/src/browser/view/console/debug-console.view.tsx
packages/debug/src/common/debug-console.ts
packages/extension/src/browser/vscode/api/main.thread.debug.ts
packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts
tools/playwright/src/debug-console-view.ts
tools/playwright/src/tests/debug.test.ts
tools/playwright/src/tests/workspaces/debug/.sumi/launch.json

修复 DebugConsole 面板右键菜单不可用问题
进一步完善 https://github.com/opensumi/core/pull/469 的修改，对齐 DebugConsole 输出样式，追加了针对 DebugConsole 右键菜单功能的 E2E 测试
fix debugConsole context menus excute

fix: debugConsole context menus excute

---

tools/cli-engine/package.json
yarn.lock

chore: remove node-notifier from cli-engine

---

README-zh_CN.md

chore: update community information

---

packages/search/src/browser/search.view.tsx

修复搜索无结果时，无结果页面不展示的BUG。
- search no result not display
- fix: search no result not display

fix: search no result not display

---

configs/ts/references/tsconfig.cli-engine.json
configs/ts/tsconfig.build.json

close https://github.com/opensumi/cli/issues/6.
build cli-engine before publish

chore: build cli-engine before publish

---

tools/cli-engine/package.json

chore: update cli-engine versison

---

.github/workflows/pr-code-review.yml

ci: add secrets check

---

packages/output/src/browser/output-contribution.ts

fix: output clear icon lag renderer

---

packages/extension/src/browser/extension.service.ts
packages/file-service/src/node/file-service-watcher.ts

close #2442.
fix file watcher path error on Windows

fix: file watcher path error on Windows

---

packages/core-electron-main/src/bootstrap/services/menu/index.ts
packages/file-tree-next/src/browser/file-tree-contribution.ts
packages/scm/src/browser/components/scm-resource-tree/scm-tree-model.service.ts
packages/startup/entry/web/app.tsx
tools/electron/src/main/index.ts

close #2359.
临时处理，关闭 devtools 开关（实际上本身也应该是关闭的）
fix electron menus will be called more than once

fix: electron menus will be called more than once

---

.github/workflows/pr-code-review.yml

ci: pr workflow check

---

.github/workflows/pr-code-review.yml

ci: fix pull request workflow by adding write permission check

---

CHANGELOG.md

chore: add v2.23.0 changelogs

---

.github/workflows/ci.yml
packages/extension-storage/src/browser/storage-path.ts
packages/extension-storage/src/browser/storage.service.ts
packages/extension-storage/src/browser/storage.ts
packages/extension-storage/src/common/storage-path.ts
packages/extension-storage/src/common/storage.ts
packages/extension/__tests__/hosted/api/vscode/ext.host.extensions.test.ts
packages/extension/__tests__/hosted/api/vscode/ext.host.storage.test.ts
packages/extension/src/browser/vscode/api/main.thread.workspace.ts
packages/extension/src/common/vscode/storage.ts
packages/extension/src/hosted/api/vscode/ext.host.extensions.ts
packages/extension/src/hosted/api/vscode/ext.host.storage.ts

close: #2435 
Append the extension id to the global storage path that will be used by the extension process

feat: extension host get path with extensionId

---

packages/keymaps/src/browser/keymaps.contribution.ts
packages/preferences/src/browser/preference-contribution.ts

fix: quickopen panel display correct localize

---

packages/core-browser/src/common/common.command.ts
packages/core-common/src/command.ts
packages/core-common/src/localize.ts
packages/editor/src/browser/monaco-contrib/command/command.service.ts
packages/electron-basic/src/browser/index.ts
packages/extension/__tests__/browser/extension-service/extension.service.test.ts
packages/extension/src/browser/vscode/contributes/commands.ts
packages/extension/src/common/extension.ts
packages/main-layout/src/browser/tabbar/tabbar.service.ts
packages/monaco/__tests__/browser/monaco-command.test.ts
packages/quick-open/src/browser/quick-open.command.service.ts
packages/theme/src/browser/theme.contribution.ts

close: #2035
localized command show alias

fix: localized command show alias

---

packages/editor/src/browser/editor-collection.service.ts

fix: output should not be editable

---

packages/core-browser/src/components/resize/resize.module.less

style: reset resize handle z-index

---

packages/theme/__tests__/browser/theme.service.test.ts
packages/theme/src/browser/index.ts
packages/theme/src/browser/theme.contribution.ts
packages/theme/src/browser/workbench.theme.service.ts
packages/theme/src/common/index.ts
packages/theme/src/common/provider.ts
packages/toolbar/src/browser/types.ts

close: #1736
add onWillApplyTheme provider

feat: add onWillApplyTheme provider

---

packages/scm/src/browser/components/scm-resource-tree/scm-tree-model.service.ts

修复scm面板文件夹右键点击报错
close #2255 
fix(scm): fix right click error on folder in scm panel

fix(scm): fix right click error on folder in scm panel

---

.github/workflows/auto-labeler.yml
.github/workflows/deploy.yml
.github/workflows/issue-labeled.yml
.github/workflows/pre-release.yml
.github/workflows/release-check.yml
.github/workflows/release.yml

把 github-actions[bot] 换成 opensumi[bot]
这里的 token 也是在 workflow 运行完会销毁。

ci: using @opensumi[bot]

---

packages/extension/src/hosted/api/vscode/env/workerEnvApiFactory.ts
packages/search/src/browser/search.view.tsx

close: #2514 
修复搜索面板打开修改排除项报错的问题

fix: 更改搜索打开排出设置回调函数

---

.github/ISSUE_TEMPLATE/-------bug-report--.md

原有的截图及问题描述有重复表达的问题
update bug-report issue template

chore: update bug-report issue template

---

packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts
packages/main-layout/src/browser/accordion/accordion.service.ts
packages/main-layout/src/browser/accordion/section.view.tsx
packages/main-layout/src/browser/accordion/styles.module.less
packages/opened-editor/__tests__/browser/opened-editor-model.service.test.ts
packages/opened-editor/__tests__/browser/opened-editor.service.test.ts
packages/opened-editor/src/browser/opened-editor.contribution.ts
packages/opened-editor/src/browser/services/opened-editor-model.service.ts
packages/opened-editor/src/common/index.ts
packages/opened-editor/src/index.ts

close: #2314
after:
- support show unsaved files in opened editor view

feat: support show unsaved files in opened editor view

---

packages/main-layout/src/browser/accordion/section.view.tsx
packages/main-layout/src/browser/accordion/styles.module.less

fixed https://github.com/opensumi/core/issues/2540
修复 reference 面板文字超长兼容问题

fix: reference pannel  style error

---

packages/preferences/src/browser/preference-contribution.ts
packages/preferences/src/browser/preferences.view.tsx
packages/terminal-next/src/browser/contribution/terminal.command.ts

close: #2656
feat: 优化 terminal 更多设置命令

feat: update command open terminal setting

---

packages/i18n/src/common/zh-CN.lang.ts
packages/preferences/src/browser/preference-settings.service.ts

add missing editor related preferences

fix: add missing editor related preferences

---

packages/comments/src/browser/comments-body.tsx
packages/components/package.json
packages/components/src/markdown/index.tsx
packages/components/src/utils/marked.ts
packages/core-browser/src/markdown/index.tsx
yarn.lock

Revert "fix: remove the marked.js warning about sanitize and add sanitizer"

---

packages/debug/src/browser/view/breakpoints/debug-breakpoints.module.less
packages/debug/src/browser/view/breakpoints/debug-breakpoints.view.tsx

improve breakpoint panel style

feat: improve breakpoint style

---

packages/editor/src/browser/editor.module.less
packages/editor/src/browser/tab.view.tsx

bugfix: https://github.com/opensumi/core/issues/2805
update: 编辑器选中菜单时样式调整

fix: update the style of the currently selected file menu

---

packages/terminal-next/src/browser/component/resize.module.less

close: https://github.com/opensumi/core/issues/2820
修改前：
修改后：
fix: 给终端面板增加top间距

fix: terminal adds top whitespace

---

packages/extension/__tests__/hosted/__mocks__/extensionLogger.ts
packages/extension/__tests__/hosted/api/sumi/ext.host.toolbar.test.ts
packages/extension/src/browser/extension-worker.service.ts
packages/extension/src/browser/extension.service.ts
packages/extension/src/browser/sumi/contributes/toolbar.ts
packages/extension/src/hosted/api/sumi/ext.host.api.impl.ts
packages/extension/src/hosted/api/sumi/ext.host.toolbar.ts
packages/extension/src/hosted/ext.host.ts
packages/extension/src/hosted/ext.process-base.ts
packages/extension/src/hosted/extension-log2.ts

refactor(ext): improve code and log message

---

packages/components/src/recycle-tree/RecycleTree.tsx

- [-] 🎉 New Features 
文件树搜索时，文件夹支持展开

文件树搜索时，文件夹支持展开

---

packages/ai-native/src/browser/ai-chat.contribution.ts
packages/ai-native/src/browser/ai-editor.contribution.ts
packages/ai-native/src/browser/components/ChatInput.tsx
packages/ai-native/src/common/index.ts
packages/core-browser/src/core-preferences.ts
packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts

现在一选中代码就显示 inlinechat 的交互过于频繁，新增开关配置项去控制这个行为

feat: support inline chat auto visiable preference

---

packages/ai-native/src/browser/ai-chat.contribution.ts
packages/ai-native/src/browser/ai-chat.service.ts
packages/ai-native/src/browser/ai-editor.contribution.ts
packages/ai-native/src/browser/override/ai-editor-tab.service.tsx
packages/ai-native/src/common/command.ts

新增 cmd + i 快捷键用于显示 inline chat

feat: support keybinding inline chat

---

packages/ai-native/src/browser/components/Icon.tsx
packages/ai-native/src/browser/override/layout/menu-bar/menu-bar.view.tsx
packages/core-browser/src/components/actions/index.tsx

固定左上角的弹出菜单的位置，同时重构左上角菜单组件的使用方式

refactor: ai menubar render & ctx menu

---

packages/ai-native/src/browser/override/ai-menu.service.tsx
packages/ai-native/src/browser/override/layout/menu-bar/menu-bar.contribution.tsx
packages/ai-native/src/browser/override/layout/menu-bar/menu-bar.view.tsx
packages/ai-native/src/browser/override/override.module.less
packages/core-browser/src/common/common.contribution.ts
packages/core-browser/src/components/actions/index.tsx
packages/core-browser/src/menu/next/renderer/ctxmenu/browser.ts
packages/menu-bar/src/browser/menu-bar.store.ts
packages/overlay/src/browser/ctx-menu/ctx-menu.service.ts
packages/overlay/src/browser/ctx-menu/ctx-menu.view.tsx

feat: support custom ctx menuitem render

---

packages/ai-native/package.json
packages/ai-native/src/browser/ai-chat.service.ts
packages/ai-native/src/browser/ai-chat.view.tsx
packages/ai-native/src/browser/components/ChatEditor.tsx
packages/ai-native/src/browser/components/StreamMsg.tsx
packages/ai-native/src/browser/components/Thinking.tsx
packages/ai-native/src/browser/components/components.module.less
packages/ai-native/src/browser/index.ts
packages/ai-native/src/browser/model/msg-stream-manager.ts
packages/ai-native/src/browser/override/theme/default-theme.ts
packages/ai-native/src/common/index.ts
packages/ai-native/src/node/index.ts
yarn.lock

feat: support chat streaming rendering

---

packages/ai-native/src/browser/inline-chat-widget/inline-chat-controller.tsx

inline chat loading 效果新增 hover 提示。error 错误提示改用 message 组件

chore: improve inline chat loading popover

---

packages/ai-native/src/browser/ai-editor.contribution.ts
packages/ai-native/src/browser/inline-completions/completeProvider.ts
packages/ai-native/src/browser/inline-completions/service/ai-completions.service.ts
packages/ai-native/src/common/index.ts

inline completion 新增 status bar 状态显示，同时优化补全效果

chore: support inline completion status bar

---

packages/ai-native/src/browser/ai-editor.contribution.ts
packages/ai-native/src/browser/inline-chat-widget/inline-chat.module.less
packages/ai-native/src/browser/inline-completions/completeProvider.ts
packages/ai-native/src/browser/override/layout/menu-bar/menu-bar.view.tsx
packages/ai-native/src/browser/override/layout/override.less
packages/ai-native/src/browser/override/layout/tabbar.view.tsx
packages/ai-native/src/browser/override/override.module.less
packages/ai-native/src/browser/override/theme/default-theme.ts
packages/components/src/scrollbars/styles.less
packages/extension/src/browser/sumi/contributes/browser-views.ts

style: improve left view & editor tab

---

packages/ai-native/src/browser/ai-editor.contribution.ts
packages/ai-native/src/browser/inline-chat-widget/inline-content-widget.tsx
packages/ai-native/src/browser/override/override.module.less

fix: inline chat editor mouseup

---

packages/markers/src/browser/tree/tree-node.module.less

fix [#3165](https://github.com/opensumi/core/issues/3165)
fix: 问题面板标题文本溢出省略

fix: omit display long title in markers

---

packages/components/src/input/ValidateInput.tsx
packages/core-electron-main/src/bootstrap/services/ui.ts
packages/debug/src/browser/view/console/debug-console.view.tsx
packages/extension/src/browser/sumi/contributes/scm.ts
packages/scm/src/common/scm.service.ts
packages/theme/src/common/color-tokens/custom/button.ts

style: fix eslint

---

scripts/build.ts

build: exit build if tsc error

---

packages/ai-native/src/browser/ai-chat.module.less
packages/ai-native/src/browser/ai-chat.view.tsx
packages/ai-native/src/browser/components/components.module.less
packages/ai-native/src/browser/components/lineVertical.tsx
packages/ai-native/src/browser/inline-chat-widget/inline-chat-controller.tsx
packages/ai-native/src/browser/override/layout/layout.module.less
packages/ai-native/src/browser/override/layout/menu-bar/menu-bar.module.less
packages/ai-native/src/browser/override/layout/override.less
packages/ai-native/src/browser/override/override.module.less
packages/ai-native/src/browser/override/theme/default-theme.ts
packages/terminal-next/src/browser/component/tab.item.tsx
packages/theme/src/common/color-tokens/ai-native.ts

fix: update dark style

---

packages/ai-native/src/browser/ai-chat.view.tsx
packages/ai-native/src/browser/components/ChatEditor.tsx
packages/core-browser/src/ai-native/reporter.ts

feat: report chat editor operate

---

packages/ai-native/src/browser/types.ts

fix: ai run components props

---

packages/ai-native/src/browser/chat-agent.view.service.ts
packages/ai-native/src/browser/chat-model.ts
packages/ai-native/src/browser/components/ChatReply.tsx
packages/ai-native/src/browser/index.ts
packages/ai-native/src/browser/types.ts
packages/ai-native/src/common/index.ts
packages/extension/src/browser/sumi-browser/contribution/chat.ts
packages/extension/src/browser/sumi-browser/contribution/index.ts
packages/extension/src/browser/sumi-browser/types.ts
packages/extension/src/browser/sumi/contributes/browser-views.ts
packages/extension/src/browser/sumi/main.thread.chat-agents.ts
packages/extension/src/common/sumi/chat-agents.ts
packages/extension/src/hosted/api/sumi/ext.host.chat.impl.ts
packages/types/sumi.d.ts
typings/sumi/index.d.ts

support custom chat response component in extension
support chat view in contributions

feat: support custom chat component

---

nixpacks.toml
railway.toml

chore: update railway config

---

packages/core-browser/package.json
yarn.lock

chore: update vscode-codicons version

---

packages/ai-native/src/browser/components/Thinking.tsx

fix: typeof error

---

packages/ai-native/src/browser/components/components.module.less

fix: markdown list style

---

packages/ai-native/src/browser/index.ts
packages/ai-native/src/browser/merge-conflict/cacheConflicts.ts
packages/ai-native/src/browser/merge-conflict/index.ts
packages/ai-native/src/browser/merge-conflict/types.ts
packages/core-common/src/types/extension.ts
packages/editor/src/browser/editor.module.less
packages/editor/src/browser/merge-editor/MergeEditorFloatComponents.tsx
packages/extension/src/browser/extension.service.ts
packages/monaco/src/browser/contrib/merge-editor/view/merge-editor.module.less

- support ai resolve conflicts in merge conflict

feat: merge contlict ai resolve

---

packages/core-browser/src/common/common.command.ts
packages/editor/src/browser/editor.contribution.ts
packages/editor/src/browser/merge-editor/MergeEditorFloatComponents.tsx
packages/editor/src/browser/merge-editor/merge-editor.provider.ts
packages/monaco/src/browser/contrib/merge-editor/merge-editor-widget.tsx
packages/monaco/src/browser/contrib/merge-editor/merge-editor.service.ts
packages/monaco/src/browser/contrib/merge-editor/model/line-range.ts
packages/monaco/src/browser/contrib/merge-editor/types.ts
packages/monaco/src/browser/contrib/merge-editor/view/actions-manager.ts
packages/monaco/src/browser/contrib/merge-editor/view/editors/resultCodeEditor.ts
packages/monaco/src/browser/contrib/merge-editor/view/grid.tsx
packages/monaco/src/browser/contrib/merge-editor/view/mini-map.tsx
packages/monaco/src/browser/contrib/merge-editor/view/stickiness-connect-manager.tsx
packages/monaco/src/browser/contrib/merge-editor/widget/resolve-result-widget.tsx
packages/monaco/src/browser/index.ts

修复 3-way 模式下 format 格式化引起的 range 错位问题

fix: 3-way format provider

---

packages/components/src/dialog/index.tsx
packages/components/src/dialog/styles.less
packages/core-browser/src/components/ai-native/inline-chat/result.tsx
packages/monaco/src/browser/contrib/merge-editor/merge-editor.service.ts
packages/monaco/src/browser/contrib/merge-editor/model/line-range.ts
packages/monaco/src/browser/contrib/merge-editor/view/actions-manager.ts
packages/monaco/src/browser/contrib/merge-editor/view/editors/resultCodeEditor.ts
packages/monaco/src/browser/contrib/merge-editor/view/grid.tsx
packages/monaco/src/browser/contrib/merge-editor/view/merge-editor.module.less
packages/monaco/src/browser/contrib/merge-editor/widget/resolve-result-widget.tsx
packages/monaco/src/browser/contrib/merge-editor/widget/stop-widget.tsx

fix: 3-way merge-range error for range

---

packages/ai-native/src/browser/merge-conflict/cache-conflicts.ts
packages/ai-native/src/browser/merge-conflict/index.ts
packages/ai-native/src/browser/merge-conflict/override-resolve-result-widget.tsx
packages/editor/src/browser/merge-editor/MergeEditorFloatComponents.tsx
packages/monaco/src/browser/contrib/merge-editor/view/grid.tsx
packages/monaco/src/browser/contrib/merge-editor/view/merge-editor.module.less

fix: ai merge conflict 

---

packages/ai-native/src/browser/merge-conflict/index.ts
packages/ai-native/src/browser/merge-conflict/override-resolve-result-widget.tsx
packages/core-browser/src/components/ai-native/inline-chat/result.tsx
packages/monaco/src/browser/contrib/merge-editor/widget/resolve-result-widget.tsx

fix: ai merge conflict fix

---

packages/ai-native/src/browser/ai-chat.service.ts
packages/ai-native/src/browser/ai-chat.view.tsx
packages/ai-native/src/browser/ai-core.contribution.ts
packages/ai-native/src/browser/ai-reporter.ts
packages/ai-native/src/browser/index.ts
packages/ai-native/src/browser/inline-completions/completeProvider.ts
packages/ai-native/src/browser/run/run.service.ts
packages/ai-native/src/common/index.ts
packages/core-browser/src/ai-native/conflict-report.service.ts
packages/core-browser/src/ai-native/index.ts
packages/core-browser/src/ai-native/reporter.ts
packages/editor/src/browser/workbench-editor.service.ts
packages/monaco/src/browser/contrib/merge-editor/merge-editor-widget.tsx
packages/monaco/src/browser/contrib/merge-editor/merge-editor.service.ts
packages/monaco/src/browser/contrib/merge-editor/types.ts
packages/monaco/src/browser/contrib/merge-editor/view/actions-manager.ts
packages/monaco/src/browser/contrib/merge-editor/view/editors/baseCodeEditor.ts
packages/monaco/src/browser/contrib/merge-editor/view/editors/currentCodeEditor.ts
packages/monaco/src/browser/contrib/merge-editor/view/editors/incomingCodeEditor.ts
packages/monaco/src/browser/contrib/merge-editor/view/editors/resultCodeEditor.ts

feat: support 3-way report

---

packages/ai-native/src/browser/ai-chat.module.less
packages/ai-native/src/browser/ai-chat.view.tsx
packages/ai-native/src/browser/chat-agent.service.ts
packages/ai-native/src/browser/chat-agent.view.service.ts
packages/ai-native/src/browser/components/ChatReply.tsx
packages/ai-native/src/browser/components/Thinking.tsx
packages/ai-native/src/browser/types.ts
packages/ai-native/src/common/index.ts
packages/extension/src/browser/sumi-browser/contribution/chat.ts
packages/extension/src/browser/sumi/main.thread.chat-agents.ts
packages/extension/src/common/sumi/chat-agents.ts
packages/extension/src/hosted/api/sumi/ext.host.chat.impl.ts
packages/types/sumi.d.ts

feat: support send message in agent directly

---

packages/ai-native/src/browser/merge-conflict/cache-conflicts.ts
packages/ai-native/src/browser/merge-conflict/index.ts
packages/ai-native/src/browser/merge-conflict/override-resolve-result-widget.tsx
packages/core-browser/src/ai-native/conflict-report.service.ts
packages/editor/src/browser/editor.module.less
packages/monaco/src/browser/ai-native/content-widget/index.tsx
packages/monaco/src/browser/contrib/merge-editor/model/line-range.ts
packages/monaco/src/browser/contrib/merge-editor/widget/resolve-result-widget.tsx

- fix: 修复数据返回内容偏移
- fix: 修复撤销恢复
- feat: 支持 AI conflict report

fix: ai native merge conflict

---

packages/ai-native/src/browser/override/layout/layout.module.less
packages/ai-native/src/browser/override/override.module.less
packages/ai-native/src/browser/override/theme/default-theme.ts
packages/ai-native/src/browser/override/theme/light-theme.ts

fix: update style by light theme

---

packages/ai-native/src/browser/ai-reporter.ts
packages/ai-native/src/browser/merge-conflict/index.ts
packages/core-browser/src/ai-native/conflict-report.service.ts
packages/core-browser/src/ai-native/reporter.ts
packages/monaco/src/browser/contrib/merge-editor/merge-editor-widget.tsx
packages/monaco/src/browser/contrib/merge-editor/merge-editor.service.ts
packages/monaco/src/browser/contrib/merge-editor/types.ts
packages/monaco/src/browser/contrib/merge-editor/view/editors/baseCodeEditor.ts
packages/monaco/src/browser/contrib/merge-editor/view/editors/resultCodeEditor.ts
packages/monaco/src/browser/contrib/merge-editor/view/merge-editor.module.less
packages/monaco/src/browser/contrib/merge-editor/widget/resolve-result-widget.tsx

fix: resolve conflict report

---

packages/core-browser/src/components/layout/split-panel.service.ts
packages/core-browser/src/components/layout/split-panel.tsx
packages/main-layout/src/browser/accordion/accordion.service.ts

fix: improve split panel initialize

---

packages/ai-native/src/browser/ai-chat.view.tsx

每次全量更新 quesions 数据，避免扩展卸载再安装重复渲染的问题

fix: update sample questions when extension dispose

---

packages/ai-native/src/browser/components/ChatReply.tsx
packages/ai-native/src/browser/components/components.module.less

optimize chat file tree css style

fix: optimize chat tree style

---

packages/ai-native/src/browser/override/layout/menu-bar/menu-bar.view.tsx

feat: hide run component

---

packages/ai-native/src/browser/ai-chat.service.ts

fix: only explain input message

---

packages/ai-native/src/browser/merge-conflict/cache-conflicts.ts
packages/ai-native/src/browser/merge-conflict/index.ts

- fix merge conflict report
- fix prompt missing

fix: merge conflict prompt

---

packages/core-browser/src/components/layout/default-layout.tsx
packages/core-browser/src/react-providers/slot.tsx
packages/startup/entry/web/layout.tsx

弃用 slot render 的 background color

chore: deprecated slot background color

---

packages/monaco/src/browser/contrib/merge-editor/merge-editor-widget.tsx

由于 3way 模式中 result 视图打开的是 git 协议的文件，而在 git 插件里 git 协议的文件是只读的，导致在执行 save 事件的时候右下角提示 Method not implemented。尤其是开启了自动保存之后，导致频繁报错。

fix: 3way merge result model save error

---

packages/ai-native/src/browser/merge-conflict/index.ts
packages/monaco/src/browser/contrib/merge-editor/view/merge-editor.module.less

- add decorations when resolved conflict

feat: add resolved decoration

---

configs/ts/tsconfig.base.json
package.json
packages/ai-native/src/browser/ai-core.contribution.ts
packages/ai-native/src/browser/inline-chat-widget/inline-chat-controller.tsx
packages/ai-native/src/browser/inline-chat-widget/inline-chat.feature.registry.ts
packages/ai-native/src/browser/override/layout/tabbar.view.tsx
packages/ai-native/src/browser/types.ts
packages/components/src/popover/index.tsx
packages/core-browser/src/ai-native/ai-config.service.ts
packages/core-browser/src/components/ai-native/ai-action/index.module.less
packages/core-browser/src/components/ai-native/ai-action/index.tsx
packages/core-browser/src/components/ai-native/index.ts
packages/core-browser/src/components/ai-native/popover/index.tsx
packages/core-common/src/types/ai-native.ts
packages/debug/package.json
packages/debug/src/browser/tree/debug-console-tree-node.define.tsx
packages/debug/src/browser/view/console/debug-console-session.ts
packages/debug/src/browser/view/console/debug-console.module.less
packages/debug/src/browser/view/console/debug-console.view.tsx
yarn.lock

feat: debug console support ai debug popover

---

packages/ai-native/src/browser/inline-chat-widget/inline-chat-controller.tsx
packages/core-browser/src/components/ai-native/ai-action/index.module.less
packages/debug/src/browser/view/console/debug-console.module.less
packages/debug/src/browser/view/console/debug-console.view.tsx

feat:  adjust ai action position in debug console

---

packages/ai-native/src/browser/override/layout/override.less
packages/core-browser/src/components/ai-native/enhanceIcon/styles.module.less

fix: style issue by desktop

---

packages/ai-native/src/browser/inline-chat-widget/inline-chat-controller.tsx
packages/ai-native/src/browser/inline-chat-widget/inline-chat.module.less
packages/core-browser/src/components/ai-native/inline-chat/styles.module.less

fix: ai panel background color issue

---

configs/alipay-cloud-extensions.json
scripts/download.js

replace the extension script download source with Alipay CloudIDE marketplace

feat: replace the extension script download source with Alipay CloudIDE Marketplace

---

packages/core-common/src/const/application.ts
packages/core-node/src/bootstrap/app.ts
packages/extension-manager/src/common/index.ts
packages/extension-manager/src/common/vsx-registry-types.ts
packages/extension-manager/src/node/index.ts
packages/extension-manager/src/node/marketplace/alipay-cloud-marketplace.service.ts
packages/extension-manager/src/node/marketplace/index.ts
packages/extension-manager/src/node/marketplace/openvsx-marketplace.service.ts
packages/extension-manager/src/node/vsx-extension.service.ts
tools/cli-engine/src/node/server.ts
tools/electron/src/node/server.ts

Replace marketplace to alipay cloudide marketplace

feat: replace marketplace to alipay cloudide marketplace

---

packages/extension/src/common/vscode/ext-types.ts
packages/extension/src/common/vscode/window.ts
packages/extension/src/hosted/api/vscode/ext.host.output.ts
packages/extension/src/hosted/api/vscode/ext.host.window.api.impl.ts
packages/types/vscode/typings/vscode.d.ts
packages/types/vscode/typings/vscode.window.d.ts

feat: add log outputchannel api

---

packages/extension-manager/src/node/marketplace/alipay-cloud-marketplace.service.ts

fix: fix extension download error

---

packages/theme/src/browser/product-icon.service.ts

修复错误引入的 `StaticResourceService` 定义

fix: unexpected static resoure service import

---

packages/design/src/browser/style/design.module.less
packages/startup/entry/sample-modules/menu-bar/menu-bar.module.less

style: improve design module style

---

packages/components/src/recycle-tree/tree/TreeNode.ts

close #3395
improve tree property performance

feat: imporve tree property performance

---

packages/ai-native/src/browser/chat/chat.view.tsx
packages/ai-native/src/browser/components/ChatReply.tsx
packages/ai-native/src/browser/components/StreamMsg.tsx
packages/ai-native/src/browser/components/Thinking.tsx
packages/ai-native/src/browser/inline-completions/completeProvider.ts
packages/core-browser/src/bootstrap/inner-providers.ts
packages/core-common/src/types/ai-native/index.ts
packages/core-common/src/types/ai-native/reporter.ts

fix: ai reporter repeat

---

packages/collaboration/__tests__/browser/collaboration-service.test.ts
packages/collaboration/__tests__/browser/textmodel-binding.test.ts
packages/collaboration/src/browser/collaboration.service.ts
packages/collaboration/src/common/constants.ts
packages/collaboration/src/node/y-websocket-server.ts
packages/core-browser/src/react-providers/config-provider.tsx
packages/core-node/src/types.ts

之前无法配置 y-websocket server 监听的端口
close:  #2405
support configure collaboration server opts

feat: support configure collaboration server opts

---

packages/components/src/input/input.less
packages/components/src/input/validate-input.less

部分样式由于 input 没有设置 box-sizing 属性导致展示异常
improve input style on design mode

style: improve input style on design mode

---

packages/core-browser/src/common/common.command.ts
packages/editor/src/browser/diff/compare.ts
packages/editor/src/browser/preference/converter.ts
packages/editor/src/browser/preference/schema.ts
packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts
packages/startup/entry/web/app.tsx

preview:
https://github.com/opensumi/core/assets/9823838/3f93dc0a-fa7e-467a-ab60-1ae5cfbfb6d7
support collapse unchanged regions on diff editor

feat: support collapse unchanged regions

---

packages/debug/src/browser/view/console/debug-console.service.ts
packages/editor/__tests__/browser/editor.collection.test.ts
packages/extension/__tests__/browser/main.thread.editor.test.ts
packages/extension/src/browser/vscode/api/main.thread.language.ts
packages/extension/src/common/vscode/model.api.ts
packages/extension/src/hosted/api/vscode/language/completion.ts
packages/monaco/__mocks__/monaco/editor/code-editor.ts
packages/monaco/package.json
packages/monaco/src/browser/monaco-snippet-suggest-provider.ts
packages/monaco/src/browser/monaco.context-key.service.ts
packages/monaco/src/browser/monaco.resolved-keybinding.ts
packages/monaco/src/browser/monaco.service.ts
yarn.lock

feat: upgrade to monaco 0.47.0

---

packages/theme/__tests__/browser/product-icon.service.test.ts
packages/theme/src/browser/product-icon.service.ts
tools/playwright/src/tests/scm.test.ts

- fix icons contribution disable when default product icon theme initial

fix: default theme register icons contribution

---

packages/design/package.json

fix: design module publish

---

packages/connection/package.json
yarn.lock

fix: add mssing pkg

---

packages/core-node/src/bootstrap/app.ts

忘记透传 collaborationOptions 到 AppConfig 了

fix: collaborationOptions not pass

---

.github/workflows/release-rc.yml
.github/workflows/release.yml

https://github.com/opensumi/actions/blob/main/src/permissionCheck.js#L11

ci: fix release ci

---

packages/core-browser/src/contextkey/markers.ts
packages/core-browser/src/contextkey/search.ts
packages/markers/src/browser/markers-contextkey.ts
packages/markers/src/browser/markers-contribution.ts
packages/markers/src/browser/markers-service.ts
packages/markers/src/browser/markers-tree.view.tsx
packages/markers/src/browser/tree/tree-model.service.ts
packages/search/src/browser/search-contextkey.ts
packages/search/src/browser/search.contribution.ts
packages/search/src/browser/search.service.ts
packages/search/src/browser/tree/search-tree.service.ts
packages/search/src/browser/tree/tree-model.service.ts

fix: tree do not need refresh when invisible

---

packages/main-layout/src/browser/accordion/accordion.service.ts

fix: do toggle view error

---

packages/ai-native/src/browser/layout/menu-bar/menu-bar.module.less

style(design): fix menu bar style

---

packages/ai-native/src/browser/chat/chat-agent.service.ts
packages/ai-native/src/browser/chat/chat-model.ts
packages/ai-native/src/browser/chat/chat.feature.registry.ts
packages/ai-native/src/browser/chat/chat.view.tsx
packages/ai-native/src/browser/components/ChatInput.tsx
packages/ai-native/src/browser/components/Thinking.tsx
packages/ai-native/src/common/index.ts
packages/extension/src/browser/sumi/main.thread.chat-agents.ts
packages/extension/src/common/sumi/chat-agents.ts
packages/extension/src/hosted/api/sumi/ext.host.chat.impl.ts
packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts
packages/types/sumi.d.ts

Agent adds two APIs
1. [chatWelcomMessage Provider]: Used to modify the default welcome prompt for the chat
2. [isDefault]: Used to set whether the agent is the default agent

feat: optimize chat agent

---

packages/debug/src/browser/view/console/debug-console.module.less
packages/debug/src/browser/view/frames/debug-call-stack.module.less

improve debug frame style with design mode

style: improve debug frame style with design mode

---

packages/core-browser/src/components/actions/index.tsx
packages/core-browser/src/components/actions/styles.module.less
packages/core-browser/src/components/layout/default-layout.tsx
packages/core-browser/src/react-providers/slot.tsx
packages/design/src/browser/style/global.less
packages/startup/entry/web/layout.tsx
packages/startup/entry/web/render-app.tsx

Design 布局下使用特定的布局
use design mode specify layout

style: use design mode specific layout

---

packages/ai-native/src/browser/ai-terminal/component/terminal-command-suggest-controller.module.less
packages/ai-native/src/browser/ai-terminal/component/terminal-inline-chat-controller.module.less
packages/ai-native/src/browser/chat/chat.module.less
packages/ai-native/src/browser/components/components.module.less
packages/ai-native/src/browser/layout/layout.module.less
packages/ai-native/src/browser/layout/menu-bar/menu-bar.module.less
packages/ai-native/src/browser/widget/inline-diff/inline-diff-widget.module.less
packages/core-browser/src/components/ai-native/ai-action/index.module.less
packages/core-browser/src/components/ai-native/content-widget/styles.module.less
packages/core-browser/src/components/ai-native/enhanceIcon/styles.module.less
packages/design/src/browser/override/override.module.less
packages/design/src/browser/style/design.module.less
packages/design/src/browser/style/global.less
packages/editor/src/browser/editor.module.less
packages/monaco/src/browser/contrib/merge-editor/view/merge-editor.module.less
packages/theme/src/common/color-tokens/design.ts

`{namespace}.{blockName}.{foreground/background...}`
use better design token name

refactor: use better design token name

---

packages/ai-native/src/browser/ai-core.contribution.ts
packages/ai-native/src/browser/layout/menu-bar/menu-bar.module.less
packages/ai-native/src/browser/layout/menu-bar/menu-bar.view.tsx
packages/core-browser/src/ai-native/ai-config.service.ts
packages/core-browser/src/layout/constants.ts
packages/core-common/src/types/ai-native/index.ts
packages/design/src/browser/style/design.module.less
packages/main-layout/src/browser/accordion/accordion.view.tsx
packages/startup/entry/web/render-app.tsx
typings/style/index.d.ts

- 修复部分 design 下的样式问题
- 新增 menubar logo 配置

style: improve design style

---

package.json
packages/monaco/__mocks__/monaco/editor/model.ts
packages/monaco/package.json
tools/dev-tool/src/webpack.js
yarn.lock

fix: missing zh-Hans translation

---

packages/ai-native/src/browser/ai-chat.view.tsx
packages/ai-native/src/browser/chat-agent.service.ts
packages/ai-native/src/browser/chat/chat-model.ts
packages/ai-native/src/browser/chat/chat.feature.registry.ts
packages/ai-native/src/browser/components/ChatInput.tsx
packages/ai-native/src/browser/components/Thinking.tsx
packages/ai-native/src/browser/index.ts
packages/ai-native/src/browser/types.ts
packages/ai-native/src/common/index.ts
packages/extension/src/browser/sumi/main.thread.chat-agents.ts
packages/extension/src/common/sumi/chat-agents.ts
packages/extension/src/hosted/api/sumi/ext.host.chat.impl.ts
packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts
packages/types/sumi.d.ts

feat: cherry-pick agent update from main branch

---

packages/ai-native/src/browser/ai-core.contribution.ts
packages/ai-native/src/browser/ai-editor.contribution.ts
packages/ai-native/src/browser/index.ts
packages/ai-native/src/browser/inline-chat-widget/inline-chat.feature.registry.ts
packages/ai-native/src/browser/inline-completions/completeProvider.ts
packages/ai-native/src/browser/merge-conflict/cache-conflicts.ts
packages/ai-native/src/browser/merge-conflict/index.ts
packages/ai-native/src/browser/merge-conflict/types.ts
packages/ai-native/src/browser/prompts/rename-prompt.ts
packages/ai-native/src/browser/rename/rename.feature.registry.ts
packages/ai-native/src/browser/rename/rename.service.ts
packages/ai-native/src/browser/types.ts
packages/core-browser/src/ai-native/ai-config.service.ts
packages/core-common/src/types/ai-native.ts
packages/editor/src/browser/monaco-contrib/callHierarchy/callHierarchy.service.ts
packages/monaco/src/browser/monaco-api/languages.ts
packages/monaco/src/common/types.ts
packages/startup/entry/sample-modules/ai-native.contribution.ts

feat: support ai rename

---

packages/ai-native/src/browser/ai-chat.view.tsx

feat: set default welcome message

---

packages/ai-native/src/browser/ai-core.contribution.ts
packages/ai-native/src/browser/ai-editor.contribution.ts
packages/ai-native/src/browser/inline-chat-widget/inline-chat.service.ts
packages/ai-native/src/browser/inline-chat-widget/inline-content-widget.tsx
packages/ai-native/src/browser/override/layout/menu-bar/menu-bar.service.ts
packages/ai-native/src/node/index.ts
packages/core-browser/src/monaco/index.ts
packages/core-common/src/ai-native/reporter.ts
packages/monaco/src/browser/ai-native/content-widget/index.tsx
packages/monaco/src/browser/monaco.contribution.ts
packages/monaco/src/browser/telemetry.service.ts

feat: add rename event track and optimize ai actions

---

packages/ai-native/src/browser/chat/chat.module.less
packages/ai-native/src/browser/chat/chat.view.tsx
packages/ai-native/src/browser/components/components.module.less
packages/ai-native/src/browser/layout/ai-layout.tsx
packages/ai-native/src/browser/layout/layout.module.less
packages/ai-native/src/browser/layout/tabbar.view.tsx
packages/design/src/browser/layout/tabbar.view.tsx
packages/design/src/browser/style/design.module.less
packages/design/src/browser/style/global.less

style: improve ai native layout

---

packages/design/src/browser/style/design.module.less
packages/main-layout/src/browser/tabbar/styles.module.less
packages/startup/package.json

style: improve tabbar icon style

---

packages/ai-native/src/browser/ai-editor.contribution.ts
packages/core-common/src/types/ai-native/reporter.ts

feat: add inline chat event track

---

packages/ai-native/src/browser/override/layout/override.less

pick https://github.com/opensumi/core/pull/3467/files

fix: monaco hover widget styles

---

packages/collaboration/src/browser/collaboration.service.ts
packages/debug/src/browser/editor/debug-breakpoint-zone-widget.tsx
packages/editor/src/browser/diff/index.ts
packages/editor/src/browser/resource.service.ts
packages/editor/src/common/editor.ts
packages/theme/src/browser/style.service.ts
packages/theme/src/common/style.ts

fix: diff editor missing dirty state indicator

---

packages/monaco/src/browser/contrib/merge-editor/view/merge-editor.module.less

style: fix merge toolbar z-index

---

packages/ai-native/src/browser/chat/chat.view.tsx
packages/ai-native/src/browser/components/ChatInput.tsx
packages/ai-native/src/browser/components/SlashCustomRender.tsx

fix: chat input auto focus

---

packages/ai-native/src/browser/components/ChatReply.tsx
packages/ai-native/src/browser/components/ChatThinking.tsx

chore: improve chatthinking component

---

packages/ai-native/src/browser/chat/chat.view.tsx
packages/ai-native/src/browser/components/ChatThinking.tsx
packages/ai-native/src/browser/types.ts

修复在使用 registerChatRender api 进行自定义渲染组件时，因使用了 hooks 引起的组件渲染异常问题

fix: registerChatRender render error

---

packages/ai-native/src/browser/ai-editor.contribution.ts
packages/startup/entry/sample-modules/ai-native.contribution.ts

fix: inline chat reporter

---

packages/core-browser/src/style/monaco-override.less
packages/debug/src/browser/editor/debug-hover.module.less
packages/debug/src/browser/view/variables/debug-variables.module.less

修复 Debug 时， 编辑器 hover 变量展示的问题，并且略微优化了一些 UI 展示。

fix: debug hover no background

---

package.json
packages/ai-native/package.json
yarn.lock

chore: lock web-tree-sitter version

---

packages/design/src/browser/style/design.module.less

style: improve tabbar margin style

---

packages/ai-native/src/browser/ai-core.contribution.ts
packages/ai-native/src/browser/override/layout/menu-bar/menu-bar.service.ts
packages/ai-native/src/common/index.ts
packages/core-browser/src/core-preferences.ts
packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts

feat: support chat visible type preference

---

.github/workflows/check.yml
.github/workflows/ci.yml
.github/workflows/deploy.yml
.github/workflows/e2e.yml
.github/workflows/release-rc.yml
.github/workflows/release.yml

ci: yarn cache might be timeout sometimes

---

packages/ai-native/src/browser/chat/chat.render.registry.ts
packages/ai-native/src/browser/chat/chat.view.tsx
packages/ai-native/src/browser/types.ts

feat: chat input custom render

---

packages/extension/src/common/vscode/window.ts
packages/extension/src/hosted/api/vscode/ext.host.statusbar.ts

correct status bar item background color mapping

fix: correct status bar item background color mapping

---

packages/design/src/browser/menu-bar/menu-bar.view.tsx

fix: fix menu position

---

packages/components/src/markdown/styles.less
packages/components/src/popover/styles.less

Before:
After:
adjust markdown styles for better readability

style: adjust markdown styles for better readability

---

packages/components/src/style/base.less
packages/core-browser/src/style/normalize.less
packages/webview/src/browser/webview.service.ts
tools/electron/src/browser/index.html

feat: use border-box as box-sizing

---

packages/components/src/overlay/styles.less
packages/editor/src/browser/editor-collection.service.ts

adjust overlay close button margin and handle disposed diff editor models

style: adjust overlay close button margin and handle disposed diff editor model

---

packages/connection/src/common/rpc/connection.ts
packages/utils/src/stream.ts

feat: support stream on error event

---

packages/ai-native/src/browser/chat/chat.view.tsx
packages/ai-native/src/browser/components/ChatInput.tsx
packages/i18n/src/common/en-US.lang.ts

调整部分边缘位置 Popover 组件的位置
update Popover component usage

style: update Popover component usage

---

packages/extension/src/browser/extension.service.ts

修复因时序问题导致的 provider not found 问题

fix: refresh not found provider

---

packages/components/src/recycle-tree/tree/TreeNode.ts
packages/extension/src/browser/components/extension-tree-view-node.tsx
packages/extension/src/browser/vscode/api/tree-view/tree-view.model.service.ts
packages/extension/src/browser/vscode/api/tree-view/tree-view.node.defined.ts
packages/extension/src/hosted/api/vscode/ext.host.treeview.ts

1. Extension Tree View 刷新支持折叠状态保留
2. 修复 TreeView 箭头点击无响应问题
optimize tree node handling collapse/expand logic

feat: optimize tree node handling collapse/expand logic

---

packages/design/src/browser/theme/default-theme.ts
packages/design/src/browser/theme/light-theme.ts

style: improve actionbar selection background color

---

README-zh_CN.md
README.md

update readme for the 3.0 version

docs: update readme for the 3.0 version

---

packages/ai-native/src/browser/components/ChatInput.tsx

修复 chatinput 的 options 样式问题
在没有 agent 插件注册的情况下按 @ 符号会出现横条

style: chat input instruction options

---

packages/extension/src/browser/vscode/api/main.thread.editor-tabs.ts

close: https://github.com/opensumi/core/issues/1404
* wrong tab operation events causing ext-host's tab api complaining about 'Invalid Tabs'
fixes tab ext-host complaining about 'INVALID tab'

fix: fix tab ext-host complaining about 'INVALID TAB'

---

packages/core-browser/src/contextkey/terminal.ts
packages/terminal-next/src/browser/terminal.context-key.ts

shellExecutionSupported
feat: support shellExecutionSupported context key

feat: support shellExecutionSupported context key

---

packages/ai-native/src/browser/components/ChatInput.tsx
packages/ai-native/src/browser/components/WelcomeMsg.tsx

- 修复输入 @ 符号时前缀出现 / 字符的问题
- 修复插件注册的 sample question 不渲染的问题

fix: agent ext sampleQuestions not render

---

packages/extension/src/browser/extension.service.ts
packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts

refactor: refactor the restart interaction of extension host

refactor: refactor the restart interaction of extension host

---

packages/design/src/browser/menu-bar/menu-bar.contribution.tsx
packages/terminal-next/src/browser/component/terminal.view.tsx
packages/terminal-next/src/browser/contribution/terminal.command.ts
packages/terminal-next/src/browser/terminal.client.ts
packages/terminal-next/src/browser/terminal.controller.ts
packages/terminal-next/src/browser/terminal.error.ts
packages/terminal-next/src/browser/terminal.search.ts
packages/terminal-next/src/common/controller.ts
packages/terminal-next/src/common/error.ts
packages/terminal-next/src/node/pty.proxy.ts
packages/terminal-next/src/node/terminal.service.client.ts

主题改变时，背景色改变没有生效。
fix terminal background color when theme changed

fix(terminal): ui state is not sync from data

---

packages/extension/src/node/extension.service.ts

fixed #3653 
refactor: do not kill the last extension host

refactor: do not kill the last extension host

---

packages/ai-native/src/browser/chat/chat.api.service.ts
packages/main-layout/src/common/main-layout.definition.ts
packages/startup/entry/sample-modules/ai-native/ai-native.contribution.ts
packages/startup/entry/sample-modules/index.ts

fix(chat): show chat view first when send message by api

---

packages/extension/src/node/extension.service.ts

fix: #3653 
fix: clean up possible zombie processes

fix(ext): clean up possible zombie processes

---

packages/design/src/browser/menu-bar/menu-bar.contribution.tsx

修复集成端注册的 design menubar 不显示
fix register design menubar item not work

fix: register design menubar item not work

---

packages/design/src/browser/style/global.less

优化布局，减少样式计算时外部边距带来的异常问题
adjust statusbar padding for better display

style: adjust statusbar padding for better display

---

packages/extension/src/browser/extension.contribution.ts
packages/extension/src/browser/vscode/builtin-commands.ts

feat: add debug command for python-debug

feat: add debug command for python-debug

---

packages/components/webpack.config.js

ide-components 里的样式文件不使用 css-loader hash

fix: remove components css-loader hash

---

packages/extension/src/browser/extension.service.ts
packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts

There is a chance of a restart failure，use notification to prompt and add refresh button

Revert "refactor: refactor the restart interaction of extension host"

---

packages/ai-native/src/browser/ai-editor.contribution.ts

修复 AI code action 在打开不同类型编辑器情况下会重复注册的问题

fix: ai code-action duplicate registration

---

packages/theme/src/browser/theme.contribution.ts

fix:  default theme ahead render

---

packages/ai-native/src/browser/ai-editor.contribution.ts

fix: code action first invalid

---

packages/ai-native/src/browser/chat/chat-agent.service.ts
packages/ai-native/src/browser/chat/chat.view.tsx
packages/ai-native/src/browser/components/ChatReply.tsx
packages/ai-native/src/common/index.ts
packages/extension/src/browser/sumi/main.thread.chat-agents.ts
packages/extension/src/common/sumi/chat-agents.ts
packages/extension/src/hosted/api/sumi/ext.host.chat.impl.ts
packages/types/sumi.d.ts

The sumi.chat.sendMessage method support passing in a component type message

feat: support send component message in chat

---

packages/ai-native/src/browser/ai-editor.contribution.ts

fix: code action click invaild

---

packages/design/src/browser/index.ts
packages/theme/src/browser/theme-store.ts
packages/theme/src/browser/theme.contribution.ts
packages/theme/src/common/theme.service.ts

引入了 design module 的情况下，主题预渲染使用 design 主题

fix: improve default ai theme preloaded

---

packages/extension/src/node/extension.service.ts

如果我们的 node 进程是使用 webpack 打包的话，插件进程无法启动。
原因：https://stackoverflow.com/questions/46392660/module-filename-is-undefined-sequelize-node-js
for those having this issue, it is also good to note that module.filename would be undefined if you bundled your files. In my case it was undefined and I fixed it by simply replacing it with __filename which yields the same outcome.
So you should be able to replace path.basename(module.filename); with path.basename(__filename);.
Fix the problem that the extension process cannot be started when using webpack to bundle

fix: extension process cannot be started when using webpack to bundle

---

nixpacks.toml
railway.toml

fix: use node18 in nixpacks

---

packages/connection/src/browser/ws-channel-handler.ts
packages/connection/src/common/connection/drivers/base.ts
packages/connection/src/common/connection/drivers/socket.ts
packages/core-browser/src/application/runtime/base-socket.ts
packages/core-browser/src/bootstrap/app.ts
packages/core-browser/src/bootstrap/connection.ts

codeblitz 需要接入 opensumi 3.0，之前连接有一些地方的类型都是写死了实现，第三方 override 会有类型问题
refactor connection: use interface-oriented rather than implementation

refactor(connection): interface-oriented rather than implementation

---

packages/design/src/browser/index.ts

让 design 主题的注册时机早一点，避免出现 dom 渲染了但主题还未注册的情况

fix: lifecycle starting register design theme

---

packages/ai-native/src/browser/chat/chat.api.service.ts
packages/ai-native/src/browser/chat/chat.view.tsx

支持在自定义的 chat render 组件里控制 chat 面板的滚动

feat: chat api support scrollToBottom

---

packages/ai-native/src/browser/contrib/code-action/code-action.contribution.ts
packages/ai-native/src/browser/contrib/code-action/code-action.handler.ts
packages/ai-native/src/browser/contrib/code-action/code-action.service.ts
packages/ai-native/src/browser/index.ts
packages/ai-native/src/browser/widget/inline-chat/inline-chat.feature.registry.ts
packages/ai-native/src/browser/widget/inline-chat/inline-chat.handler.ts
packages/core-browser/src/ai-native/command.ts

code action 拆成独立的 contribution，以及重构原来的 command 注册方式
重构: 将 code action 和 inline chat 代码进行抽离

refactor: code action register

---

packages/ai-native/src/browser/layout/ai-layout.tsx

修复 ai layout 的 top layout 高度无法自定义的问题

chore: update SlotRenderer default sizes based on layout configuration

---

packages/ai-native/src/browser/chat/chat.api.service.ts
packages/ai-native/src/browser/chat/chat.view.tsx
packages/ai-native/src/browser/components/ChatReply.tsx
packages/ai-native/src/common/index.ts

add api for rendering chat message history messages

feat: add api for rendering chat message history messages

---

packages/connection/src/common/rpc-service/proxy/json.ts
packages/connection/src/common/rpc-service/proxy/sumi.ts
packages/connection/src/common/rpc/multiplexer.ts
packages/extension/src/browser/extension-node.service.ts
packages/extension/src/browser/extension-worker.service.ts
packages/extension/src/common/vscode/protocols.ts
packages/extension/src/hosted/ext.process-base.ts
packages/extension/src/hosted/worker.host.ts

worker 线程与主线程通信不需要序列化
communication with worker threads does not require serialization

feat: communication with worker threads does not require serialization

---

packages/file-tree-next/src/browser/file-tree.service.ts
packages/file-tree-next/src/common/file-tree-node.define.ts

移除老旧的冗余逻辑，直接基于 path 进行文件节点读取
optimize compact mode handling and node updates

refactor(file-tree): optimize compact mode handling and node updates

---

packages/core-browser/src/common/common.command.ts
packages/core-browser/src/quick-open/index.ts
packages/quick-open/src/browser/prefix-quick-open.service.ts
packages/quick-open/src/browser/quick-open.contribution.ts

某些场景下需要用命令打开命令面板，并且带有默认输入
add a command to open the command palette with value

feat: add a command to open the command palette with value

---

packages/ai-native/src/browser/ai-core.contribution.ts
packages/ai-native/src/browser/contrib/inline-completions/completeProvider.ts
packages/ai-native/src/browser/contrib/inline-completions/constants.ts
packages/ai-native/src/browser/contrib/inline-completions/inline-completions.handler.ts
packages/ai-native/src/browser/contrib/inline-completions/promptCache.ts
packages/ai-native/src/browser/contrib/inline-completions/provider.ts
packages/ai-native/src/browser/contrib/inline-completions/service/ai-completions.service.ts
packages/ai-native/src/browser/contrib/inline-completions/types.ts
packages/core-browser/src/core-preferences.ts
packages/core-common/src/settings/ai-native.ts
packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts

新增一个配置可以让用户关闭 prompt 工程，优化请求相关的逻辑
add preference to controller whether enable prompt engineering

feat: add preference to controller whether enable prompt engineering

---

packages/ai-native/src/browser/widget/inline-chat/inline-chat-controller.ts
packages/ai-native/src/browser/widget/inline-chat/inline-chat.handler.ts
packages/startup/entry/sample-modules/ai-native/ai.back.service.ts

修复 inline chat 流式渲染时的代码块渲染不全的问题

fix: inline chat controller code block

---

CHANGELOG.md

docs: add v3.1.0 changelog

---

packages/monaco-enhance/src/browser/zone-widget.ts

adjust zone widget width for scrollbar

fix: adjust zone widget width for scrollbar

---

packages/components/src/scrollbars/styles.less

add border-radius to scrollbar thumbs

style: add border-radius to scrollbar thumbs

---

packages/ai-native/src/browser/widget/inline-diff/inline-diff-widget.tsx
packages/design/src/browser/index.ts
packages/design/src/browser/style/global.less
packages/design/src/browser/theme/override.token.ts

before:
after:
改进 design 模式下 code action 的样式

style: improve action widget styles

---

packages/design/src/browser/style/design.module.less

before:
after:
add box-sizing and border-radius properties

style: add box-sizing and border-radius properties

---

packages/components/__tests__/recycle-tree/tree/path.test.ts
packages/components/src/recycle-tree/path.ts
packages/components/src/recycle-tree/tree/TreeNode.ts
packages/components/src/recycle-tree/tree/model/treeState/TreeStateManager.ts
packages/components/src/recycle-tree/types/watcher.ts
packages/debug/src/browser/editor/debug-hover-tree.model.service.ts
packages/debug/src/browser/view/console/debug-console-tree.model.service.ts
packages/debug/src/browser/view/watch/debug-watch-tree.model.service.ts
packages/markers/src/browser/tree/tree-model.service.ts
packages/opened-editor/__tests__/browser/opened-editor.service.test.ts
packages/opened-editor/src/browser/opened-editor-node.define.ts
packages/opened-editor/src/browser/services/opened-editor-model.service.ts
packages/opened-editor/src/browser/services/opened-editor-tree.service.ts
packages/outline/src/browser/services/outline-model.service.ts
packages/utils/__tests__/path.test.ts
packages/utils/src/path.ts

移除了树路径计算中的 new Path 相关逻辑
optimize tree performance

feat: optimize tree performance

---

packages/design/src/browser/style/design.module.less

before:
after:
adjust title actions style

style: adjust title actions style

---

packages/ai-native/src/browser/ai-core.contribution.ts
packages/ai-native/src/browser/ai-editor.contribution.ts
packages/ai-native/src/browser/contrib/base/index.ts
packages/ai-native/src/browser/contrib/code-action/code-action.handler.ts
packages/ai-native/src/browser/contrib/inline-completions/completeProvider.ts
packages/ai-native/src/browser/contrib/inline-completions/inline-completions.handler.ts
packages/ai-native/src/browser/contrib/inline-completions/model/competionModel.ts
packages/ai-native/src/browser/contrib/interface-navigation/interface-navigation.contribution.ts
packages/ai-native/src/browser/contrib/rename/rename.handler.ts
packages/ai-native/src/browser/index.ts
packages/ai-native/src/browser/preferences/index.ts
packages/ai-native/src/browser/preferences/schema.ts
packages/ai-native/src/browser/widget/inline-chat/inline-chat.handler.ts
packages/core-browser/src/core-preferences.ts
packages/core-common/src/settings/ai-native.ts
packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts
packages/startup/entry/sample-modules/ai-native/ai.back.service.ts

backport to v3.1
- #3763
Fix inline completion occasionally not appearing
optimize monaco contrib registration

refactor(ai-native): optimize monaco contrib registration

---

packages/design/src/browser/style/design.module.less

before:
after:
improve SCM action button style

style: improve SCM action button style

---

packages/ai-native/src/browser/contrib/merge-conflict/index.ts
packages/core-browser/src/common/common.command.ts
packages/core-browser/src/components/actions/index.tsx
packages/core-browser/src/menu/next/menu-util.ts
packages/core-common/src/commands/git.ts
packages/editor/src/browser/merge-conflict/merge-conflict.model.ts
packages/editor/src/browser/merge-conflict/merge-conflict.service.ts
packages/editor/src/browser/merge-conflict/types.ts
packages/editor/src/browser/merge-editor/MergeEditorFloatComponents.tsx
packages/extension/src/browser/vscode/api/main.thread.treeview.ts
packages/monaco/src/browser/contrib/merge-editor/components/merge-actions/index.tsx
packages/monaco/src/browser/contrib/merge-editor/components/merge-actions/merge-actions.module.less
packages/monaco/src/browser/contrib/merge-editor/index.ts
packages/monaco/src/browser/contrib/merge-editor/mapping-manager.store.ts
packages/monaco/src/browser/contrib/merge-editor/merge-editor.service.ts
packages/monaco/src/browser/contrib/merge-editor/model/line-range.ts
packages/monaco/src/browser/contrib/merge-editor/navigate-to.ts
packages/monaco/src/browser/contrib/merge-editor/view/editors/currentCodeEditor.ts
packages/monaco/src/browser/contrib/merge-editor/view/editors/incomingCodeEditor.ts
packages/monaco/src/browser/contrib/merge-editor/view/editors/resultCodeEditor.ts
packages/monaco/src/browser/contrib/merge-editor/view/grid.tsx
packages/monaco/src/browser/contrib/merge-editor/view/mini-map.tsx
packages/scm/src/browser/components/scm-resource-tree/scm-tree-api.ts
packages/scm/src/browser/components/scm-resource-tree/scm-tree.service.ts
packages/scm/src/browser/scm.contribution.ts

1. 原来的 git stage 实现超级无敌黑，现在把这个逻辑干掉
2. 点击上一个下一个会滚动到某个 conflict 的上一行而不是当前行
optimize merge conflicts features

feat: optimize merge conflicts

---

packages/core-browser/src/components/ai-native/interactive-input/index.module.less

fix: adjust search icon styles

---

packages/ai-native/src/browser/widget/inline-chat/inline-chat.handler.ts
packages/ai-native/src/browser/widget/inline-diff/inline-diff-previewer.ts
packages/ai-native/src/browser/widget/inline-stream-diff/inline-stream-diff.handler.tsx

fix: abort streaming inline diff

---

packages/terminal-next/src/browser/terminal.client.ts

fix: set cwd when terminal recovery

---

configs/vscode-extensions.json
packages/extension/src/hosted/api/vscode/ext.host.api.impl.ts

fix: export tab input api in ext host

---

packages/ai-native/src/browser/widget/inline-diff/inline-diff-previewer.ts

fix: inline diff format indentation

---

packages/editor/__tests__/browser/editor-service.test.ts
packages/editor/src/browser/editor-collection.service.ts
packages/editor/src/browser/editor.module.less
packages/editor/src/browser/editor.view.tsx
packages/editor/src/browser/workbench-editor.service.ts
packages/editor/src/common/editor.ts

fix: workbench cannot layout editor

---

packages/editor/__tests__/browser/editor-service.test.ts
packages/editor/src/browser/editor-collection.service.ts
packages/editor/src/browser/editor.contribution.ts
packages/editor/src/browser/editor.module.less
packages/editor/src/browser/editor.view.tsx
packages/editor/src/browser/workbench-editor.service.ts
packages/editor/src/common/editor.ts

fix: workbench editor layout

---

packages/core-common/src/node/index.ts
packages/core-common/src/node/utils.ts
packages/core-electron-main/src/bootstrap/app.ts
packages/core-node/src/bootstrap/app.ts
packages/extension/src/hosted/ext.process-base.ts

fix: suppress EPIPE errors when log

---

packages/editor/src/browser/editor.module.less
packages/editor/src/browser/tab.view.tsx

fix: editor tabbar cannot scroll

---

packages/ai-native/src/browser/widget/inline-chat/inline-chat.handler.ts

fix: update data reporting parameter

---

packages/core-browser/src/components/layout/split-panel.tsx

fix: split panel layout

---

packages/ai-native/src/browser/components/ChatEditor.tsx

fix: highlight component affects global style after uninstallation

---

packages/ai-native/src/browser/contrib/intelligent-completions/intelligent-completions.controller.ts

fix: back service register completion not work

---

packages/ai-native/src/browser/widget/inline-chat/inline-chat-editor.controller.ts

修复 inline diff 的 chat 按钮点击无效的问题

fix: inline diff interactive input invalid

---

packages/ai-native/src/browser/contrib/base/index.ts
packages/ai-native/src/browser/contrib/intelligent-completions/intelligent-completions.controller.ts
packages/ai-native/src/browser/contrib/problem-fix/problem-fix.controller.ts
packages/ai-native/src/browser/widget/inline-chat/inline-chat-editor.controller.ts
packages/ai-native/src/browser/widget/inline-diff/inline-diff.controller.ts
packages/ai-native/src/browser/widget/inline-hint/inline-hint.controller.ts
packages/ai-native/src/browser/widget/inline-input/inline-input.controller.ts

fix: ai feature accidental invalid

---

packages/core-browser/src/react-providers/config-provider.tsx
packages/editor/src/browser/editor-collection.service.ts
packages/editor/src/browser/workbench-editor.service.ts

add config for diff editor state restore

fix: add config for diff editor state restore

---

packages/ai-native/src/browser/widget/inline-chat/inline-chat-controller.ts
packages/ai-native/src/common/index.ts
packages/ai-native/src/common/utils.ts

chore: add extract code utils

---

packages/comments/src/browser/comments-thread.ts
packages/comments/src/browser/comments-zone.view.tsx
packages/comments/src/browser/comments.contribution.ts

fix: comments thread cannot be closed

---

packages/types/vscode/typings/vscode.tests.d.ts

相关代码已经在 https://github.com/opensumi/core/pull/4167 被实现了，此次补个类型

feat: support TestRunProfile.onDidChangeDefault

---

packages/core-common/src/const/application.ts

feat: update vscode engine to 1.94.2

---

packages/ai-native/src/browser/index.ts
packages/ai-native/src/browser/mcp/mcp-server.feature.registry.ts
packages/ai-native/src/browser/mcp/tools/runTerminalCmd.ts

https://github.com/user-attachments/assets/f490830a-eb4b-4991-8b0a-b15a9ba2b02a

feat: run terminal cmd tool

---

packages/ai-native/src/browser/chat/chat.view.tsx
packages/ai-native/src/browser/components/ChatInput.tsx

chore: improve auto scroll behavior

---

packages/ai-native/src/browser/ai-core.contribution.ts

fix: mcp reconnect fix

---

packages/ai-native/src/browser/mcp/tools/components/Terminal.tsx
packages/core-browser/src/components/ai-native/interactive-input/index.tsx
packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts

fix: terminal cmd add command

---

packages/ai-native/src/browser/chat/chat-agent.service.ts
packages/ai-native/src/browser/chat/chat-proxy.service.ts
packages/ai-native/src/node/base-language-model.ts
packages/core-common/src/types/ai-native/index.ts

fix: system prompt not working

---

packages/ai-native/src/browser/ai-core.contribution.ts
packages/ai-native/src/browser/chat/chat-agent.service.ts
packages/ai-native/src/node/base-language-model.ts
packages/core-common/src/types/ai-native/index.ts

fix: register editor side widget issue

---

packages/ai-native/src/browser/chat/chat-agent.service.ts
packages/ai-native/src/browser/chat/chat.view.tsx
packages/ai-native/src/browser/mcp/base-apply.service.ts
packages/ai-native/src/browser/mcp/mcp-server.feature.registry.ts
packages/core-browser/src/ai-native/ai-reporter.ts
packages/core-common/src/types/ai-native/reporter.ts
packages/startup/entry/sample-modules/ai-native/apply.service.ts

fix: chat reporter
fix: chat reporter issues

fix: chat reporter issues

---

packages/ai-native/src/browser/ai-core.contribution.ts
packages/ai-native/src/browser/chat/chat.internal.service.ts
packages/ai-native/src/browser/components/components.module.less
packages/ai-native/src/browser/mcp/base-apply.service.ts
packages/ai-native/src/browser/widget/inline-chat/inline-chat-controller.ts
packages/ai-native/src/browser/widget/inline-diff/inline-diff-manager.tsx
packages/ai-native/src/browser/widget/inline-diff/inline-diff-widget.module.less
packages/ai-native/src/common/types.ts

fix: issues about multiple file apply
fix: issues about multiple file apply

fix: issues about multiple file apply

---

packages/ai-native/src/browser/chat/apply.service.ts
packages/ai-native/src/browser/chat/chat-proxy.service.ts
packages/ai-native/src/browser/index.ts
packages/ai-native/src/node/base-language-model.ts
packages/startup/entry/sample-modules/index.ts

feat: provide default apply service

feat: provide default apply service

---

packages/ai-native/src/browser/context/llm-context.service.ts

fix: attach file snippets

---

packages/ai-native/src/browser/chat/chat.view.tsx
packages/ai-native/src/browser/components/ChatToolRender.module.less
packages/ai-native/src/browser/components/ChatToolRender.tsx
packages/ai-native/src/browser/mcp/config/components/mcp-config.view.tsx
packages/ai-native/src/browser/mcp/config/mcp-config.contribution.ts
packages/components/src/markdown-react/parse.tsx
packages/i18n/src/common/en-US.lang.ts
packages/i18n/src/common/zh-CN.lang.ts

chore: improve mcp views

---

packages/ai-native/src/common/index.ts

fix: remove sumi- prefix to prevent model misspell
fix: remove sumi- prefix to prevent model misspell

fix: remove sumi- prefix to prevent model misspell

---

packages/ai-native/src/browser/mcp/base-apply.service.ts

chore: add more context in chat reporter
chore: add more context in chat reporter

chore: add more context in chat reporter
